### ISSUE TITLE
maths on active scalar

### ISSUE THREAD

**Issue by craigmillernz** [pyvista/pyvista-support#10]
I'd like to do maths on the active scalar, such as taking the log10.
`np.log10(model.active_scalar) ` returns a numpy array not a vtk object.
Alternatively can I log transform the colour scale?

**Comment by banesullivan** [comment]
Hi @craigmillernz - what you want to do is totally possible! PyVista is built for direct use with NumPy so there's no need to worry about VTK data types and all of those nuances. As a user, all you have to do is pass an array to your PyVista mesh and PyVista will handle the rest.

Here's an example:

```py
>>> import pyvista as pv
>>> import numpy as np
>>> from pyvista import examples
>>> mesh = examples.download_st_helens()
>>> mesh.plot(use_panel=False)
```

![download](https://user-images.githubusercontent.com/22067021/58678167-fb996300-831b-11e9-8074-bfd3ef2f0927.png)



Perform some math like `np.log10`
```py
>>> myarr = np.log10(mesh.active_scalar)
>>> type(myarr)
numpy.ndarray
```

And send that array back to PyVista for plotting
```py
>>> mesh['stuff'] = myarr
>>> np.allclose(mesh['stuff'], np.log10(mesh.active_scalar))
True
```


```py
>>> mesh.plot(scalars='stuff', use_panel=False)
```
![download](https://user-images.githubusercontent.com/22067021/58678140-e91f2980-831b-11e9-9567-40ae85327a7f.png)

**Comment by banesullivan** [comment]
> Alternatively can I log transform the colour scale?

As for transforming the color mapping... this is still a work in progress that I haven't figured out quite yet. A `norm` option was requesting in https://github.com/pyvista/pyvista/issues/122

**Comment by craigmillernz** [comment]
Thanks, it was getting it back into pyvista that was the trick.
