### ISSUE TITLE
How to extend volume of a 3D scanned surface to a certain thickness

### ISSUE THREAD

**Issue by Nowfal1993** [pyvista/pyvista-support#100]
## Description
I have a 3D scanned surface. I need to extend the  volume to a certain height in Z axis,. I tried with the `.add_mesh_clip_plane()`. But the surface is getting flattened like a plane. I actually want to volumize the lower portion of the surface to the minimum value of the Z (Valley). As a result the top view look like exactly my surface and the bottom view looks like a plane passing throgh the minimum value of Z

This is my actual triangulated surface from the poin cloud data
![grafik](https://user-images.githubusercontent.com/59694177/72071087-4c7a2c80-32eb-11ea-88fe-dcdde2b10108.png). 
After doing the clipping to extend the volume, the bottom view looks like : 
![grafik](https://user-images.githubusercontent.com/59694177/72071465-2a34de80-32ec-11ea-95ad-31067d2d22d8.png). 
and the top view looks like: 
![grafik](https://user-images.githubusercontent.com/59694177/72071522-4769ad00-32ec-11ea-98fd-0166bb48d3d6.png)

So is there any other way to extend the volume without changing the triangulated surface?

**Comment by banesullivan** [comment]
Can you share this particular data file?

**Comment by Nowfal1993** [comment]
Hi, Thank you for your response. 
The actual surface scanned data is .stl file. But the size of the file is too high to add here. So I saved the point data in a .csv file and attached here. 

[example.zip](https://github.com/pyvista/pyvista-support/files/4042338/example.zip)

**Comment by Nowfal1993** [comment]
Hi @banesullivan. I tried in another two methods. 

1. I have created the projection of the plane at requied thickeness and then combined the plane and the projected plane in a pyvista.Multiblock(). So that I can plot them together. But the problem is I cannot do any surface triangulation to create a solid block. (AttributeError: 'MultiBlock' object has no attribute 'delaunay_2d')

2. The second method is concatenate the suface points and the projected plane points. So that I can do the suface triangulation. In that way I can visuilise the suface with a required thickness.  But the problem is that triangulation is performed in such a way that , the bottom of the triangles is from the projected plane and the  top is from the the actual surafce. so that the surface is not properly triangulated as it is.  showing upo and down from top to bottom plane. For better clasrification I attaching the video slide that I got from the second method.  
[conactenate_tri.pptx](https://github.com/pyvista/pyvista-support/files/4053899/conactenate_tri.pptx)

So how we can make it as proper solid surface having the thickness? Thanks in advance.

**Comment by Nowfal1993** [comment]
Hi @banesullivan, Is there any other possibility to include the surface thickness?. I hope you understood my trial method from the last post. Thanks

**Comment by banesullivan** [comment]
Hey, @Nowfal1993, sorry for my slow response in this one! I will have time to take a look this evening. 

In the meantime, you can merge datasets in a MultiBlock object with the `combine` filter before the `delaunay_2d`

You may want to concatenate all the points from the plane and the surface you have then do a **3D** Delaunay filter and then extract its surface

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Nowfal1993** [comment]
Hey @banesullivan. I will check it out. But for a clarification,  ultimately what I need to get is the surface with a thickness. So that the inside volume is also filled, Not the external boundaries. 

for example, the end result should be like in the clipping a mesh by a surface `examples.load_random_hills()`

  
![grafik](https://user-images.githubusercontent.com/59694177/72418960-25ed4300-377c-11ea-8c6a-814720a990f5.png)

**Comment by Nowfal1993** [comment]
Hi @banesullivan, I have tried merging the surfaces in a multiblock with a `combine` filter.and  the followed by a `delaunay_2d `. But the `delaunay_2d` is saying that `AttributeError: 'MultiBlock' object has no attribute 'delaunay_3d'`

About the second method of concatenating the surface and then a 3d_triangulation. its taking a long to show nothing. 
So do you have any other idea or suggestion on this?
 Thanks and Regards

**Comment by Nowfal1993** [comment]
Hi @banesullivan. I tried with inserting points between the actual surface and the projected plane by taking mean of the z cordinates of actual surface and the projected plane. And concatenate all the points(surface, projection and the mean points). then tried with `delaunay_2d`. But still is showing the same results to that what i described in method two in the previous post. 

I am really stuck to this point and any help will be appreciated. Thanks in advance

**Comment by Nowfal1993** [comment]
It would be very helpful if anyone can help me on this. Thanks

**Comment by akaszynski** [comment]
Hello,
I can help.  Could you please post the code to generate the mesh, or ideally, you can simply write the mesh using `mesh.save('mesh.vtk')`, zip it, and upload here here.

**Comment by Nowfal1993** [comment]
Hi @akaszynski, Thanks for the help. here is my mesh
[mesh.zip](https://github.com/pyvista/pyvista-support/files/4087182/mesh.zip)

**Comment by akaszynski** [comment]
This should do it.  We don't have an extrusion filter implemented (yet), so you'll have to use the vtk module for that

```python
import pyvista

# load points and tessellate to mesh
points = pyvista.read('mesh.vtk')
meshed = points.delaunay_2d()

# Linear extrude
import vtk
extrude = vtk.vtkLinearExtrusionFilter()
extrude.SetInputData(meshed)
extrude.SetVector(0, 0, 1)
extrude.Update()
extruded_mesh = pyvista.wrap(extrude.GetOutput())
```
![mesh](https://user-images.githubusercontent.com/11981631/72751374-c221aa80-3bbf-11ea-8841-6fc50e04db14.png)

@banesullivan, think we should add something like this to the main API as a common method for meshes?

**Comment by banesullivan** [comment]
@akaszynski, I think it would be good to include a wrapper for `vtkLinearExtrusionFilter` in the `PolyDataFilters` class perhaps as `def extrude()`. From glancing at the `vtkLinearExtrusionFilter` class, it has a lot of options, so this filter might take a minute to fully implement beyond just supporting a single vector extrusion.

**Comment by akaszynski** [comment]
Actually, I remembered that https://github.com/pyvista/pyvista/pull/449 already has a basic implementation of the extrude filter.  I need to finish the PR...

**Comment by Nowfal1993** [comment]
Hi @akaszynski, Extrusion seems interesting. But now the results is like hollow inside. But what I actually looking is its should be a solid surface like in the clipping a mesh by a surface `examples.load_random_hills()`.(As I emsntione d before). ultimately I need to slice the solid surface and find the area for my reamining computation like https://github.com/pyvista/pyvista-support/issues/102.  Also the the bottom surface have to be flat surface. 

As it is hollow now, the area after slicing is always showing zero. 
![grafik](https://user-images.githubusercontent.com/59694177/72793379-a9a2a600-3c3a-11ea-8f88-4b4e6e6fb8ff.png)
But we are almost close

**Comment by Nowfal1993** [comment]
Does  `vtkLinearExtrusionFilter` have any other options to extrude the volume, not only the surface boundaries? 
Thanks

**Comment by banesullivan** [comment]
> Does `vtkLinearExtrusionFilter` have any other options to extrude the volume, not only the surface boundaries?

nope, it just extrudes to form more 2D geometries.

-----

Curious: there might be another way to approach this problem... it looks as though the surface mesh is structured. Do you perhaps actually have a structured grid (made of quads) that you are triangulating (e.g. a meshgrid)? If so, we may be able to work some magic and extend the grid to have 3D cells. This is a bit problematic with triangulated meshes though. 

From just looking at your mesh, it looks like a meshgrid (uniform XY and varying Z much like the wave example in PyVista which we can do the following with:

```py
import numpy as np
import pyvista as pv
from pyvista import examples

struct = examples.load_structured()
struct.plot(show_edges=True)
```

![download](https://user-images.githubusercontent.com/22067021/72866852-06817900-3c9a-11ea-93a8-d973dcc8f64d.png)

```py
top = struct.points.copy()
bottom = struct.points.copy()
bottom[:,-1] = -10.0 # Whereever you want the plane
vol = pv.StructuredGrid()
vol.points = np.vstack((top, bottom))
vol.dimensions = [*struct.dimensions[0:2], 2]
vol.plot(show_edges=True)
```

![download](https://user-images.githubusercontent.com/22067021/72866889-34ff5400-3c9a-11ea-84dd-fecd87eed0d2.png)


And here is a slice!
```py
vol.slice().plot(show_edges=True)
```
![download](https://user-images.githubusercontent.com/22067021/72866896-3a5c9e80-3c9a-11ea-87f0-4d029b509817.png)


-----


With a little bit of guessing/`numpy.unique`, I made a `StructuredGrid` of your points and repeated this process, however this is not a safe solution. You will need to go to wherever you are creating this surface and preserve its original geometry rather than triangulate it.

```py
import pyvista as pv
from pyvista import examples
import numpy as np

pc = pv.read("/Users/bane/Desktop/mesh.vtk")

nx = len(np.unique(pc.points[:,0]))
ny = len(np.unique(pc.points[:,1]))
nz = 1

surface = pv.StructuredGrid()
surface.points = pc.points.copy()
surface.dimensions = [nx, ny, nz]
assert np.product(surface.dimensions) == surface.n_points
surface.plot(show_edges=True, notebook=0)
```

<img width="624" alt="Screen Shot 2020-01-21 at 10 11 05 PM" src="https://user-images.githubusercontent.com/22067021/72867087-f7e79180-3c9a-11ea-9aac-29a5841c05ad.png">

But some edges are ill-formed, so you ***really*** need to see if the original version of this exists somewhere:

<img width="624" alt="Screen Shot 2020-01-21 at 10 15 07 PM" src="https://user-images.githubusercontent.com/22067021/72867405-0d10f000-3c9c-11ea-8915-2fbdd5731c56.png">


But yeah, we can still make a volume and slice it. It's just an ill-formed mesh, so the kernel may randomly crash when plotting or the slice might look weird.


```py
top = surface.points.copy()
bottom = surface.points.copy()
bottom[:,-1] = 10.0 # Whereever you want the plane
vol = pv.StructuredGrid()
vol.points = np.vstack((top, bottom))
vol.dimensions = [*surface.dimensions[0:2], 2]
assert np.product(vol.dimensions) == vol.n_points

vol.slice().plot()
```

![download](https://user-images.githubusercontent.com/22067021/72867640-dedfe000-3c9c-11ea-86aa-94251fb1d1c6.png)

**Comment by banesullivan** [comment]
You could also try a sorting algorithm to properly sort the coordinates by XY to then create the structured surface which gets rid of the ill-formed edges:

```py
import pandas as pd
df = pd.DataFrame(dict(zip(["x", "y", "z"], pc.points.T)))
sorted_points = df.sort_values(["x", "y"]).values

surface = pv.StructuredGrid()
surface.points = sorted_points
surface.dimensions = [nx, ny, nz]
assert np.product(surface.dimensions) == surface.n_points

# Now check to make sure surface is still kosher
p = pv.Plotter(notebook=0)
p.add_mesh(surface, color="red")
p.add_mesh(pc)
p.show()
```
<img width="624" alt="Screen Shot 2020-01-21 at 10 44 46 PM" src="https://user-images.githubusercontent.com/22067021/72868579-abeb1b80-3c9f-11ea-8f5d-45ba497b8e8b.png">


<img width="624" alt="Screen Shot 2020-01-21 at 10 45 00 PM" src="https://user-images.githubusercontent.com/22067021/72868585-b0afcf80-3c9f-11ea-8a76-78034d3cf32c.png">

**Comment by banesullivan** [comment]
**note to self:** the `add-to-gallery` tag was added because it would probably be useful to explain how structured surfaces can be reformed into volumes with a little magic. It would be good to put that wave example in the docs.

**Comment by akaszynski** [comment]
@banesullivan, thanks for your effort figuring this out.

**Comment by Nowfal1993** [comment]
@banesullivan and @akaszynski. I really appreciate your guidance and the time you spent to help on this. It would be great if you can keep this issue open for a while. So if I have further discussion on it, I can come up here. Thanks again.

**Comment by banesullivan** [comment]
@Nowfal1993, I'm going to go ahead and close this to help declutter the open support tickets. Note that you can always post here after it closes and we can reopen the issue if needed.

If you have more questions that are more general/not specifically on this topic, it'd be great to open a separate issue, but feel free to come back to this thread!

**Comment by Nowfal1993** [comment]
@banesullivan. Ok. Thank you so much for the help

**Comment by banesullivan** [comment]
Just an FYI for later: in https://github.com/pyvista/pyvista-support/issues/100#issuecomment-577020845, I mentioned that we should add this to the docs as creating a "terrain-following mesh" is common. here is a neat example

```py
from pyvista import examples
import pyvista as pv
import numpy as np

# Get a StructuredGrid
grid = examples.download_crater_topo().warp_by_scalar()

# make a terrain following mesh
levels = np.arange(50) * 20.0 # Z spacing

xx = np.repeat(grid.x, len(levels), axis=-1)
yy = np.repeat(grid.y, len(levels), axis=-1)
zz = np.repeat(grid.z, len(levels), axis=-1) + levels.reshape((1, 1, -1))
terrain = pv.StructuredGrid(xx, yy, zz)
terrain["zz"] = zz.ravel(order="F")

terrain.plot()
```

![download](https://user-images.githubusercontent.com/22067021/73230374-39b08600-413a-11ea-8fb1-e059ba263f04.png)

**Comment by Nowfal1993** [comment]
Hi @banesullivan, 

I got another mesh which is attached here. when I try that one, its showing assertion error. the previos mesh we have tried have equal numbver of points in x and y axis. But this time the mesh have differnt number of points and also its curved. I cannot able to get rid of it. Any idea?

Thanks in advance. 

 
[mesh_example.zip](https://github.com/pyvista/pyvista-support/files/4199462/mesh_example.zip)

**Comment by banesullivan** [comment]
You just need a better method for finding the "unique" values along each axis within some tolerance likely. I'd recommend going to whatever software is making these meshes and see if it has an `nx` or `ny` described somewhere.

**Comment by Nowfal1993** [comment]
@banesullivan But Its not always good to say that the the surface should have always equal number of x points and y points. because the method which described above is only works with surface having equal number x and y points.
for the below surface example, 
![grafik](https://user-images.githubusercontent.com/59694177/74537329-296e1880-4f3a-11ea-9956-d7335b519ab3.png)
the surface can extend it to 3d as we descusse before
![grafik](https://user-images.githubusercontent.com/59694177/74537293-18250c00-4f3a-11ea-920a-6d5cd9bf0229.png)

but if the surface is not , for example:
