### ISSUE TITLE
Extracting elevation of outer surface as numpy array

### ISSUE THREAD

**Issue by mkondratyev85** [pyvista/pyvista-support#101]
## Description

Dear `pyvista` team members, I want to get a 2d numpy array consisting of elevation of cells of the top surface (facing the 'sky') of my unstructured grid. 

For example, following this snipped from tutorial (https://docs.pyvista.org/examples/01-filter/clipping.html) I can create a 3d mesh representing some hill.

```python
surface = examples.load_random_hills()

# Create a grid around that surface
grid = pv.create_grid(surface)

# Clip the grid using the surface
model = grid.clip_surface(surface)

# Compute height and display it
model.elevation().plot()
```

![](https://docs.pyvista.org/_images/sphx_glr_clipping_005.png)

How can I convert elevations data of the cells of the top surface as 2d numpy array?

Thank you

**Comment by banesullivan** [comment]
> How can I convert elevations data of the cells of the top surface as 2d numpy array?

Generally speaking for any 3D mesh, this isn't exactly doable without resampling your mesh to a rectilinear space. For example, this mesh's outer surface has many different cell geometries that are not uniform and thus cannot be directly injected into a 2D array (a rectilinear grid)

<img width="1297" alt="Screen Shot 2020-01-14 at 2 12 54 PM" src="https://user-images.githubusercontent.com/22067021/72383145-14525f80-36d8-11ea-827d-4bd5056761be.png">

The best thing you can do is extract the outer surface of the mesh, clean up the sides that are not of interest, project that surface to a plane, and then resample that data onto a rectilinear grid.

Here is a hacky solution to that that will work for this mesh but not all meshes in general.... the tricky part is cleaning up the sides of the mesh you don't want inncluded.

```py
import matplotlib.pyplot as plt
import pyvista as pv
from pyvista import examples
import numpy as np

def make_model():
    surface = examples.load_random_hills()

    # Create a grid around that surface
    grid = pv.create_grid(surface)

    # Clip the grid using the surface
    model = grid.clip_surface(surface)
    return model.elevation()

# Compute height and display it
model = make_model()

# Extract the surface of the mesh we care about
surf = model.elevation().extract_surface()
bounds = np.array(model.bounds).reshape((3,2))
# trim X and Y
bounds[0:2,0] += 0.01 * model.length
bounds[0:2,1] -= 0.01 * model.length 
# trim bottom of Z
bounds[2,0] += 0.01 * model.length
clipped = surf.clip_box(bounds.ravel(), invert=False)
clipped.plot()
```

![download](https://user-images.githubusercontent.com/22067021/72384165-19b0a980-36da-11ea-80d1-f90cfb472c56.png)


```py
# project to a plane
origin = model.center
origin[-1] = model.bounds[4]
plane = clipped.extract_geometry().project_points_to_plane(origin)

p = pv.Plotter()
p.add_mesh(clipped, opacity=0.5)
p.add_mesh(plane)
p.enable_depth_peeling()
p.show()
```
![download](https://user-images.githubusercontent.com/22067021/72384194-27662f00-36da-11ea-8ec7-d9aede0225c9.png)


```py
# now resample that plane to a rectilinear grid
x = np.linspace(*plane.bounds[0:2])
y = np.linspace(*plane.bounds[2:4])
z = np.array([plane.bounds[5]])
rect = pv.RectilinearGrid(x, y, z).sample(plane)
rect.plot()
```

![download](https://user-images.githubusercontent.com/22067021/72384197-28975c00-36da-11ea-89c6-14aa2098d9de.png)

And here is the 2D array!

```py
array = rect["Elevation"].reshape(rect.dimensions[0:2])
plt.pcolormesh(x, y, array)
```

![download](https://user-images.githubusercontent.com/22067021/72384217-34831e00-36da-11ea-8921-3e73a7c43337.png)

**Comment by mkondratyev85** [comment]
Thank you so much for the answer. That is exactly what I need!

**Comment by mkondratyev85** [comment]
Another possible way of extracting top surface from the mesh could be like this:

(function `make_model` was defined in https://github.com/pyvista/pyvista-support/issues/101#issuecomment-574382709)

```python
# Compute height and display it
model = make_model()

# Extract the surface of the mesh we care about
surf = model.elevation().extract_surface()

# Compute normals
surf.compute_normals(inplace=True)

# Extract Z part from Normals
surf['Normals_z'] = np.ascontiguousarray( surf['Normals'][:,2] )
```

Now I would like to extract all cells with `Normals_z > 0`. I.e. all cells facing upwards is the top surface in this case. But I don't know how to extract cells from mesh that require some condition. Is it possible?

**Comment by banesullivan** [comment]
This is an elegant solution, thanks @mkondratyev85!

To complete it, take a look at the [`extract_cells`](https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.extract_cells) filter and pass the IDs of the cells that meet your condition.

Also, make sure to only compute the cell normals.

Here is the code:

```py
# Compute normals
surf.compute_normals(cell_normals=True, point_normals=False, inplace=True)

# Get list of cell IDs that meet condition
ids = np.arange(surf.n_cells)[surf['Normals'][:,2] > 0.0]

# Extract those cells
top = surf.extract_cells(ids)
```
