### ISSUE TITLE
How to find the area of slices

### ISSUE THREAD

**Issue by Nowfal1993** [pyvista/pyvista-support#102]
## Description
Hi Support team. How can we find the area of the sliced surface. For example  
```
import pyvista as pv
from pyvista import examples
import numpy as np
import matplotlib.pyplot as plt
surface = examples.load_random_hills()

# Create a grid around that surface
grid = pv.create_grid(surface)

# Clip the grid using the surface
model = grid.clip_surface(surface)

# Compute height and display it
model.elevation().plot()
```
This results in this ouput surface
![grafik](https://user-images.githubusercontent.com/59694177/72330490-e27cd100-36b6-11ea-9b27-824b4ed61998.png)

If we slice the surface in the z axis as in the code below
```
import pyvista as pv
from pyvista import examples
import numpy as np
import matplotlib.pyplot as plt

surface = examples.load_random_hills()

# Create a grid around that surface
grid = pv.create_grid(surface)

# Clip the grid using the surface
model = grid.clip_surface(surface)

cmap = plt.cm.get_cmap("viridis", 4)
slices = model.slice_along_axis(n=7, axis="z")
slices.plot(cmap=cmap)
```
This will results in the following image with 7 slices along the z axis.
![grafik](https://user-images.githubusercontent.com/59694177/72330817-6fc02580-36b7-11ea-89a7-5b9350921b15.png)

How we can find the area of each slice?

**Comment by Nowfal1993** [comment]
I tried the folowing code segment after slicing 
```
sliced_plane = slices[1].compute_cell_quality()
print('area', sliced_plane .area)
```

I think its giving the area of the slice

**Comment by banesullivan** [comment]
Have you tried the [`.compute_cell_sizes()`](https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.compute_cell_sizes) filter:

```py
sliced_plane = slices[1].compute_cell_sizes()
np.sum(sliced_plane["Area"])
```

**Comment by Nowfal1993** [comment]
Thanks @banesullivan. Clear now. 
Thanks for the help. 
Regards
