### ISSUE TITLE
SetPoints SetCells

### ISSUE THREAD

**Issue by bistek** [pyvista/pyvista-support#104]
Hello, I want to initialize an empty PolyData object and add nodes and cells later on. This is useful for [another issue](https://github.com/pyvista/pyvista-support/issues/97) on importing Gocad ASCII files, and could be useful also in other situations.

In the PyVista documentation I have found [the following](https://docs.pyvista.org/core/points.html?highlight=setpoints).

```
import pyvista
grid = pyvista.PolyData()
```

_This creates an empty grid, and is not useful until points and cells are added to it. VTK points and cells can be added with SetPoints and SetCells, but the inputs to these need to be vtk.vtkCellArray and vtk.vtkPoints objects, which need to be populated with values._

To convert node coordinates from a numpy array (x y z columns and one row for each point) to vtkPoints I have found the method `pyvista.vtk_points(points, deep=True)`. Is this correct?

But I do not find how to convert the cells from numpy to vtkCellArray.

Then I guess that all I have to do is
```
grid.SetPoints(vtkPoints)
grid.SetCells(vtkCellArray)
```
Correct?

One more question: would it be possible to append points and cells incrementally, as I read them from a file line-by-line? This will make my code **VERY** simple!

Thanks very much!

**Comment by banesullivan** [comment]
In my experience, there can be a lot of issues with dynamically adding cells/points to `PolyData` meshes. It's best practice to set all the points/cells at once or use filtering routines to remove/produce new points/cells on a new version of the mesh.

I would highly recommend not messing with the `vtkCellArray` or `vtkPoints` array and just keep track of your points/cells in numpy arrays/lists and pass them to the `PolyData` object upon instantiation.

For instance, have some numpy array track all your nodes/faces while reading your file, then pass them to the `PolyData` object's init method:

```py
import pyvista as pv
import numpy as np

file = """3
1 0 0
0 1 0
1 1 2
1
0 1 2
"""

lines = file.splitlines()
n_verts = int(lines[0].strip())

nodes = []
faces = []

for i in range(1, n_verts+1):
    nodes.append([float(v) for v in lines[i].split()])

n_faces = int(lines[i + 1])
for j in range(1, n_faces+1):
    faces.append([int(v) for v in lines[i+j+1].split()])

# create PolyData
nodes = np.array(nodes)
faces = np.c_[np.full(len(faces), 3), np.array(faces)].ravel()

mesh = pv.PolyData(nodes, faces)
```

**Comment by bistek** [comment]
Thanks!

Unfortunately in our case this means storing in temporary variables a lot of other parameters that come with gocad objects, and then the nodes and cells could be very numerous, and finally you have to add all this to the Polydata at the end. So this is going to be quite inefficient.

Is there a way to add nodes and cells to an empty PolyData? Node-by-node and cell-by-cell while reading them, or all at once after reading all of them? I've looked for a method in filters, but I've found just methods to eliminate or slice nodes and cells - not to add them.

Another option I've found directly with vtk (inspired by [this page in PyVista documentation](https://docs.pyvista.org/core/points.html?highlight=add)) is this:

```
import numpy as np
import pyvista as pv
from vtk.util.numpy_support import numpy_to_vtk

vertices = np.array([[0.0, 0.0, 0.0],[0.0, 1.0, 0.0],[1.0, 0.0, 0.0],[1.0, 1.0, 0.0],[2.0, 0.0, 0.0],[2.0, 1.0, 0.0]])
cells = np.array([[0, 1, 2],[1, 2, 3],[2, 3, 4],[3, 4, 5]])

vertices_vtk = numpy_to_vtk(vertices)
cells_vtk = numpy_to_vtk(cells)

current_object = pv.PolyData()

current_object.SetPoints(vertices_vtk)
current_object.SetCells(cells_vtk)
```

However the SetPoints line gives this error:
`TypeError: SetPoints argument 1: method requires a vtkPoints, a vtkDoubleArray was provided.`

and the SetCells line this error:
`AttributeError: 'PolyData' object has no attribute 'SetCells'`

Thanks!

**Comment by bistek** [comment]
And if I use ShallowCopy like here to add a mesh later to an empty PolyData?

https://lorensen.github.io/VTKExamples/site/Python/Filtering/CombinePolyData/

**Comment by banesullivan** [comment]
Here is a little helper method to dynamically update the points/vertex cells of `PolyData` with the changes in https://github.com/pyvista/pyvista/pull/554 that allow us to access the vertex cells

```py
import pyvista as pv
import numpy as np

def append_points(mesh, points):
    if mesh.n_points == 0:
        mesh.points = np.array(points).reshape((-1, 3))
    else:
        mesh.points = np.vstack((mesh.points, points))
    # Have to remake the cells each time
    mesh.verts = mesh._make_vertice_cells(mesh.n_points)
    return True


# Create empty PolyData
mesh = pv.PolyData()
# Dynamically append the points
append_points(mesh, [[0,0,0],[9,2,1]])
```

**Comment by bistek** [comment]
Great, thanks!

**Comment by banesullivan** [comment]
It's a bit hacky, but I hope this helps! Once you make the reader for pyvista/pyvista#4902 using this, I can have a peek at how to simplify things further
