### ISSUE TITLE
Geodesic path original point ids

### ISSUE THREAD

**Issue by bvafa** [pyvista/pyvista-support#105]
## Description
Good day,
How can I extract the original mesh points' ids of a geodesic path points?
The geodesic method of a mesh outputs the point coordinates of the path points, but I also need the path point ids initially set/indexed by the mesh itself.
Thanks a lot,

**Comment by banesullivan** [comment]
Thanks for pointing out that the id list was missing, @bvafa! This functionality will be added in https://github.com/pyvista/pyvista/pull/544

**Comment by bvafa** [comment]
Thanks a lot.
I just added the lines
`original_ids = vtk_id_list_to_array(dijkstra.GetIdList())`
`output["vtkOriginalPointIds"] = original_ids`
into filter.py; however, I wasn't successful to extract out the Ids. I think the original_ids was empty (NoneType). Could you please guide me through?
Thank again.

**Comment by banesullivan** [comment]
Do you have the method `vtk_id_list_to_array`:  https://github.com/pyvista/pyvista/pull/544/files#diff-328f2895214e3ed55b604a1f0cff6853R45-R47

**Comment by bvafa** [comment]
Thank you. I added the method as described. It works now. This now gives the Ids:
`pntsIds = geo["vtkOriginalPointIds"]`

**Comment by banesullivan** [comment]
> However, it seems that it gives out the pointIds in reverse order compared to the order of the point coordinates by geo.points.

From everything I've checked, that doesn't seem to be the case. I just added a test [in that PR](https://github.com/pyvista/pyvista/pull/544/files#diff-5bc99bfa04bfdf5567c27427cade537aR139-R141) to confirm that the IDs given in `"vtkOriginalPointIds"` are correct

Can you confirm that they are not correct and possibly provide example code/output?

**Comment by bvafa** [comment]
Hello, Can you check this out please:
`sphere = pv.Sphere()`
`sphPnts =  sphere.points`
`ids = 0   # start`
`idt = 10  # target`
`Pnt_ids = sphPnts[ids]`
`Pnt_idt = sphPnts[idt]`
`geo = sphere.geodesic(ids, idt)`
`geoPntsIds = geo["vtkOriginalPointIds"]`
`geoPntsCs = geo.points`
`print(Pnt_ids)`
`print(geoPntsCs[0])`
`print(geoPntsIds[0]==ids)`
`print(geoPntsIds)  # it prints [10, 9, ...,2, 0] insted of [0,2,3,..,10]`

**Comment by banesullivan** [comment]
I think consistency is key here. The IDs themselves are correct - the ID for each node in the filtered mesh corresponds to the ID of that node in the parent mesh. The reverse order there shouldn't really matter as the IDs are consistent across both meshes... does this make sense?

It appears the `vtkDijkstraGraphGeodesicPath` is implemented using a heap so it kinda makes sense that the points in the output mesh are from `end_vertex` to `start_vertex` as the algorithm outputs them in that order

Hope this helps!

**Comment by banesullivan** [comment]
Just trying to declutter open issues, so I am closing this as it should be resolved on the `master` branch of PyVista. Please feel free to post here again if something is awry still
