### ISSUE TITLE
How to compare a ground truth mesh with 300 other meshes and plot a distance map?

### ISSUE THREAD

**Issue by Beethov06** [pyvista/pyvista-support#106]
Hello world !

Quite new in python and vtk programming world, i've been trying to compute a comparison algorithm on python using traditional coding (eurk....) in order to create a 3D rendering of a multiple mesh comparison, like this kind of result ( http://qims.amegroups.com/article/viewFile/28539/25101/178969 ). i've tried for 1week but did not succeed....

I just found Pyvista and hope i'll be able to compute that easier but...

I've got one ground thruth (segmentation file, many format available as nii, mha, mhd, vtk) and more than 300 other segmentations of the same object in the same orientation, in the same image but all with a slight difference. i would like to graphically compute where theses differences are mainly located.

please, tell me that it is possible with pyvista :-)

**Comment by banesullivan** [comment]
Hi @Beethov06, this sounds like a really cool problem and something I think PyVista could help with!

Curious: do the meshes themselves change? I.e. do the locations of the vertices change? And are there varying amounts of vertices across the meshes?
Or
Does some scalar value change across the same mesh?
Or
Both?

Also, would you be able to share the ground truth mesh and maybe 2 others to help us tackle this? (VTK format would be easiest to work with)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Beethov06** [comment]
> Hi @Beethov06, this sounds like a really cool problem and something I think PyVista could help with!
> 
> Curious: do the meshes themselves change? I.e. do the locations of the vertices change? And are there varying amounts of vertices across the meshes?
> Or
> Does some scalar value change across the same mesh?
> Or
> Both?
> 
> Also, would you be able to share the ground truth mesh and maybe 2 others to help us tackle this? (VTK format would be easiest to work with)
> 
> Sent with [GitHawk](http://githawk.com)

Thank you for your answer.

Meshes are changing i think cause every new meshe is the result of a new segmentation (eevn if not changing image/segmentation parameters). For Scalar and vertices amount i don't know ><

I just made a [we transfert](https://wetransfer.com/downloads/476986faa5efe301f9d3fedeac31805320200119145153/609bdc4d25f86b7be7992ec32f9ed5e320200119145153/3dc676) of GT + 2 seg.


Crossing fingers...

**Comment by banesullivan** [comment]
@Beethov06, from what you sent me, it appears you have identical meshes and a varying scalar field across those meshes:

```py
import pyvista as pv
import numpy as np
from glob import glob
from tqdm import tqdm # Because 300 meshes will take a long time
# tqdm will report on the status of the for-loops

# Ground truth
gt = pv.read("/Users/bane/Desktop/PYVISTA/GT.vtk")
# To compare against ground truth
to_compare = pv.read(glob("/Users/bane/Desktop/PYVISTA/test*.vtk"))

# Assert that all of comparison meshes have the same spatial reference as the ground truth
for block in to_compare:
    assert gt.origin == block.origin
    assert gt.spacing == block.spacing
    assert gt.dimensions == block.dimensions
```

This makes this very similar to the work done in #83, so you may want to peak at that thread for some insight/ideas on how to compares data arrays. Differently however is the fact that your domain/mesh is constant, so we can do all kinds of things to "compare" the scalar fields of any given mesh to the ground truth mesh.

Since the meshes are all `UniformGrid`'s with the same spatial reference, all nodes align and thus all the scalars align by element so we can do any sort of array math with numpy to come up with metrics

```py
all_arrays = gt["scalars"].copy()
# Difference from ground truth mesh for each mesh
for block in tqdm(to_compare):
    block["difference"] = block["scalars"] - gt["scalars"]
    stacked = np.c_[block["scalars"], gt["scalars"]]
    block["var"] = np.var(stacked, axis=1)
    block["std"] = np.std(stacked, axis=1)
    all_arrays = np.c_[all_arrays, block["scalars"]]

# get the variance across all mehes for the GT mesh
gt["var"] = np.var(all_arrays, axis=1)
```
And since you have `UniformGrid` meshes, we can volume render!
```py
p = pv.Plotter(notebook=1)
p.add_mesh(gt.outline())
p.add_volume(gt, opacity="sigmoid_6", scalars="var", clim=[-1,1])
p.camera_position = [(-51.11664298147881, -24.067370596349733, 4.023900110753978),
 (-35.03117242458467, 26.788602802833857, 4.92792726025254),
 (-0.03474386808119212, -0.006775784383567851, 0.999373279799267)]
p.show()
```

![download](https://user-images.githubusercontent.com/22067021/72755411-a8647100-3b87-11ea-9aee-caed714922f1.png)



Or you could extract an isosurface of the ground truth body and color it by the variance which sorta looks like the link you shared (I'm not sure what sort of comparison metric they are using though)

```py
# Extract an iso surface where the scalars array is 2.0
iso_surface = gt.contour([2.0], scalars="scalars")

p = pv.Plotter(notebook=1)
p.add_mesh(gt.outline())
p.add_mesh(iso_surface, scalars="var", cmap="jet", clim=[0,1])
p.camera_position = [(-51.11664298147881, -24.067370596349733, 4.023900110753978),
 (-35.03117242458467, 26.788602802833857, 4.92792726025254),
 (-0.03474386808119212, -0.006775784383567851, 0.999373279799267)]
p.show()
```

![download](https://user-images.githubusercontent.com/22067021/72755313-718e5b00-3b87-11ea-9212-78e388825263.png)

**Comment by Beethov06** [comment]
Totally impressed by what i'm reading. never been able to compte that. 

I could ask you about 30 questions, but I don't want to waste your time because of my inexperience...

I really thank you.

**Comment by banesullivan** [comment]
> do you know why my background is black behind models

Ah, I have my local set to use the document plotting theme and yours is probably using the default... which should be grey-ish. Check out https://docs.pyvista.org/examples/02-plot/themes.html

If it's black, can you post a screenshot?

> why the window is not an "interractive" one?... Only like Jpeg images (as posted in your answer)

Are you in a Jupyter notebook/IPython environment? If so, pass `notebook=False` when instantiating the `Plotter` and an interactive pop-up window will appear. Otherwise, a static image is shown in the cell output

```py
p = pv.Plotter(notebook=False)
...
```

> I could ask you about 30 questions, but I don't want to waste your time because of my inexperience...

Happy to help, but the docs/[quick examples](https://docs.pyvista.org/examples/index.html) and other issues in this support forum likely have the answers to many of your questions 😉

**Comment by Beethov06** [comment]
Everything is working. Just thank you so much!

Pyvista is really an amazing tool. Traditional vtk computing is nos nasty near it !!

**Comment by banesullivan** [comment]
Huh, then maybe some of the meshes don’t have the spatial reference? (That’s what that assertion error would mean). 

Are you able to share all 300 in the mhd format? I could at least set up the workflow, then others/you can chime in on the comparison metrics to use. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by banesullivan** [comment]
Or maybe just share the problem mesh? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Beethov06** [comment]
I've compute every mesh in .vtk but always the same assertion error...
i've tried to delete meshes with no scalar inside (segmentation fail) but same problem

[Here](https://wetransfer.com/downloads/dd16a20e4e121bc290c3b88868e5a81120200122210914/1959f0d0c18c1e9ad20bce16a567c92e20200122210914/783273) the 300 meshes. 

Really appreciate your help.

**Comment by banesullivan** [comment]
Looks to me like the meshes are all the same just that the test meshes forgot to have their `origin` set. In the following script, I force the test meshes to all have the same `origin` as the GT mesh as the other important aspects of the spatial reference are the same.

Note that the original script would not execute... to much memory allocation, so this is my attempt to calculate variance on the fly. Ref https://math.stackexchange.com/a/20596 - you will definitely want to double check what I did.

```py
import pyvista as pv
import numpy as np
from glob import glob
from tqdm import tqdm # Because 300 meshes will take a long time
# tqdm will report on the status of the for-loops

pv.set_plot_theme("document")

# Ground truth
gt = pv.read("./GT.vtk")


# To compare against ground truth
# This reads in several meshes into a single MultiBlock dataset
to_compare = pv.read(glob("test/*.vtk"))

# Assert that all of comparison meshes have the same spatial reference as the ground truth
for block in tqdm(to_compare):
    assert gt.spacing == block.spacing
    assert gt.dimensions == block.dimensions
    # Let's force them all to have the same origin
    block.origin = gt.origin 
#


# Now compute variance
a = gt["scalars"].copy().astype(float)
b = gt["scalars"].copy().astype(float) ** 2    
for block in tqdm(to_compare):
    a += block["scalars"]
    b += block["scalars"] ** 2
n = to_compare.n_blocks
var = 1 / n * (b - (a**2)/n)

gt["var"] = var


# Annd plotting:

iso_surface = gt.contour([2.0], scalars="scalars")

p = pv.Plotter(notebook=False)
p.add_mesh(gt.outline())
p.add_mesh(iso_surface, scalars="var", cmap="jet", clim=[0,1])
p.camera_position = [(-51.11664298147881, -24.067370596349733, 4.023900110753978),
 (-35.03117242458467, 26.788602802833857, 4.92792726025254),
 (-0.03474386808119212, -0.006775784383567851, 0.999373279799267)]
   
p.show()
```

![download](https://user-images.githubusercontent.com/22067021/72946926-a80dd680-3d3d-11ea-8fec-792c1fae2ba6.png)

**Comment by Beethov06** [comment]
Great ! seems to work ! but i have an error....


  File ".folder\to\the\code\distance_map.py", line 38, in <module>
    var = 1 / n * (b - ((a**2)/n))

ZeroDivisionError: division by zero

i've tried to modify it but doesn't work. i do not understand why !

**Comment by akaszynski** [comment]
Sounds like `n` is zero at some point.

**Comment by banesullivan** [comment]
Likely the glob pattern is wrong and you’re not actually reading any data in the MultiBlock dataset?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Beethov06** [comment]
It works ! Halleluia!

Thank you guys, and specially @banesullivan

**Comment by Beethov06** [comment]
Excuse me, 

about that old topic, i have a last question. Does the colour scale of the variance show measures in mm or without unit? i’m not sure about the metric used to compare segmentions? Do you think so it is easily computable to show the variability between segmentations in mm if it is not?


Thank you!!!!


Best regards, 
CV

**Comment by akaszynski** [comment]
All the units of the scalar bar are in the units of the coordinates of the meshes.  If the mesh coordinates are in mm or in, it will be reflected there.  If you'd like those units in the scalar bar title then:
```python
p.add_mesh(iso_surface, scalars="var", cmap="jet", clim=[0,1], stitle='Variation (mm)')
```

**Comment by Beethov06** [comment]
Great answer! Thank you so much.
