### ISSUE TITLE
enable_path_picking save line

### ISSUE THREAD

**Issue by MattiaMartinelli** [pyvista/pyvista-support#109]
Good morning,
when I use the enable_path_picking() instrument how is it possible to save the created line as an object that I could plot for example in another view?

Thank you

Mattia

**Comment by banesullivan** [comment]
Hi @MattiaMartinelli! when usingn the `enable_path_picking()` tool, you can access the created path via the created `picked_path` attribute of the plotter. So after closing your plotter, you can access the object like:

```py
p = pv.Plotter(notebook=False)
p.add_mesh(mesh)
p.enable_path_picking()
p.show()

... # plotter is closed by user

# Grab the picked path
path = p.picked_path
```

You could also leverage a callback to do whatever you want with the picked line as it is created. For instance:

```py
p = pv.Plotter(notebook=False, shape=(1,2))
p.add_mesh(mesh,)

def callback(picked_path):
    p.subplot(0,1)
    p.add_mesh(picked_path, color="pink", 
               line_width=10,
               name="picked_path")
    p.subplot(0,0) # Reactivate the left renderer

p.enable_path_picking(callback)

p.link_views() # Share camera position
p.show()
```

**Comment by MattiaMartinelli** [comment]
Dear Bane, thank'you for your answer. 
I take this opportunity to ask you another question.
I saw that there is the possibility to use notebook plotting backends: X3D and K3D in pyvista notebook.
Is it possible to do the same with the Qtinteractor?

Thank you 

Mattia

**Comment by banesullivan** [comment]
> I saw that there is the possibility to use notebook plotting backends: X3D and K3D in pyvista notebook.

These features never actually made it into PyVista. We only support vtkjs via Panel at the moment. One day when someone has the time, we'll get back to notebook rendering

> Is it possible to do the same with the Qtinteractor?

I'm not sure I follow what you mean. There is a `BackgroundPlotter` in PyVista but Qt interfaces cannot be embedded in notebooks.
