### ISSUE TITLE
combine two meshes in a way that result is a single solid mesh

### ISSUE THREAD

**Issue by mkondratyev85** [pyvista/pyvista-support#110]
## Description

Sometimes when I add two meshes which has common side (I use '+' sign to do this) the resulting mesh behaves like it is two different volumes. For example, if I try extract_surface() method on the resulting mesh it will return two surfaces instead of one. Is there a way to make sure that resulting mesh would behave like a single solid volume instead of two separates?

**Comment by akaszynski** [comment]
If the two meshes have coincident points, this should combine them into one mesh.  Would it be possible to zip and post the meshes here?

**Comment by mkondratyev85** [comment]
Thank you for clarification. I've found that I had a tiny gap between two meshes. The gap was introduced because apparently I had wrong understanding of `clip` method.
