### ISSUE TITLE
Plotting multiple lines using a loop

### ISSUE THREAD

**Issue by bvafa** [pyvista/pyvista-support#111]
## Description
Hi,
I am trying to plot several lines. However, when I loop over the lines to get plotted, pyvista does not plot some of the lines. However, it plots any line if not looped.
Each line is in a dictionary as {lineId:linePoints}. such that linePoints is an array of point coordinates.
To plot the lines I use the following:
```
plotter = pv.Plotter()
plotter.background_color = "white"
lines = {} # some dictionary containing lines
for id in lines:
   linePoints = lines[id]
   polyLine = pv.PolyData(linePoints)
   polyLine.points = linePoints
   theCell = np.arange(0, len(linePoints), dtype=np.int)
   theCell = np.insert(theCell, 0, len(linePoints))
   polyLine.lines = theCell
   tube = polyLine.tube(radius=tubesize)
   plotter.add_mesh(tube, color='blue', smooth_shading=True)
plotter.show()
```
Above totally works for each line if aimed to be plotted individually.

Thank you for your help.

**Comment by banesullivan** [comment]
This sounds like the bug in https://github.com/pyvista/pyvista/issues/386 which was fixed in https://github.com/pyvista/pyvista/pull/521 and hasn’t been released yet.

Hotfix: try using a unique `name` argument on the `add_mesh` call

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by banesullivan** [comment]
@bvafa, I'm fairly confident this was the result of the bug mentioned above, so I am going to close this as it should be fixed on the `master` branch.

**Comment by RichardScottOZ** [comment]
Ok, I am wondering if this should work?

p = pv.Plotter(notebook=False)
for index, d in enumerate(density_list):
    v, t = read_GOCAD_ts(r'H:\GDP00037\Data\Geophysics\Gravity\Iso_Surfaces\Constrained\SA_Geophysics_Gravity_Inversion_Constrained_IsoSurface_' + d)

    t = t -1

    tri_index = t

    faces = np.empty_like(tri_index, shape=(tri_index.shape[0], 4) )
    faces[:, 0] = 3
    faces[:, 1:] = tri_index

    surf2 = pv.PolyData(v, faces)

    p.add_mesh(surf2, name=d)

p.show_grid(color='black')
p.set_background(color='white')
p.show()

**Comment by RichardScottOZ** [comment]
Any single mesh plots fine, but the look gets kernel death.

**Comment by banesullivan** [comment]
@RichardScottOZ, I'm not sure what's going wrong with your script. 

This is likely unrelated to the original issue/reported bug, so would you please open a new issue with more details, screen captures and possibly sample data?

**Comment by RichardScottOZ** [comment]
No problem, will do this morning. >0 prob a weird windows thing.

**Comment by RichardScottOZ** [comment]
@banesullivan  done in https://github.com/pyvista/pyvista-support/issues/403
