### ISSUE TITLE
Creating a mesh that represents a space between two givven surfaces.

### ISSUE THREAD

**Issue by mkondratyev85** [pyvista/pyvista-support#112]
## Description

Suppose we have two meshes like that:

```python
import pyvista as pv
import numpy as np

x = np.arange(-10, 10, 0.5)
y = np.arange(-10, 10, 0.5)
x, y = np.meshgrid(x,y)
r = np.sqrt(x**2 + y**2)
z2 = np.sin(r) + 5
z1 = np.zeros_like(z2)

grid1 = pv.StructuredGrid(x, y, z1)
grid2 = pv.StructuredGrid(x, y, z2)

p = pv.Plotter()

p.add_mesh(grid1)
p.add_mesh(grid2)
p.show()
```

![image](https://user-images.githubusercontent.com/32978900/73227722-8773cf80-41c8-11ea-932a-65eb67609038.png)

How can I create a mesh that would correspond to the space between the top and the bottom meshes?

**Comment by banesullivan** [comment]
This is incredibly similar to #100, maybe take a peak at that thread and this post: https://github.com/pyvista/pyvista-support/issues/100#issuecomment-577013950


Since you have two structured grids with the same XY dimensions, we can work a little magic to combine them into a closed volume. Since the points are structured, we can stack them and increase the Z dimension.

```py
assert grid1.dimensions[0:2] == grid2.dimensions[0:2]

merged = pv.StructuredGrid()
merged.points = np.vstack((grid1.points, grid2.points))
merged.dimensions = [*grid1.dimensions[0:2], 2]
merged.plot(show_edges=True)
```

![download](https://user-images.githubusercontent.com/22067021/73228893-1afbc080-4135-11ea-9f0a-2d9be7cc2950.png)

**Comment by mkondratyev85** [comment]
Thank you. That's exactly what I need. I guess this approach would fail in case when the top and the bottom surfaces have different number of cells. What to do in this case?

**Comment by banesullivan** [comment]
> I guess this approach would fail in case when the top and the bottom surfaces have different number of cells. What to do in this case?

Then this approach would not work and it becomes a much more complicated problem. There are a number of different ways to approach it and some are mentioned in #100. Also, you have to decide on whether you want a closed surface or a full 3D mesh.

It really depends on the surface meshes you have, their resolutions, extents, relative orientations, etc. It gets complicated real quick. The more assumptions you can make, the better... like are the two surfaces' extents the same in the XY plane? If so, you could create 4 planes for the outer walls and merge the meshes. Or you could extrude the bottom surface upward using https://github.com/pyvista/pyvista-support/issues/100#issuecomment-576397272 then clip that extrusion using the top surface with the `.clip_surface` filter.

It really just depends on the data at hand and would require a lot of user decisions, so it's hard to say more without a concrete example.

**Comment by banesullivan** [comment]
Also, PyVista isn't really a meshing library. There are many other software out there that would be able to do this sort of meshing then yield a result that PyVista can work with for 3D plotting, filtering, etc.

One such software is [`pygmsh`](https://github.com/nschloe/pygmsh)

**Comment by mkondratyev85** [comment]
So, PyVista is mostly a visualisation tool? Then what tool can you suggest to use for the purpose of refinement of selected cells in the mesh, generated with PyVista?

**Comment by banesullivan** [comment]
> So, PyVista is mostly a visualisation tool?

Yes, primarily a visualization and data management tool with quite a bit of analysis/filtering methods.

> Then what tool can you suggest to use for the purpose of refinement of selected cells in the mesh

what exactly do you mean by refinement? Maybe something like [`pyacvd`](https://github.com/pyvista/pyacvd) would help with resampling. also, PyVista does have the `subdivide` filter for refining `PolyData` meshes.

Also pinging @akaszynski as Alex does more work with mesh refinement than I

Here are two examples with interactive cell refinement based on a selection. First using PyVista's subdivide filter and second using `pyacvd`:

```py
import pyvista as pv
from pyvista import examples

# Use a triangulatd meesh
mesh = examples.download_cow_head().triangulate()
```

```py
p = pv.Plotter(notebook=False)
p.add_mesh(mesh, color=True, show_edges=True)

def refine(selection):
    sub_div = selection.extract_geometry().subdivide(2, subfilter="linear")
    # Show it interactively
    p.add_mesh(sub_div, color="red", name="sub_div", pickable=False, style="wireframe")

p.enable_cell_picking(mesh=mesh, callback=refine, through=False, show=False)

p.show()
```


<img width="624" alt="Screen Shot 2020-01-29 at 6 37 04 PM" src="https://user-images.githubusercontent.com/22067021/73412611-609bc300-42c6-11ea-9b06-d7db20834666.png">




```py
import pyacvd

p = pv.Plotter(notebook=False)
p.add_mesh(mesh, color=True, show_edges=True)
p.add_text("PyACVD", position="lower_left")

def refine(selection):
    clus = pyacvd.Clustering(selection.extract_geometry())
    clus.subdivide(3)
    clus.cluster(20000)
    remesh = clus.create_mesh()
    # Show it interactively
    p.add_mesh(remesh, color="red", name="remesh", pickable=False, style="wireframe")

p.enable_cell_picking(mesh=mesh, callback=refine, through=False, show=False)

p.show()
```

<img width="624" alt="Screen Shot 2020-01-29 at 6 36 38 PM" src="https://user-images.githubusercontent.com/22067021/73412608-5ed1ff80-42c6-11ea-8de7-7e324721950b.png">

**Comment by mkondratyev85** [comment]
Thank you for very informative and detailed answer. You provide excellent support!
