### ISSUE TITLE
Varying Outputs when Plotting Multiple Boxes onto one Window

### ISSUE THREAD

**Issue by war-mbw** [pyvista/pyvista-support#115]
Hey,
I'm struggling  to highlight multiple areas in a given vtk modell by adding boxes at identified positions. The following script demonstrates the core part.

```
import pyvista as pv

n = 10
r = .2
centers = [[i,j,0] for i in range(n) for j in range(n)]

for i in range(5):
    p = pv.Plotter(off_screen=True, window_size=[400,300])
    for c in centers:
        p.add_mesh(pv.Box(pv.Sphere(r, c).bounds))
    p.show(screenshot='boxes{:d}.png'.format(i))
    p.close()
```

And here is my outcome.
![boxes0](https://user-images.githubusercontent.com/54351846/73450783-6943d600-4366-11ea-9d87-f9d31f13a07d.png)
![boxes1](https://user-images.githubusercontent.com/54351846/73450791-6d6ff380-4366-11ea-97c1-531bfa33151c.png)
![boxes2](https://user-images.githubusercontent.com/54351846/73450841-88426800-4366-11ea-8392-5119b678bffb.png)
![boxes3](https://user-images.githubusercontent.com/54351846/73450876-955f5700-4366-11ea-895a-ff219d3832dc.png)
![boxes4](https://user-images.githubusercontent.com/54351846/73450884-98f2de00-4366-11ea-96bc-785dd0cd94ff.png)

What am I doing wrong here?

Kind regards,
Mario

**Comment by GuillaumeFavelier** [comment]
Hello @war-mbw, thank you for reporting in here. Could you share your configuration with us by using:

```py
import pyvista as pv
pv.Report()
```

I believe a similar issue has been reported in https://github.com/pyvista/pyvista/issues/386 and fixed in https://github.com/pyvista/pyvista/pull/521. We plan to release the version `0.23.1` with the fix soon but you can install `PyVista` from the `master` branch in the meantime. Let me know it this fixed your issue.

**Comment by war-mbw** [comment]
... the configuration for now
```
--------------------------------------------------------------------------------
  Date: Thu Jan 30 15:48:23 2020 W. Europe Standard Time

           Windows : OS
                 8 : CPU(s)
             AMD64 : Machine
             64bit : Architecture
          127.7 GB : RAM
            Python : Environment

  Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64
  bit (AMD64)]

            0.23.0 : pyvista
             8.1.2 : vtk
            1.16.4 : numpy
             2.5.0 : imageio
             1.4.3 : appdirs
             0.4.3 : scooby
             3.1.1 : matplotlib
            5.13.0 : PyQt5
             7.6.1 : IPython
             1.0.0 : colorcet
             0.6.0 : panel

  Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```

**Comment by war-mbw** [comment]
Hello Guillaume,
I'm afraid the update from master didn't help.
Setting a **distinct** name by
```
name='i{:d} j{:d}'.format(c[0], c[1])
```
did do the trick.
Mario

**Comment by banesullivan** [comment]
huh, the master branch should have fixed this. Are you sure you installed from the master branch correctly?

```
pip install git+git://github.com/pyvista/pyvista@master
```

**Comment by banesullivan** [comment]
For the archives, duplicate of #111

**Comment by war-mbw** [comment]
... had to download pyvista-master.zip from https://github.com/pyvista/pyvista

**Comment by GuillaumeFavelier** [comment]
Thank you for sharing your solution, it will be useful for future reference

**Comment by GuillaumeFavelier** [comment]
Also, feel free to close if you don't have the issue anymore @war-mbw

**Comment by war-mbw** [comment]
```
import pyvista as pv
n = 10
r = .2
centers = [[i,j,0] for i in range(n) for j in range(n)]
p = pv.Plotter(off_screen=True, window_size=[400,300])
for k, c in enumerate(centers):
    p.add_mesh(pv.Box(pv.Sphere(r, c).bounds), name='tmp{:d}'.format(k))
p.show(screenshot='boxes.png')
p.close()
```

Thanks for the workaround.
Mario
