### ISSUE TITLE
Strange result of clip_surface()

### ISSUE THREAD

**Issue by mkondratyev85** [pyvista/pyvista-support#116]
## Description

Sometimes, when I use `clip_surface()` method, the result I get is just an initial mesh with irregular holes with strange pattern.

## Example Data

Consider I have a mesh and a surface:

```python
import numpy as np
import pyvista as pv


x = np.arange(-10, 10, 0.5)
y = np.arange(-10, 10, 0.5)
x, y = np.meshgrid(x,y)
r = np.sqrt(x**2 + y**2)
z2 = np.sin(r) + 5
z1 = np.zeros_like(z2)

grid1 = pv.StructuredGrid(x, y, z1)
grid2 = pv.StructuredGrid(x, y, z2)

merged = pv.StructuredGrid()
merged.points = np.vstack((grid1.points, grid2.points))
merged.dimensions = [*grid1.dimensions[0:2], 2]

intrusion = pv.ParametricEllipsoid(10, 5, 5).cast_to_unstructured_grid()

p = pv.Plotter()
p.add_mesh(intrusion, show_edges=True)
p.add_mesh(merged, show_edges=True)
p.show()
```

![mesh1](https://user-images.githubusercontent.com/32978900/73498701-1f182e80-4412-11ea-8694-9d7ef6f262a3.png)

And then I clip the mesh with surface.

```python
clip = merged.clip_surface(intrusion)
clip.plot()
```

![mesh2](https://user-images.githubusercontent.com/32978900/73498745-3eaf5700-4412-11ea-92fa-92092f73405b.png)

What is it? A bug? Sometimes the clipping method works fine and sometimes it fails. I've tried to cast the grid as unstructured or structured, I've tried to export geometry, non of these approaches seemed to affect the result.

**Comment by banesullivan** [comment]
Huh, that's crazy looking. The `clip_surface` filter can really struggle if the surface used for the clipping isn't closed/watertight or if anything is off about the surface.

For example if your change `intrusion = pv.Sphere(10)` then all works. I think in this case, the `ParametricEllipsoid` is producing a bad mesh for clipping as it isn't technically closed. We can use `pymeshfix` to reveal the holes:

```py
import pymeshfix
fixer = pymeshfix.MeshFix(intrusion)
holes = fixer.extract_holes()

p = pv.Plotter()
p.add_mesh(intrusion)
p.add_mesh(holes, color="red", line_width=10)
p.show()
```

![download](https://user-images.githubusercontent.com/22067021/73500094-14f92000-437f-11ea-8aa7-faf9bfebeffc.png)


unfortunately, PyMeshFix is segfaulting when repairing that mesh.... and PyVista's `fill_holes` filter cannot be counted on

**Comment by mkondratyev85** [comment]
Huh! Is there a reliable way to make sure that my surface is good enough for the `clip_surface()` before calling this method? Something like checking `holes` after this snipped?

```python
import pymeshfix
fixer = pymeshfix.MeshFix(intrusion)
holes = fixer.extract_holes()
```

Something like to check if there is any holes?

**Comment by mkondratyev85** [comment]
I've changed the code by using your advice and everything works fine. Thanks.

Here is the working snipped:

```python
import numpy as np
import pyvista as pv


x = np.arange(-10, 10, 0.5)
y = np.arange(-10, 10, 0.5)
x, y = np.meshgrid(x,y)
r = np.sqrt(x**2 + y**2)
z2 = np.sin(r) + 5
z1 = np.zeros_like(z2)

grid1 = pv.StructuredGrid(x, y, z1)
grid2 = pv.StructuredGrid(x, y, z2)

merged = pv.StructuredGrid()
merged.points = np.vstack((grid1.points, grid2.points))
merged.dimensions = [*grid1.dimensions[0:2], 2]

# create an ellipsoid from a sphere
intrusion = pv.Sphere(10)
transform_matrix = np.eye(4)
transform_matrix[0,0] = 0.5
transform_matrix[1,1] = 0.4

intrusion.transform(transform_matrix)

p = pv.Plotter()
p.add_mesh(intrusion, show_edges=True)
p.add_mesh(merged, show_edges=True)
p.show()

clip = merged.clip_surface(intrusion)
clip.plot(show_edges=True)

```

![mesh3](https://user-images.githubusercontent.com/32978900/73501194-1c6d0780-4419-11ea-840c-74c60c81f7b4.png)

**Comment by banesullivan** [comment]
Take a look at the `n_open_edges` property of `PolyData` meshes: https://docs.pyvista.org/core/points.html#pyvista.PolyData.n_open_edges

If it is greater than zero then it’s not a closed surface!

Thing is, we don’t check that in the `clip_surface` filter because curvi-planar surface can be used (and I use them often to clip geological models by faulting surfaces)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by banesullivan** [comment]
I totally think I just made up the term “curvi-planar” but hopefully you get what I mean

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by banesullivan** [comment]
It might be good to document this behavior/make a dedicated example to surface clipping

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mkondratyev85** [comment]
So the surface have to be watertight only in the part where it intersects the volume of the mesh?

**Comment by banesullivan** [comment]
Not exactly. The surface clipping algorithm struggles when the clipping surface folds back on itself without being watertight (regardless of where it intersects the mesh being clipped). For example, the original surface that you used was folding back on itself without closing, but we could use open surfaces that do not fold back on themselves, like a corner or curvy surface.

If you are trying to extract regions of interest from a mesh, the surface needs to be watertight. If you are trying to clip one extent of the mesh by a surface, it can be open.
