### ISSUE TITLE
Saving mesh into legacy vtk version 2.0

### ISSUE THREAD

**Issue by mkondratyev85** [pyvista/pyvista-support#117]
Is there a way to save a mesh created with pyvista in vtk legacy format of version 2.0?

**Comment by mkondratyev85** [comment]
I've tried to use this snipped but it still saves in version 4.2 not 2.0

```python
import vtk
writer = vtk.vtkUnstructuredGridWriter()
writer.SetFileName("/tmp/output.vtk")
writer.SetInputDataObject(mesh)
writer.Write()
```

**Comment by banesullivan** [comment]
Hi @mkondratyev85! Unfortunately, we do not support writing to legacy formats in PyVista. Please see https://github.com/pyvista/pyvista/issues/254#issuecomment-501917396 and perhaps head to [discourse.vtk.org](https://discourse.vtk.org) to see if VTK supports writing to legacy formats.

And note that [`pyvtk`](https://github.com/pearu/pyvtk) might have some functionality for writing to legacy formats but isn't something we plan to incorporate into PyVista

**Comment by banesullivan** [comment]
@mkondratyev85, if you find a way to successfully write out a PyVista data set to legacy format 2.0 using `pyvtk` or another library, please share it here for other users to find!

**Comment by mkondratyev85** [comment]
I was trying to save the mesh to use it with Sfepy (http://sfepy.org/). Unfortunately right now sfepy reads only 2.0 vtk version. You can check this link for more context https://github.com/sfepy/sfepy/issues/578#issuecomment-581159145. 

The author has showed me the way to convert vtk mesh to the format that is readable by Sfepy, but I'm afraid this way is useless for all the other cases, unfortunately.

**Comment by banesullivan** [comment]
Ah, thanks for following up!
