### ISSUE TITLE
remove_actor

### ISSUE THREAD

**Issue by bistek** [pyvista/pyvista-support#121]
Hello, I am trying to remove a PolyData object from a BackgroundPlotter.

I create the plotter and add the PolyData simply with:

```
plotter = pv.BackgroundPlotter()
plotter.add_mesh(polydata_object)
```

Then to remove it I suppose I have to do just this:

`plotter.remove_actor(plot_object)`

However I get this error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\Anaconda3\lib\site-packages\pyvista\plotting\plotting.py in remove_actor(self, actor, reset_camera)
   2077         """
   2078         for renderer in self.renderers:
-> 2079             renderer.remove_actor(actor, reset_camera)
   2080         return True
   2081 

~\Anaconda3\lib\site-packages\pyvista\plotting\renderer.py in remove_actor(self, actor, reset_camera)
    957         # First remove this actor's mapper from _scalar_bar_mappers
    958         _remove_mapper_from_plotter(self.parent, actor, False)
--> 959         self.RemoveActor(actor)
    960 
    961         if name is None:

TypeError: RemoveActor argument 1: method requires a vtkProp, a vtkPolyData was provided.
```

I have seen that there was an issue, recently closed, on this topic, so I upgraded PyVista with pip to the last release 0.23.1, but I still got the same error.

Now I have some different hypotheses:

- the issue is still not solved on the pip release.
- the issue is still not solved for BackgroundPlotter.
- I am doing something wrong

Thanks!

**Comment by GuillaumeFavelier** [comment]
Hello @bistek ,

The error message you posted helped me understand the situation, thank you for sharing. So it appears that you tried to call `remove_actor()` with a `vtkPolyData` object,  I suppose `plot_object` is the name of the object you send to `add_mesh()` or you plotted somehow?

In PyVista's API, the functions like [`add_mesh`](https://docs.pyvista.org/plotting/plotting.html?highlight=add_mesh#pyvista.BasePlotter.add_mesh) will return a `vtkActor` object. You can call `remove_actor()` on this object. 

I would do the following:

```py
...
plotter = pv.BackgroundPlotter()
actor = plotter.add_mesh(plot_object)
plotter.remove_actor(actor)
```

Let me know if this was helpful.

**Comment by bistek** [comment]
Hello and thanks very much for the prompt answer. This works if I have just one actor, but suppose I have several mesh that I plot in a for loop.

I've created an actor for each mesh with a dictionary like this:

```
actor = dict()
i = 0
for plot_object in <my objects here>:
    actor[i] = plotter.add_mesh(plot_object)
    i += 1
```

This works and I can do for instance `plotter.remove_actor(actor[3])`, but it is a bit complicated. It would be easier to have a `remove_mesh` method.

Thanks!

**Comment by GuillaumeFavelier** [comment]
Oh okay! Well there is also the option to name your meshes with `add_mesh()`:

```py
i = 0
for plot_object in <my objects here>:
    plotter.add_mesh(plot_object, name="mesh_{}".format(i))
    i += 1
```

Then you can remove any of them with: `remove_actor("mesh_3")`

**Comment by bistek** [comment]
Thanks!
