### ISSUE TITLE
BackgroundPlotter custom menus and buttons

### ISSUE THREAD

**Issue by bistek** [pyvista/pyvista-support#122]
Hello, I was wondering if there is an already tested way to add custom menus and buttons to the BackgroundPlotter. I guess it should be possible since in the end it is a Qt window. I have not been able to find an example.

Thanks!

**Comment by banesullivan** [comment]
Hi there, we've been working on expanding how users can customize the `BackgroundPlotter` with buttons/menus. You can currently do this, but the interface isn't all that clean. We are hoping to expand [`pyvista-gui`](https://github.com/pyvista/pyvista-gui) into a fully customizable suite with tons of templates/easy to add features but we haven't had the time yet to make it functional.

In the meantime, here is an example of how to add custom menus and a toolbar to the `BackgroundPlotter`:


```py
import pyvista as pv
from pyvista import examples

from PyQt5.QtWidgets import  QAction


st_helens = examples.download_st_helens().warp_by_scalar()


plotter = pv.BackgroundPlotter()

def add_st_helens():
    plotter.add_mesh(st_helens, name="st helens")

# Add a drop down menu
user_menu = plotter.main_menu.addMenu('My Features')
user_menu.addAction('Add St. Helens', add_st_helens)

# Add a toolbar
def add_action(toolbar, key, method, main_window):
    action = QAction(key, main_window)
    action.triggered.connect(method)
    toolbar.addAction(action)
    return

user_toolbar = plotter.app_window.addToolBar('User Toolbar')
add_action(user_toolbar, 'Line Widget', plotter.add_line_widget, plotter.app_window)
```

![2020-02-09 12 37 49](https://user-images.githubusercontent.com/22067021/74108582-078b2500-4b39-11ea-8bf1-b082112a5543.gif)

**Comment by bistek** [comment]
Good, thanks!

BTW, how do I access properties of the line widget? Particularly coordinates of the end points.

Thanks!

**Comment by banesullivan** [comment]
You’d need to pass a callback method when activating the line widget. See https://docs.pyvista.org/plotting/widgets.html#line-widget

So in order to have a Qt button handle all that, you’d need a custom function to properly call the `add_line_widget` method with your callback

Something like

```py
def line_callback(a, b):
    # do stuff with the two points
    pass

def add_line():
    plotter.add_line_widget(line_callback)

# put add_line on the Qt button
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bistek** [comment]
Great thanks!

**Comment by bistek** [comment]
Dear Bane, we have another problem with the background plotter. We are using `enable_path_picking` to pick lines in a plotter where we have some mesh. The meshes are in UTM coordinates, with very large numbers like [540169.0, 5094171.2, 2316.6] and I suspect that this is part of the problem since when we were testing on small objects the problem was less pronounced.

The problem is two-sided:

1) The `enable_path_picking` tool returns nodes of the underlying mesh, and if the mesh has a coarse resolution, these points are very far apart. I tried to see if it is possible to use the `use_mesh=False` option as in the underlying method `enable_point_picking`, but it does not work.

2) This is the part of the problem that I think is related to large coordinates. When using meshes in UTM the picking is even more erratic, and this results in completely messed up paths.

Thanks!

**Comment by bistek** [comment]
One more question. Is there a method to click on an object and "select" it , or get the name of the actor?

**Comment by banesullivan** [comment]
Apologies for the delay on this. @bistek, would you please open a new issue about these picking issues? In the meantime, I'll try to find a solution

**Comment by bistek** [comment]
Done #133, thanks!

**Comment by HametAl** [comment]
> Hi there, we've been working on expanding how users can customize the `BackgroundPlotter` with buttons/menus. You can currently do this, but the interface isn't all that clean. We are hoping to expand [`pyvista-gui`](https://github.com/pyvista/pyvista-gui) into a fully customizable suite with tons of templates/easy to add features but we haven't had the time yet to make it functional.
> 
> In the meantime, here is an example of how to add custom menus and a toolbar to the `BackgroundPlotter`:
> 
> ```python
> import pyvista as pv
> from pyvista import examples
> 
> from PyQt5.QtWidgets import  QAction
> 
> 
> st_helens = examples.download_st_helens().warp_by_scalar()
> 
> 
> plotter = pv.BackgroundPlotter()
> 
> def add_st_helens():
>     plotter.add_mesh(st_helens, name="st helens")
> 
> # Add a drop down menu
> user_menu = plotter.main_menu.addMenu('My Features')
> user_menu.addAction('Add St. Helens', add_st_helens)
> 
> # Add a toolbar
> def add_action(toolbar, key, method, main_window):
>     action = QAction(key, main_window)
>     action.triggered.connect(method)
>     toolbar.addAction(action)
>     return
> 
> user_toolbar = plotter.app_window.addToolBar('User Toolbar')
> add_action(user_toolbar, 'Line Widget', plotter.add_line_widget, plotter.app_window)
> ```
> 
> ![2020-02-09 12 37 49](https://user-images.githubusercontent.com/22067021/74108582-078b2500-4b39-11ea-8bf1-b082112a5543.gif) [ ![2020-02-09 12 37 49](https://user-images.githubusercontent.com/22067021/74108582-078b2500-4b39-11ea-8bf1-b082112a5543.gif) ](https://user-images.githubusercontent.com/22067021/74108582-078b2500-4b39-11ea-8bf1-b082112a5543.gif) [ ](https://user-images.githubusercontent.com/22067021/74108582-078b2500-4b39-11ea-8bf1-b082112a5543.gif)

Is there a way to remove default items from menu bar and toolbar, or we need to disable the default menu and tool bars and then define and add our own menu and tool bars?
