### ISSUE TITLE
Multiple colors for geometric objects while plotting

### ISSUE THREAD

**Issue by bhaveshshrimali** [pyvista/pyvista-support#123]
Hi,
I just stumbled upon pyvista and was intrigued by it's functionality. Great tool!
I had a simple question regarding plotting the geometries. 
For instance, is it possible to plot the union of different geometric objects, each with it's own color? 
For example, fo a union of two spheres inside of a box, namely
```
import pyvista as pv

s1 = pv.Sphere(radius=0.1, center=(0.5,0.5,0.5))
s2 = pv.Sphere(radius=0.1, center=(0.25,0.2,0.6))
b = pv.Box(bounds=(0,1,0,1,0,1))
bs = (s2 + s1) + b
bs.plot(background_color="blue", opacity=0.5) # I tried a few things here but no success yet
```
I would want a separate color for the spheres `s1 + s2` and the box `b`. Is it possible?

**Comment by bhaveshshrimali** [comment]
Update: I tried the following but this doesn't let me interact with the plot. I am able to save the final plot which does my job for now but would like to know if there is a way to interact
```
plt = pv.Plotter()
plt.add_mesh(s1, color="red", label = r"Sphere")
plt.add_mesh(s2, color="red", label = r"Sphere2")
plt.add_mesh(b, color="blue", opacity=0.5, show_edges=True, label=r"Cube")
plt.isometric_view_interactive()
plt.show(interactive=True)
```
This closes the window automatically. I am running on Windows10 and `python-3.7`. Any suggestions ?

**Comment by banesullivan** [comment]
So, you may want to read up on boolean operations in https://docs.pyvista.org/examples/01-filter/boolean-operations.html where the `+` operator is a `boolean_add` for `PolyData` meshes and a merging method for all other mesh types.

To perform a boolean union, use the `boolean_union()` filter: https://docs.pyvista.org/examples/01-filter/boolean-operations.html#boolean-union

And then you can use the added `"PointSource"` scalars array to see which parts of the created mesh came from which input:

```py
import pyvista as pv
import numpy as np

def make_cube():
    x = np.linspace(-0.5, 0.5, 25)
    grid = pv.StructuredGrid(*np.meshgrid(x, x, x))
    return grid.extract_surface().triangulate()

# Create to examplee PolyData meshes for boolean operations
sphere = pv.Sphere(radius=0.65, center=(0, 0, 0))
cube = make_cube()

# Boolean union
union = sphere.boolean_union(cube)

# Show it
p = pv.Plotter()
p.add_mesh(union, opacity=0.75, show_edges=True, 
           scalars="PointSource", cmap=["red", "blue"])
p.show()
```

----- 

For your issue with showing the plotter... are you running inside a python script, IPython, jupyter notebook, or what?

Also, don't use `isometric_view_interactive()`, just `isometric_view()`

**Comment by banesullivan** [comment]
Also, the boolean operations we offer aren't the best... I'd recommend using a library more focused on boolean operations and then use PyVista for plotting. [`pymesh `](https://pymesh.readthedocs.io/en/latest/mesh_boolean.html) looks really great!

**Comment by bhaveshshrimali** [comment]
I'd check out `pymesh`. I am going to try out the tutorials as you suggested above. Regarding the plotter, I was running a python script in windows command prompt. 

I have tried reproducing the same on Ubuntu but have run into another issue. When I run the following code, I get a blank screen (I believe it should plot the box right?)

```python
import pyvista as pv 
s1 = pv.Sphere(radius=0.1, center=(0.5,0.5,0.5))
s2 = pv.Sphere(radius=0.1, center=(0.25,0.3,0.6))
b1 = pv.Box(bounds=(0,1,0,1,0,1))
b1.plot()  #this plots the box without any problems
pvplt = pv.Plotter()
pvplt.add_mesh(b1, color="blue", opacity=0.5, label=r"box", show_edges=True)
# pvplt.add_mesh(s1, color="red", label=r"sphere1")
# pvplt.add_mesh(s2, color="red", label=r"sphere2")
pvplt.view_isometric()
pvplt.save_graphic("trialBox.pdf")
pvplt.show()
```

[trialBox.pdf](https://github.com/pyvista/pyvista-support/files/4182121/trialBox.pdf)

**Comment by banesullivan** [comment]
Huh. That's odd. Can you share a `Report()`:

```py
import pyvista as pv
print(pv.Report())
```

Try taking away the call to `pvplt.view_isometric()`... we technically do that by default and I'm wondering if the camera's clipping planes are not properly set when you call that (which would be a bug)

**Comment by bhaveshshrimali** [comment]
I checked, if I specify `opacity < 1` it doesn't plot the box. For instance, 
```python
import pyvista as pv 
import numpy as np
def make_cube():
    x = np.linspace(0, 1, 25)
    grid = pv.StructuredGrid(*np.meshgrid(x, x, x))
    return grid.extract_surface().triangulate()

s1 = pv.Sphere(radius=0.1, center=(0.5,0.5,0.5))
s2 = pv.Sphere(radius=0.1, center=(0.25,0.3,0.6))
b1 = pv.Box(bounds=(0.,1,0,1,0,1))  #make_cube() works fine too!
# b1.plot()
pvplt = pv.Plotter()
pvplt.add_mesh(b1, color="blue", opacity=1)
# pvplt.add_mesh(s1, color="red", opacity=1, label=r"sphere1")
# pvplt.add_mesh(s2, color="red",opacity=1, label=r"sphere2")
pvplt.view_isometric()
pvplt.save_graphic("trialBox.pdf")
pvplt.show()
```

[trialBox.pdf](https://github.com/pyvista/pyvista-support/files/4182166/trialBox.pdf)

**Comment by bhaveshshrimali** [comment]
This is the report. I am pretty sure I got it to work on another linux machine. At least the images weren't clipped

```
--------------------------------------------------------------------------------
  Date: Mon Feb 10 11:23:29 2020 CST

             Linux : OS
                24 : CPU(s)
            x86_64 : Machine
             64bit : Architecture
            Python : Environment
        GPU Vendor : nouveau
      GPU Renderer : NV98
       GPU Version : 3.3 (Core Profile) Mesa 19.2.8

  Python 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]

            0.23.1 : pyvista
             8.1.2 : vtk
            1.18.1 : numpy
             2.6.1 : imageio
             1.4.3 : appdirs
             0.5.1 : scooby
             3.1.2 : matplotlib
            7.12.0 : IPython
--------------------------------------------------------------------------------

```

**Comment by banesullivan** [comment]
Ahh... Mesa. Are you in a VM? You may have to jump through some hoops to properly set up OpenGL

**Comment by bhaveshshrimali** [comment]
No, I am not running on a VM. Do you have any specific instructions on setting up OpenGL ?

**Comment by bhaveshshrimali** [comment]
And this is the report for the windows machine where the plotter is not rendered interactive. 
--------------------------------------------------------------------------------
  Date: Mon Feb 10 11:50:50 2020 Central Standard Time

           Windows : OS
                 8 : CPU(s)
             AMD64 : Machine
             64bit : Architecture
            Python : Environment
        GPU Vendor : Intel
      GPU Renderer : Intel(R) HD Graphics P630
       GPU Version : 4.5.0 - Build 26.20.100.7106

  Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64
  bit (AMD64)]

            0.23.2 : pyvista
             8.1.2 : vtk
            1.17.4 : numpy
             2.6.1 : imageio
             1.4.3 : appdirs
             0.5.1 : scooby
             3.1.2 : matplotlib
            7.10.1 : IPython
             1.3.3 : scipy
--------------------------------------------------------------------------------

**Comment by banesullivan** [comment]
I don't have any detailed install instructions as it's only needed on VMs. This is very, very odd. Especially since `b1.plot()` works fine for you. Does the window that appears show the cube but not the PDF?

**Comment by banesullivan** [comment]
and does `pvplt.screenshot("trialBox.png")` work instead of `pvplt.save_graphic("trialBox.pdf")`?

**Comment by bhaveshshrimali** [comment]
Yes, precisely that. Everything appears fine on the window, but the saved `pdf`/`png`/`svg` files are clipped (on the linux workstation). 

Everything works fine on windows except that the plotter is not interactive. I can do fine with this for now, but would be interseting to know the issue on linux workstation (and if there is a fix).

[trialBox.pdf](https://github.com/pyvista/pyvista-support/files/4182332/trialBox.pdf)

I must add that the hardware on the linux machine is old (~2011) and I don't know if that has to do something with the problem. I haven't used/tested OpenGL on it.

**Comment by banesullivan** [comment]
Ah. hm. the Linux machine might need some updating then... I can't speak too much to what would be needed there.

> Everything works fine on windows except that the plotter is not interactive. I can do fine with this for now, but would be interseting to know the issue on linux workstation (and if there is a fix).

The plotting window should be interactive... can you share exactly how you are running that code and perhaps a screen capture if the plotter appears then disappears?

---

also! on the windows VM, I see you have PyVista 0.23.2 installed. This is a broken version we took down from PyPI yesterday (it's probably still live on mirrors). Beware that you may need to downgrade to 0.23.1 for some features. ref https://github.com/pyvista/pyvista/issues/600

**Comment by bhaveshshrimali** [comment]
I can do a screen capture in sometime. I did `pip`-installed it. Can do a fresh 0.23.1 install just to see

**Comment by bhaveshshrimali** [comment]
So this is what happens when run on Windows 10. You can skip to the 45 sec mark on `Renderer.mp4` (attached here as a zip file) where it crashes. It saves the graphic as expected though (`pdf` file).

[sphMono_fo_ 25.pdf](https://github.com/pyvista/pyvista-support/files/4195329/sphMono_fo_.25.pdf)

[Renderer.zip](https://github.com/pyvista/pyvista-support/files/4195325/Renderer.zip)

**Comment by bhaveshshrimali** [comment]
The report on windows. I uninstalled `0.23.2` and then `pip`-installed `0.23.1`
![image](https://user-images.githubusercontent.com/22624037/74383641-344b7080-4db5-11ea-8a07-4fdb86ec130f.png)

**Comment by banesullivan** [comment]
That screen recording is odd behavior. Can you share the plotting part of your code?

**Comment by bhaveshshrimali** [comment]
```python
def plotSpheres(xc, rc, fo):
    """
    docstring
    """
    pvplt = pv.Plotter()
    pvplt.add_mesh(pv.Box(bounds=(0,1,0,1,0,1)), color="blue", opacity=0.3, show_edges=True)
    for idx_sph, sph in enumerate(xc):
        pvplt.add_mesh(pv.Sphere(radius=rc[idx_sph], center=(sph[0], sph[1], sph[2])), color="red")
    pvplt.view_isometric()
    # pvplt.save_graphic("sphMono_{0:.2f}.eps".format(fo))
    pvplt.save_graphic("sphMono_fo_{0:3d}.pdf".format(int(100*fo)))
    pvplt.show()

```

It runs absolutely fine on my Ubuntu machine (laptop). 
```
--------------------------------------------------------------------------------
  Date: Wed Feb 12 19:22:47 2020 CST

             Linux : OS
                 4 : CPU(s)
            x86_64 : Machine
             64bit : Architecture
            Python : Environment
        GPU Vendor : Intel Open Source Technology Center
      GPU Renderer : Mesa DRI Intel(R) Sandybridge Mobile
       GPU Version : 3.3 (Core Profile) Mesa 19.2.8

  Python 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]

            0.23.1 : pyvista
             8.1.2 : vtk
            1.17.0 : numpy
             2.6.1 : imageio
             1.4.3 : appdirs
             0.5.1 : scooby
             3.1.1 : matplotlib
            5.13.0 : PyQt5
             7.7.0 : IPython
--------------------------------------------------------------------------------

```

**Comment by banesullivan** [comment]
Pinging @pyvista/developers, any idea why the plotter is automatically disappearing here?

**Comment by bhaveshshrimali** [comment]
Just to add, I tested the above code on yet another Windows machine and it seems to work without any problems (perhaps the only windows system so far that allows an interactive plot that I need). I will keep looking out as to why the plotter disappears on my laptop.

**Comment by bhaveshshrimali** [comment]
[This](https://github.com/pyvista/pyvista-support/issues/128#issuecomment-585932976) seems to do the trick, so essentially
```python
pvplt.disable_depth_peeling()
```
does the trick and `plotter` no longer disappears automatically. I just browsed through that issue and tried to see if disabling `depth-peeling` worked.

**Comment by akaszynski** [comment]
Yep, we should disable depth peeling by default.

**Comment by julienfranz** [comment]
Hi, I am not sure if this is related to this thread, but I want to do the same thing in my plot.
I have a .mesh file having 2 arrays (each corresponds to the interior and exterior part of the mesh): e.g,

--

Header | Data Arrays
-- | --
UnstructuredGridInformationN Cells29111N Points5435X Bounds-8.884e-01, 8.861e-01Y Bounds-1.095e+00, 1.167e+00Z Bounds-1.000e+00, 1.267e+00N Arrays2 | N Cells | 29111 | N Points | 5435 | X Bounds | -8.884e-01, 8.861e-01 | Y Bounds | -1.095e+00, 1.167e+00 | Z Bounds | -1.000e+00, 1.267e+00 | N Arrays | 2 | NameFieldTypeN CompMinMaxmedit:refPointsfloat6410.000e+003.000e+00medit:refCellsint6410.000e+003.000e+00 | medit:ref | Points | float64 | 1 | 0.000e+00 | 3.000e+00 | medit:ref | Cells | int64 | 1 | 0.000e+00 | 3.000e+00

N Cells | 29111
N Points | 5435
X Bounds | -8.884e-01, 8.861e-01
Y Bounds | -1.095e+00, 1.167e+00
Z Bounds | -1.000e+00, 1.267e+00
N Arrays | 2

medit:ref | Points | float64 | 1 | 0.000e+00 | 3.000e+00
medit:ref | Cells | int64 | 1 | 0.000e+00 | 3.000e+00

--

Now, I want to plot the two surfaces in different colors? Is this possible? The exterior surface is originally labeled by 0 and the interior by 1. Thank you.
