### ISSUE TITLE
All edges of a mesh

### ISSUE THREAD

**Issue by bvafa** [pyvista/pyvista-support#124]
## Description
Hi,
Is there any direct method to get all edges of a mesh?
I know I can extract all the faces and then compute unique edges out of them. I wrote a code that uses sets, but it is a bit slow. I thought there should be a faster way.

Thank you

**Comment by akaszynski** [comment]
Is this a triangular or mixed face mesh?  There’s a trick with meshes with just triangular faces.

**Comment by bvafa** [comment]
Just a triangular mesh.
Thanks

**Comment by akaszynski** [comment]
This should work for you
```python
import numpy as np
import pyvista

sphere = pyvista.Sphere()

assert sphere.is_all_triangles(), 'this trick only works with triangular meshes'

# get the faces with one row per face (includes vtk padding)
faces = sphere.faces.reshape(-1, 4)

# extract all edges (triangle is ABC)
edges0 = faces[:, 1:3]  # edges AB
edges1 = faces[:, (1, 3)]  # edges AC
edges2 = faces[:, 2:]  # edges BC

# stack
edges = np.vstack((edges0, edges1, edges2))

# make a polydata
edges_with_padding = np.empty((edges.shape[0], 3), np.int32)
edges_with_padding[:, 0] = 2
edges_with_padding[:, 1:] = edges

edges_pd = pyvista.PolyData(sphere.points, edges_with_padding.ravel())

edges_pd = pyvista.PolyData()
edges_pd.plot(style='wireframe')
```

**Comment by banesullivan** [comment]
What about the `wireframe()` filter?

```py
edges = sphere.wireframe()

edges.plot(color="k")
```

![download](https://user-images.githubusercontent.com/22067021/74185124-44bce900-4c05-11ea-9cb7-03a8a921b1bf.png)

Then you can access all the edges as line segments:

```py
>>> edges.lines
array([  2,   0,   1, ...,   2,  31, 841])
```

**Comment by akaszynski** [comment]
@banesullivan, nice!  Yes, that's a little easier.

**Comment by banesullivan** [comment]
I must admit, the naming of the [`wireframe()`](https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.wireframe) and [`extract_edges()`](https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.extract_edges) filters wasn't thought out too well... `wireframe()` wraps the `vtkExtractEdges ` algorithm and `extract_edges()` wraps the `vtkFeatureEdges` algorithm

**Comment by akaszynski** [comment]
Maybe the naming isn't the best, but it might be tough to change it at this point.  Think it's worth it to change?

**Comment by banesullivan** [comment]
It would be a high impact change... we are still sub version 1 so as long as we throw in deprecation warnings its fair. I know I use both of those filters a lot in old code, so it might get annoying to fix

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bvafa** [comment]
Thank you all.
I also tried, `extract_edges` with feature angle of 0; do you think the property `lines` of that method would also contain all the edges?

**Comment by banesullivan** [comment]
Nope, I gave `extract_edges` with a feature angle of 0 and it didn't quite get all of them. The `wireframe` filter will though

**Comment by bvafa** [comment]
Thanks a lot.

**Comment by banesullivan** [comment]
I'm going to leave this open until we decide if those filters should be renamed. Perhaps:

- `extract_edges` -> `extract_feature_edges`
- `wireframe` -> `extract_all_edges`

**Comment by akaszynski** [comment]
That's much better.  Since we're not switching names, adding a degenerated method warning wouldn't be too difficult.
