### ISSUE TITLE
Girth measurement from 3D model

### ISSUE THREAD

**Issue by Huzaifi96** [pyvista/pyvista-support#126]
Hi, 

I have been working on 3d body measurement. In this case, I have used the plane widget to slice the head of 3d human model and get the sliced meshes. Therefore, I would like to know if there is any method to get the **girth/circumference** of this sliced meshes.

Here is the code:

```py
import pyvista as pv
import numpy as np

vol = pv.PolyData('C:/Users/huzai/Desktop/hms ff.stl')
p = pv.Plotter(notebook=False)
p.add_mesh(vol)
p.add_mesh_slice(vol,normal='z',generate_triangles=False,widget_color='Blue')
p.show_axes()
p.show()

w = p.plane_sliced_meshes # to get sliced meshes

sliced = w[0]
sliced.plot()
```

from `p.show()` :
![sliced](https://user-images.githubusercontent.com/58688246/74217658-0dbd0500-4ce3-11ea-9541-87ba4d0c4fa7.jpg)

and from `sliced.plot()` : 

![sliced head](https://user-images.githubusercontent.com/58688246/74217796-6ab8bb00-4ce3-11ea-8954-6bf583719ae4.png)

**Comment by akaszynski** [comment]
Could you please upload the scan here?  We're really just trying to get the total line length, and I think I can grab that but I'd like to demo it on your mesh.

**Comment by banesullivan** [comment]
That slice of a surface mesh should produce line cells, so you can use the `compute_arc_length` filter to get the total distance around the slice as each line cell will have a distance. Here I do the exact same workflow with our example human mesh:

```
from pyvista import examples
vol = examples.download_human()
```

```py
>>> np.sum(sliced.compute_arc_length()["arc_length"])
72.22151
```

another option is to use the `compute_cell_sizes` filter which is a bit more general and will work for all mesh types:

```py
np.sum(slc.compute_cell_sizes()["Length"])
72.22151550425204
```

**Comment by Huzaifi96** [comment]
> Could you please upload the scan here? We're really just trying to get the total line length, and I think I can grab that but I'd like to demo it on your mesh.

@akaszynski , here is the scan model
[human model.zip](https://github.com/pyvista/pyvista-support/files/4189379/human.model.zip)

**Comment by Huzaifi96** [comment]
@banesullivan  It works ! , I have try using both `compute_arc_length` and `compute_cell_sizes` method :

`np.sum(sliced.compute_arc_length()["arc_length"])`
`103.16757`

and

`np.sum(sliced.compute_cell_sizes()["Length"])`
`103.16756947859025`

**Comment by akaszynski** [comment]
Excellent, thanks @banesullivan and @Huzaifi96.  I think adding this to `examples.downloads` would be really helpful, maybe even as a gallery example.
