### ISSUE TITLE
selecting/picking a line

### ISSUE THREAD

**Issue by bvafa** [pyvista/pyvista-support#127]
## Description
Good day,
I have a set of points on a triangular mesh. The points are either on the edges of the mesh or on the vertices of the mesh. The sequences of these points creates lines (i.e line segments). I plot both the mesh and the lines and use `enable_point_picking` method of the plotter. Now, I need to be able to select any lines. Is there any method?
Currently, I have defiled a line class that stores tail and head points of a line (sequence of points). When I plot the lines, I also plot  tail and head points corresponding to the lines' tail and head points using `add_points`. These plotted points have different colors and are rendered as spheres for better visualization. Then I can pick those points in the plotter view and find the line that contains tail/head points close to the picked points (a tolerance is defined). In this way I can select a line.
I want to know if there is any better/direct way.

Thank you so much,

**Comment by banesullivan** [comment]
Have you tried `enable_cell_picking()`? Lines are cells, so you should be able to pick individual lines that way.

When plotting the tail and head points of the lines, be sure to set `pickable=False` on those so that the picker only sees the lines

**Comment by banesullivan** [comment]
Here is an example:

```py
from pyvista import examples
import pyvista as pv

# Whole bunch of lines that make a mesh
mesh = examples.download_bunny_coarse().triangulate().wireframe()

p = pv.Plotter(notebook=False)
p.add_mesh(mesh, pickable=True)
p.enable_cell_picking(through=False)
p.add_points(mesh.points, pickable=False, color="red", render_points_as_spheres=True)
p.show()
```

![2020-02-11 09 59 40](https://user-images.githubusercontent.com/22067021/74259562-5362d900-4cb5-11ea-9b1d-284b54863545.gif)

**Comment by bvafa** [comment]
Thank you. I tried something like this but no success:
```
someMesh = # a triangular mesh
p = pv.Plotter(notebook=False)
p.add_mesh(someMesh, pickable=False, name="mymesh")
linePoints_1 = # nparray of points (point coordinates). they can be located on or close to "someMesh"
linePoints_2 =  # nparray of points. they can be located on or close to "someMesh"
p.add_lines(linePoints_1, name="myline1")
p.add_lines(linePoints_2, name="myline2")
p.enable_cell_picking(through=False)
p.show()
```

Many thanks,

**Comment by banesullivan** [comment]
Sorry for the delay on this, @bvafa... There's no way we could tell what wasn't working without including your data and/or screenshots

Also, visible cell picking may have had some issues as outlined in https://github.com/pyvista/pyvista/pull/799 that you may have been experiencing
