### ISSUE TITLE
Plotter window freezes when setting opacity for add_mesh

### ISSUE THREAD

**Issue by danpak94** [pyvista/pyvista-support#128]
## Description

The plotter window freezes when I try to set the opacity value to any value other than 1 for the `add_mesh` function. This problem also seems to occur when I'm using constant color; if I use `mesh = py.Plane()` instead (which contains `mesh.point_arrays['TextureCoordinates']`), the window no longer freezes.

I reproduced this error on both Spyder and command prompt. I am using Python version 3.6.6, pyvista version 0.23.1 (conda-forge).

I would really appreciate your help solving this issue!

Edit: problem occurs on Windows 10 with Python 3.6.6, but not on Ubuntu 16.04.02 LTS with Python 3.6.10..

Simple code to reproduce the issue:

```py
import argparse
import pyvista as pv
from pyvista import examples

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("-o", "--opacity", default=1, type=float)
    args = parser.parse_args()
    
    opacity = args.opacity
    
    print('opacity: {}'.format(opacity))
    
    mesh = examples.download_bunny_coarse()
    # mesh = py.Plane()
    
    plotter = pv.Plotter(notebook=False)
    actor = plotter.add_mesh(mesh, opacity=opacity)
    plotter.show()
```

## Example Data

No example data provided because issue is reproducible with meshes provided within the library.

**Comment by banesullivan** [comment]
Can you share a report: `print(pv.Report())`

**Comment by danpak94** [comment]
--------------------------------------------------------------------------------
  Date: Thu Feb 13 14:17:30 2020 Eastern Standard Time

           Windows : OS
                 8 : CPU(s)
             AMD64 : Machine
             64bit : Architecture
           15.9 GB : RAM
           Jupyter : Environment
        GPU Vendor : Intel
      GPU Renderer : Intel(R) HD Graphics 530
       GPU Version : 4.5.0 - Build 23.20.16.4973

  Python 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 11:27:44)
  [MSC v.1900 64 bit (AMD64)]

            0.23.1 : pyvista
             8.1.1 : vtk
            1.15.4 : numpy
             2.4.1 : imageio
             1.4.3 : appdirs
             0.5.1 : scooby
             2.2.3 : matplotlib
             5.9.2 : PyQt5
             6.5.0 : IPython

  Intel(R) Math Kernel Library Version 2018.0.3 Product Build 20180406 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------

**Comment by banesullivan** [comment]
Can you try adding `plotter.disable_depth_peeling()` before the `add_mesh` calls?

**Comment by danpak94** [comment]
That did the trick! Awesome, thank you so much!

Would it be possible to know why it solved the issue?

**Comment by banesullivan** [comment]
We enabled depth peeling by default in version PyVista v0.23.1 and on a hunch I thought that might have something to do with your problem. It's a bit concerning that depth peeling caused those issues for you... my guess is that something is awry with our depth peeling routine's compatibility with VTK 8.1.1.

Pinging @GuillaumeFavelier, do you think this warrants disabling depth peeling by default? Note that I was having issues with it and disabled it for VTK>8.2 in https://github.com/pyvista/pyvista/pull/599

**Comment by akaszynski** [comment]
Yep, I think disabling it by default (like in VTK) is the way to go.  As a rule, features that segfault certain platforms or certain situations (I'm looking at you `"q"` key) should be disabled by default.
