### ISSUE TITLE
How to fill missing points in point cloud and to make structured grid

### ISSUE THREAD

**Issue by metrologist07** [pyvista/pyvista-support#130]
## Description
Hi Pyvista team, Thanks for having such a user friendly tool like this. 
I am working on surface topography relted task and i am new to this package. I have a point data from a scan. and the task is much similar to which described in #100. But m facing a problem,(also described there), I have point set with 1493 unique points in x axis and 800 in y axis. So as you mentioned there in #100, the number of points should be 1194400. But 1193014 points are only there in my data. So if I am trying to make the surface with thickness, its showing assertion errors on the dimension. How we can resolve it. 

As a try, i tried with filling the missing points (1194400-1193014 = 1386 points) with `nan` , so that I can satisfy the condition on the dimension, but the surface with thickness is seems very wierd. Any  suggesion  will be appreciated. 
Thanks

## Example Data
[example_mesh.zip](https://github.com/pyvista/pyvista-support/files/4214438/example_mesh.zip)

**Comment by akaszynski** [comment]
Hello,

The problem is that we don't know where to insert the missing points, and inserting them at the end doesn't seem to be the solution.  Also the factors of 1193014 are:
```
1
2
596507
1193014
```
I'd clean up the data and then go ahead and structure it afterwards.

**Comment by metrologist07** [comment]
Hi @akaszynski, 
What I have done so far is that, out ot 1193014 points, we have1493 unique x points and 800 unique y points are there. So I created a combination of those unique points, then I have 1493x800 = 1194400 points. Then find the missing combination of {x,y} from our data, then assign nan to the z values of the missing points. and try the same code to make the structured grid. 
import pyvista as pv
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from itertools import product, compress

nx_1 = np.unique(grid.points[:,0])
ny_1 = np.unique(grid.points[:,1])
new_x_y = set(product(nx_1,ny_1)

x_y_zip = zip(grid.points[:,0], grid.points[:,1])
x_y_list = set(x_y_zip)

**Comment by akaszynski** [comment]
I like how you effectively regenerated the (x,y) grid, but what we still have is a bunch of missing "z" values that we don't know where to place.

Instead, we preserve the original order of the z values and simply regenerate the x values:
```python
import numpy as np
import pyvista as pv

pc = pv.read('./mesh_rectangle.vtk')

# extract unique x/y values and create a grid
xrng = np.unique(pc.points[:, 0])
yrng = np.unique(pc.points[:, 1])
x, y = np.meshgrid(xrng, yrng)

# extract the z values and then add in nans to fill in the missing values
nans = np.empty(1386)
nans[:] = np.nan
z = np.hstack((pc.points[:, -1], nans))
z = z.reshape(x.shape)

# display
surface = pv.StructuredGrid(x, y, z)
surface.plot()
```
![desktop 1_147](https://user-images.githubusercontent.com/11981631/74879400-56bb2c00-5369-11ea-8ec0-42620cb3b529.png)

**Comment by metrologist07** [comment]
Hi @akaszynski, Thank you for your valuable suggestion.  But as @banesullivan mentioned in #100, when I tried to create a terrain following mesh or making thickenss for this StructuredGrid. Its seems weird ill formed surface with partially open on one side. 
Terrain foloowing mesh looks like:
![grafik](https://user-images.githubusercontent.com/61153946/74936927-5d8a8300-53eb-11ea-9804-5db0eb298c73.png)
and the thick surface looks like:
![grafik](https://user-images.githubusercontent.com/61153946/74937431-4ef09b80-53ec-11ea-8aa8-97bc1a7f58ea.png)

**Comment by metrologist07** [comment]
Hi @akaszynski, Just now I found an another problem. I just plotted the structured surface and the original data. It seems like it is it differ each other. Here the tan color surface is structured grid and the elevation plot is the original data
![grafik](https://user-images.githubusercontent.com/61153946/74954125-ebbe3380-5402-11ea-8ee4-fe1add53e03d.png)

**Comment by banesullivan** [comment]
I think the weirdness happening above is due to having NaN point vertices. Perhaps add actual values there (maybe the mean) and then use the snippets in https://github.com/pyvista/pyvista/issues/318 to mask those points as "blank". You do this by passing the IDs of each blank point to `mesh.BlankPoint(id)`

I'm not 100% on whether it'll work but worth a try

**Comment by banesullivan** [comment]
> Hi @akaszynski, Just now I found an another problem. I just plotted the structured surface and the original data. It seems like it is it differ each other. Here the tan color surface is structured grid and the elevation plot is the original data


This looks like a classic ordering issue. Looks like the Z array is transposed

**Comment by akaszynski** [comment]
Thanks @banesullivan.  You're correct, just transpose Z and you should be good to go.

**Comment by metrologist07** [comment]
> 
> 
> > Hi @akaszynski, Just now I found an another problem. I just plotted the structured surface and the original data. It seems like it is it differ each other. Here the tan color surface is structured grid and the elevation plot is the original data
> 
> This looks like a classic ordering issue. Looks like the Z array is transposed

@banesullivan , Thanks for the suggestion, But I didn't understandthe point. Since the meshgrid we created(`x, y = np.meshgrid(xrng, yrng)`) , the x and y is of shape (800, 1493) and the z we make is also of shape (800, 1493). if we transpose z it will become (1493, 800). hence its showing `Exception: Input point array shapes must match exactly
`

**Comment by banesullivan** [comment]
Maybe “transpose” was the wrong word.

In the code that generates that mesh (I think from https://github.com/pyvista/pyvista-support/issues/130#issuecomment-588487069), use `”F”` ordering on the reshape call - that’s where the problem should be originating:

```py
z = np.hstack((pc.points[:,-1], nans))
z = z.reshape(x.shape, order=“F”)
```

*Disclaimer: I haven’t run any of this code and am really just guessing on what’s happening here from experience*

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akaszynski** [comment]
Turns out the trick is:
```python
import numpy as np
import pyvista as pv

pc = pv.read('~/Downloads/example_mesh/mesh_rectangle.vtk')

# extract unique x/y values and create a grid
xrng = np.unique(pc.points[:, 0])[::-1]
yrng = np.unique(pc.points[:, 1])[::-1]
x, y = np.meshgrid(xrng, yrng)


# extract the z values and then add in nans to fill in the missing values
nans = np.empty(1386)
nans[:] = np.nan
z = np.hstack((pc.points[:, -1], nans))
z = z.reshape(x.shape)

# pc.points[:, -1]

# display
surface = pv.StructuredGrid(x, y, z)
```

**Comment by akaszynski** [comment]
Tried this and a bunch of different approaches and couldn't get the data lined up.  I think your best bet is to investigate the missing data from whatever's producing the arrays, as it seems like it's going to be quite difficult to clean it up without knowing where to place the missing Z data.

After playing around the data for a bit, this was closest I got (using fortran ordering doesn't seem to work here).

```python
import numpy as np
import pyvista as pv

pc = pv.read('~/Downloads/example_mesh/mesh_rectangle.vtk')

# extract unique x/y values and create a grid
xrng = np.unique(pc.points[:, 0])[::-1]
yrng = np.unique(pc.points[:, 1])[::-1]
x, y = np.meshgrid(xrng, yrng)

# extract the z values and then add in nans to fill in the missing values
nans = np.empty(1386)
nans[:] = np.nan
z = np.hstack((pc.points[:, -1], nans))
z = z.reshape(x.shape)

# pc.points[:, -1]

# display
surface = pv.StructuredGrid(x, y, z)
surface.points[:, 0]
# surface.plot(eye_dome_lighting=True)
```

**Comment by metrologist07** [comment]
Hi @akaszynski and @banesullivan. the above code will make the surface aligned with the actual surface. But the points are not same, means its looks like two different surfaces. 
![grafik](https://user-images.githubusercontent.com/61153946/75359000-03d6fc80-58b4-11ea-8c72-8bcca91c4d53.png)

I have found better soultion for this using defaultdict

import pyvista as pv
import numpy as np
from collections import defaultdict
pc= pv.read('mesh_rectangle.vtk')
nx_1 = np.unique(pc.points[:,0])
ny_1 = np.unique(pc.points[:,1])
z = np.repeat(np.nan,len(nx_1)*len(ny_1))
x, y = np.meshgrid(nx_1, ny_1)
x_y = list(zip(np.reshape(x,-1),np.reshape(y,-1), z))

x_y_actual = list(zip(pc.points[:,0], pc.points[:,1], pc.points[:,-1]))

dict_obj_1 = defaultdict(list)
for x1,y1,z1 in x_y:
    dict_obj_1[x1,y1].append(z1)

dict_obj_2 = defaultdict(list)
for x2,y2,z2 in x_y_actual:
    dict_obj_2[x2,y2].append(z2)

checkresult = list(set(dict_obj_1.keys()).intersection(set(dict_obj_2.keys())))
for key in list(checkresult):
    dict_obj_1[key] = dict_obj_2[key]
