### ISSUE TITLE
Convert MultiBlock object to Pandas Dataframe

### ISSUE THREAD

**Issue by jacobgrasmick** [pyvista/pyvista-support#131]
I am trying to convert this MultiBlock, which contains 10 keys to a pandas dataframe. I think the Table class is designed for this but I seem to be missing something...

```
In: model_slc2
Out: 
MultiBlock (0x1e99af21768)
  N Blocks:	10
  X Bounds:	1.000, 808481.188
  Y Bounds:	1.000, 1698607.375
  Z Bounds:	-284.849, -1.000
```

Here are the keys:
```model_slc2.keys()
Out: 
['Block-00',
 'Block-01',
 'Block-02',
 'Block-03',
 'Block-04',
 'Block-05',
 'Block-06',
 'Block-07',
 'Block-08',
 'Block-09']
```

The output can either be a single dataframe with a column identifying the key or a unique dataframe for each unique key.

**Comment by banesullivan** [comment]
Sorry for the delay on this

To convert a spatially referenced dataset to a dataframe (table), you must choose what exactly you want to include in the table (e.g. mesh vertices, cell centers, point/cell data).

Here is a routine to convert a the point data of a single mesh to a dataframe.

```py
import pandas as pd
def to_dataframe(mesh):
    """Convert a single mesh to a Pandas DataFrame."""
    for name, arr in mesh.point_arrays.items():
        if arr.ndim != 1:
            raise AssertionError("Array ({}) is multi-component which Pandas doesn't like. Fix that.".format(name))
    data = dict(zip(["x", "y", "z"], mesh.points.T))
    data.update(mesh.point_arrays)
    return pd.DataFrame.from_dict(data)
```

You can either merge the entire `MultiBlock` dataset into a single mesh to make a dataframe or you can convert each individual block to their own dataframes. Here I merge all into one using the `combine()` filter of `MultiBlock` datasets:

```py
to_dataframe(model_slc2.combine())
```
