### ISSUE TITLE
Custom colormap

### ISSUE THREAD

**Issue by bvafa** [pyvista/pyvista-support#132]
## Description
Hello,
Is there any way to introduce a new/custom matplotlib color map into the `cmap` of the `add_mesh` method.
I want to create a color map using the following example:
```
top = cm.get_cmap('Oranges_r', 128)
bottom = cm.get_cmap('Blues', 128)
newcolors = np.vstack((top(np.linspace(0, 1, 128)), bottom(np.linspace(0, 1, 128))))
newcmp = ListedColormap(newcolors, name='OrangeBlue')
```

Thank you.

**Comment by banesullivan** [comment]
Have you tried passing that custom colormap to the `add_mesh` method yet? It should work...

See https://docs.pyvista.org/examples/02-plot/cmap.html#custom-made-colormaps

**Comment by bvafa** [comment]
Perfect; Thank you.
