### ISSUE TITLE
How to slice a surface into number of slices along a particular normal 

### ISSUE THREAD

**Issue by metrologist07** [pyvista/pyvista-support#134]
## Description
HI Support team, We have` slice` , `slice_along_axis `to slice the surface. But I need to slice my surface in a particular direction and a certain number of slices. 

As per the documentation, 
 In `slice` : We can slice the surface in a particular normal. But only one slice 
In `slice_along_axis` : We can slice the the surface into number of slices but only in either x or y or z axis. 

So if my surface normal is not along the proper axis as x, y or z, i cannot use  `slice_along_axis` . and `slice ` have no options to normal. Is there any way to do that?. 

[surface_mesh.zip](https://github.com/pyvista/pyvista-support/files/4256748/surface_mesh.zip)

**Comment by banesullivan** [comment]
I'd recommend making two points along your normal, then generating a line between those two points to provide the centers of the slice. Once you have that, its eay:

```py
import pyvista as pv
import numpy as np
from pyvista import examples

mesh = examples.download_brain()

vec = np.random.rand(3)
# Normalize the vector
normal = vec / np.linalg.norm(vec)

# Make points along that vector for the extent of your slices
a = mesh.center + normal * mesh.length / 3.0
b = mesh.center - normal * mesh.length / 3.0

n_slices = 5
line = pv.Line(a, b, n_slices)

# Generate all of the slices
slices = pv.MultiBlock()
for point in line.points:
    slices.append(mesh.slice(normal=normal, origin=point))

p = pv.Plotter()
p.add_mesh(mesh.outline(), color="k")
p.add_mesh(slices, opacity=0.75)
p.add_mesh(line, color="red", line_width=5)
p.show()
```
![download](https://user-images.githubusercontent.com/22067021/75369403-9c538980-5880-11ea-8453-435f13f66f73.png)


I don't think this is something we will ever include as a filter in PyVista as there are a lot of moving parts/user-defined parameters.

**Comment by banesullivan** [comment]
It would be good to include this example in https://docs.pyvista.org/examples/01-filter/slicing.html#slice-along-line
