### ISSUE TITLE
Creating a 2.5D image/section (example with GPR)

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista-support#135]
Lately, I've been asked by a number of folks how to create a 2.5D image/sectional mesh of data like GPR or airborne EM profiles (geophysics applications). This example provides a look into how to create a 2.5D sectional mesh from *typical* data in those use cases.

Related:

- https://github.com/pyvista/pyvista-support/issues/28
- `PVGeo.filters.BuildSurfaceFromPoints`
- https://github.com/pyvista/pyvista/issues/318
- https://github.com/iannesbitt/readgssi/issues/8

-----

Suppose you have some GPR data (or anything that produces a line of data with values at depth). With this data, you'll have a 2D image/array of your data values and 3D coordinates of where that line/profile is in 3D space (often where you collected the data on the surface of topography). Attached below are some example data for this: 1) XYZ coordinates of a GPR path and 2) a 2D array of data values produced from the GPR (

*the data here are wacky (it's difficult to get sharable data of decent quality), so ignore them but pay attention to the structure. The coordinates we have are technically shifted up and we have some NaN filler above the surface - its weird and just ignore it. **You'll typically have a more uniform looking profile in 2D with the coordinates associated to the top of each column in your 2D array***

Example Data: [data.zip](https://github.com/pyvista/pyvista-support/files/4258550/data.zip)

So let's get to it...

```py
import pyvista as pv
import numpy as np
import matplotlib.pyplot as plt

# Extract the data archive and load these files
# 2D array of XYZ coordinates
path = np.loadtxt("path.txt", skiprows=1)
# 2D array of the data values from the imaging equipment
data = np.load("data.npy")
```

```py
plt.figure(figsize=(15,3))
plt.pcolormesh(data, cmap="seismic", clim=[-1,1])
plt.gca().invert_yaxis()
```
![download](https://user-images.githubusercontent.com/22067021/75395088-de93bf80-58ae-11ea-9f50-128c73b0d52d.png)

Above, the GPR profile is shown (the 2D array/image of data)

```py
# View the path
plt.scatter(path[:,1], path[:,0])
plt.axis("image")
plt.xlabel("Northing")
plt.ylabel("Easting")
```

![download](https://user-images.githubusercontent.com/22067021/75391283-fe26ea00-58a6-11ea-893f-7e4450acd35a.png)

Above, the path of the GPR profile is shown from a top-down perspective. Since we have the full coordinates (XY and Z), we can create a structured mesh "draping" down from those coordinates to hold the GPR image data.

```py
assert len(path) in data.shape, "Make sure coordinates are present for every trace."
# If not, you'll need to interpolate the path!

# Grab the number of samples (in Z dir) and number of traces/soundings
nsamples, ntraces = data.shape # Might be opposite for your data, pay attention here

# Define the Z spacing of your 2D section
z_spacing = 0.12

# Create structured points draping down from the path
points = np.repeat(path, nsamples, axis=0)
# repeat the Z locations across
tp = np.arange(0, z_spacing*nsamples, z_spacing)
tp = path[:,2][:,None] - tp
points[:,-1] = tp.ravel()
```

```py
# Make a StructuredGrid from the structured points
grid = pv.StructuredGrid()
grid.points = points
grid.dimensions = nsamples, ntraces, 1

# Add the data array - note the ordering!
grid["values"] = data.ravel(order="F")
```

And now we can plot it! or process or do anything, because it is a PyVista mesh and the possibilities are endless with PyVista

```py
grid.plot(cmap="seismic", clim=[-1,1])
```

![2020-02-26 15 04 01](https://user-images.githubusercontent.com/22067021/75392427-40512b00-58a9-11ea-9bf1-d2cf92943604.gif)

------

If you have *any* questions about this, do ping me in this thread. This is just one way to do this and I have many other tricks for these kinds of data.

**Comment by banesullivan** [comment]
If anyone has other example data for this kind of situation, please share it and I can easily make a snippet/function for handling your data

**Comment by putupradnya** [comment]
> Lately, I've been asked by a number of folks how to create a 2.5D image/sectional mesh of data like GPR or airborne EM profiles (geophysics applications). This example provides a look into how to create a 2.5D sectional mesh from _typical_ data in those use cases.
> 
> Related:
> 
> * [Visualise a 2D image (from array of x, y, z and data points) #28](https://github.com/pyvista/pyvista-support/issues/28)
> * `PVGeo.filters.BuildSurfaceFromPoints`
> * [StructuredGrid tutorials and add blank points/cells pyvista#318](https://github.com/pyvista/pyvista/issues/318)
> * [Interoperability with PyVista iannesbitt/readgssi#8](https://github.com/iannesbitt/readgssi/issues/8)
> 
> Suppose you have some GPR data (or anything that produces a line of data with values at depth). With this data, you'll have a 2D image/array of your data values and 3D coordinates of where that line/profile is in 3D space (often where you collected the data on the surface of topography). Attached below are some example data for this: 1) XYZ coordinates of a GPR path and 2) a 2D array of data values produced from the GPR (
> 
> _the data here are wacky (it's difficult to get sharable data of decent quality), so ignore them but pay attention to the structure. The coordinates we have are technically shifted up and we have some NaN filler above the surface - its weird and just ignore it. **You'll typically have a more uniform looking profile in 2D with the coordinates associated to the top of each column in your 2D array**_
> 
> Example Data: [data.zip](https://github.com/pyvista/pyvista-support/files/4258550/data.zip)
> 
> So let's get to it...
> 
> ```python
> import pyvista as pv
> import numpy as np
> import matplotlib.pyplot as plt
> 
> # Extract the data archive and load these files
> # 2D array of XYZ coordinates
> path = np.loadtxt("path.txt", skiprows=1)
> # 2D array of the data values from the imaging equipment
> data = np.load("data.npy")
> ```
> 
> ```python
> plt.figure(figsize=(15,3))
> plt.pcolormesh(data, cmap="seismic", clim=[-1,1])
> plt.gca().invert_yaxis()
> ```
> 
> ![download](https://user-images.githubusercontent.com/22067021/75395088-de93bf80-58ae-11ea-9f50-128c73b0d52d.png)
> 
> Above, the GPR profile is shown (the 2D array/image of data)
> 
> ```python
> # View the path
> plt.scatter(path[:,1], path[:,0])
> plt.axis("image")
> plt.xlabel("Northing")
> plt.ylabel("Easting")
> ```
> 
> ![download](https://user-images.githubusercontent.com/22067021/75391283-fe26ea00-58a6-11ea-893f-7e4450acd35a.png)
> 
> Above, the path of the GPR profile is shown from a top-down perspective. Since we have the full coordinates (XY and Z), we can create a structured mesh "draping" down from those coordinates to hold the GPR image data.
> 
> ```python
> assert len(path) in data.shape, "Make sure coordinates are present for every trace."
> # If not, you'll need to interpolate the path!
> 
> # Grab the number of samples (in Z dir) and number of traces/soundings
> nsamples, ntraces = data.shape # Might be opposite for your data, pay attention here
> 
> # Define the Z spacing of your 2D section
> z_spacing = 0.12
> 
> # Create structured points draping down from the path
> points = np.repeat(path, nsamples, axis=0)
> # repeat the Z locations across
> tp = np.arange(0, z_spacing*nsamples, z_spacing)
> tp = path[:,2][:,None] - tp
> points[:,-1] = tp.ravel()
> ```
> 
> ```python
> # Make a StructuredGrid from the structured points
> grid = pv.StructuredGrid()
> grid.points = points
> grid.dimensions = nsamples, ntraces, 1
> 
> # Add the data array - note the ordering!
> grid["values"] = data.ravel(order="F")
> ```
> 
> And now we can plot it! or process or do anything, because it is a PyVista mesh and the possibilities are endless with PyVista
> 
> ```python
> grid.plot(cmap="seismic", clim=[-1,1])
> ```
> 
> ![2020-02-26 15 04 01](https://user-images.githubusercontent.com/22067021/75392427-40512b00-58a9-11ea-9bf1-d2cf92943604.gif) [ ![2020-02-26 15 04 01](https://user-images.githubusercontent.com/22067021/75392427-40512b00-58a9-11ea-9bf1-d2cf92943604.gif) ](https://user-images.githubusercontent.com/22067021/75392427-40512b00-58a9-11ea-9bf1-d2cf92943604.gif) [ ](https://user-images.githubusercontent.com/22067021/75392427-40512b00-58a9-11ea-9bf1-d2cf92943604.gif)
> 
> If you have _any_ questions about this, do ping me in this thread. This is just one way to do this and I have many other tricks for these kinds of data.

I have a question, how to add a cross section in the figure? can we add another line to structural grid?
