### ISSUE TITLE
Creating model for FEA from binarised image slices

### ISSUE THREAD

**Issue by steersteer** [pyvista/pyvista-support#136]
Hi,
I have a big set of segmented image slices from a CT scan that I would like to create a tetrahedral volume mesh from in order to use for finite element analysis in software such as Abaqus.
At the moment I have it stored in a 3D numpy array. I'm having some trouble in making the mesh from this. 
So far I have tried marching cubes to find the verts and faces, then using this created a mesh using "tetgen.TetGen(C_verts, C_faces)". This then need to be made manifold but this takes hours for the large quantity of images. Once this finally finishes, the inner hollow volume has what I'm going to call "strings" throughout.
Is there a better way to do this? 

I have attached a sample set of images

[Cortical_Mask.zip](https://github.com/pyvista/pyvista-support/files/4261062/Cortical_Mask.zip)

**Comment by banesullivan** [comment]
Can you provide code to read the TIF images into a 3D numpy array?

-----

If you have a 3D NumPy array, simply pass that array to the `pyvista.wrap` method and voila!, you'll have a full 3D mesh which you can threshold/contour/tetrahedralize/do whatever your heart desires.

You may want to checkout [this example](https://docs.pyvista.org/examples/00-load/create-uniform-grid.html#creating-a-uniform-grid) to learn more about creating `UniformGrid`s from NumPy arrays.

Here's my attempt at reading the images in as a single 3D array and doing this. You'll want to adjust the pixel spacing of the volume to something that makes sense for your data, I chose something that looked pretty.

```py
import imageio
import pyvista as pv
import numpy as np

basename = "/Users/bane/Library/Mobile Documents/com~apple~CloudDocs/Downloads/Cortical_Mask/cortical_mask_{}.tiff"
images = []
for i in range(50):
    img = imageio.imread(basename.format(i+1))
    images.append(img)
# Works because all images are uniform and ordered
stack = np.moveaxis(np.array(images), 0, -1)

volume = pv.wrap(stack.astype(int))
# You'll want to adjust the pixel spacing alomng each axis
volume.spacing = 0.1, 0.1, 1

volume.plot(cmap="binary")
```

![download](https://user-images.githubusercontent.com/22067021/75474999-32f17a80-5955-11ea-80e5-1f698f0755bb.png)


Now you can do stuff
```py
truth = volume.threshold(0.5)
truth.plot(color=True)
```

![download](https://user-images.githubusercontent.com/22067021/75475034-44d31d80-5955-11ea-9c74-0b32b139c03c.png)

**Comment by banesullivan** [comment]
I just want to add a few things from slack so that they're here for anyone else looking into this:

@steersteer:
> And in regards to the tetrahedralising, I wanted to do that for the purposes of finite element analysis

@banesullivan:

> You can tetrahedralize the threshold (`truth`) mesh that I have [above] by the `triangulate()` filter but this will take a long time because it has to turn about ~11 million voxels into ~55 million tetrahedrals. You’ll probably want to majorly decimate/subsample that mesh before tetrahedralizing it.
>
> Another option, of course, would be to extract the surface of the threshold result (`truth.extract_surface()`), decimate that, then feed that as the manifold surface to TetGen

**Comment by steersteer** [comment]
Thanks for your help so far. Feel like this is getting somewhere.
I tried to decimate the truth mesh as I'm actually looking for not such a fine final tetrahedral mesh but come across the error "'UnstructuredGrid' object has no attribute 'decimate'". Obviously I've missed a step somewhere

**Comment by banesullivan** [comment]
You'll need to extract the outer surface before you can decimate it.

`truth.extract_surface().decimate()`

**Comment by steersteer** [comment]
Now I get this: "ERROR:root:Can only decimate triangles"

**Comment by banesullivan** [comment]
Ah yeah, you're extracting the surface of a voxelized mesh, so the cells are all quads. You'll need to triangulate it before decimation:

```py
truth.extract_surface().triangulate().decimate(0.9)
```

Note that this could take a while because its a rather big mesh and you'll be effectively doubling its size by turning squares into triangles

**Comment by steersteer** [comment]
Ok, I think I might have to resort to software to mesh it from a surface, I tried that with only 2 slices and it hadn't finished when I stopped the process at 10 minutes. I have about 1800 slices in my full data set so that would take days

**Comment by banesullivan** [comment]
You can also subsample the volume before thresholding using the `extract_subset` filter on the `UniformGrid`. I don't think this is on the latest release but only on the `master` branch.

See https://docs.pyvista.org/examples/02-plot/volume.html?highlight=extract_subset#extracting-a-voi
