### ISSUE TITLE
Is there a filter to extract the boundary of the structure derived from the Delaunay_3d output?

### ISSUE THREAD

**Issue by empet** [pyvista/pyvista-support#137]
This a question, not an issue. I installed  pyvista only recently, and I experimented  a few filters. Among them, the `Delaunay_3d`, for which I couldn't find any example.
For a 3D point cloud I called `Delaunay_3d` with a nonzero alpha,  and with a custom function I extracted the lists of indices that define the simplexes [https://en.wikipedia.org/wiki/Simplex](https://en.wikipedia.org/wiki/Simplex) of the unstructured grid, i.e. tetrahedra, triangles, edges and isolated points. The resulting simplicial structure is plotted   both with a transparent and an opaque appearance. Now my question  is there a filter to extract from this structure (pyvista unstructured grid) its external faces  (the triangles that form the structure's boundary, that are visible in the second image, below)? 
![alphashape0](https://user-images.githubusercontent.com/3627253/75483986-8c3ac780-59b0-11ea-9273-29077258a7e3.png)

![alphashape1](https://user-images.githubusercontent.com/3627253/75484000-952b9900-59b0-11ea-89a7-b9904c98bf33.png)

Thanks!!!

**Comment by banesullivan** [comment]
Try [`.extract_surface()`](https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.extract_surface) or [`.extract_geometry()`](https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.extract_geometry) both will acheive what you're hoping to do but have slightly different options

**Comment by banesullivan** [comment]
> I installed pyvista only recently, and I experimented a few filters. Among them, the Delaunay_3d, for which I couldn't find any example.

If you're up for making an example in [our gallery](https://docs.pyvista.org/examples/index.html) with some cool 3D data, we'd welcome a PR for a new example on the Delaunay 3D filter!

**Comment by empet** [comment]
`extract_geometry()` did the job. Thank you!!!

I'll try to work this weekend on an  example of `Delaunay_3d()` filter.

**Comment by SnehithR** [comment]
> This a question, not an issue. I installed pyvista only recently, and I experimented a few filters. Among them, the `Delaunay_3d`, for which I couldn't find any example.
> For a 3D point cloud I called `Delaunay_3d` with a nonzero alpha, and with a custom function I extracted the lists of indices that define the simplexes https://en.wikipedia.org/wiki/Simplex of the unstructured grid, i.e. tetrahedra, triangles, edges and isolated points. The resulting simplicial structure is plotted both with a transparent and an opaque appearance. Now my question is there a filter to extract from this structure (pyvista unstructured grid) its external faces (the triangles that form the structure's boundary, that are visible in the second image, below)?
> ![alphashape0](https://user-images.githubusercontent.com/3627253/75483986-8c3ac780-59b0-11ea-9273-29077258a7e3.png)
> 
> ![alphashape1](https://user-images.githubusercontent.com/3627253/75484000-952b9900-59b0-11ea-89a7-b9904c98bf33.png)
> 
> Thanks!!!

Can you tell how you got the indices of faces after triangulation?

**Comment by banesullivan** [comment]
The `faces` property of the mesh. 

Please open a new issue when asking new questions.
