### ISSUE TITLE
convert UnstructuredGrid to numpy.ndarray

### ISSUE THREAD

**Issue by Hailey-Liu** [pyvista/pyvista-support#141]
## Description

Dear all, thanks for having this pyvista-support. I am very new to pyvista and encounter some problem. I am trying to convert the output of `voxelize()` method to a numpy.ndarray where 0 indicates voids and 1 indicates occupation. Any ideas to accomplish that? Many thanks.

## Example Data

Using the example below, any suggestions on converting the `voxel(UnstructuredGrid)` to numpy.ndarray?
```
from pyvista import examples
import pyvista as pv
import numpy as np

surface = examples.download_foot_bones()
voxels = pv.voxelize(surface, density=surface.length/100)
p = pv.Plotter(notebook=False)
p.add_mesh(voxels, color=True, show_edges=True)
p.show()
```
## Screen shot
<img width="384" alt="Screen Shot 2020-03-19 at 5 02 36 PM" src="https://user-images.githubusercontent.com/44219935/77115249-63807d80-6a04-11ea-989c-92b8d84ba89c.png">

**Comment by akaszynski** [comment]
I just went into the source for `pyvista.voxelize` and saw that `mask` was exactly what you were looking for in terms of a numpy bool array describing which voxel is in or out of the surface mesh.

```python
from pyvista import examples
import pyvista
import numpy as np

mesh = examples.download_foot_bones()
density = mesh.length / 100
x_min, x_max, y_min, y_max, z_min, z_max = mesh.bounds
x = np.arange(x_min, x_max, density)
y = np.arange(y_min, y_max, density)
z = np.arange(z_min, z_max, density)
x, y, z = np.meshgrid(x, y, z)

# Create unstructured grid from the structured grid
grid = pyvista.StructuredGrid(x, y, z)
ugrid = pyvista.UnstructuredGrid(grid)

# get part of the mesh within the mesh's bounding surface.
selection = ugrid.select_enclosed_points(mesh.extract_surface(),
                                         tolerance=0.0,
                                         check_surface=False)
mask = selection.point_arrays['SelectedPoints'].view(np.bool)
mask = mask.reshape(x.shape)

pyvista.plot(grid.points, scalars=mask)
```
![desktop 1_157](https://user-images.githubusercontent.com/11981631/77123273-f559ac00-6a3f-11ea-9f1f-b4ff65a75fa4.png)

**Comment by Hailey-Liu** [comment]
Hi @akaszynski , thanks for pointing me to the `mask`. I did some plot to look at the mask, but it looks very different from the point cloud data.
```
from pyvista import examples
import pyvista
import numpy as np

mesh = examples.download_foot_bones()
density = mesh.length / 100
x_min, x_max, y_min, y_max, z_min, z_max = mesh.bounds
x = np.arange(x_min, x_max, density)
y = np.arange(y_min, y_max, density)
z = np.arange(z_min, z_max, density)
x, y, z = np.meshgrid(x, y, z)

# Create unstructured grid from the structured grid
grid = pyvista.StructuredGrid(x, y, z)
ugrid = pyvista.UnstructuredGrid(grid)

# get part of the mesh within the mesh's bounding surface.
selection = ugrid.select_enclosed_points(mesh.extract_surface(),
                                         tolerance=0.0,
                                         check_surface=False)
# mask = selection.point_arrays['SelectedPoints'].view(np.bool)
mask = selection.point_arrays['SelectedPoints']
mask = mask.reshape(x.shape)
mask = pyvista.wrap(mask).threshold(1)

# pyvista.plot(grid.points, scalars=mask, notebook=False)
p = pyvista.Plotter(notebook=False)
p.add_mesh(mask)
p.show()
```
<img width="810" alt="Screen Shot 2020-03-20 at 2 44 18 PM" src="https://user-images.githubusercontent.com/44219935/77196560-f92a1480-6ab9-11ea-9ca5-34963b171d26.png">

**Comment by akaszynski** [comment]
It seems you changed
```python
mask = selection.point_arrays['SelectedPoints'].view(np.bool)
mask = mask.reshape(x.shape)
pyvista.plot(grid.points, scalars=mask)
```
to:
```
mask = mask.reshape(x.shape)
mask = pyvista.wrap(mask).threshold(1)
```
And then tried to plot it with:
```
p = pyvista.Plotter(notebook=False)
p.add_mesh(mask)
p.show()
```

The problem is that `mask` is a numpy boolean array, and plotting that array won't give you the correct representation of data as you're just plotting `True`/`False` without any associated coordinates.  The coordinates of all points is `ugrid.points` and to get the coordinates of the points within the mesh you'd run:
```python
ugrid.points[mask]
```

This was why you need to know the coordinates, and the mask of those coordinate to get a good plot:
```python
pyvista.plot(grid.points, scalars=mask, notebook=False)
```

**Comment by Hailey-Liu** [comment]
Thanks @akaszynski . I just figure out how to transform the coordinates to 3d numpy.ndarray where 0 indicates voids and 1 indicates occupation. So I will just close this issue.

**Comment by Vysakh5391** [comment]
@Hailey-Liu : I am working on a similar problem where I have to obtain a binary 2d array of different slices of the voxel data. Could you please tell me how you solved the voxel slice to binary matrix problem? Thank you very much in advance!

**Comment by nikolarobottesla** [comment]
@akaszynski @Hailey-Liu thanks for this question and answer it helped me.

Note the mask indexing order is z, y, x.  Therefore reshape using x.shape scrambles the array. It doesn't show in the plot @akaszynski was doing because scalers must get flattened to match up to the grid.points in plot()

Also note np.meshgrid by default swaps the order of the 1st 2 inputs unless you set indexing="ij"

**Comment by Adeniyilowee** [comment]
> 

@Vysakh5391 were you able to solve the issue, please I would like to know how you did it. Thank you in advance.

**Comment by Adeniyilowee** [comment]
> @akaszynski @Hailey-Liu thanks for this question and answer it helped me.
> 
> Note the mask indexing order is z, y, x. Therefore reshape using x.shape scrambles the array. It doesn't show in the plot @akaszynski was doing because scalers must get flattened to match up to the grid.points in plot()
> 
> Also note np.meshgrid by default swaps the order of the 1st 2 inputs unless you set indexing="ij"

Please, @nikolarobottesla can you please demonstrate with code what you meant. I am a little bit confused. Many thanks.
