### ISSUE TITLE
Adding new vertices, edges, and cells to a triangular mesh (stl)

### ISSUE THREAD

**Issue by bvafa** [pyvista/pyvista-support#142]
## Description
Hi,
Is there any way to add new vertices to a triangular mesh and then update the mesh to include the consequent edges and cells? To this end I need to be able to remove some existing edges and cells and add desired edges and cells in addition to the desired nodes.
Thank you,

**Comment by akaszynski** [comment]
It sounds like what you'd like to do is possible.  Could you please post a code sample of what you've attempted or have so far?

**Comment by bvafa** [comment]
Hi,
Thanks for your reply,
I have not written the code yet but the steps for an example are like this:
1) Load a mesh. 
2) select a cell
3) find the centroid of the cell and define a vertex there.
4) create 3 edges from the vertices of the original cell to the centroid.
5) now delete the original (selected) cell and add the 3 new cells instead.
Please see the figure.
What I need is to get direct access to the vertices, edges, and cells of the original mesh for removing and adding them.
![dvdngcell](https://user-images.githubusercontent.com/59977117/77502889-c8cbd880-6e21-11ea-8e89-9c891d6a215d.jpg)

Thank you,
Stay safe and sound,

**Comment by akaszynski** [comment]
That makes sense now.  If you're working with a `stl` it's going to be represented as `PolyData` within `pyvista` and you'll only need to use the following properties of a `PolyData`:
```python
import pyvista as pv

sphere = pv.Sphere()
print(sphere.points)
print(sphere.faces)
```
The `faces` array is a padded array containing concatenated faces in the form of `[[3, 0, 1, 2], [3, 0, 2, 3]]...` and so on.  The "padding" is the size of each face.  In the case of a stl, they're all triangles, and that will always be 3.  You can extend an existing mesh manually by creating a new face array.

One easy way of doing this reshaping the face array:
```python
sphere.faces.reshape(-1, 4)
```
This way each row of the face array is a single face.  Create a new points array with the updated points by appending the new points to the existing points array.  Finally, create a new mesh with:
```python
mesh = pv.PolyData(new_points, new_faces)
```

**Comment by bvafa** [comment]
Perfect. Thanks a lot

**Comment by akaszynski** [comment]
When you get a chance, please close the issue if you think you're good to go.
