### ISSUE TITLE
Export to X3D

### ISSUE THREAD

**Issue by dennissergeev** [pyvista/pyvista-support#143]
## Description

I was hoping pyvista can export scenes to X3DOM format (as [this table](https://github.com/pyvista/pyvista/issues/146#issue-427904545) indicates), but I can't find how to do it. Or is this not implemented yet?

Thanks.

**Comment by akaszynski** [comment]
Hello,

We're lacking that support at the moment.  I'm thinking of breaking up the PR into smaller ones like what we did for the ITK plotter.

If you'd like, I'd really appreciate a PR with X3DOM support.  Even if you can only just start the PR, I can start adding to it too as it's a feature that I also am interested in.

**Comment by dennissergeev** [comment]
Hi @akaszynski 

I'm not sure I have enough experience to lead such a PR, but I'd be happy to help with "low-hanging fruit" parts of this...

**Comment by akaszynski** [comment]
I'd take a look at what @banesullivan did initially in #300 and just implement his work for X3D.  Don't do anything fancy, just add basic support and testing.

**Comment by banesullivan** [comment]
@dennissergeev, all you need is what is in this file: https://github.com/pyvista/pyvista/pull/300/files#diff-387c9596d7cd40675c8b070c55ab6250

~25 lines of code

**Comment by dennissergeev** [comment]
Thanks @banesullivan !

**Comment by chen112p** [comment]
Hello has this update been merged to master yet? my version of pyvista installed with pip3 doesnt have this patch implemented.

> @dennissergeev, all you need is what is in this file: https://github.com/pyvista/pyvista/pull/300/files#diff-387c9596d7cd40675c8b070c55ab6250
> 
> ~25 lines of code

I tried to manually add line 3039 to 3085 to the BasePlotter class. However, the output x3d file cannot be read by Blender for some reasons.

Junting Chen

**Comment by banesullivan** [comment]
@chen112p, we decided not to support x3d in PyVista in favor of other notebook-plotting interfaces described here: https://docs.pyvista.org/api/plotting/plotting.html#plotting-in-a-jupyter-notebook

I do not foresee PyVista support x3d export

**Comment by banesullivan** [comment]
You can try to borrow this script though: https://github.com/pyvista/pyvista/pull/300/files#diff-45e6d8f24b6c76b2eea9fb5f8559765115b2501f44670cd1597bf757b719d0b3

No guarantees it'll work though
