### ISSUE TITLE
Area,points,volumes of cells in StructuredGrid (ideally without for loops)

### ISSUE THREAD

**Issue by Camkash** [pyvista/pyvista-support#145]
I've managed to get some of the data by using for loops or other operations, but it's very slow.

I'm currently looking at StructuredGrid but ideally this would be applicable to other types as well.

For finite element, it's required to get the following for calculations:

- The points of each cell by index coordinate. So for gridspace of (100,100,10), the result would be (100,100,10,3)

- Cell face areas. For gridspace this would be (100,100,10,6) as there are 6 faces to a grid element.

- Cell volumes. For gridspace this would be (100,100,10).

- Ideally cell neighbour index. For gridspace this would be (100,100,10,6,3). So for example, the neighbours for (40,40,5) would be [[39,40,5],[41,40,5],[40,39,5],[40,41,5],[40,40,4],[40,40,6]]. Ideally each face area would correspond to each cell neighbour.

I'm looking to avoid for loops in python as they are very slow. I could try combining it with Cython, but it would be nice to know if these features already exist!

**Comment by akaszynski** [comment]
Could you please post a code example and I can see if there's anything to vectorize it?  There are also features within `vtk` that compute cell volume and cell neighbours.

**Comment by keurfonluu** [comment]
You can take a look at a code of mine, there are vectorized functions to calculate volumes, face areas and neighbors for FEA/FVM: https://github.com/keurfonluu/toughio/blob/master/toughio/mesh/_properties.py

It's probably not the best (I am using too much dictionaries) but could be a good starting point. The mesh is defined as a ``meshio.Mesh`` but it should be straightforward to adapt it to a ``pyvista.UnstructruredGrid``.

Note that the normal vectors are not necessarily pointing outward.

**Comment by Camkash** [comment]
Thank you @keurfonluu  I will take a look!

Hey @akaszynski, I've posted my code that works in python, but I'm attempting to Cythonize. I've posted this in StackOverflow in the following link: 

https://stackoverflow.com/questions/60933592/cythonize-error-failed-with-exit-status-2-numpy-and-pyvista

I'd like to Cythonize the following code, but I receive an error.

```
import numpy as np
cimport numpy as np
import pyvista as pv
from mesh_funcs import *
cimport cython 
from libcpp cimport bool
#import matplotlib.pyplot as plt


#Getting mesh points from pyvista unfortunately with a for loop
cdef class pv_cell:
    def pv_grid_cell_data(mesh2,bool points_toggle=True,
                          bool centres_toggle=True,bool volumes_toggle=True, bool areas_toggle=True):
        
        if areas_toggle==True:
            points_toggle==True
            
        if centres_toggle==True:
            points_toggle==True
        
        cdef np.ndarray gcp=np.zeros([mesh2.n_cells,8,3])
        cdef np.ndarray gcc=np.zeros([mesh2.n_cells,3])
        cdef np.ndarray gcv=np.zeros([mesh2.n_cells,3])
        cdef np.ndarray grid_facets=np.array([[0,1,2,3], [0,1,5,4], [1,2,6,5], [7,6,2,3], [7,3,0,4], [4,5,6,7]])
        cdef np.ndarray gca=np.zeros([mesh2.n_cells,6])
            
        for n1 in range(0,mesh2.n_cells):
            if points_toggle==True:
                gcp[n1]=mesh2.extract_cells(n1).points
                
            if centres_toggle==True:
                gcc[n1]=[np.mean(gcp[n1][:,0]),np.mean(gcp[n1][:,1]),np.mean(gcp[n1][:,2])]
                
            if volumes_toggle==True:
                gcv[n1]=mesh2.extract_cells(n1).compute_cell_sizes()["Volume"]
            
            if areas_toggle==True:

                for n2 in range(0,6):
                    ph8=gcp[n1][grid_facets[n2]]
                    gca[n1,n2]=tri_area(ph8[[0,2,3]])+tri_area(ph8[[0,1,3]])
        return gcp,gcc,gcv,gca

```
My setup.py is as follows

```
from setuptools import setup
from Cython.Build import cythonize
import numpy

setup(
    ext_modules=cythonize("pv_cell_funcs.pyx"),include_dirs=[numpy.get_include()])
```

I launch setup.py with the following.
```
python setup.py build_ext --inplace
pause
```

The error is very long. It states bool is an undeclared identifier. It then lists a lot of syntax errors. The last line is 
```
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\...x64\\cl.exe' failed with exit status 2
```

**Comment by akaszynski** [comment]
Cython is a bit outside the scope of `pyvista`, but...

If you'll be including c++ code, your language must also be `c++`:
```python
setup(
    ext_modules=cythonize("./pv_cell_funcs.pyx", language='c++'),
    include_dirs=[numpy.get_include()])
```

**Comment by akaszynski** [comment]
If this solves your problem, please close this issue.

**Comment by Camkash** [comment]
@akaszynski I specified my language as C++. The errors are still the same.

```
c:\programdata\anaconda3\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
pv_cell_funcs.c(1789): error C2146: syntax error: missing ')' before identifier '__pyx_v_points_toggle'
pv_cell_funcs.c(1789): error C2081: 'bool': name in formal parameter list illegal
pv_cell_funcs.c(1789): error C2061: syntax error: identifier '__pyx_v_points_toggle'
pv_cell_funcs.c(1789): error C2059: syntax error: ';'
pv_cell_funcs.c(1789): error C2059: syntax error: ','
pv_cell_funcs.c(1789): error C2059: syntax error: ')'
pv_cell_funcs.c(1832): error C2065: 'bool': undeclared identifier
pv_cell_funcs.c(1832): error C2146: syntax error: missing ';' before identifier '__pyx_v_points_toggle'
pv_cell_funcs.c(1832): error C2065: '__pyx_v_points_toggle': undeclared identifier
pv_cell_funcs.c(1833): error C2065: 'bool': undeclared identifier
pv_cell_funcs.c(1833): error C2146: syntax error: missing ';' before identifier '__pyx_v_centres_toggle'
.
.
.
pv_cell_funcs.c(1937): warning C4013: '__pyx_pf_13pv_cell_funcs_7pv_cell_pv_grid_cell_data' undefined; assuming extern returning int
pv_cell_funcs.c(1937): error C2065: '__pyx_v_points_toggle': undeclared identifier
pv_cell_funcs.c(1937): error C2065: '__pyx_v_centres_toggle': undeclared identifier
pv_cell_funcs.c(1937): error C2065: '__pyx_v_volumes_toggle': undeclared identifier
pv_cell_funcs.c(1937): error C2065: '__pyx_v_areas_toggle': undeclared identifier
pv_cell_funcs.c(1937): warning C4047: '=': 'PyObject *' differs in levels of indirection from 'int'
pv_cell_funcs.c(1952): error C2146: syntax error: missing ')' before identifier '__pyx_v_points_toggle'
pv_cell_funcs.c(1952): error C2081: 'bool': name in formal parameter list illegal
pv_cell_funcs.c(1952): error C2061: syntax error: identifier '__pyx_v_points_toggle'
pv_cell_funcs.c(1952): error C2059: syntax error: ';'
pv_cell_funcs.c(1952): error C2059: syntax error: ','
pv_cell_funcs.c(1952): error C2059: syntax error: ')'
```

**Comment by akaszynski** [comment]
Try upgrading to the latest `cython` and `numpy`.  If that doesn't work, please run `scooby.Report(['numpy', 'cython'])`.

**Comment by banesullivan** [comment]
A few of these can be calculated from PyVista. Let's look at a simple structured grid example:

```py
import pyvista as pv
from pyvista import examples
import numpy as np

grid = examples.load_uniform().cast_to_structured_grid()
grid.plot(show_edges=True)
```

![download](https://user-images.githubusercontent.com/22067021/78465861-d8240f00-76c8-11ea-9610-f6d0d426399f.png)


> The points of each cell by index coordinate. So for gridspace of (100,100,10), the result would be (100,100,10,3)

```py
grid.points.reshape((*grid.dimensions, 3))
```

> Cell volumes. For gridspace this would be (100,100,10).

It's important to note that we define a `StructuredGrid`'s dimensions by the structure of the nodes, not the voxels/cells. Thus in a (100,100,10) sized grid, this data would be (99, 99, 9)

```py
grid.compute_cell_sizes()["Volume"].reshape(np.array(grid.dimensions)-1)
```

> Cell face areas. For gridspace this would be (100,100,10,6) as there are 6 faces to a grid element.

this one is a doozy. It looks like you have code to do it though? You could vectorize/parallelize the `extract_cells` filter to extract every cell and then convert the extracted cell (a voxel/hexahedron) to a `PolyData` mesh and run the `compute_cell_sizes` filter again, this time grabbing the `"Area"` array. That will have tons of duplicate values though because adjacent cells share faces.


> Ideally cell neighbour index. For gridspace this would be (100,100,10,6,3). So for example, the neighbours for (40,40,5) would be [[39,40,5],[41,40,5],[40,39,5],[40,41,5],[40,40,4],[40,40,6]]. Ideally each face area would correspond to each cell neighbour.

This can be done with simple grid mathemagic - however, you will not have a uniform array here. voxels/hexahedrons on the edges of the volume could have 3 (corner) or 4 (edge) and internal voxels/hexahedrons will have 6.

Here's a function to get them for any given index in grid coordinates:

```py
def get_neighbors(location, shape):
    """Get the neighbor indices of the cell 
    at location in a grid of the size shape."""
    i, j, k = location
    nx, ny, nz = shape
    neighbors = []
    if i > 0:
        neighbors.append([i-1,j,k])
    if i < nx-1:
        neighbors.append([i+1,j,k])
    if j > 0:
        neighbors.append([i,j-1,k])
    if j < ny-1:
        neighbors.append([i,j+1,k])
    if k > 0:
        neighbors.append([i,j,k-1])
    if k < nz-1:
        neighbors.append([i,j,k+1])
    return neighbors
```

vectorize that across your grid space if you want them all
