### ISSUE TITLE
Polydata plotting: is there any way to (slightly) change the LUT for certain points only?

### ISSUE THREAD

**Issue by truenicoco** [pyvista/pyvista-support#146]
Here is a visual example of something similar to what I am trying to achieve: https://www.youtube.com/watch?v=gNHI-Dk_Yqc
Is there any easy way to achieve such visualisation using pyvista?

Let's try with words now…

I have a mesh with a point array that I represent using a looking up table. I would like to "highlight" some points of this mesh without disturbing the looking up table too much. It could be done by changing their [lightness](https://en.wikipedia.org/wiki/HSL_and_HSV), for instance. Ideally, I would like to use a second point array to change this lightness parameter continuously, but thresholding to highlight certain points would be OK too.

My solution right now is to threshold the second point array, change the values of the first point array to something below the `clim` range and use `below_color`. The problem with this approach is that I visually lose the first point array information.

![](https://framapic.org/1nmO1UuwVeZE/UF2F0ankQgYR)

**Comment by banesullivan** [comment]
Perhaps you could try thresholding the values of interest on the fly and add them to the scene as an overlay. Something like the following:

```py
import pyvista as pv
from pyvista import examples

mesh = examples.download_st_helens().warp_by_scalar()

# extract the region to highlight
roi = mesh.threshold([1.62e3, 2.1e3])
bounds = roi.extract_feature_edges(boundary_edges=True, 
                          non_manifold_edges=False, feature_edges=False,
                          manifold_edges=False)

# plot it up
p = pv.Plotter(notebook=0)
p.add_mesh(mesh,)
p.add_mesh(roi, opacity=0.15, color="white")
# needed to fix coincident issues
p.mapper.SetRelativeCoincidentTopologyPolygonOffsetParameters(-3, -3)
p.add_mesh(bounds, color="white")
p.show()
```

<img width="580" alt="Screen Shot 2020-03-31 at 6 42 02 PM" src="https://user-images.githubusercontent.com/22067021/78081753-5312c000-737f-11ea-8aee-bc545a654cc6.png">



-----

Note that we have some issues with coincident topology at the moment and I added a setting in there to make it a bit prettier.

**Comment by truenicoco** [comment]
This is great, thank you very much.

For the record, since my mesh is not a polydata (it has tetrahedra), I used `extract_feature_edges()` with the default parameters to make it work.
