### ISSUE TITLE
Finding visible vertices of mesh 

### ISSUE THREAD

**Issue by anderspe73** [pyvista/pyvista-support#147]
Hi everyone, new to pyvista and in need of some help. I have a triangular mesh in 3D and I am trying to determine which vertices are visible from a given position. I would like to do so without displaying/plotting the mesh or any manual clicking. Is this doable with pyvista? If not, any pointer/suggestions would be greatly appreciated.

**Comment by banesullivan** [comment]
So as somewhat alluded in your post, this type of selection is currently possible in an interactive fashion using the visible cell selection tool (`Plotter.enable_cell_picking(through=False)`. We can leverage that same workflow in an automated fashion without user interaction as follows.

This might get a bit messy, but if we can make a streamlined routine for this, then we could add this as a feature in PyVista to make the user-facing side of this more simple.

-----

So I managed to get this to work at one point, but I'm having trouble now with it crashing my kernel. I'm going to post the broken code for now and see if I or someone else can come back to this. 


<details>

```py
import pyvista as pv
from pyvista import examples
import vtk

mesh = examples.load_random_hills()


# this is the camera position I want to use
cpos = [(6.57262195669236, 19.99388479424327, 6.691549967725345),
 (-1.399057787405183, 11.379489876926161, 3.061306711824895),
 (-0.15620748713919835, -0.2573168739454372, 0.9536179776748158)]

p = pv.Plotter(notebook=False)
p.add_mesh(mesh)
p.camera_position = cpos




#######
# perfrom the automatic picking
selector = vtk.vtkOpenGLHardwareSelector()
selector.SetFieldAssociation(vtk.vtkDataObject.FIELD_ASSOCIATION_CELLS)
selector.SetRenderer(p.renderer)
selector.SetArea(0,0,p.window_size[0],p.window_size[1])
selection = selector.Select()

extractor = vtk.vtkExtractSelection()
extractor.SetInputData(0, mesh)
extractor.SetInputData(1, selection)
extractor.Update()

visible = pv.wrap(extractor.GetOutput())

p.add_mesh(visible, color="pink", style="wireframe")
p.show()
```

</details>

**Comment by c0mm3nt** [comment]
This is exactly what I have been looking for!
The sample code is nearly functional. I just needed to add an initial render before performing the selection.

The following code should work without issue. 
I also tested it for FIELD_ASSOCIATION_POINTS to get vertices as well.

```python
import pyvista as pv
from pyvista import examples
import vtk

mesh = examples.load_random_hills()

# this is the camera position I want to use
cpos = [(6.57262195669236, 19.99388479424327, 6.691549967725345),
 (-1.399057787405183, 11.379489876926161, 3.061306711824895),
 (-0.15620748713919835, -0.2573168739454372, 0.9536179776748158)]

p = pv.Plotter(notebook=False)
p.add_mesh(mesh)
p.camera_position = cpos

# Trigger a render to initialize OpenGL context
render_window = p.renderer.GetRenderWindow()
render_window.Render()  

# Now set up and perform selection
selector = vtk.vtkOpenGLHardwareSelector()
selector.SetFieldAssociation(vtk.vtkDataObject.FIELD_ASSOCIATION_CELLS)
selector.SetRenderer(p.renderer)
selector.SetArea(0, 0, p.window_size[0], p.window_size[1])
selection = selector.Select()

extractor = vtk.vtkExtractSelection()
extractor.SetInputData(0, mesh)
extractor.SetInputData(1, selection)
extractor.Update()

visible = pv.wrap(extractor.GetOutput())

p.add_mesh(visible, color="pink", style="wireframe")
p.show()
```

**Comment by banesullivan** [comment]
awesome @c0mm3nt! Thanks for following up with the working code!

Considering this issue is 5 years old and you've made a working example, I'm going to mark this as closed. If you feel this is something that could be implemented as a part of the Plotter API, please feel free to contribute!

**Comment by el-hult** [comment]
This was excellent! Thank you for sharing this code. I want to do some automatic view-selection, rendering an object from multiple angles, and selecting the one where a certain part is as visible as possible. Counting visible vertices like this, using FIELD_ASSOCIATION_POINTS worked.

But if the goal is to just get the visible *points*, then the algorithm `vtkSelectVisiblePoints` ([link](https://vtk.org/doc/nightly/html/classvtkSelectVisiblePoints.html#details)) is an alternative. It does not return a mesh back, but a PointSet, so you cannot render a wireframe as in the original example. But someone still might find that useful. The code is slightly simpler.

```python
import pyvista as pv
import vtk

spheres = pv.merge([
    pv.Sphere(center=(-1, -1, 0), radius=1),
    pv.Sphere(center=(0, -2, 3), radius=2)])
cube = pv.Cube(center=(0, 0, 0), x_length=2, y_length=2, z_length=2)

plotter = pv.Plotter()
plotter.add_mesh(spheres)
plotter.add_mesh(cube)
plotter.camera_position = (10, 15, -10)

render_window = plotter.renderer.GetRenderWindow()
render_window.Render()

select_visible_points = vtk.vtkSelectVisiblePoints()
select_visible_points.SetInputData(0, spheres)
select_visible_points.SetRenderer(plotter.renderer)
select_visible_points.Update()

visible = pv.wrap(select_visible_points.GetOutput())
plotter.add_mesh(visible, color="pink")
plotter.show()
```

I'm sharing this in case someone else has a similar problem in the future. This seems like the appropriate place to share the snippet.

ps. this algorithm seems to miscalculate visibility sometimes, if the camera is set with `plotter.camera.position = ...` instead of `plotter.camera_position`. So use the appropriate setters for the camera to get more reliable results.

**Comment by banesullivan** [comment]
Nice find with `vtkSelectVisiblePoints`, @el-hult! I'd love to see us incorporate `vtkSelectVisiblePoints` as a part of the renderer API in PyVista somehow. If you're up for/have ideas, please feel free to open an issue in the main pyvista repository: github.com/pyvista/pyvista/issues/
