### ISSUE TITLE
Background plotter freezes over plotting many lines

### ISSUE THREAD

**Issue by bvafa** [pyvista/pyvista-support#150]
## Description
Hello,
I need to plot many line segments on a triangular mesh. I use `plotter.add_lines` in a loop over the lines. When I use the non-background plotter, everything is fine. However, the background plotter seems to be adding and displaying the lines one by one and usually it freezes.
I am OK with using the non-background plotter; however, I need the toolbar menu like what exists in the background plotter window, like, save camera and take screen shot.
Any suggestion?

Thank you
stay well,

**Comment by akaszynski** [comment]
Could you please provide some sample data so I can try to reproduce this bug on my end?  Also, a `pyvista.Report()` would be helpful as well.

**Comment by bvafa** [comment]
Hi,
Sure. I attached the report. However, I have restarted my computer and now the background plotter works fine. I will let you know if it freezes again and I'll send you the code to try. Thank you.

This is the report:
  Date: Sun Apr 05 10:24:24 2020 Daylight Time
                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
       Environment : IPython
        GPU Vendor : ATI Technologies Inc.
      GPU Renderer : AMD Radeon HD 7500 Series
       GPU Version : 4.5.13399 Core Profile Context 15.201.1151.1008
  Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64
  bit (AMD64)]
           pyvista : 0.24.0
               vtk : 8.1.2
             numpy : 1.17.3
           imageio : 2.6.1
           appdirs : 1.4.3
            scooby : 0.5.2
        matplotlib : 3.1.3
             PyQt5 : 5.11.3
           IPython : 7.9.0

**Comment by akaszynski** [comment]
Thanks for the report.  It's strange that restarting the computer would have changed the environment.

**Comment by bvafa** [comment]
I am using pycharm community edition. Sometimes I have strange problem and I need to restart either the program or the PC. It should be from my side not pyvista. Thanks.

**Comment by akaszynski** [comment]
Closing as this seems not related to `pyvista`.
