### ISSUE TITLE
Identifying polydata 

### ISSUE THREAD

**Issue by bvafa** [pyvista/pyvista-support#151]
## Description
Hi,
Suppose we have two polyData objects (like triangular meshes) and we use `.enable_point_picking` along with a callback function and the keyword `use_mesh=True`. Therefore, a pointer to any mesh whose points are picked is passed to the callback function. How can we identify which polydata object is subjected to the point picking? I am thinking about using  'id()' to compare their identity. Is it a good way?
For example:
```py
mesh1 = pv.read(meshFile1)
mesh2 = pv.read(meshFile2)
mesh1Id = id(mesh1)
mesh2Id = id(mesh2)
plotter = pv.Plotter(notebook=False)
def callback(onMesh, pId):
    if id(onMesh) == mesh1Id:
         print("mesh1")
    elif id(onMesh) == mesh2Id:
          print("mesh2")
    else:
          pass
plotter.enable_point_picking(callback=callback, show_message=True, font_size=12, color='red', point_size=17, use_mesh=True, show_point=True, render_points_as_spheres=True)

plotter.show()
```

Thank you
Best regards

**Comment by akaszynski** [comment]
Yes, `id` would work here.  You could also monkeypatch the polydata by adding a `name` property to it.  For example:
```python
mesh1.name = 'mesh1'
mesh2.name = 'mesh2'

# picking code....
def callback(onMesh, pId):
    print(onMesh.name, 'selected')

**Comment by banesullivan** [comment]
Technically `id()` is not always unique - you could use the `memory_address` property on all PyVista meshes though. Reference https://github.com/pyvista/pyvista/issues/386#issuecomment-571889585 and https://github.com/pyvista/pyvista/pull/521

Though I really like the name attribute Alex shows above!

**Comment by akaszynski** [comment]
We might consider having named meshes.  Perhaps default `name` to the file name?

**Comment by bvafa** [comment]
Thank you.
I successfully used:
```
myMesh= pv.read(meshFile1)
setattr(myMesh, 'name', 'SomeName')
```
That 'memory_address' string property is also a good choice. I think having a built-in name property for the polyData class is useful. 

Thank you,
Best,
