### ISSUE TITLE
Direct user input during plotting

### ISSUE THREAD

**Issue by bvafa** [pyvista/pyvista-support#152]
## Description
Hi,
I need to be able to input some numbers/string as a plotter is open (whether the background plotter or the other one). My project involves selecting some polydata/points plotted and naming them; and also changing some of their properties/attributes. Is there any widget that takes direct user input (string) typed through the keyboard?

Thanks very much,

**Comment by banesullivan** [comment]
There isn't a widget that does this in PyVista, though you could make your own! I'd recommend using the `BackgroundPlotter` and then making a Qt window/widget that appears during the picking callback to take user input and adjust the view appropriately

**Comment by bvafa** [comment]
Thanks for your reply.
Could you please give me some reference/guide/hint toward making a Qt window appearing along with the background plotter? I really appreciate your help.
Thanks a lot,

**Comment by akaszynski** [comment]
I recommend taking a look at https://github.com/pyvista/pyvista-gui where we basically create a new `PyQt` window and use the baseplotter object as a widget within the application.

**Comment by banesullivan** [comment]
I wish I could provide some sample code to help here, but I'm not too great at PyQt development. The module Alex mention is a great place to start but even that still needs quite a bit of work.

**Comment by bvafa** [comment]
Thank you. I will try it after learning some PyQt.
Best,

**Comment by banesullivan** [comment]
If you end up having a working prototype, please share it! It may help others hoping to pair Qt user interface with PyVista and will help me learn how to do this stuff well

**Comment by SterlingButters** [comment]
@bvafa did you ever get something working?
