### ISSUE TITLE
Out-of-focus effect in pyvista

### ISSUE THREAD

**Issue by mli0603** [pyvista/pyvista-support#160]
Hi all,

I am currently experimenting out-of-focus effect in PyVista. According to the VTK documentation, there is an out-of-focus effect when the camera has a [focal disk](https://vtk.org/doc/nightly/html/classvtkCamera.html#a7dd7b58aaf8d5d0c46293f9fd187735c) and [focal distance](https://vtk.org/doc/nightly/html/classvtkCamera.html#ae8717da72934634189d1149041c2e1bb) value passed. I did a minimal experiment and failed to see such effect. Can someone help? I think we can create a wrapper around this if this can actually work out. I am currently using VTK 9.0.0.

Here is the code I used to test
```python
import pyvista as pv

cube = pv.Cube(center=(0,0,0),x_length=1,y_length=1,z_length=1)

# no blur
p = pv.Plotter()
p.add_mesh(cube)
p.add_axes()
p.set_position([0,0,4]) # move camera back a little
p.renderer.ResetCameraClippingRange() # needed otherwise objects got chopped
p.show(screenshot='no_blur.png')

# add blur
p = pv.Plotter()
p.add_mesh(cube)
p.add_axes()
p.set_position([0,0,4]) # move camera back a little
p.camera.SetFocalDistance(1) # set focal distance
p.camera.SetFocalDisk(0.01)
p.renderer.ResetCameraClippingRange() # needed otherwise objects got chopped
p.show(screenshot='blur.png')
```

However, the output looks identical. I am attaching the output below. 
No blur (case 1)
![no_blur](https://user-images.githubusercontent.com/13513172/81229338-a2bb5b80-8fbd-11ea-83df-20b7549c47ee.png)

With blur (case 2)
![blur](https://user-images.githubusercontent.com/13513172/81229351-a7800f80-8fbd-11ea-8da6-3c80205a7305.png)

**Comment by akaszynski** [comment]
Sorry, been busy and I've been meaning to test this out with VTK v9.

**Comment by akaszynski** [comment]
Looked into this and it turns out you need to have a ray tracing enabled renderer.  We use the default opengl renderer for `pyvista`.  It seems that `vtkOSPRayPass` isn't included in the python wheel for vtk by default.  I'm still looking into this.

**Comment by GuillaumeFavelier** [comment]
Thanks for looking into this @akaszynski, I'm kinda hyped by this if it works :)

**Comment by akaszynski** [comment]
I've opened a comment here: https://discourse.vtk.org/t/vtkospraypass-in-python/3304 and I'll get back to this issue if there's any development.

**Comment by mli0603** [comment]
I saw they got back and decided not to include `vtkOSPRayPass` in the wheel. Does this mean we will not be able to access this feature?

**Comment by akaszynski** [comment]
Correct.  At the moment it sounds like it would be quite a bit of work to support that in a standard wheel.

If you wish, you can build VTK from source and include the additional renderer and python bindings.  I've built from source in the past and it's not super difficult, and they have directions here [VTK building](https://vtk.org/Wiki/VTK/Building/Windows).
