### ISSUE TITLE
Transformation matrix and box widgets

### ISSUE THREAD

**Issue by jacobo3d** [pyvista/pyvista-support#161]
Hi,

I'm trying to set a transformation matrix to a box widget. I'm sure this is me not knowing exactly how the vtkBoxWidget works.

I have for instance this transformation matrix:
[1.951897455335484, 0.0, 0.0, 0.0049065793642351155, 0.0, 0.32505666386421594, 0.0, 0.80699898002856, 0.0, 0.0, 1.156954202138952, 0.25239413761413, 0.0, 0.0, 0.0, 1.0]

I convert that to vtkMatrix4x4 and apply it to both a pyvista.Cube() actor (yellow) and to a vtkBoxWidget. The white points in the yellow cube corners are the ground truth, to check if the transformation is correct. The same matrix yields different results in both the cube and the box widget.

The cube matches the ground truth, which is the desired result. The box widget is applied to an object with the same bounding box as the ground truth (or the result of the yellow cube transformation), and results after applying the transformation matrix don't match the ground truth. It looks like some transformation values are added on top of the ones I'm applying to.

Any guidance to help me understand how to apply that transformation matrix to the box widget for it to match the result seen in the cube would be much appreciated.

<img width="559" alt="image" src="https://user-images.githubusercontent.com/1640526/81349573-18363300-9075-11ea-831d-b8fc2194e349.png">

Thanks!

**Comment by jacobo3d** [comment]
The detailed description here gave me the answer:
https://vtk.org/doc/nightly/html/classvtkBoxWidget.html#details

**Comment by akaszynski** [comment]
Thanks for posting that!  It will be helpful if anyone else attempts the same thing.
