### ISSUE TITLE
Help plotting multiple PolyData with colour on a BackgroundPlotter at once

### ISSUE THREAD

**Issue by TheodoreT** [pyvista/pyvista-support#163]
Since I am quite new to `pyvista` lib I would appreciate some help on how to plot some `PolyData` on a `BackgroundPlotter` as discussed in pyvista/pyvista#717.

I have 4 numpy arrays for the corresponding coordinates of faces/polygons and their corresponding color, something like that:

```
x = np.array([[-0.93333333, -0.93333333, -0.93333333, -0.93333333],
 [-0.93333333, -0.93333333, -0.93333333, -0.93333333],
 [-1.,         -1.,         -1.,         -1.        ],
 [-1.,         -1.,         -1.,         -1.        ]])

y = np.array([[1., 1., 1., 1.],
 [1., 1., 1., 1.],
 [1., 1., 1., 1.],
 [1., 1., 1., 1.]])

z = np.array([[-1.,         -0.93333333, -0.86666667, -0.8       ],
 [-0.93333333, -0.86666667, -0.8,        -0.73333333],
 [-0.93333333, -0.86666667, -0.8,        -0.73333333],
 [-1.,         -0.93333333, -0.86666667, -0.8       ]])

colormat = np.array([[0.11484721, 0.11484721, 0.11484721],
 [0.11648363, 0.11648363, 0.11648363],
 [0.12010454, 0.12010454, 0.12010454],
 [0.12384401, 0.12384401, 0.12384401]])
```

Now each column in the x, y, z matrices corresponds to the four 3d coordinates of the quadrangle and each row in the colormat matrix to the face color (it is grayscale). For example, something like:

![image](https://user-images.githubusercontent.com/10189018/81948292-19291080-95f1-11ea-8aef-fe9663a0a773.png)

for the first quadrangle.

I was able to plot the vertices from the first quadrangle with the following code:

    import pyvista as pv

    plotter = pv.BackgroundPlotter()
    for i in range(4):
        verts = [np.stack([x[:, i], y[:, i], z[:, i]], axis=1)]
        surf = pv.PolyData(np.array(verts))
        plotter.add_mesh(surf, color=list(colormat[i,:]))

this worked though it plots the quadrangles one by one, but I couldn't figure out 
1. how to add the color information to the whole face, with the above it seems like it draws the color value only to the points or something and 
2. how to draw all quandrangles with color at once without the `for` loop if possible

Thanks.

**Comment by banesullivan** [comment]
I'd recommend checking out the docs on what is a mesh: https://docs.pyvista.org/getting-started/what-is-a-mesh.html

Then check out this example about creating PolyData: https://docs.pyvista.org/examples/00-load/create-poly.html

Once you have a feel for those concepts, try creating a mesh.

Effectively, you have 10 unique points and 4 cells. So, create a `PolyData` mesh with those 10 nodes and mark the space between them as cells. To do this, you will need to remove duplicated nodes, better order your nodes, and then create a `faces` array with the correct IDs. 

For example:

```py
import numpy as np
import pyvista as pv

points = np.array([[-0.93333333,  1.        , -1.        ],
                   [-0.93333333,  1.        , -0.93333333],
                   [-0.93333333,  1.        , -0.86666667],
                   [-0.93333333,  1.        , -0.8       ],
                   [-0.93333333,  1.        , -0.73333333],
                   [-1.        ,  1.        , -1.        ],
                   [-1.        ,  1.        , -0.93333333],
                   [-1.        ,  1.        , -0.86666667],
                   [-1.        ,  1.        , -0.8       ],
                   [-1.        ,  1.        , -0.73333333],
                   ])

faces = np.array([[4, 0, 1, 6, 5],
                  [4, 1, 2, 7, 6],
                  [4, 2, 3, 8, 7],
                  [4, 3, 4, 9, 8]])

colormat = np.array([[0.11484721, 0.11484721, 0.11484721],
                     [0.11648363, 0.11648363, 0.11648363],
                     [0.12010454, 0.12010454, 0.12010454],
                     [0.12384401, 0.12384401, 0.12384401]]) * 255

mesh = pv.PolyData(points, faces)
mesh["colors"] = colormat

p = pv.Plotter()
p.add_mesh(mesh, show_edges=True, scalars="colors", rgb=True)
p.show()
```

![download](https://user-images.githubusercontent.com/22067021/81960564-24734080-95df-11ea-9dc0-c291cfb35249.png)

**Comment by TheodoreT** [comment]
@banesullivan thank you for the reply and the example. What you are suggesting would effectively work if you are able to obtain the unique vertices and their connection IDs in the faces array. In your example you are providing this information manually. 

My question is then, from my input x, y, z matrices is it possible to obtain these two new matrices, i.e. the points and faces arrays,  directly in pyvista or I need to use another 3d library two get this arrays and then feed them to pyvista for visualization.

**Comment by banesullivan** [comment]
Ah yep, if you do not have a cell IDs/faces array then you will need to use a triangulation technique to automate the mesh generation.

Try creating a point cloud mesh in `PolyData` with all of your vertices, then run the `clean` filter to remove duplicated points, and then a Delaunay triangulation filter

```py
pc = pv.PolyData(verts).clean()
surf = pc.delaunay_2d() # check parameters
```

see https://docs.pyvista.org/core/filters.html#pyvista.PolyDataFilters.delaunay_2d

**Comment by banesullivan** [comment]
Also, if your points are ordered to begin with, you could create a `StucturedGrid` to have a mesh with quads instead of triangles. There are plenty of other issues in this repo about doing that and should be some examples in the docs

**Comment by TheodoreT** [comment]
@banesullivan I need to have my mesh in quads so triangulation will not work for me. Thus, `StructureGrid` seems to be what I need. However, I am trying to use it given the examples on the documentation but it does not give the desired output. For example consider the following quad example:

```
points = np.array([[0., 1., 1.],
       [0., 1., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])
quad = pv.StructuredGrid()
quad.points = points
quad.dimensions = [2, 1, 2]
quad.plot(show_edges=True, show_grid=True, cpos="xz")
```

the points are in anti-clockwise (this shouldn't make any difference) order, thus this should give a quad but instead I am getting the following output:

![image](https://user-images.githubusercontent.com/10189018/82058306-1511f700-96b4-11ea-9886-b74a1c119af1.png)

what am I missing?

**Comment by TheodoreT** [comment]
ok, I got it the points need to be on a Z arrangement:
```
P1._______.P2
  |       |
  |       |
P3._______.P4
```

**Comment by TheodoreT** [comment]
@banesullivan I do not know what I am doing wrong but I cannot make it work. As I said my only information is the point coordinates, thus I tried to follow your example at https://github.com/pyvista/pyvista-support/issues/16#issuecomment-503206897

I loaded my points and visualized it with `PolyData`:

```
poly = pv.PolyData(verts).clean()
poly['order'] = np.linspace(0,1,poly.n_points)
poly.plot(notebook=False, show_grid=True, point_size=10)
```
and I got the following output which seems fine:

![image](https://user-images.githubusercontent.com/10189018/82090831-d2691280-96e5-11ea-8932-35067a982644.png)

Then I tried to plot it with `StructuredGrid` and I am getting a crappy output:
```
structured = pv.StructuredGrid()
structured.points = poly.points
structured.dimensions = [31, 1, 31]
elevation = structured.elevation()
elevation.plot(show_edges=True, show_grid=True, notebook=False)
```
![image](https://user-images.githubusercontent.com/10189018/82091404-ce89c000-96e6-11ea-9891-fe95a9f7fbef.png)
So my only guess is that my points are not ordered correctly, though the linear trend in the color mapping on `PolyData` plot shows that they are.

**Comment by akaszynski** [comment]
I think you're correct; your points aren't ordered properly.  I think you might have to use fortran ordering with your point array.  Can you

**Comment by TheodoreT** [comment]
@akaszynski any idea how to do that? I've tried a quick thought with `points.reshape((-1,3), order='F')` but it didn't really do anything. I am checking on `sorted` now.

**Comment by TheodoreT** [comment]
finally I ended up using the following solution with `PolyData` since I know that my points are in clockwise/anti-clockwise order for each quad:

    faces = np.arange(0, len(verts), 1)
    faces = np.split(faces, width) # where width in my case is 900 points
    faces = np.insert(faces, 0, 4, axis=1) # adding the information that my faces represent a quad

    mesh = pv.PolyData(verts, faces)
    mesh["colors"] = colormat
    plotter.add_mesh(mesh, show_edges=False, scalars="colors", rgb=True)

**Comment by akaszynski** [comment]
Thanks for posting your solution!

**Comment by banesullivan** [comment]
Glad you got it working, @ttsesm! Apologies for not following up
