### ISSUE TITLE
Bug with threshold filter

### ISSUE THREAD

**Issue by mli0603** [pyvista/pyvista-support#164]
Hi!

I have a binary volumetric data which has some sparse voxels being 1. I want to visualize how they look in space, so I tried to follow [this example](https://docs.pyvista.org/examples/01-filter/using-filters.html) where threshold is used.

Then I found a bug of the threshold function, which I am not sure if it comes from VTK or PyVista. The accuracy of the threshold function seems to be low such that the thresholded result is not actually correct. Here is a simple example

```python
import pyvista as pv
import numpy as np

# fail
volume = np.zeros([50,50,50])
volume[0] = 1 # there should be 50*50 points equal to 1
v = pv.wrap(volume)
threshed = v.threshold(0.5)
print(threshed) # return 0

# worked
volume = np.zeros([50,50,50])
volume[:25] = 1 # there should be 25*50*50 points equal to 1
v = pv.wrap(volume)
threshed = v.threshold(0.5)
print(threshed) # return 62500
```

In the first case, we know there should be `50*50` points being 1, while the output is `0`. In the second case, it worked. This makes me think that there may be some rounding happening at the back?

Another question is that is there any way I can directly show sparse voxels like this (i.e. without the `threshold` filter)?
![image](https://user-images.githubusercontent.com/13513172/82098665-6382be00-96d3-11ea-8663-c4831c106ab0.png)

Thank you!

**Comment by akaszynski** [comment]
Thanks for posting your code, it makes it easier to propose a solution.

Regarding the first issue regarding the `vtkThreshold` filter, it turns out that we need to add a parameter to allow for the setting of the `SetAllScalars` option.  Right now that setting is True by default, meaning that all points of a cell must match the threshold criteria.  I'm creating a new PR to address this issue.

For the time being, you can simply add 
```python
alg.SetAllScalars(all_scalars)
```
Right after
```
alg = vtk.vtkThreshold()
```

As for the second issue, I think you'll have to apply a threshold filter of some type in order to identify the parts of the `UniformGrid` that you'd like to plot.  @banesullivan, could you chime on if there's another way?

**Comment by banesullivan** [comment]
> As for the second issue, I think you'll have to apply a threshold filter of some type in order to identify the parts of the UniformGrid that you'd like to plot. @banesullivan, could you chime on if there's another way?

That's correct, you'll have to apply the threshold filter. You could also experiment with ghosting cells with the VTK data objects (but this isn't supported by PyVista)

**Comment by akaszynski** [comment]
Actually, I think we support ghosting cells.  See `remove_cells’

**Comment by banesullivan** [comment]
That method is only enabled for `PolyData`, `UnstructuredGrid`, and `StructuredGrid` meshes (points-based meshes)... we should think about expanding that to all types. So you'll have to run `cast_to_unstructured_grid`

This would work if you are thresholding on CELL data but not POINT data - I think @mli0603 cares about point data so they may have to run the`threshold` filter.

If working with CELL data, then you could do the following which is pretty nifty and a lot more lightweight than running a threshold filter.

```py
from pyvista import examples
import numpy as np

source = examples.load_uniform()

vol = source.cast_to_unstructured_grid()
ghosts = np.argwhere(vol["Spatial Cell Data"]>250)
vol.remove_cells(ghosts)
vol.plot()
```

![download](https://user-images.githubusercontent.com/22067021/82743006-091cd980-9d33-11ea-83fe-5c6db69546de.png)
