### ISSUE TITLE
Renderings are static

### ISSUE THREAD

**Issue by sbonaretti** [pyvista/pyvista-support#166]
Hi, 
I have just installed pyvista (v.0.24.2) and I am trying the notebook `create-point-cloud.ipynb` locally.
The rendering I get is a static figure. I do not get the interactivity that I can experience for the same notebook on binder, neither when I locally try in JupyterLab nor in Jupyter notebook itself. 
Am I missing some enabling? Cannot find anything in the documentation. 
Thanks!

**Comment by akaszynski** [comment]
Hello,

There's additional documentation regarding interactive notebooks plots here:
https://docs.pyvista.org/plotting/itk_plotting.html?highlight=itkwidgets

I personally use `itkwidgets`, but it's a bit of pain to setup.  `panel` works really well, and they've had some really great new features as of late.

**Comment by sbonaretti** [comment]
Thanks for replying so quickly! Where can I find an example with Panel? Thanks!

**Comment by akaszynski** [comment]
Sure!  We really should add an example to the docs.

```python
import pyvista
sphere = pyvista.Sphere()
sphere.plot(use_panel=True)
```

**Comment by sbonaretti** [comment]
Thanks again. It still does not work, neither in JupyterLab nor Jupyter notebook itself. Do you have any suggestion? Am I missing some installation?

**Comment by akaszynski** [comment]
Did you install `panel` with `pip install panel`?

**Comment by sbonaretti** [comment]
It works!!! I had't installed it! I thought it was already in the anaconda environment, and I did not get any error from the code. Thanks for helping me so quickly! :)

**Comment by sbonaretti** [comment]
Does `use_panel=True` work for all plotting commands or only `plot`? 
When I try:
```
import pyvista as pv
from pyvista import examples

mesh = examples.download_knee_full()

p = pv.Plotter(notebook=False)
p.add_mesh_threshold(mesh)
p.show(use_panel=True)
```
I get an external window. 
Thanks!!!

**Comment by akaszynski** [comment]
That's strange, because it should display to panel.  Let me look into this.

**Comment by banesullivan** [comment]
Make sure you have `panel` installed and put the `notebook` argument to `True` as `panel` would be inside the notebook 😉  (`notebook=False` will force plotting to pop out of the notebook env and into a window)
