### ISSUE TITLE
How to pick a single grid cell under the mouse location?

### ISSUE THREAD

**Issue by rodrigomologni** [pyvista/pyvista-support#177]
PyVista Support,

Could you provide an example of how to pick a single grid cell under the mouse location, please? I'm running the code below, but pressing P isn't working.

```
import pyvista as pv

def picked_cells(subgrid):
    print(subgrid)

grid = pv.UniformGrid((10, 20, 5))

plotter = pv.Plotter()
plotter.add_mesh(grid, show_edges=True)
plotter.enable_cell_picking(callback=picked_cells)
plotter.show()
```

![image](https://user-images.githubusercontent.com/1608652/84300093-34236d80-ab28-11ea-85e2-9b6b78a1adad.png)

When I use `through=False`, the message "Press P to pick a single cell under the mouse" is shown, but P doesn't work and R produces incorrect selections even with a NVIDIA card.

![image](https://user-images.githubusercontent.com/1608652/84301826-cdec1a00-ab2a-11ea-9e72-03d0aaed833f.png)

**Comment by akaszynski** [comment]
I'm also running into the same issue on Linux despite also using a NVIDIA GPU.  For some reason the indices mapped by `vtkOpenGLHardwareSelector` do not correspond to the selected mesh.  It's as if there's some sort of conversion happening internally within `vtkOpenGLHardwareSelector` and the mesh it's using is different than the one used by the main renderer.

**Comment by rodrigomologni** [comment]
I downgraded PyVista to version 0.22.0. R is producing correct selections now, but P still doesn't work.

![image](https://user-images.githubusercontent.com/1608652/84531517-1f2b1380-acbb-11ea-9b07-048140023842.png)

About my Python environment:

```
--------------------------------------------------------------------------------
  Date: Fri Jun 12 14:53:46 2020 Hora oficial do Brasil

                OS : Windows
            CPU(s) : 4
           Machine : AMD64
      Architecture : 64bit
               RAM : 7.9 GB
       Environment : Python

  Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64
  bit (AMD64)]

           pyvista : 0.22.0
               vtk : 9.0.0
             numpy : 1.17.3
             scipy : 1.4.1
           IPython : 7.15.0
        matplotlib : 3.2.1
            scooby : 0.5.2
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment]
Fixed this in https://github.com/pyvista/pyvista/pull/799
