### ISSUE TITLE
Multiple slider inputs for single callback function.

### ISSUE THREAD

**Issue by jb4earth** [pyvista/pyvista-support#179]
## Description

I have a callback function / generator that creates a shape based on some inputs (it looks something like this): 

```
def generate_mandelbulb_mesh(va,vb,vc,iterations):
    # some calls to my mandelbulb meshing library goes here making a mesh from the given inputs
    # any mesh will do, maybe consider a sphere with resolution N and radius R
    return mesh
```

Right now I hold vb,vc,iterations constant and set the slider to drive va but I would love to be able to drive all of them from the viewer sliders.

**Comment by adeak** [comment]
One thing is not clear to me. It seems like your function returns a dataset. How does this work as a callback? If you change a slider or toggle a button, what happens?

Or is it really that you're calling `generate_mandelbulb_mesh` manually, but the parameters for the mesh are determined by the widgets?

**Comment by jb4earth** [comment]
You’re right on, the parameters for the mesh are determined by the widget.

This thread seems relevant: https://github.com/mne-tools/mne-python/pull/7509

**Comment by adeak** [comment]
OK. Looking at [add_slider_widget](https://docs.pyvista.org/plotting/widgets.html#pyvista.WidgetHelper.add_slider_widget) it does indeed seem that you can't just query the value of the slider, and looking at the object returned from `add_slider_widget` there's no straightforward attribute that holds this.

So what I would do is define an auxiliary class that keeps track of the parameters you need for creating the mesh. The callbacks of each slider change these attributes. On mesh generation the attributes are read out. I suspect you can even use [a dataclass](https://docs.python.org/3/library/dataclasses.html) if you don't want to hack your own class together.

But @banesullivan might have a better suggestion in mind; they did mention that they know what to do here.

**Comment by banesullivan** [comment]
I would handle this with a class-based callback. For example:

```py
import pyvista as pv


class MyCustomRoutine():
    def __init__(self, mesh):
        self.output = mesh # Expected PyVista mesh type
        # default parameters
        self.kwargs = {
            'radius': 0.5,
            'theta_resolution': 30,
            'phi_resolution': 30,
        }

    def __call__(self, param, value):
        self.kwargs[param] = value
        self.update()
    
    def update(self):
        # This is where you call your simulation
        result = pv.Sphere(**self.kwargs)
        self.output.overwrite(result)
        return
    

starting_mesh = pv.Sphere()    
engine = MyCustomRoutine(starting_mesh)

p = pv.Plotter(notebook=False)
p.add_mesh(starting_mesh, show_edges=True)
p.add_slider_widget(
    callback=lambda value: engine('phi_resolution', int(value)),
    rng=[3, 60],
    value=30,
    title="Phi Resolution",
    pointa=(.025, .1), pointb=(.31, .1),
)
p.add_slider_widget(
    callback=lambda value: engine('theta_resolution', int(value)),
    rng=[3, 60],
    value=30,
    title="Theta Resolution",
    pointa=(.35, .1), pointb=(.64, .1),
)
p.add_slider_widget(
    callback=lambda value: engine('radius', value),
    rng=[0.1, 1.5],
    value=0.5,
    title="Radius",
    pointa=(.67, .1), pointb=(.98, .1),
)
p.show()
```

![2020-06-13 15 30 25](https://user-images.githubusercontent.com/22067021/84577508-d9d61700-ad8a-11ea-82d5-51c4cf1a9270.gif)


The trick is to add a mesh to the scene that you will overwrite in-place with the results from your simulation code. Keep track of the arguments in your custom class and place the sliders where you want them

**Comment by banesullivan** [comment]
Also, the `'modern'` styles for sliders is slick:

```py
...
p.add_slider_widget(
    ...
    style='modern',
)
```

![Screen Shot 2020-06-13 at 3 42 06 PM](https://user-images.githubusercontent.com/22067021/84577678-8664c880-ad8c-11ea-9f54-81f322d7e76c.png)
