### ISSUE TITLE
Hide/show actors

### ISSUE THREAD

**Issue by bistek** [pyvista/pyvista-support#182]
Hello, is it possible to hide and show actors without removing them from the scene, as is done in VTK with `.SetVisibility(True/False)`?

This will simplify maintaining a list of actors and showing them or not when needed.

Thanks very much!

**Comment by bistek** [comment]
I see now that a similar issue is addressed [here](https://github.com/pyvista/pyvista-support/issues/69), but I am working with **pyvistaqt** so this is different.

**Comment by banesullivan** [comment]
Here's a way to do it with the checkbox button widget:

```py
import pyvista as pv

mesh = pv.Sphere()

p = pv.Plotter(notebook=0)
actor = p.add_mesh(mesh)

def toggle_vis(flag):
    actor.SetVisibility(flag)

p.add_checkbox_button_widget(toggle_vis, value=True)

p.show()
```

![2020-06-17 12 33 53](https://user-images.githubusercontent.com/22067021/84924681-e31af880-b096-11ea-9863-0d525d766fb2.gif)

**Comment by banesullivan** [comment]
> but I am working with pyvistaqt so this is different.

Not different actually. The `BackgroundPlotter` in `pyvistaqt` inherits from the same base as the `Plotter` so the API calls are all the same

**Comment by banesullivan** [comment]
If you're savvy with PyQt, then you could add a list view of all actors in the scene into a new widget and put a toggle button next to those items that callback to `SetVisibility`

**Comment by bistek** [comment]
This was the idea. Thanks very much!!!

**Comment by bistek** [comment]
Hi, this is an old issue and I have been using SetVisibility for some time. Unfortunately I have just found a bug or at leas an unexpected behaviour. If a scalar property or a texture is shown it appears that SetVisibility does not work, i.e. it is not able to show or hide the actor.

Do you have ideas about this?

Thanks!

**Comment by akaszynski** [comment]
@bistek, could you open a new issue for this?  This sounds like something we should fix.

**Comment by bistek** [comment]
@akaszynski, done. It is issue #408. Thanks!
