### ISSUE TITLE
Plotting vectors/arrows with fixed size but different colours

### ISSUE THREAD

**Issue by samcoveney** [pyvista/pyvista-support#184]
Hello!

Is there any way to plot arrows/vectors with different colours (defined by an array of floats, not by the 'color' command) but equal size? My specific use case is for vector magnitude to be displayed as color, but vector length to be uniform.

(But more generally, it would be good to know how to independently control vector length and color with two distinct arrays).

I have tried to do this by modifying several of these examples: https://docs.pyvista.org/examples/01-filter/glyphs.html but I cannot figure it out.

Thanks in advance

**Comment by banesullivan** [comment]
> Is there any way to plot arrows/vectors with different colours (defined by an array of floats, not by the 'color' command)

This is what the `scalars` argument to `Plotter.add_mesh` is for.

> My specific use case is for vector magnitude to be displayed as color, but vector length to be uniform. ... it would be good to know how to independently control vector length and color with two distinct arrays

To create the arrows, use the `glyph` filter with the `orient` and `scale` arguments set to the names of the two arrays you want to orient and scale the vectors by, respectively. If you want constant sized arrows, set `scale` to `False`. To color the arrows by some array, then when plotting, specify the `scalars` array as the name of the array you want to color by. Here is another version of that same example:

```py
import pyvista as pv
from pyvista import examples

# Example dataset with normals
mesh = examples.load_random_hills()

# create a subset of arrows using the glyph filter
arrows = mesh.glyph(scale=False, orient="Normals", tolerance=0.05)

p = pv.Plotter()
p.add_mesh(arrows, scalars="Elevation", cmap="terrain")
p.add_mesh(mesh, color="lightgrey")
p.show()
```

<img width="624" alt="Screen Shot 2020-06-22 at 7 37 21 AM" src="https://user-images.githubusercontent.com/22067021/85283368-402dfa00-b45b-11ea-9343-fc41a84ba4dd.png">

**Comment by samcoveney** [comment]
Thanks very much for your reply, this is really helpful.

However, I find that this solution does not scale with the magnitude of the coordinates.

The following code will fail to plot visible arrows (they are tiny):

```python
import pyvista as pv
from pyvista import examples
import numpy as np

# Example dataset with normals
mesh = examples.load_random_hills()

# increase magnitude of coordinates
# works for SCALE = 1
# fails for SCALE = 100
SCALE = 100

# Extract information from mesh
X = mesh.points * SCALE
Normals = mesh["Normals"]
Elevation = mesh["Elevation"]

# Create a new mesh object, to see how to set values
mesh = pv.PolyData(X)
mesh.point_arrays["Normals"] = Normals * SCALE
mesh.point_arrays["Elevation"] = Elevation * SCALE 

# create a subset of arrows using the glyph filter
arrows = mesh.glyph(scale = False, orient="Normals")

p = pv.Plotter()
p.add_mesh(arrows, scalars="Elevation", cmap="terrain")
p.add_mesh(mesh, color="lightgrey")
p.show()
```

For my application, I have had some luck with setting the point arrays for the arrows (the array to set to 'orient') as CONSTANT * unit vectors and scale = 1.0 (where CONSTANT is required to make the arrows large enough to see).

Any idea what the problem is?

Thanks

**Comment by banesullivan** [comment]
when `scale=False` for the glyph filter, the arrows still have to be sized appropriately because actual geometric arrows are created, so they are scaled via the magnitude of the normal (which should be `1.0`). Use the `factor` argument of the `glyph` filter to account for your scaling:

```py
arrows = mesh.glyph(scale = False, orient="Normals", factor=SCALE)
```

See [`glyph()`](https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.glyph) for detials on the arguments to this filter

**Comment by samcoveney** [comment]
That's great, thanks, the ```factor``` argument with ```scale = False``` solves my problem. Thanks again
