### ISSUE TITLE
extracting data from unstructured grid using spline

### ISSUE THREAD

**Issue by haspelstfs** [pyvista/pyvista-support#185]
Topic: extracting data from unstructured grid using spline

## Description

Hi everyone,

I am trying to extract a scalar data array in the from of a spline. I have an unstructured grid where I want to extract data in a cut plane and additionally in this plane I want only the data for a given spline (e.g. circle).
I have tried to do it using slice_along_line and created a spline (e.g. spline) but the returned object looks odd and not what I would expect.

Any suggestions?

Happy to hear from you!

Greets,

Philip

## Example Code

grid = pv.UnstructuredGrid('pathToVTK')
x, y, z = circle(radius, slicePlaneOffset)
points = np.c_[x, y, z]
spline = pv.Spline(points, 20)
slc = grid.slice_along_line(spline)

**Comment by banesullivan** [comment]
Can you provide that `circle` function to generate the spline? Also, if you could include your data, that would also be very helpful

**Comment by banesullivan** [comment]
I have a feeling you're going to want to use the `sample` method. e.g.:

```py
stuff = spline.sample(grid)
```

**Comment by haspelstfs** [comment]
Hi Bane, thanks a lot for your fast reply--> your post did the trick!
I also tried your solution but the other way around: stuff = grid.sample(spline)
Here the circle function anyway:
def circle(r,y):
    """Equation: x= cos(deg)*r, z = sin(deg)*r"""
    theta = np.linspace(0, 2* np.pi, 20)
    x = r * np.cos(theta)
    y = np.full(len(theta), y)
    z = r * np.sin(theta)
    print("radius :", np.sqrt(x**2,z**2))
    return x, y, z
The dataset unfortunately is very large (LES grid with over 12 Million cells).
Glad it works 😄
