### ISSUE TITLE
Finite element mesh normals

### ISSUE THREAD

**Issue by zmrogers** [pyvista/pyvista-support#187]
## Description

I would like to read an Abaqus input file (*.inp) and calculate vectors normal to specified nodes based on their node IDs or the coordinates of the nodes. The mesh is composed of solid elements. The nodes lie on the outer surface of the mesh.

I have read the file using pyvista.read() which results in an UnstructuredGrid. 

I see there are classes within pyvista that have compute_normal methods but an UnstructuredGrid is not one of them,

**Comment by banesullivan** [comment]
Can you share such example data?

You'll likely need to convert the `UnstructuredGrid` to `PolyData` via the `extract_surfac()` filter then compute the normals via `compute_normals()`. I assume your dataset has no 3D geometries but only 2D face cells, correct?

I'd recommend following this example once you have `PolyData` if that's suitable for your data: https://docs.pyvista.org/examples/01-filter/compute-normals.html

**Comment by zmrogers** [comment]
This worked. Thank you!
