### ISSUE TITLE
Getting pixel size in shape units using pyvista.Plotter

### ISSUE THREAD

**Issue by lisonator** [pyvista/pyvista-support#192]
## Description
I'd like to calculate an area and center of mass of a projection of a 3d shape in. To accomplish this I want to use pyvista.Plotter with parallel projection, specify camera view, and get an image of the projection as numpy array using pyvista.Plotter.image. From this point I can calculate projection area and center of mass in respectively pixels^2 and pixels.

The problem I'm having is I cannot find a way to extract information, which would let me convert those measures from pixels to shape units (e.g. if the vertices are specified in meters, I want to have the results also in meters). 

Do you have any recommendations?

## Example Data

```
import pyvista as pv
import numpy as np
from scipy.ndimage import center_of_mass

box1 = pv.Box((0,1,2,3,-1,0.5))
box2 = pv.Box((0,3,2,3,1,1.5))
shape = box1 + box2
plotter = pv.Plotter(off_screen=True,window_size=[800,800])
plotter.add_mesh(shape)
plotter.background_color = (0,0,0)
plotter.camera.ParallelProjectionOn()
plotter.view_vector([1,2,3])
img = plotter.image
area_px = np.sum(np.any(img,axis=-1))
center_px = center_of_mass(np.any(img,axis=-1))
```

**Comment by banesullivan** [comment]
Why are you doing it this way?.... do you really need to do this in a computer vision-esque approach?

Why not just compute these values in that space directly? E.g. the `center` property of all PyVista meshes.

**Comment by banesullivan** [comment]
PolyData have a `center_of_mass()` method that will return the coordinates for the center of mass of the mesh

**Comment by lisonator** [comment]
Thanks for quick response. The reason I'm doing it that way is that I want area and center of mass of the projection of the shape and not the shape itself.

**Comment by banesullivan** [comment]
So in essence, you want to compute the center of mass of what's rendered on the camera's viewing plane and reproject that point to world coordinates?

**Comment by lisonator** [comment]
Exactly. Center of mass and area.

**Comment by banesullivan** [comment]
I'm not sure how this would work for the area, but I remember doing this a long while back for general coordinates back when I was experimenting with the depth image stuff (ref https://github.com/pyvista/pyvista/issues/368). Basically we were projecting stereo images (depth maps) back into 3D world coordinates - but the code I had in one example should work for this scenario.

@tomtomatron actually took this way further and is much more versed in computer vision than I and may be able to share some code snippets to do this?

Otherwise, I'll have to go deep diving to find this code... but it does exist... somewhere... and then I'll need to update it to work in this context

**Comment by Keou0007** [comment]
@lisonator I've done what I think you want for myself. My approach is to insert a sphere of known radius at the focal point of the camera, then extract the frame as a screenshot and search for pixels in the colour of the sphere. Turning lighting off makes the colour change binary. Once you have the pixel locations of the sphere, it's trivial to extract the height and width and then use the known radius to get per pixel scale conversion factor out.

The code below incomplete, but hopefully it has enough of the pieces you need. I start with a small sphere and double it's radius till it's taking up at least 20% of the window height so I can have some confidence in the accuracy of the conversion factor. I also average between the height and width of the sphere if the pixel size results in a slightly skewed image.

I also use a similar approach to find the pixel location of the domain origin in my screenshots.

```
GREEN = (0, 255, 0)

def measure_circle(points):
    """
    Take an array of (row, col) tuples representing pixels making up a circle
    and return the coordinates of the centre as a (row, col) tuple,
    along with the height and width of the circle in pixels
    """
    left = np.min(points[:, 1])
    right = np.max(points[:, 1])
    top = np.min(points[:, 0])
    bottom = np.max(points[:, 0])

    centre = (int(top + (bottom - top) / 2), int(left + (right - left) / 2))
    height = bottom - top + 1
    width = right - left + 1

    return centre, height, width


def find_circle(image, colour=GREEN):
    """
    find a circle of a given colour in an image and return
    the location of the pixels making up that circle as an array
    of (row, col) tuples
    """
    return np.array(list(zip(*np.where(np.all(image == colour, axis=-1)))))

def calibrate_view(cpos, parallel_scale):

    scene = pv.Plotter()
    scene.camera_position = cpos
    scene.camera.SetParallelProjection(1)
    scene.camera.SetParallelScale(parallel_scale)
    scene.background_color = (0, 0, 0)
    scene.render()

    focal_point = scene.camera_position[1]
    height_threshold = int(scene.window_size[1] * 0.2)
    height = 0
    width = 0
    radius = start_size / 2
    while height < height_threshold:
        radius = radius * 2
        print("inserting sphere with radius", radius)
        sphere = pv.Sphere(
            center=focal_point,
            radius=radius,
            theta_resolution=1000,
            phi_resolution=1000,
        )
        actor = scene.add_mesh(sphere, color=GREEN, lighting=False, reset_camera=False)
        frame = scene.screenshot(None, return_img=True)
        _, height, width = measure_circle(find_circle(frame, GREEN))
        scene.remove_actor(actor)

    if height != width:
        height = (height + width) / 2

    m_per_pixel = radius * 2 / height

    print("radius:", radius)
    print("height in pixels:", height)
    print("metre per pixel:", m_per_pixel)
    print("mm per pixel:", m_per_pixel * 1000)

```

**Comment by Keou0007** [comment]
bit of google searching has proved fruitful. Turns out that the parallelscale value is the worlds units visible above and below the focal point. So if you want a metres per pixel scale, it's just parallelscale * 2 / window_size[1]. I checked this against my calibration factors measured using the code above and it's the same to within rounding error of less than 1%.

**Comment by lisonator** [comment]
Thanks for suggestions @Keou0007 . Regarding 'sphere calibration approach' I did something similar in the end, but with a square/cube.  
Your second suggestion sounds as it is something I was looking for! I'll need to play with it :)
