### ISSUE TITLE
Contours for single slide

### ISSUE THREAD

**Issue by CLDiego** [pyvista/pyvista-support#193]
## Description
Hi, 

I'm trying to obtain the contours of a slice that comes from a vtk mesh. I've seen that this is possible for the whole mesh, but I've been able to make it work once I slice the volume. Is this possible currently?

## Example Data
I'm using the following code:
```
mesh = pv.read(f_name)
mesh.set_active_scalars(k_scalar)
mesh = mesh.cell_data_to_point_data()
contours = mesh.contour()
single_slice = mesh.slice(normal=[0, 0, 1])

p = pv.Plotter()
p.add_mesh(single_slice, cmap=cmap,  log_scale=True)
p.add_mesh(contours)
p.show()
```

However, in this case the contours come from the 3D volume and not the 2D slide. Any suggestions are welcomed. Thanks!

**Comment by banesullivan** [comment]
Perhaps just changing your order of operations? 

```py
single_slice = mesh.slice(normal=[0, 0, 1])
contours = mesh.contour()
```

But this should yield the same result...

I'm not really sure what you are asking/looking for?

**Comment by CLDiego** [comment]
Hi @banesullivan,

Yes, yields the same result. I'm trying to apply the contour filter to the single_slice.

I just found that the slice function has a boolean flag to apply the contour filter directly after the slicing operation.

However, it does not seem to be a way to control its parameters.

I'm trying the following code:
`
mesh = mesh.cell_data_to_point_data()
contours = mesh.contour(isosurfaces=20, rng=(1e02, 5e02))
single_slice = mesh.slice(normal=[0, 0, 1], contour=True)
`

But the countour range does not change in the single_slice

**Comment by banesullivan** [comment]
> But the countour range does not change in the single_slice

Well, your `single_slice` is a slice of `mesh`... there's no way it could be aware of the contours you have in `contours`. The boolean flag for `contour=True` is equivalent to calling `.contour()` after the slice filter with default parameters.

Try:

```py
mesh = mesh.cell_data_to_point_data()
contours = mesh.contour(isosurfaces=20, rng=(1e02, 5e02))
single_slice = contours.slice(normal=[0, 0, 1], )
```

This way, you've hained three operations together: `mesh` -> `contours` (via `. mesh.contour()`) -> `single_slice` (via `contours.slice()`)

**Comment by CLDiego** [comment]
Thanks @banesullivan , I see what you mean. I guess it didn't cross my mind that I could slice through the contour filter !
