### ISSUE TITLE
Point and Cell IDs

### ISSUE THREAD

**Issue by zmrogers** [pyvista/pyvista-support#194]
## Description
Do Points and Cells have IDs associated with them, similar to how nodes and elements in a finite element model have IDs associated with them?

I have created a StructuredGrid from an array of coordinates then created a PolyData using extract_surface. I have the index of a point of interest. I would like to know the ID of the node represented by this point in my original model.

Can the StructuredGrid be constructed such that IDs are associated with points from the outset and carried forward into the PolyData object?

Something like:

grid = pv.StructuredGrid(x,y,z,ID)
-->

**Comment by akaszynski** [comment]
Hello @zmrogers,

`StructuredGrid` instances do not have proper cell IDs.  For that, cast to an unstructured grid with `cast_to_unstructured_grid`.  At that point, you can either add IDs to the cells by introducing something in the `cell_arrays`:
```
my_ugrid['ids'] = np.arange(my_ugrid.n_cells)
```

**Comment by banesullivan** [comment]
> I have the index of a point of interest. I would like to know the ID of the node represented by this point in my original model.

The index is the point ID
