### ISSUE TITLE
Update colormap when changing thresholds of a mesh with a widget

### ISSUE THREAD

**Issue by vpicouet** [pyvista/pyvista-support#195]
Hello,
and thank you for all the help you are providing.
The following code displays a the emission of a galaxy (2 spatial dimension + spectra one).
There are 3 widgets to change the thresholds of the pixels we visualize (+ one to stretch the plot in the thridace direction).
Is it possible to update the vmin,vmax values of the colormap so that we still use the whole camp dynamic (something like this, no histogram needed)
<img width="318" alt="image" src="https://user-images.githubusercontent.com/37241971/86141930-ea102500-baf2-11ea-80e2-104bdb588830.png">.
For now I have this:
<img width="994" alt="image" src="https://user-images.githubusercontent.com/37241971/86141441-5a6a7680-baf2-11ea-8213-906f919db32c.png">

The code is here 

"""

    from pyvista import Plotter, set_plot_theme, wrap
    from astropy.io import fits
    class Change3dMesh():
        def __init__(self, mesh):
            self.output = mesh 
            self.kwargs = {
                'DensityMin': 0.5,
                'DensityMax': 0.5,
                'StretchingFactor': 0.5,}
    
        def __call__(self, param, value):
            self.kwargs[param] = value
            self.update()
        
        def update(self):
            result = createMesh(**self.kwargs)
            self.output.overwrite(result)
            return
     
    set_plot_theme("document")
    data=fits.open('/Users/Vincent/Downloads/lya_cube_merged_with_artificial_source_CU_1pc.fits')[0].data#[:n,:n,:n]
    data = np.log10(data[:,:,:])

    mask=(data.ravel()>np.nanpercentile(data,0.1)) & (data.ravel()<np.nanpercentile(data,99.9))
    
    print(np.sum(mask)/len(mask))
    xx, yy, zz = np.indices(data.shape)#np.me 
    starting_mesh = wrap(np.array([yy.ravel()[mask],zz.ravel()[mask],xx.ravel()[mask]]).T)   
    starting_mesh['Intensity']= data.ravel()[mask]#np.log10(data.ravel()[mask])#exp(-((yy-yy.mean())**2+(xx-xx.mean())**2+(zz-zz.mean())**2)/100).ravel()
    
    def createMesh(DensityMin=0.5,DensityMax=0.5,StretchingFactor=0.5):
        mask = (data.ravel()>DensityMin) & (data.ravel()<DensityMax)
        mesh =  wrap(np.array([yy.ravel()[mask],zz.ravel()[mask],StretchingFactor*xx.ravel()[mask]-np.nanmean(StretchingFactor*xx.ravel()[mask])]).T)
        mesh['Intensity']= data.ravel()[mask]#np.log10(data.ravel()[mask])#exp(-((yy-yy.mean())**2+(xx-xx.mean())**2+(zz-zz.mean())**2)/100).ravel()
        return mesh
    
    engine = Change3dMesh(starting_mesh)
    
    
    
    p = Plotter(notebook=False,window_size=[2*1024, 2*768], title='3D')
    p.add_mesh(starting_mesh, show_edges=True,point_size=5,nan_opacity=0,cmap='jet',name='Data')
    m = p.add_slider_widget(
        callback=lambda value: engine('DensityMin', int(value)),
        rng=[np.nanmin(data[np.isfinite(data)]),np.nanmax(data[np.isfinite(data)])],
        value=np.nanmin(data[np.isfinite(data)]),
        title="Density Threshold Min",
        pointa=(.025, .9), pointb=(.31, .9),
    )
    p.add_slider_widget(
        callback=lambda value: engine('DensityMax', int(value)),
        rng=[np.nanmin(data[np.isfinite(data)]),np.nanmax(data[np.isfinite(data)])],
        value=np.nanmax(data[np.isfinite(data)]),
        title="Density Threshold Max",
        pointa=(.35, .9), pointb=(.64, .9),
    )
    p.add_slider_widget(
        callback=lambda value: engine('StretchingFactor', value),
        rng=[0, 1],
        value=0.5,
        title="Stretching Factor",
        pointa=(.67, .9), pointb=(.98, .9),
    )
    p.show()
"""
And you can find the fits image here:
https://nuage.osupytheas.fr/s/NNeMtNWoNmqexqT

Thanks for your help!

Best

Vincent

**Comment by vpicouet** [comment]
One solution I found was to change the update function by 
```
        def update(self):
            p.remove_actor('Data')
            result = createMesh(**self.kwargs)
            p.add_mesh(result, show_edges=True,point_size=5,opacity=0.2,nan_opacity=0,cmap='jet',clim=[np.nanmin(result['Intensity']),np.nanmax(result['Intensity'])],name='Data')
            return
```
It looks better even though it results in clearing the plot every time we touch a widget...
<img width="706" alt="image" src="https://user-images.githubusercontent.com/37241971/86471924-8712ce00-bd3e-11ea-9921-4a8cc6cadd53.png">
Let me know if there is a better way,
Thanks a lot!

Best

**Comment by banesullivan** [comment]
Are you just trying to update the colormap's limits? If so, [`Plotter.update_scalar_bar_range`](https://docs.pyvista.org/plotting/plotting.html#pyvista.BasePlotter.update_scalar_bar_range) is what you're looking for

**Comment by vpicouet** [comment]
Thank a lot! It works well, I did not see these update command!
<img width="976" alt="image" src="https://user-images.githubusercontent.com/37241971/87398733-a3243400-c5b6-11ea-86aa-5abb69598911.png">
Is there a way to change the parameters of the add_mesh function like the point_size or opacity arguments? I could not find those!
Anyway, thanks for the colormap trick!

**Comment by banesullivan** [comment]
`add_mesh` returns the actor. You can set those propertie via:

```py
...
a = p.add_mesh(mesh, **kwargs)
...

# update later
a.GetProperty().SetOpactity(0.5)
```

or you could do this with a slider:

```py
p = pv.Plotter()
a = p.add_mesh(pv.Sphere())
p.add_slider_widget(callback=a.GetProperty().SetOpacity, rng=[0,1])
p.show()
```

**Comment by vpicouet** [comment]
Thanks a lot for the help!
I guess the issue can be closed!
