### ISSUE TITLE
Slicing and Identify specific points on the surface mesh 

### ISSUE THREAD

**Issue by MariaFda** [pyvista/pyvista-support#197]
Hi everyone!

I have a 3D mesh and I'm wondering if I could slicing it, and save these different parts. Besides, If I could identify specific points in the body. 

Thanks to everyone, 

Here is the mesh. I have to put into a zip, because the original file is a .obj 
[spider.obj.zip](https://github.com/pyvista/pyvista-support/files/4860793/spider.obj.zip)

**Comment by banesullivan** [comment]
You likely want to take a look at the various widgets we offer in PyVista: https://docs.pyvista.org/plotting/widgets.html#widgets

Specifically, this example may be helpful: https://docs.pyvista.org/plotting/widgets.html#plane-widget

```py
import pyvista as pv

mesh = pv.read('spider.obj')

p = pv.Plotter(notebook=False)
p.add_mesh_clip_plane(mesh)
p.show()
```

Then when your done clipping, save the clipped mesh via:

```py
p.plane_clipped_meshes[0].save('clipped.obj')
```

**Comment by MariaFda** [comment]
Thanks for answering, the interactive function looks very cool and useful. Also, do you know anything that could be work for detecting landmarks on the surface mesh?. 


Thankss!! :)

**Comment by banesullivan** [comment]
> Also, do you know anything that could be work for detecting landmarks on the surface mesh?.

I don't - PyVista does not have any tools for segmentation/feature identification. PyVista can do things like extract parts of a mesh that meet criteria like where the feature angles meet some degree, etc.
