### ISSUE TITLE
Is it possible to change or remove the plotter text after plotter.add_text

### ISSUE THREAD

**Issue by davidxmiller** [pyvista/pyvista-support#198]
Hello,
Is it possible to change or remove the plotter text after plotter.add_text?
I am looking to change the text shown for each frame in a GIF animation.
I can call plotter.add_text during the animation step, but the text is added over the top (as expected) rather than replacing the existing text.
I can access the textActor that is returned from the the original add_text, but haven't found a way to use this to either alter the text, or to remove the text.
Thanks,
Dave.

**Comment by banesullivan** [comment]
The "PyVista way" to do this would be to use the `name` keyword argument when adding the text. Then repeatedly call the `add_text` method with the same `name` argument to update that text. For example:

```py
...
plotter = pv.Plotter()

# Adfter instantiatied the plotter
def update_text(text):
    plotter.add_text(text, name="mylabel")

... # Your time-varying routine:
for time in steps:
    update_text("Time: {:.2f}".format(time))
```

Here is a full example using [this demo](https://docs.pyvista.org/examples/02-plot/gif.html):

<details>

```py
import pyvista as pv
import numpy as np

x = np.arange(-10, 10, 0.25)
y = np.arange(-10, 10, 0.25)
x, y = np.meshgrid(x, y)
r = np.sqrt(x ** 2 + y ** 2)
z = np.sin(r)

# Create and structured surface
grid = pv.StructuredGrid(x, y, z)

# Create a plotter object and set the scalars to the Z height
plotter = pv.Plotter()
plotter.add_mesh(grid, scalars=z.ravel())

def update_text(text):
    plotter.add_text(text, name="mylabel")

print('Orient the view, then press "q" to close window and produce movie')

# setup camera and close
plotter.show(auto_close=False)

# Open a gif
plotter.open_gif("~/Desktop/wave.gif")

pts = grid.points.copy()

# Update Z and write a frame for each updated position
nframe = 15
for phase in np.linspace(0, 2 * np.pi, nframe + 1)[:nframe]:
    z = np.sin(r + phase)
    pts[:, -1] = z.ravel()
    plotter.update_coordinates(pts)
    plotter.update_scalars(z.ravel())
    update_text("Phase: {:.2f}".format(phase))
    plotter.write_frame()

# Close movie and delete object
plotter.close()
```

</details>

![wave](https://user-images.githubusercontent.com/22067021/86546875-cee35200-bf04-11ea-97b4-9ba5322d5307.gif)

**Comment by davidxmiller** [comment]
Hi Bane,
Great, thanks for your speedy response. I've tested adding a label in my program and it works perfectly, thanks.
As an aside thanks for PyVista, I'd just finished getting VTK going in python and had started using it when I came across PyVista, it's much easier to use :)
Thanks,
Dave.
