### ISSUE TITLE
Method to add tensor data?

### ISSUE THREAD

**Issue by jrwrigh** [pyvista/pyvista-support#202]
I know that adding a scalar or vector to a data set is simply:
``` py
grid['data_name'] = data_nparray
```
where `data_nparray` is Nx1 for a scalar and Nx3 for a vector.

But I'm not sure how to go about adding tensor data. Is that a supported feature? If so, what order should the data be in?

Note: In response the bot, I'll add that I submitted this as an issue since either A) the feature doesn't exist or B) the feature isn't' documented. That said, the scalar and vector operations I reference above don't seem to be documented anywhere either.

**Comment by banesullivan** [comment]
Unfortunately, we do not really have any features in PyVsita that leverage tensors. Let us know what you're doing with tensors don the road and maybe we can get feature requests going for filters that utilize tensors.

**Comment by jrwrigh** [comment]
I'm mainly just dealing with reynolds stress tensors. So most of my operations are really just getting the tensor values into the correct reference frame.

In a typical workflow, the stresses are stored referencing a global coordinate system. The stresses are more useful when they're referencing a wall-adjusted coordinate system (ie. normal to the wall and two directions parallel to a wall), where that coordinate system may continuously vary over a surface (both for the normal direction and the orientation of the wall-parallel directions). 

All that said, I'm mainly using pyvista as a method to get plain text file into a vtk form so I can view this in Paraview. Though I'll definitely need to check out the python widgets y'all have. They look quite nice.
