### ISSUE TITLE
GeoTiff as DEM

### ISSUE THREAD

**Issue by bistek** [pyvista/pyvista-support#205]
Hello, is it possible to import a digital elevation model that is recorded in a geotiff file? This will be a one-band floating point tiff with georeferencing information.

Thanks very much!

**Comment by banesullivan** [comment]
This thread has a good example: https://github.com/pyvista/pyvista-support/issues/14

You won't need to make a texture since you just have floating point values

**Comment by bistek** [comment]
Hello, sorry but I did not explain very well!

I am talking about importing a geotiff that contains the digital elevation data. I.e. the floating point values are meters above see level. Therefore, internally this geotiff will be converted to a vtk structured grid.

Thanks!!

**Comment by bistek** [comment]
Then you could also texture the grid with some image that sometimes could even come as a geotiff, but in this case you need to read it as image data. 

Thanks again!

**Comment by banesullivan** [comment]
I meant to share #17 earlier

Read any raster via:

```py
import pyvista as pv
import xarray as xr
import numpy as np

def read_raster(filename):
    """
    Helpful: http://xarray.pydata.org/en/stable/auto_gallery/plot_rasterio.html
    """
    # Read in the data
    data = xr.open_rasterio(filename)
    values = np.asarray(data)
    nans = values == data.nodatavals
    if np.any(nans):
        # values = np.ma.masked_where(nans, values)
        values[nans] = np.nan
    # Make a mesh
    xx, yy = np.meshgrid(data['x'], data['y'])
    zz = values.reshape(xx.shape) # will make z-comp the values in the file
    # zz = np.zeros_like(xx) # or this will make it flat
    mesh = pv.StructuredGrid(xx, yy, zz)
    mesh['data'] = values.ravel(order='F')
    return mesh

topo = read_raster('topography.tif')
```

**Comment by bistek** [comment]
Great! Exactly this. Thanks very much!

**Comment by Boorhin** [comment]
Hi,
Thanks @banesullivan  for this, it is still very useful. Since it is one of the only ref to inject a geotiff topo file in Pyvista, I would like to update it as Xarray has changed in the last 5 years. Here is the function I came with and it includes a coarsening factor as some DEMs are very large.

``` python
import numpy as np
import pyvista as pv
import xarray as xr

def read_raster(filename,subsampling):
    data = xr.open_dataarray(filename,engine="rasterio", decode_coords="all")
    # Downsampling
    dc=data.coarsen(x=subsampling,y=subsampling,boundary="trim").mean() 
    values = dc.values[0]
    # Make a mesh
    xx, yy = np.meshgrid(dc['x'], dc['y'])
    mesh = pv.StructuredGrid(xx, yy, values)
    return mesh

topo = read_raster('topography.tif',10)
pl = pv.Plotter()
pl.add_mesh(topo, opacity=0.5)
pl.show_grid()
widget = pl.add_north_arrow_widget()
pl.show()

```
Maybe it will be useful to someone. I removed the scalar data as it is only useful to color code the altitude and since scalars don't need to be flattened anymore in Pyvista, I would simply add the z of the points as scalars in the add_mesh command.
Best!
