### ISSUE TITLE
Sorting point_array data for plotting with matplotlib

### ISSUE THREAD

**Issue by Aquan1412** [pyvista/pyvista-support#208]
Hello,

I want to use pyvista for the post-processing of CFD results. Currenty I'm trying to extract slices of surface data in order to plot them with matplotlib. Overall, my pipeline seems to work: I import a *.vtu dataset, then I set a threshold on the boundary marker ID in order to only include data from solid walls, and finally i slice throgh the resulting mesh. However, when I try to plot the data with matplotlib I get strange results:

Pressure distriubution extracted with pyvista:
![pressureDistribution_pyvista](https://user-images.githubusercontent.com/19516499/87549162-c1209000-c6ad-11ea-9a8e-3aeb874a1978.png)

If I use the same approach to extract the slice with paraview and  then use the vtk.numpy_interface.dataset_adapter to convert the data to numpy arrays, I get the following result (which is actually what I expect):
![pressureDistribution_paraview](https://user-images.githubusercontent.com/19516499/87549170-c5e54400-c6ad-11ea-8dfb-10560d568114.png)

It seems that the arrays obtained from pyvista are for some reason sorted differently than than those obtained from paraview, even though both should use the same underliying vtk routines, right?

Here's a simple example of the code I'm currently using:
```
import numpy as np
import pyvista as pv
import matplotlib.pyplot as plt

filename = "testData.vtu"

data = pv.read(filename)

# create a new array to filter the dataset based on boundary marker ID
data.cell_arrays["myFilter"] = np.zeros(len(data.cell_arrays["CADGroupID"]))
for i, value in enumerate(data.cell_arrays["CADGroupID"]):
    if value == 1:
        data.cell_arrays["myFilter"][i] = 0
    else:
        data.cell_arrays["myFilter"][i] = 1

threshold = data.threshold(value=0.5, scalars="myFilter")

cut = threshold.slice(origin=(0, 0.05, 0), normal=(0, 1, 0))

fig = plt.figure(figsize=(8,6))
sp = fig.add_subplot(111)
sp.plot(cut.points[:,0], cut["pressure"])
sp.invert_yaxis()
sp.grid(ls="--")
sp.set_xlabel("x [m]")
sp.set_ylabel("pressure [-]")
fig.savefig("pressureDistribution_pyvista.png", dpi=300)
```

Is  there a way to reproduce the paraview behaviour with pyvista?

And this is the dataset I used to create the plots above:
[testData.vtu.gz](https://github.com/pyvista/pyvista-support/files/4925486/testData.vtu.gz)

**Comment by banesullivan** [comment]
> It seems that the arrays obtained from pyvista are for some reason sorted differently than than those obtained from paraview, even though both should use the same underliying vtk routines, right?

There are a few different slicing filters and we may be using a different one that you are leveraging in ParaView. Also, the options of the filter (e.g. to produce intersection polygons or not) can affect the output like this.

I'd have to dive into your ParaView state file to see why exactly the results are different.

In the meantime, you'll just have to sort the data by X like so:

```py
def get_sorted(ax, data):
    ids = np.argsort(ax)
    return ax[ids], data[ids]

a, b = get_sorted(cut.points[:,0], cut["pressure"])

fig = plt.figure(figsize=(8,6))
sp = fig.add_subplot(111)
sp.plot(a, b, '.')
sp.invert_yaxis()
sp.grid(ls="--")
sp.set_xlabel("x [m]")
sp.set_ylabel("pressure [-]")
fig.savefig("pressureDistribution_pyvista.png", dpi=300)
```

![pressureDistribution_pyvista](https://user-images.githubusercontent.com/22067021/87553838-6709d580-c681-11ea-8cb6-6a8be3916b29.png)

**Comment by banesullivan** [comment]
Initially, I had thought the recently introduced `strip` filter would fix this but I wasn't able to get it working for these data.

See #169 and https://github.com/pyvista/pyvista/pull/807

**Comment by banesullivan** [comment]
The other option is that we could implement a helper routine to sort the lines of a mesh:

```py
lines = cut.lines.reshape((-1,3))
lines # sort this so the lines are in order from some origin point
```

**Comment by Aquan1412** [comment]
Thanks for the quick reply. However, this isn't exactly what I'm after. I would really like to be able to plot the data as a continous line (I'm using the extracted data as input for a number of plotting scripts where I compare data from different sources, and it would be a lot of work to adapt all the scripts). And actually, if I plot it as individual points it also works with the original dataset, no sorting required.

The other option, the helper routine, sounds interesting and might be the solution I'm looking for.

Looking at my paraview code I also noticed, that I'm not doing exactly the same: in pyvista is use "slice", in paraview I use "PlotOnIntersectionCurves". Is there a comparable filter available in pyvista?

**Comment by banesullivan** [comment]
The closest equivalent we have is by stripping the closed-loop you have to a single polyline, then use that node order of the polyline to do the plotting. This is what I was trying to do earlier... not sure where my head was at

Note that I use the new `strip` filter. I don't think this has made it to a release yet so you may need to run off PyVista `master`. See #169 and https://github.com/pyvista/pyvista/pull/807
```py
# Use the newly created strip filter (see above comment for links)
cut = threshold.slice(origin=(0, 0.05, 0), normal=(0, 1, 0), ).strip(join=True)

# Because this is a closed-loop, we can do this - gets the order of the nodes around the loop
ids = cut.lines[1:-1]

# Do your plotting but use the `ids` to access the data in the right order
...
sp.plot(cut.points[:,0][ids], cut["pressure"][ids])
...
```
![download](https://user-images.githubusercontent.com/22067021/87623290-159a2e80-c6f3-11ea-8ab4-0a1ea7dcde69.png)

**Comment by Aquan1412** [comment]
Thanks a lot, that's exactly what I was looking for! I also tested it on a number of other samples, and it works without problems.
