### ISSUE TITLE
[MNT] What tags should be available?

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista-support#21]
We should add some more tags to make finding issues easier. What else should be included?

Perhaps a tag for each mesh type so that what if you are looking for examples specific to `PolyData` you go go to the `PolyData` tag (etc. for other mesh types)

Anything else?

**Comment by banesullivan** [comment]
I also added a new tag for called `meshfix` for PyMeshFix related questions. Perhaps we should do this for TetGen, PyACVD, omfvista, etc too?

**Comment by GuillaumeFavelier** [comment]
Maybe a tag for the `API` related questions? Like how things work or the architecture in general and probably a tag for the `documentation` too.
