### ISSUE TITLE
Offset arrays no longer supported in VTK 9 when generating an UnstructuredGrid

### ISSUE THREAD

**Issue by fbeaudo** [pyvista/pyvista-support#210]
## Description

I currently need to produce an UnstructuredGrid based on data contained in numpy arrays. Because of compatibility issues experienced by some users, I recently upgraded to VTK 9 (and pyvista 0.25.3). After the upgrade, I started  getting the following warning when running the code on my laptop:

> /home/fbeaudoi/.cache/pypoetry/virtualenvs/device-ksA0Gg98-py3.7/lib/python3.7/site-packages/pyvista/core/pointset.py:610: UserWarning: VTK 9 no longer accepts an offset array
  warnings.warn('VTK 9 no longer accepts an offset array')

On my computer, the code still works fine. However, running the same code, a colleague of mine gets the same warning, followed by 

> Fatal Python error: Segmentation fault

So it seems like we have to find a way to build the UnstructuredGrid without an offset array. However, it is not clear to me how to do so, since I do not see how VTK will be able to identify the start of each cell in the cells array without the offset array. The code I wrote is directly based on the following tutorial from the Pyvista web page (which I checked produces the same error):

[https://docs.pyvista.org/examples/00-load/create-unstructured-surface.html](url)

It would be very nice to know how to build an UnstructuredGrid without the offset array; ideally, how could this be done in the tutorial above ?

**Comment by akaszynski** [comment]
Hi @fbeaudo,

Building unstructured grids can be a bit tricky and you're correct that the current documentation is lacking.  I'll do the best I can to update it this evening.

**Comment by fbeaudo** [comment]
@akaszynski Thanks a lot for your reply. Regarding the documentation update: this would be hugely appreciated !

**Comment by akaszynski** [comment]
A little late on this.  Please let me know if this is additional example documentation is sufficient or if you'd like a better/different example.

```python
###############################################################################
# UnstructuredGrid with Shared Points
# -----------------------------------
#
# The next example again creates an unstructured grid containing
# hexahedral cells, but using common points beween the cells.

# these points will all be shared between the cells
points = np.array([[0. , 0. , 0. ],
                   [1. , 0. , 0. ],
                   [0.5, 0. , 0. ],
                   [1. , 1. , 0. ],
                   [1. , 0.5, 0. ],
                   [0. , 1. , 0. ],
                   [0.5, 1. , 0. ],
                   [0. , 0.5, 0. ],
                   [0.5, 0.5, 0. ],
                   [1. , 0. , 0.5],
                   [1. , 0. , 1. ],
                   [0. , 0. , 0.5],
                   [0. , 0. , 1. ],
                   [0.5, 0. , 0.5],
                   [0.5, 0. , 1. ],
                   [1. , 1. , 0.5],
                   [1. , 1. , 1. ],
                   [1. , 0.5, 0.5],
                   [1. , 0.5, 1. ],
                   [0. , 1. , 0.5],
                   [0. , 1. , 1. ],
                   [0.5, 1. , 0.5],
                   [0.5, 1. , 1. ],
                   [0. , 0.5, 0.5],
                   [0. , 0.5, 1. ],
                   [0.5, 0.5, 0.5],
                   [0.5, 0.5, 1. ]])


# Each cell in the cell array needs to include the size of the cell
# and the points belonging to the cell.  In this example, there are 8
# hexahedral cells that have common points between them.
cells = np.array([[ 8,  0,  2,  8,  7, 11, 13, 25, 23],
                  [ 8,  2,  1,  4,  8, 13,  9, 17, 25],
                  [ 8,  7,  8,  6,  5, 23, 25, 21, 19],
                  [ 8,  8,  4,  3,  6, 25, 17, 15, 21],
                  [ 8, 11, 13, 25, 23, 12, 14, 26, 24],
                  [ 8, 13,  9, 17, 25, 14, 10, 18, 26],
                  [ 8, 23, 25, 21, 19, 24, 26, 22, 20],
                  [ 8, 25, 17, 15, 21, 26, 18, 16, 22]]).ravel()

# each cell is a VTK_HEXAHEDRON
celltypes = np.empty(8, dtype=np.uint8)
celltypes[:] = vtk.VTK_HEXAHEDRON

# the offset array points to the start of each cell (via flat indexing)
offset = np.array([ 0, 9, 18, 27, 36, 45, 54, 63])

# Effectively, when visualizing a VTK unstructured grid, it will
# sequentially access the cell array by first looking at each index of
# cell array (based on the offset array), and then read the number of
# points based on the first value of the cell.  In this case, the
# VTK_HEXAHEDRON is described by 8 points.

# for example, the 5th cell would be accessed by vtk with:
start_of_cell = offset[4]
n_points_in_cell = cells[start_of_cell]
indices_in_cell = cells[start_of_cell + 1: start_of_cell + n_points_in_cell + 1]
print(indices_in_cell)


###############################################################################
# Finally, create the unstructured grid and plot it

# if you are using VTK 9.0 or newer, you do not need to input the offset array:
# grid = pv.UnstructuredGrid(cells, celltypes, points)

# if you are not using VTK 9.0 or newer, you must use the offset array
grid = pv.UnstructuredGrid(offset, cells, celltypes, points)

# plot the grid
grid.plot(show_edges=True)
```

**Comment by fbeaudo** [comment]
@akaszynski Thanks a lot for this detailed tutorial and sorry for the late reply. It does fix my problem. It seems like the solution was just to ignore offset arrays altogether.
Though this absolutely works, I am a bit surprised it is so simple, as I would have thought the offset is used to detect the beginning of the description of each cell in the cells array. But thinking about it now, it appears to me that VTK can guess the beginning of each cell based on the cell_type array, since the type of a cell uniquely defines its number of nodes. Do you think this is how VTK version 9 or higher does it ?
Otherwise thanks again for the great example.

**Comment by akaszynski** [comment]
> But thinking about it now, it appears to me that VTK can guess the beginning of each cell based on the cell_type array, since the type of a cell uniquely defines its number of nodes. Do you think this is how VTK version 9 or higher does it ?

Actually, I think it just uses the data encoded within `cells` to internally create its own `offset` array, but I can't be 100% sure as I didn't look at their source.

**Comment by fbeaudo** [comment]
@akaszynski OK, thanks !
