### ISSUE TITLE
How do I change the plane/angle elevation() works in

### ISSUE THREAD

**Issue by montymagic9** [pyvista/pyvista-support#214]
I am trying to generate a coloured height map (image file) of a small object which was reconstructed in Meshroom. The output of Meshroom gives me a very rough point cloud and .obj file.

I tried simply plotting data.elevation() from the point cloud file, but in this case is it colouring it from low to high **diagonally** (maybe because it's angling where to colour it based on the lowest and highest points which happen to be on opposite ends). Is there a way to colour it from a fixed plane preferably through the origin, upwards rather than diagonally.

I drew an example to illustrate my issue. I want it to be colouring from low to high following the blue arrow, but it is currently colouring it in the direction of the red arrow.
![pyvista_issue1](https://user-images.githubusercontent.com/5530323/88710093-07dea300-d10e-11ea-8b5a-14982ddc284c.PNG)

I essentially want to be achieving this #101 but when I tried this code with my .obj file and using delaunay to generate a mesh the output was too simplistic/scaled down and not very clean, perhaps because my obj file has a lot of disconnected parts etc.

I am open to suggestions of a different approach.

**Comment by banesullivan** [comment]
The elevation filter is actually adding scalars along the blue vector in your diagram (assuming your sketch is drawn in cartesian coordinates and that blue arrow is pointing in the +Z direction). 

Please see the documentation for the `elevation` filter [here](https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.elevation). The `low_point` and `high_point` arguments are what specifies the vector on which the points are projected for mapping the scalar elevation values. By default (outlined in the docs for this filter), the low point is the bottom center of mesh bounds and the high point is the top center of the bounding box. Thus, the default behavior is what you describe with the blue arrow in your diagram.

If however, you want to define any arbitrary vector (normal from a plane) then you'd just appropriately set the `high_point` and `low_point`.

Hope this helps!


> but when I tried this code with my .obj file and using delaunay to generate a mesh the output was too simplistic/scaled down and not very clean, perhaps because my obj file has a lot of disconnected parts etc.

There's not much we can do/say without having the mesh file you are using.

**Comment by montymagic9** [comment]
This was very useful in understanding the elevation filter. Thank you.
