### ISSUE TITLE
How can I add coloring and contours to Pyvista.StructuredGrid created from np.meshgrid ?

### ISSUE THREAD

**Issue by trhoye** [pyvista/pyvista-support#217]
[IRAP_ASCII_EXAMPLE_sea_floor.txt](https://github.com/pyvista/pyvista-support/files/5020979/IRAP_ASCII_EXAMPLE_sea_floor.txt)

## Description
Hi 
I have created a StructuredGrid based on reading a surface (Format: __Irap__ imported with __xtgeo__).
__Irap__ is a common surface file format used in the  oil industry available in RMS, Petrel, etc.
The imported surface is transformed to a numpy.meshgrid (code line 34)

Re. z-values: z-value matrix had to be twisted into a correct a numpy array, including missing value handling (see codelines 36..39). 

Failed however to get  the map __depth-coloured__ (see code line 51).
Failed also to add __contours__ (see code line 47).

What is needed to get added depth-colours and contour lines to the plot?.
(see example data attached .. a seafloor map - depth have positive values .. made negative in code line 39).
#### python code:

1    > import pyvista as pv
2    > import xtgeo.surface as xt #used to read __irap__-format used in RMS
3    > import numpy as np
4    > import matplotlib as mpl
5    > import matplotlib.pyplot as plt
6    > 
7    > fname = 'my_irap_ascii_surfa_file'
8    > path  = 'C:/Users/.....path to file.../'
9    > inputfile=path+fname
10  > 
11  > surf1=xt.RegularSurface(inputfile,fformat='irap_ascii') # loaded ok
12  > print(surf1.ncol, surf1.nrow, surf1.xori, surf1.yori, surf1.xinc, surf1.yinc)
13  >
14  > #outfname='modified_TopUtsira.gri'
15  > #surf1.to_file(path+outfname)
16  > 
17  > #print(surf1)
18  > 
19  > nx=surf1.ncol 
20  > dx=surf1.xinc
21  > x0=surf1.xori # xmin
22  > xn=x0+(nx*dx) #xmax
23  > #print('X: ',x0,xn,dx)
24  > 
25  > ny=surf1.nrow 
26  > dy=surf1.yinc
27  > y0=surf1.yori #ymin 
28  > yn=y0+ny*dy #ymax
29  > #print('Y: ',y0,yn,dy)
30  > 
31  > #creating numpy arrays for x,y mesh construction
32  > x = np.arange(x0,xn,dx)
33  > y = np.arange(y0,yn,dy)
34  > x, y = np.meshgrid(x, y)
35  > 
36  > z = surf1.values.data #value marix needed a transform, to work, + a fix for missing data
37  > z[z==1.0e+33]=np.nan #missing data fix
38  > z = z.T
39  > z=z*-1
40  > 
41  > #print(np.nanmin(z),np.nanmax(z)) 
42  > zmin=np.nanmin(z)
43  > zmax=np.nanmax(z)
44  > 
45  > #constructing mesh
46  > mesh = pv.StructuredGrid(x,y,z)
47  > #contours = mesh.contour()  # => __AssertionError: Input dataset for the contour filter must have scal..
48  > print(mesh)
49  > 
50  > p = pv.Plotter(notebook=False, border=True) #ok 
51  > p.add_mesh(mesh,clim=[zmin,zmax], __cmap='gist_rainbow')__  #seems ok but plot do not use colors !
52  > p.add_axes()                      #ok
53  > p.add_bounding_box()      #ok
54  > p.show_grid()                     #ok 
55  > p.view_xy(negative=False) #ok
56  > p.show()                             #plot toogaphy in 3d without colors

**Comment by trhoye** [comment]
example data added

**Comment by banesullivan** [comment]
> #contours = mesh.contour() # => __AssertionError: Input dataset for the contour filter must have scal..

That's your problem! You do not have any scalars on your mesh. You need to add scalar data on your mesh to do any contouring or coloring. You could use the `.elevation()` filter or add the `z` values directly.

```py
mesh = pv.StructuredGrid(x,y,z).elevation()
contours = mesh.contour()

p = pv.Plotter(notebook=False, border=True)
p.add_mesh(contours, clim=[zmin,zmax], cmap='gist_rainbow')
p.add_axes()
p.add_bounding_box()
p.show_grid()
p.view_xy(negative=False)
p.show()
```

**Comment by banesullivan** [comment]
or

```py
mesh = pv.StructuredGrid(x,y,z)
mesh['my scalars'] = z.ravel(order='f')
...
```

**Comment by banesullivan** [comment]
See https://docs.pyvista.org/getting-started/what-is-a-mesh.html#what-are-attributes

**Comment by trhoye** [comment]
Muchos gracias, and Thanks a lot for pyVista.

**Comment by bistek** [comment]
Hello, two questions:

1) Is there a "sort of" elevation() filter to add also x and y values (and be able to use them in a color map)?

2) I have the suspect that elevation() might duplicate the z values, and that this could cause memory and/or performance problems for large objects. Is this correct? Or maybe the z values obtained from elevation() are just a reference to the original ones, so no duplication is done?

Thanks!

**Comment by banesullivan** [comment]
Please open a new issue for new questions.
