### ISSUE TITLE
How to display two scalar bars with a same name in two renders?

### ISSUE THREAD

**Issue by rodrigomologni** [pyvista/pyvista-support#220]
Hi Team!

I would like to add one scalar bar in each render using `add_mesh`. However, the scalar bar on the right render is shown only when the scalars of each render are different. I tried to overcome this condition by setting `show_scalar_bar=True`, but it didn't work. Shouldn't this have worked? 🤔

![image](https://user-images.githubusercontent.com/1608652/89438424-31578a00-d71f-11ea-83b8-6e4b45883f99.png)

```python
scalars = 'Net to Gross Ratio (Cell Count)'

self.plotter = QtInteractor(shape=(1, 2))
self.plotter.subplot(0, 0)
self.plotter.add_axes()
self.plotter.add_text('Petrel', 'upper_edge')

self.plotter.add_mesh(petrel, scalars=scalars, clim=(0, 1), show_edges=True, lighting=False)

camera = self.plotter.camera
self.plotter.subplot(0, 1)
self.plotter.add_axes()
self.plotter.add_text('Shift', 'upper_edge')

self.plotter.add_mesh(shift, scalars=scalars, clim=(0, 1), show_edges=True, lighting=False, show_scalar_bar=True)

self.plotter.camera = camera
```

Observation: both `petrel` and `shift` are unstructured grids and have a scalar array named 'Net to Gross Ratio (Cell Count)'.

**Comment by akaszynski** [comment]
The issue is with the way we treat scalar bars internally.  Normally, there's one scalar bar per plotter instead of one scalar bar per renderer, which may or may not be the way we'd like to implement this by default.  One workaround is to simply make a minor change to the scalar bar title:

```python
import pyvista as pv
from pyvista import examples
mesh = examples.download_cow()
mesh['my scalars'] = mesh.points[:, 2]
pl = pv.Plotter(notebook=0, shape=(1, 2), border=False)
pl.subplot(0, 0)
pl.add_mesh(mesh, show_edges=True)
pl.subplot(0, 1)
pl.add_mesh(mesh, show_edges=True, stitle='my scalars ')  # notice just an extra space here
pl.show()
```
![image](https://user-images.githubusercontent.com/11981631/89449867-ecc7f080-d716-11ea-83fa-c274bde98793.png)

**Comment by rodrigomologni** [comment]
Hi @akaszynski! Ohhhhh... Your solution worked! Thank you very much for answering me quickly. ✌️

![image](https://user-images.githubusercontent.com/1608652/89450406-df1f6480-d730-11ea-96ee-5ec05311eea4.png)
