### ISSUE TITLE
Operation on surfaces (UniformGrids) imported with SurferGridReader() 

### ISSUE THREAD

**Issue by trhoye** [pyvista/pyvista-support#222]
## Description
Thanks for the awesome PyVista and PVGeo. 🥇 

PS! I'm fairly new to python, struggeling a bit with all your data formats.

This is about __Uniform Grids__ as imported by __SurferGridReader()__ 
Could you give an example of how to add / subtract 2 such imported surfaces.

Import done by:
+    grd1 = SurferGridReader().apply(fname1)
+    top = grd1.warp_by_scalar(scale_factor=1)

+   grd2 = SurferGridReader().apply(fname1)
+   thickness = grd2.warp_by_scalar(scale_factor=1)_

I want to subtract __thickness__ from the __top__.  __(new_top=top-thickness)__ ,
and learn how to do different other user designed math operations on such grids.

One possibility could be by converting to numpy arrays...
(something like: nx=grd1.dimensions[0],  xmin = grd1.x[0], xmax = grd.x[len(grd.x)-1] ...e.t.c)

I believe you have a smarter way?
An example would be nice .. including storing result as a Surfer grid.

**Comment by trhoye** [comment]
I think I found a solution:
(used more lines than needed to make it more readable)

#grid sub-traction function:
def sub_grids(grid1,grid2):
    pname1 = grid1.array_names[0] #the array name was 'Data'
    p1=grid1.get_array(pname1)
    pname2 = grid2.array_names[0] #also 'Data'
    p2=grid2.get_array(pname2)
    #...Grid-Grid operation
    p3 = p1-p2
    #...
    grid=grid1
    grid[pname1]=p3
    return grid

**Comment by banesullivan** [comment]
Ah, nice work. Your function should work if the underlying mesh between the two are the same.

Could you perhaps provide sample data for this? Are `grid1` and `grid2` coming from separate files?

**Comment by trhoye** [comment]
grid1 and grid 2 are coming from separate files, but with the same structure.
I did read them with PVGeo (base on one of your examples:  
   uniform_grid1 = SurferGridReader().apply(fname1)         
   grid1 = uniform_grid1.warp_by_scalar(scale_factor=1)     # result here was defined as a structured grid
