### ISSUE TITLE
Convert Cloud data [x,y,z] to Face and Vertices

### ISSUE THREAD

**Issue by MOAMSA** [pyvista/pyvista-support#223]
Hello,
I need to convert point data to vertices and faces in order to import them to a software tool.
I there a pythonic way to do this? 
I used the below code:
```
cloud = pv.PolyData(arr_3d)
cloud.plot(point_size=1)
surf = cloud.delaunay_2d()
surf.plot(show_edges=True)

faces = surf.faces
verts = surf.verts
```
I tried the below code to regenerate the surface using verts and face
```
surf1 = pv.PolyData(verts, faces)
surf1.plot(scalars=np.arange(3), cpos=[-1, 1, 0.5])
```
 
I got the below error
`ValueError: Empty meshes cannot be plotted. Input mesh has zero points.`

**Comment by akaszynski** [comment]
Try using `points` instead of `verts`.  If that doesn't work, can you upload `arr_3d` here?

**Comment by MOAMSA** [comment]
Pointdata: 
[points.xlsx](https://github.com/pyvista/pyvista-support/files/5044500/points.xlsx)
Thanks,

**Comment by MOAMSA** [comment]
Thanks, It works!
