### ISSUE TITLE
How can I remove a specific array from a grid?

### ISSUE THREAD

**Issue by rodrigomologni** [pyvista/pyvista-support#234]
Hi! I would like to remove a specific array from a grid. Is there a method for this? I found only methods to remove all arrays from point/cell/field data. 😕

**Comment by banesullivan** [comment]
Use the `del` operator on the array:

```py
del mesh.point_arrays['array name']
```

and likewise for `cell_arrays`

**Comment by rodrigomologni** [comment]
Thank you, @banesullivan! ✌️
