### ISSUE TITLE
Pyvista  - ? Turn on/off surface objects added in pyvista.Plotter interactively

### ISSUE THREAD

**Issue by trhoye** [pyvista/pyvista-support#235]
## Description
This question is maybe similar to: https://github.com/pyvista/pyvistaqt/issues/10

Assume 2 or more surfaces added in pyvista.Plotter(notebook=False).
Is it a possibility to interactively turn on/off added surfaces and other objects  interactively ?

simple example:
I would like to turn on off plots objects interactively, such as  
\- surface_1
\- surface_2
\- wells 
in the case:

> plotter = pyvista.Plotter(notebook=False)
> plotter.add_mesh(surface_1)
> plotter.add_mesh(surface_2)
> plotter.add_mesh(wells)
> ...
> plotter.add_legend(legend_entries)
> plotter.show() 

brgds 
Trond

**Comment by banesullivan** [comment]
You are probably looking for something similar to https://github.com/pyvista/pyvista-support/issues/182#issuecomment-645482993

Just keep track of the actors returned from `add_mesh` and then have your UI callback set `actor.SetVisibility(flag)` whether that UI is with a widget in the scene or in your custom application
