### ISSUE TITLE
Best way to create tube with thick edges (bored cylinder)

### ISSUE THREAD

**Issue by NSimpraga** [pyvista/pyvista-support#236]
Hi,

I need to 3D model a tube condenser, which I did, but I am having trouble creating tubes that will represent water inlet/outlets in the model. I can create a cylinder and turn off capping but the walls of the cylinder don't have thickness.

I thought of creating a smaller cylinder inside a bigger one and then clipping them but the clip_surface method is not working for me at all. 

```
import pyvista as pv

cyl1 = pv.Cylinder(direction=(0,0,1), radius=5, height=10)
cyl2 = pv.Cylinder(direction=(0,0,1), radius=3, height=10)

clipped = cyl1.clip_surface(cyl2)

plotter = pv.Plotter(notebook=False)
plotter.add_mesh(clipped, show_edges=False)
plotter.show_axes()
plotter.show()
```

When I run this I get such an output:
![image](https://user-images.githubusercontent.com/52497291/91282455-aa2f8c00-e789-11ea-9f09-e774f1b9ccaf.png)

Am I approaching the problem wrong, is there a better way to do this?

**Comment by NSimpraga** [comment]
I have found out about boolean functions so I am pretty sure that was what I was looking for!

**Comment by akaszynski** [comment]
Sorry we didn't get back to you sooner!

Turns out it's slightly more complicated as you have to flip the normals of one of the meshes to get it to cut correctly.  Here's what worked for me:

```py
import pyvista as pv

cyl1 = pv.Cylinder(direction=(0,0,1), radius=5, height=10).triangulate()
cyl2 = pv.Cylinder(direction=(0,0,1), radius=4.5, height=11).triangulate()
cyl2.flip_normals()  # this must happen

tube = cyl2.boolean_cut(cyl1)

cpos = [(-10.5, -15.3, 27.8),
        (0.0, 0.0, 0.0),
        (0.14, 0.84, 0.51)]


pl = pv.Plotter()
pl.add_mesh(tube, 'grey')
pl.camera_position = cpos
pl.background_color = 'w'
pl.show()
```

![image](https://user-images.githubusercontent.com/11981631/91918716-f21a4b80-ec80-11ea-9fd7-1f6bef68dcf1.png)

**Comment by banesullivan** [comment]
There's also the `CylinderStructured` helper to do similar things. See https://docs.pyvista.org/utilities/geometric.html?highlight=cylinderstructured#pyvista.CylinderStructured

**Comment by NSimpraga** [comment]
@akaszynski Thanks for the input!
@banesullivan  This is.... so easy, I can't believe I was drilling holes using boolean all along while there was something as easy as this. Thanks again!

Another question vaguely related to this.. So I need to dynamically create a rather large amount of pipes. Those pipes need to go through a disk so I wanted to drill holes in the disk for all these pipes. Turns out boolean_cut is rather heavy and takes a lot of time to calculate and visualize if there are for example ~50 pipes.

```
import pyvista as pv
import numpy as np

r=5
h=10
rp=r/16
d=r/8

y1 = np.arange(0, r, 2*rp+d)
z1 = np.arange(0, r, 2*rp+d)
y2 = np.arange(0, -r, -2*rp-d)
z2 = np.arange(0, -r, -2*rp-d)

y= np.concatenate((y1,y2))
z= np.concatenate((z1,z2))

disk = pv.Cylinder(radius=r*1.5, height=h/10).triangulate()

pipes = pv.PolyData()
for i in y:
    for j in z:
        pipes = pipes + pv.Cylinder(center=(0,i,j), radius=rp, height=h).triangulate()

pipes.flip_normals()
res = pipes.boolean_cut(disk)
plotter = pv.Plotter(notebook=False)
plotter.add_mesh(res)
plotter.show()
```

This gives me the following:
![image](https://user-images.githubusercontent.com/52497291/92217486-0ab07e80-ee98-11ea-9bca-f67354aafbd3.png)

But it took quite a while to compute, maybe a few minutes even. If I do more pipes (smaller pipe radius ->rp), after running it just doesn't do anything. 
Is this the best way to do something like this? Should it be so hardware intensive so it basically hangs and freezes when there are a lot of objects involved?

**Comment by akaszynski** [comment]
This works fairly well:

```python
import pyvista as pv
import numpy as np

r=5
h=10
rp=r/16
d=r/8

y1 = np.arange(0, r, 2*rp+d)
z1 = np.arange(0, r, 2*rp+d)
y2 = np.arange(0, -r, -2*rp-d)
z2 = np.arange(0, -r, -2*rp-d)

y= np.concatenate((y1,y2))
z= np.concatenate((z1,z2))

res = 64
res_pipe = 64
disk = pv.CylinderStructured(radius=r*1.5, height=h/10, theta_resolution=res,
                             z_resolution=2).extract_surface()
disk = disk.triangulate().delaunay_3d().extract_surface()


pipes = pv.PolyData()
centers = []
for i in y:
    for j in z:
        center = (0, i, j)
        if center not in centers:
            centers.append(center)

for center in centers:
    pipe = pv.CylinderStructured(center=center, radius=rp, height=h/9,
                                 theta_resolution=res_pipe, z_resolution=2).extract_surface()
    pipe = pipe.triangulate()
    pipe.flip_normals()
    pipes += pipe


cut_disk = disk.boolean_cut(pipes, tolerance=1E-8)
cut_disk.plot(color='w', notebook=False)
```

![image](https://user-images.githubusercontent.com/11981631/92256071-74c52580-ee90-11ea-9ef4-df598633dfa6.png)
