### ISSUE TITLE
Projection Under Mouse Cursor

### ISSUE THREAD

**Issue by dbodily1** [pyvista/pyvista-support#239]
Is there a simple way to project from the mouse position directly onto the mesh?  I'm picking cells on my mesh fine but wanted to get more accurate and actually project directly on the mesh.  The problem is especially exacerbated by low-res meshes.

**Comment by akaszynski** [comment]
Another idea is to implement a callback to give you real time feedback by picking the current cell below your mouse continuously.  Are you selecting several cells?

**Comment by dbodily1** [comment]
> Another idea is to implement a callback to give you real time feedback by picking the current cell below your mouse continuously. Are you selecting several cells?

I just need a single point under the mouse cursor, on the mesh.

**Comment by dbodily1** [comment]
def picked_point(picked_pt):
    direction = picked_pt-p.camera_position[0]
    direction = direction/np.linalg.norm(direction)
    start = picked_pt-1000*direction
    end = picked_pt+10000*direction
    intersection,ix = stl.ray_trace(start,end, first_point=True)
    if len(intersection) > 0:
        point = intersection
        color = get_colors(len(point))
        w = p.add_sphere_widget(callback=None, center=point,
                                   color=color, radius=3,
                                pass_widget=True)
    else:
        print("Point Not On STL!")


This seemed to fix my issue - though it's a bit of a hack - pyvista should implement this function

**Comment by dbodily1** [comment]
def picked_point(picked_pt):
    direction = picked_pt-p.camera_position[0]
    direction = direction/np.linalg.norm(direction)
    start = picked_pt-1000*direction
    end = picked_pt+10000*direction
    intersection,ix = stl.ray_trace(start,end, first_point=True)
    if len(intersection) > 0:
        point = intersection
        color = get_colors(len(point))
        w = p.add_sphere_widget(callback=None, center=point,
                                   color=color, radius=3,
                                pass_widget=True)
    else:
        print("Point Not On STL!")

This worked

**Comment by dbodily1** [comment]
p.pick_mouse_position() AFTER calling p.track_mouse_position()

**Comment by bo-wu** [comment]
@dbodily1  Thank you for sharing the idea and code.
I am very new to PyVista and also seldom use vtk, but would like use PyVista to implement that as you mentioned. 
How could I arrange the main framework to do that? I guess I should use some callback function? but don't know which one.
Would you please give me some guide or hint? Thank you in advance. 

What I have tried is as following:

```
    mesh = pv.read('./test.obj')
    p = pv.Plotter(notebook=False)
    p.add_mesh(mesh, show_edges=False, color='w')
    p.track_mouse_position()
    pt = p.pick_mouse_position()
    picked_point(pt)
```

**Comment by bo-wu** [comment]
@dbodily1 @akaszynski Thank you for sharing the idea and code.
I am very new to PyVista and also seldom use vtk, but would like use PyVista to implement that as you mentioned.
How could I arrange the main framework to do that? I guess I should use some callback function? but don't know which one.
Would you please give me some guide or hint? Thank you in advance.

What I have tried is as following:

```
    mesh = pv.read('./test.obj')
    p = pv.Plotter(notebook=False)
    p.add_mesh(mesh, show_edges=False, color='w')
    p.track_mouse_position()
    pt = p.pick_mouse_position()
    picked_point(pt)
    p.show()
```

**Comment by bo-wu** [comment]
@dbodily1 @akaszynski Thank you for sharing the idea and code.
I am very new to PyVista and also seldom use vtk, but would like use PyVista to implement that as you mentioned.
How could I arrange the main framework to do that? I guess I should use some callback function? but don't know which one.
Would you please give me some guide or hint? Thank you in advance.

What I have tried is as follows:

```
    mesh = pv.read('./test.obj')
    p = pv.Plotter(notebook=False)
    p.add_mesh(mesh, show_edges=False, color='w')
    p.track_mouse_position()
    pt = p.pick_mouse_position()
    picked_point(pt)
    p.show()
```

but I the following error: 
EBA2B740]vtkOpenGLRenderWindow.c:93    WARN| Error invoking helper with no framebuffer
Fatal Python error: Segmentation fault

Current thread 0x00007f09eba2b740 (most recent call first):
  File "/home/.local/lib/python3.8/site-packages/pyvista/plotting/picking.py", line 556 in pick_mouse_position

**Comment by banesullivan** [comment]
@bo-wu, te segfault is happening because you are trying to perform a pick on a scene that hasn't been rendered. We should have a catch for that and raise an error in PyVista.

-----

For completeness, here is a demo of doing this:

```py
import pyvista as pv
from pyvista import examples
import numpy as np


class Picker:
    def __init__(self, plotter, mesh):
        self.plotter = plotter
        self.mesh = mesh
        self._points = []
        
    @property
    def points(self):
        """To access all th points when done."""
        return self._points
        
    def __call__(self, *args):
        picked_pt = np.array(self.plotter.pick_mouse_position())
        direction = picked_pt - self.plotter.camera_position[0]
        direction = direction / np.linalg.norm(direction)
        start = picked_pt - 1000 * direction
        end = picked_pt + 10000 * direction
        point, ix = self.mesh.ray_trace(start, end, first_point=True)
        if len(point) > 0:
            self._points.append(point)
            w = p.add_mesh(pv.Sphere(radius=3, center=point),
                           color='red')
        return


mesh = examples.load_airplane()
    
p = pv.Plotter(notebook=False)
p.add_mesh(mesh, show_edges=True, color='w')

picker = Picker(p, mesh)
p.track_click_position(picker, side='right')
p.add_text('Use right mouse click to pick points')

p.show()
```

![2020-11-10 23 39 22](https://user-images.githubusercontent.com/22067021/98777508-219ab200-23ae-11eb-91d8-3fc3a9434cc7.gif)

**Comment by banesullivan** [comment]
There is also a way of doing this with visible cell picking if you have multiple meshes in the scene but it is less stable

**Comment by bo-wu** [comment]
@banesullivan 
Thanks a lot for your reply. That's an excellent example!
