### ISSUE TITLE
extract the nodes (vertices ) of a mesh  mapping the bounding box of add_mesh_slice

### ISSUE THREAD

**Issue by ghazalbangash** [pyvista/pyvista-support#241]
my main goal is to to be able to deform a mesh around a curve/bounding box/slice etc
I have been able to slice my mesh using add_mesh_slice() method which gives me the bounds of the box around that slice 
![Untitled](https://user-images.githubusercontent.com/47847589/92372854-c67ce280-f112-11ea-98b8-1accab1e2731.png)

this is giving me the bounds of the red box around my mesh,i want all the nodes and if possible the cells mapping this red box or the nodes near this box

any ideas how i can implement this?

**Comment by akaszynski** [comment]
Glad to see `pyvista` being used for this!

I'll need a minimum working example to be able to help you out on this one.

**Comment by ghazalbangash** [comment]
@akaszynski Thank you soo much for your reply 
basically i want something like this 

![doc_2020-09-09_08-52-25](https://user-images.githubusercontent.com/47847589/92554294-36f24380-f27a-11ea-8150-fd0a5e8baa35.GIF)
the main logic behind this is that you are able to slice/cut the mesh with a plane at every orientation ,find the nodes intersecting the two meshes and then deform the shape accordingly (something like a bounding box)
Now i want to be a able to get the nodes intersecting the my mesh using the plane from add_mesh_slice method which has my desired UI

**Comment by akaszynski** [comment]
This looks a bit like sculptor mesh morphing: http://gosculptor.com/

I imagine that you already have a RBF based interpolation method and want to apply it to a `pyvista` mesh.  If you do, it's still going to be non-trivial to setup a GUI based approach (pyside or pyqt) for grabbing the points at an intersection plane and then moving them with a pyvista enabled callback.

I'd say that if you want to implement this, look up plane slices operations within the [pyvista docs](docs.pyvista.com) and try to implement that without a UI.  Once you have the basics working, consider the UI only as a last resort.  Creating the UI will, ironically, take most of your time since programming callbacks tend to be a pain.

**Comment by ghazalbangash** [comment]
> This looks a bit like sculptor mesh morphing: http://gosculptor.com/
> 
> I imagine that you already have a RBF based interpolation method and want to apply it to a `pyvista` mesh. If you do, it's still going to be non-trivial to setup a GUI based approach (pyside or pyqt) for grabbing the points at an intersection plane and then moving them with a pyvista enabled callback.
> 
> I'd say that if you want to implement this, look up plane slices operations within the [pyvista docs](docs.pyvista.com) and try to implement that without a UI. Once you have the basics working, consider the UI only as a last resort. Creating the UI will, ironically, take most of your time since programming callbacks tend to be a pain.

thats exaclty what i have been doing and trying to implement but the major issue i am stuck with is that i cant seem to obtain the mesh points near the intersecting plane 
thank you for the advice

**Comment by ghazalbangash** [comment]
@akaszynski  is there anyway to get the points on that plane_slice_meshes curve?

**Comment by akaszynski** [comment]
Please let me see what you have so far.  It's much easier to explain with example code.

**Comment by ghazalbangash** [comment]
> Please let me see what you have so far. It's much easier to explain with example code.

i got them after changing them into a polyline thanks a lot

**Comment by banesullivan** [comment]
@ghazalbangash, it would be great if you would share the solution to your problem for other people that encounter a similar challenge.
