### ISSUE TITLE
How to apply textures to the mesh (not visualizing it)

### ISSUE THREAD

**Issue by josepereiroml** [pyvista/pyvista-support#242]
## Description

Hey I've been trying to add the texture to the mesh without using the Plotter function, I want to actually add the texture to the mesh and use it in different libraries for example, do you know how I can do this? To add the texture to the mesh and save the object as a .obj file. Thank you very much.

**Comment by akaszynski** [comment]
Hello,

Could you please post what you've tried so far so I can take a look at it?

**Comment by banesullivan** [comment]
We do not really support this. The mesh and the texture are separate entities and you can only ever apply a texture to a mesh during rendering (this goes for all 3D software). There is no correspondence between the texture pixels and the nodes/cells of a mesh.

However, we do have a helper method for computing texture coordinates on a mesh. See [`texture_map_to_plane`](https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.texture_map_to_plane)

To create an OBJ file, you're basically just saving the mesh's vertices and triangles to a file (which you already have), then saving the texture coordinates for those vertices in that same file (which hopefully you have or you know how to properly compute those), then you'll save the texture as a separate image file next to the OBJ mesh file. I'd recommend following the format details on Wikipedia: https://en.wikipedia.org/wiki/Wavefront_.obj_file#File_format

We do provide a sort-of working way to do this with the Plotter's `export_obj` method:

```py
p = pv.Plotter()
p.add_mesh(mesh)
p.export_obj("foo")
p.close()
```

but you'll have to save the texture yourself and make sure to bring that to whatever other software you are using

**Comment by josepereiroml** [comment]
Thank you Bane I could export the object and it's working perfectly.

**Comment by shakasaki** [comment]
hi @josepereiroml, could you please provide an example of how you did this? Specifically, how you save the texture as an object based on Bane's suggestion above?
I have the texture and mesh handy and can visualize both well in pv.Plotter.. but I do not manage to export the texture! Thanks for the input!
