### ISSUE TITLE
How to plot colorful point cloud

### ISSUE THREAD

**Issue by EthanZhangYi** [pyvista/pyvista-support#245]
I want to plot a point cloud with colors for each points, and save it as an image from a specific view. Like the image below.
How to do it? Can anyone give some help?
![Selection_001](https://user-images.githubusercontent.com/13479831/91930118-9b5d5200-ed12-11ea-8529-04c4db2685da.png)

**Comment by guochengqian** [comment]
hi pyvista team, 
Thank you all for the efforts in open sourcing this library. 
I would like to ask: How to assign different colors to each point in `add_points`? 

I have an array of `points` with size [N, 3] (N coordinates in 3D domain), and another array of `colors` with size [N, 3] (RGB colors of N points)

How to assign `colors` to `points` in the `add_points` funciton?

**Comment by akaszynski** [comment]
You can add different color maps using `cmap`. Is that what you're looking for?

**Comment by guochengqian** [comment]
@akaszynski 
Thank you very much! I updated my question to make it clear. 

I have found the solution. I think the official document should consider providing such an example (assign a list of RGB colors to each point) since it is commonly used.

```
plotter = pv.Plotter()
plotter.add_points(points, opacity=opacity, point_size=point_size, render_points_as_spheres=True, scalars=colors, rgb=True)
plotter.show()

```

**Comment by Luis-PP** [comment]
> @akaszynski Thank you very much! I updated my question to make it clear.
> 
> I have found the solution. I think the official document should consider providing such an example (assign a list of RGB colors to each point) since it is commonly used.
> 
> ```
> plotter = pv.Plotter()
> plotter.add_points(points, opacity=opacity, point_size=point_size, render_points_as_spheres=True, scalars=colors, rgb=True)
> plotter.show()
> ```

@[guochengqian](https://github.com/guochengqian) How do you define "colors"?
