### ISSUE TITLE
Representing wells (boreholes) as tubes using top/bottom (or from/to)

### ISSUE THREAD

**Issue by jacobgrasmick** [pyvista/pyvista-support#25]
I would like to represent boreholes as 'tubes' using top/bottom elevation of the samples. See example file. 

Basically, the tube would connect Easting,Northing,Elevation.top to Easting,Northing,Elevation.bot and the color would be based on the 'Geol' field. 

Also, could you please provide an example of how you would represent the 'Geol' field as categories? Similar to the functionality in ParaView. Would also appreciate an example of manually defining the color for each category, and the color legend displaying the 'Geol' string (rather than integers). 

[example well.xlsx](https://github.com/pyvista/pyvista-support/files/3388125/example.well.xlsx)

**Comment by banesullivan** [comment]
Hey @jacobgrasmick - sorry for the delay on this! I went on a camping trip and have been offline. I will post a solution to this tomorrow

**Comment by banesullivan** [comment]
There are a number of ways to do this, but here's one that makes sense for this dataset:

```py
import pandas as pd
import pyvista as pv
import numpy as np

sheet = pd.read_excel('example.well.xlsx')
print(sheet.keys())
sheet.head()
```

```py
# Spatial reference
xy = np.c_[sheet['Easting'].values, sheet['Northing'].values]
zt = sheet['Elevation.top'].values
zb = sheet['Elevation.bot'].values
# Attributes
geol = sheet['Geol'].values
hole_id = sheet['HOLE_ID'].values

# Map string geology categories to a numerical value
soils, smapping = np.unique(geol, return_inverse=True)
```

```py
# Treat every section as it's own entitiy
lines = pv.MultiBlock()
for i, coord in enumerate(xy):
    a = np.hstack([coord, zt[i]])
    b = np.hstack([coord, zb[i]])
    line = pv.Line(a, b,)
    line.clear_arrays()
    line['Geol'] = np.asarray([smapping[i],])
    line['HOLE_ID'] = np.asarray([hole_id[i],])
    lines.append(line)

# Now merge/combine all the lines, clean the dataset, and split into connected wells    
wells = lines.combine().extract_geometry().clean().split_bodies()
```

```py
# Then apply a tube filter to each well
tubes = pv.MultiBlock()
for well in wells:
    tubes.append(well.extract_geometry().tube())
tubes.plot(n_colors=7)
```

![download](https://user-images.githubusercontent.com/22067021/61482119-1c168e80-a957-11e9-9c00-57ca50f0935a.png)

```py
for i, typ in enumerate(soils):
    print('{} -> {}'.format(i, typ))
```

which prints:
```
0 -> E
1 -> F1
2 -> F2
3 -> FILL
4 -> M
5 -> O(B)
6 -> O(C)
7 -> O(D)
```


Note that we have yet to implement the ability to label scalar bars (reference https://github.com/pyvista/pyvista/issues/298)

**Comment by jacobgrasmick** [comment]
Thanks @banesullivan ! This is perfect. 

I wonder if a similar approach as this could allow for custom labels:
https://matplotlib.org/3.1.1/gallery/ticks_and_spines/colorbar_tick_labelling_demo.html

**Comment by banesullivan** [comment]
> I wonder if a similar approach as this could allow for custom labels:
> https://matplotlib.org/3.1.1/gallery/ticks_and_spines/colorbar_tick_labelling_demo.html

Something like that would be exactly like what I hope to implement

**Comment by banesullivan** [comment]
FYI - the latest version of PyVista now supports categorical string arrays with the scalar bar!

Here's an updated version of this script:

```py
import pandas as pd
import pyvista as pv
import numpy as np

sheet = pd.read_excel('example.well.xlsx')

# Spatial reference
xy = np.c_[sheet['Easting'].values, sheet['Northing'].values]
zt = sheet['Elevation.top'].values
zb = sheet['Elevation.bot'].values
# Attributes
geol = sheet['Geol'].values
hole_id = sheet['HOLE_ID'].values


# Treat every section as it's own entitiy
lines = pv.MultiBlock()
for i, coord in enumerate(xy):
    a = np.hstack([coord, zt[i]])
    b = np.hstack([coord, zb[i]])
    line = pv.Line(a, b,)
    line.clear_arrays()
    line['Geol'] = np.asarray([geol[i],])
    line['HOLE_ID'] = np.asarray([hole_id[i],])
    lines.append(line)

# Now merge/combine all the lines, clean the dataset, and split into connected wells    
wells = lines.combine().extract_geometry().clean().split_bodies()

# Then apply a tube filter to each well
tubes = pv.MultiBlock()
for well in wells:
    tubes.append(well.extract_geometry().tube())
tubes.plot(scalars='Geol')
```

![download](https://user-images.githubusercontent.com/22067021/62655689-c282fd80-b91f-11e9-94a7-63f2cf18fb79.png)

**Comment by jc-barreto** [comment]
Hello @banesullivan  This example is quite similar to what I would like to do, I have try to run this example (with the same excel -example.well.xlsx file and code from here), and the lithology is  not showing up:
![image](https://user-images.githubusercontent.com/42352209/155358494-0944cf12-51de-4278-b4da-35a434b5c39d.png)
I couldn't figure out where is the part of the colorbar in the code, I'm not familiar with PyVista

**Comment by banesullivan** [comment]
Huh. Some things have changed in Pandas and PyVista since this was posted. There currently appears to be a regression in PyVista, which I have posted here: https://github.com/pyvista/pyvista/issues/2311

**Comment by jack-tuna** [comment]
Hey all, 

I just tried to run the above example on my own data and got a similar issue. When I look at the geology of any line segment it returns the associated lith code: 

```
import pandas as pd
import pyvista as pv
import numpy as np

sheet = pd.read_excel('../data/example.well.xlsx')

# Spatial reference
xy = np.c_[sheet['Easting'].values, sheet['Northing'].values]
zt = sheet['Elevation.top'].values
zb = sheet['Elevation.bot'].values
# Attributes
geol = sheet['Geol'].values
hole_id = sheet['HOLE_ID'].values


# Treat every section as it's own entitiy
lines = pv.MultiBlock()
for i, coord in enumerate(xy):
    a = np.hstack([coord, zt[i]])
    b = np.hstack([coord, zb[i]])
    line = pv.Line(a, b,)
    line.clear_arrays()
    line['Geol'] = np.asarray([geol[i],])
    line['HOLE_ID'] = np.asarray([hole_id[i],])
    lines.append(line)

lines[0]['Geol']
```

returns;
`array(['FILL'], dtype='<U4')`

However when I check the combined wells it appears the geology and holeid data does not transfer across:

```
# Now merge/combine all the lines, clean the dataset, and split into connected wells    
wells = lines.combine().extract_geometry().clean().split_bodies()
wells[0]['Geol']
```

returns:
`
array(['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      dtype='<U1')
`

Any idea what would be causing this? Thanks in advance!
