### ISSUE TITLE
Storing Polygon Meshes to VTK

### ISSUE THREAD

**Issue by captain-pool** [pyvista/pyvista-support#250]
Hey Guys,
I'm trying to save a Polygon Mesh to VTK using PyVista, but I couldn't find something that can help me with it.
In my case, I'm having a numpy array of `(N, 3)` points, and a **Jagged List** of connected vertices. For example,
the vertex set looks like:
```
array([[0, 0, 0],
       [1, 0, 1.5],
       [1, 0.4, 0.1],
       [0.8, 0.5, 0.12]
       [0.1, 0.2, 0.3]])
```
and the edge set looks something like:
```
[[0, 1, 2],
 [0, 2, 3, 1],
 [0, 2, 4],
 [2, 3, 4, 5]]
```
**NOTE:** These values are randomly chosen, not sure if they represent something useful or not. My point is, I have an ndarray object for vertices and a nested list for the faces.

Does anyone know anything that I can use to write to disk / visualize this kind of mesh?
Thanks!

**Comment by akaszynski** [comment]
Your points array is good, but you'll need to reformat your edge set (really faces array) to be:

```python
import numpy as np
import pyvista as pv

points = np.array([[0, 0, 0],
                   [1, 0, 1.5],
                   [1, 0.4, 0.1],
                   [0.8, 0.5, 0.12],
                   [0.1, 0.2, 0.3]])

faces = np.hstack(([[3, 0, 1, 2],
                    [4, 0, 2, 3, 1],
                    [3, 0, 2, 4],
                    [4, 2, 3, 4, 5]]))

mesh = pv.PolyData(points, faces)
mesh.plot()  # visualize
mesh.save('mymesh.vtk')  # save to disk
```

You may want to check out the docs at docs.pyvista.org as well as there's lots of helpful examples there.

**Comment by captain-pool** [comment]
Hey @akaszynski , thanks for your reply. I'll definitely go through the documentation examples. Thanks for pointing them out :)

I copy pasted the fragment that you wrote. Here's the error it gives me. 

![Screenshot](https://user-images.githubusercontent.com/13994201/94365590-da06e200-00ef-11eb-9602-eb3d733e7728.png)


Also, I'm new to pyvista, so maybe I'm wrong. I have been using Trimesh, meshio, open3d, etc, all of them require the faces to be in the form of a 2D matrix, which is pretty logical since each row represented a face and the values represented the vertices which connect to form the cell. However, hstacking the faces, would give one contiguous array of `ndims = 1`, right? How does pyvista figure out which values form a face?

**Comment by akaszynski** [comment]
In this case, it's not possible to have a 2D array as each face is a different size (unless you make the array sized to the maximum face size, which would lead to a lot of wasted space).  For our example, the first value represents the size of each face, and VTK walks through the faces array when displaying the mesh to "see" how large each face is.

First, it steps to the first face, sees the size of the face, and then reads that number of faces.  It will then increment the counter by one and read the next face.  This way you can have an entire array of faces as a single, 1 dimensional contiguous array.

In this example:
```py
faces = np.hstack(([[3, 0, 1, 2],
                    [4, 0, 2, 3, 1],
                    [3, 0, 2, 4],
                    [4, 2, 3, 4, 5]]))
```
The faces array will look like:
```py
array([3, 0, 1, 2, 4, 0, 2, 3, 1, 3, 0, 2, 4, 4, 2, 3, 4, 5])
```
And VTK is smart enough to walk through array provided you wrote the "header" of each face correctly.  This way you can add an arbitrary number of points to each face.

**Comment by captain-pool** [comment]
Aah I see! Now I know what i was doing wrong.
Thanks for the clarification!
Adrish
