### ISSUE TITLE
Adding interpolated  point arrays to spline

### ISSUE THREAD

**Issue by jpmorr** [pyvista/pyvista-support#252]
## Description
I'm plotting trajectories of position over time as a spline with pyvista. Sometimes, to make the spline  look a little better I'm using the number of points option to make the spline smoother which works greater.

But now I'm trying to add some scalar information to the spline for plotting  - I'd like to colour the spline by the velocity, but I'd like to be able to do this with the interpolated smooth spline. 

Is there a way of generating the spline with the associated scalars so that it too get's interpolated? Or do I simply have to go and manually interpolate the velocity data to be the same size before adding?

## Example Data
This works:
````py
import numpy as np
import pyvista as pv
theta = np.linspace(-4 * np.pi, 4 * np.pi, 100)
z = np.linspace(-2, 2, 100)
r = z**2 + 1
x = r * np.sin(theta)
y = r * np.cos(theta)
points = np.column_stack((x, y, z))
vel = np.random.rand(100)

spline = pv.Spline(points)
spline["velocities"] = vel 

tube = spline.tube(radius=0.001)
p = pv.Plotter()
p.add_mesh(tube, scalars="velocities")
p.show()
````

But this obviously doesn't:
````
spline = pv.Spline(points, 1000)
spline["velocities"] = vel 
````

What way is spline doing the interpolation and what would the the correct way to interpolate the velocity data to best fit this? It would be great if there an automatic interpolation when adding additional data.

**Comment by akaszynski** [comment]
This gets you closer:

```py
import numpy as np
import pyvista as pv
theta = np.linspace(-4 * np.pi, 4 * np.pi, 100)
z = np.linspace(-2, 2, 100)
r = z**2 + 1
x = r * np.sin(theta)
y = r * np.cos(theta)
points = np.column_stack((x, y, z))
vel = np.random.rand(100)

spline = pv.Spline(points)
spline["velocities"] = vel 

radius = 0.01
tube = spline.tube(radius=radius)
tube.plot(scalars="velocities")

# finer spline
fine_spline = pv.Spline(points, 1000).tube(radius=radius)  # radius must be the same
fine_spline = fine_spline.sample(spline, tolerance=10)
fine_spline.plot(scalars='velocities')
```

Still, it's not close enough:
```py

import matplotlib.pyplot as plt
plt.plot(spline['arc_length'], spline['velocities'])
plt.plot(fine_spline['arc_length'], fine_spline['velocities'])
plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/11981631/94572781-a2eb1a80-022e-11eb-9730-48fa9eb7ce58.png)

Seems that there's an issue with some points not interpolating properly.  You could always mask these points(seems that these points have zero values at `"arc_length"` and `"velocities"`, but you might have better luck just using `numpy.interp`.

**Comment by banesullivan** [comment]
The [`interpolate`](https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.interpolate) filter will perform a bit better than the `sample` filter as it can use a gaussian kernel to interpolate between the points avoiding those null values. As you increase the radius, the interpolation will get smoother. Here is an example that I think is pretty good:

```py
import numpy as np
import pyvista as pv

theta = np.linspace(-4 * np.pi, 4 * np.pi, 100)
z = np.linspace(-2, 2, 100)
r = z**2 + 1
x = r * np.sin(theta)
y = r * np.cos(theta)
points = np.column_stack((x, y, z))
vel = np.random.rand(100)

# Create a PyVista mesh of the original data
cloud = pv.PolyData(points)
cloud["velocities"] = vel

# Coarse spline of original data
spline_course = pv.Spline(cloud.points)
spline_course["velocities"] = cloud["velocities"]

# Smooth spline interpolating the data values
spline_fine = pv.Spline(cloud.points, 1000).interpolate(spline_course, radius=0.5, sharpness=1)
```

```py
import matplotlib.pyplot as plt
plt.figure(figsize=(10,5))
plt.plot(spline_course["arc_length"], spline_course["velocities"])
plt.plot(spline_fine["arc_length"], spline_fine["velocities"])
```

![download](https://user-images.githubusercontent.com/22067021/94642478-71f7fd80-02a1-11eb-8d37-8ca3cdccc7b9.png)


You can experiment with the radius and sharpness to get what you like

**Comment by jpmorr** [comment]
Thanks for these two solutions. The gauss interpolation seems more robust as it has no strange values, but will keep both methods in mind for future reference.

**Comment by akaszynski** [comment]
Looks like interpolate is the way to go.  Thanks @banesullivan!
