### ISSUE TITLE
Generate animation by changing slicing location

### ISSUE THREAD

**Issue by dvm-shlee** [pyvista/pyvista-support#255]
## Description

Hi, thank you for disseminating this great library! 
I was struggled with using the vtk, but with the pyvista, my life became much easier!

I'm trying to generate some brain slice animation.
Basically, what I'm trying to do is as below.
1. plot transparent brain mesh (surface)
2. slice anterior part of brain volume (this has scalar, so can show the detailed structure of a particular slice), add it and write frame
3. update the slice image to a little bit posterior and write a frame (the previous slice need to be removed)

below is my code. (this is just plotting first transparent brain surface but not the slice
and the generated gif it unable to open.

I look forward to your reply! Thank you again!

## Example Data

```py
# mesh : transparent brain surface
# vol : scalar brain volume

p = pv.Plotter()
p.add_mesh(mesh, show_scalar_bar=False, smooth_shading=True, 
                    opacity=[0, 0, 0.1, 0.2, 0.3, 0.1, 0.0], cmap='bone', ambient=0.4)
p.show(cpos=cpos, auto_close=False)
p.open_gif("slicing.gif")

ymin, ymax = anat.GetBounds()[2:4]
actor = None
for slice_pos in np.linspace(ymin, ymax, 10):
    sliced_vol = vol.slice(normal=[0, 1, 0], origin=[0, slice_pos, 0])
    actor = p.add_mesh(sliced_vol)
    p.update()
    p.mesh.compute_normals(cell_normals=False, inplace=True)
    p.write_frame()

p.close()
```

**Comment by banesullivan** [comment]
Its really tough to help you here without your data.

Here is an attempt using a brain volume from our examples module:

```py
import pyvista as pv
from pyvista import examples
import numpy as np

vol = examples.download_brain()
mesh = vol.contour([150,])

cpos = [(366.45595659861465, 547.175369887026, 104.74237527170493),
 (88.7777792415466, 112.37157711063615, 75.40583563922539),
 (-0.054149209891690434, -0.032754269648720004, 0.9979955014366972)]

p = pv.Plotter()
p.enable_depth_peeling()
p.add_mesh(mesh, color='grey', smooth_shading=True, opacity=0.25)
p.show(cpos=cpos, auto_close=False)
p.open_gif("slicing.gif")

def add_slice(slice_pos):
    sliced_vol = vol.slice(normal=[0, 1, 0], origin=[0, slice_pos, 0])
    p.add_mesh(sliced_vol, name='slice')
    p.write_frame()

ymin, ymax = mesh.GetBounds()[2:4]
positions = np.linspace(ymin, ymax, 10)

for slice_pos in positions:
    add_slice(slice_pos)
# And loop back for inifinte effect
for slice_pos in positions[::-1]:
    add_slice(slice_pos)

p.close()
```

![slicing](https://user-images.githubusercontent.com/22067021/94982291-7ff28c00-04f6-11eb-8f58-48196b1a100d.gif)

**Comment by dvm-shlee** [comment]
@banesullivan The code you replied works great for me! Thank you so much. BTW, I'm wondering how the slice can be animated to the next slice without removing the previously added slice? Is it because you use the name of the object so when it allocated, it reflashed?

**Comment by banesullivan** [comment]
> Is it because you use the name of the object so when it allocated, it reflashed?

Exactly. Take out the `name` argument and each slice will remain in the scene (also take out the second, reverse loop I have to avoid adding the same slice twice)

```py
...

def add_slice(slice_pos):
    sliced_vol = vol.slice(normal=[0, 1, 0], origin=[0, slice_pos, 0])
    p.add_mesh(sliced_vol)
    p.write_frame()

...

for slice_pos in positions:
    add_slice(slice_pos)

p.close()
```

**Comment by dvm-shlee** [comment]
@banesullivan Thanks a lot! I will close the issue!

**Comment by banesullivan** [comment]
FYI, it may help to set the `clim` in the `add_mesh` call to avoid having the scalar bar updating through the GIF

**Comment by dvm-shlee** [comment]
@banesullivan Cool! Thanks for the tip!
