### ISSUE TITLE
segfault when trying to construct UnstructuredGrid of VTK_WEDGEs

### ISSUE THREAD

**Issue by mkondratyev85** [pyvista/pyvista-support#256]
I have two csv files.
`points.csv` contains coordinates of points x, y, z1, z2.
There are two layers of points and they have common x and y coordinates.
File `cells.csv` contains indexes of points in each cell. Each cell
consists of three points.

```python
import pandas as pd
import pyvista as pv
import numpy as np
import vtk


df_points = pd.read_csv('points.csv')
df_cells = pd.read_csv("cells.csv")

x = df_points.x.values
y = df_points.y.values
z1 = df_points.z1.values
z2 = df_points.z2.values

nodes1 = df_cells.node1
nodes2 = df_cells.node2
nodes3 = df_cells.node3

points1 = [(x_, y_, z_) for x_, y_, z_ in zip(x, y, z1)]
points2 = [(x_, y_, z_) for x_, y_, z_ in zip(x, y, z2)]

cells = [[3, n1, n2, n3] for n1, n2, n3 in zip(nodes1, nodes2, nodes3)]

points1 = np.array(points1)
points2 = np.array(points2)
cells = np.hstack(cells)

surface1 = pv.PolyData(points1, cells)
surface2 = pv.PolyData(points2, cells)

plotter = pv.Plotter()
plotter.add_mesh(surface1, show_edges=True)
plotter.add_mesh(surface2, show_edges=True)
plotter.show()
```

![Снимок экрана от 2020-10-02 15-48-40](https://user-images.githubusercontent.com/32978900/94890818-1eb5c300-04cc-11eb-9fc8-eae68b6325f0.png)

Now I want to construct UnstructuredGrid consisting of VTK_WEDGEs.
Each wedge is three points from the top layer and three points from the bottom layer.

```python
points = points1 + points2

LAYER_NODES_N = len(x)

nodes4 = nodes1 + LAYER_NODES_N
nodes5 = nodes2 + LAYER_NODES_N
nodes6 = nodes3 + LAYER_NODES_N

cells = [(6, n1, n2, n3, n4, n5, n6) for
         n1, n2, n3, n4, n5, n6 in
         zip(nodes1, nodes2, nodes3, nodes4, nodes5, nodes6)]

cells = np.hstack(cells)
points = np.array(points)
celltypes = np.empty(len(cells), dtype=np.uint8)
celltypes[:] = vtk.VTK_WEDGE

offset = np.array([i*7 for i in range(len(nodes1))], dtype=int)

mesh = pv.UnstructuredGrid(offset, cells, celltypes, points)
```

It looks like it works. But when I try to plot the mesh I catch segfault.

``` python
mesh.plot()

>>> 
Fatal Python error: Segmentation fault
```

What could be the reason for this?

[files.zip](https://github.com/pyvista/pyvista-support/files/5316116/files.zip)

**Comment by akaszynski** [comment]
Hello,

Looks like you're running into an issue where the `cells` array is attempting to reference points that don't exist:

```py
UnstructuredGrid (0x7f2a25c08280)
  N Cells:	22155
  N Points:	1708
  X Bounds:	0.000e+00, 7.768e+02
  Y Bounds:	0.000e+00, 5.064e+02
  Z Bounds:	5.459e+00, 8.578e+00
  N Arrays:	0

In [3]: mesh.offset
Out[3]: array([    0,     7,    14, ..., 22134, 22141, 22148])

In [4]: mesh.cells
Out[4]: array([   6,    0,    1, ..., 3402, 3403, 3404])

In [5]: mesh.points.shape
Out[5]: (1708, 3)
```

The last cell (and probably more) are referencing the point at index 3404, which doesn't exist since you only have 1708 points.  I'd double check the way you're creating the cells.

**Comment by mkondratyev85** [comment]
Thank you for your answer. I found a bug in the way I concatenated two lists `points = points1 + points2`. I've changed this line to  `points = [*points1, *points2]` and now my two lists are merged indeed. 

`mesh.offset`
`>>> [    0     7    14 ... 22134 22141 22148]`

`mesh.cells, mesh.cells.max(), mesh.cells.shape`
`>>> [   6    0    1 ... 3401 3402 3403] 3414 (22155,)`

`mesh.points.shape`
`>>> (3416, 3)`

Now, if I understand the meanings of those parameters correctly, the numbers look to be correct.
But I still have the same segfault when trying to plot the resulting mesh.

**Comment by mkondratyev85** [comment]
Ok. I found the problem. I was building `celltypes` array based on the length of `cells` array after I did `hstack` on it. So the length of the `cells` array was way bigger than the number of cells. 

This code works fine.

```python

points = np.array(points)
celltypes = np.empty(len(cells), dtype=np.uint8)
celltypes[:] = vtk.VTK_WEDGE

offset = np.array([i*7 for i in range(len(cells))], dtype=int)
cells = np.hstack(cells)

mesh = pv.UnstructuredGrid(offset, cells, celltypes, points)
```

**Comment by akaszynski** [comment]
Totally missed your comment four days ago, but I'm glad you were able to figure this out!

It's a bit of work creating unstructured grids within VTK as the cells, offset, celltypes, and points all need to be contiguous grids and VTK has no room for errors (or error checking in general), but the array access times are quite fast, and it really lends itself to many applications.

One note: if you're using `vtk>=9.0.0`, you don't need the offset array; it's enough just to supply `cells`, `celltypes`, and `points`.

**Comment by mkondratyev85** [comment]
It would be nice if pyvista would check simple assertions like the number of cells compared to the len of celltypes array or the last value in offset compared to the len of celltypes etc. It would help the user to debug errors while creating meshes.
