### ISSUE TITLE
Texture Mapping

### ISSUE THREAD

**Issue by KDarshan20** [pyvista/pyvista-support#257]
Hello,
   I found PyVista while surfing the internet for a library that would help me in my project, a 3D solar system animation. So while working on the project I came across a problem: I couldn't get the textures mapped correctly. For instance,
```
import pyvista
sphere = pyvista.Sphere()
tex = pyvista.read_texture("Earth.png")
sphere.texture_map_to_plane(inplace=True)
sphere.plot(texture=tex)
```
Gave the following output:
![image.png](https://user-images.githubusercontent.com/60852800/95277669-f92e0e00-086b-11eb-8494-6b757cc44343.png)
While I want it to look like the in-built globe example:
![1602034348488_image.png](https://user-images.githubusercontent.com/60852800/95277692-0a771a80-086c-11eb-92ad-d130cd9fdfd2.png)
Earth.png:
![Earth.png](https://user-images.githubusercontent.com/60852800/95278273-75752100-086d-11eb-8d7c-d1a2818ec09d.png)

**Comment by akaszynski** [comment]
@banesullivan has done a lot of the implementation of texture mapping, so he'll probably correct me if I'm wrong, but I think the issue is that there's no way for `pyvista`/`vtk` to know the mapping between your earth png and the sphere.  The `texture_map_to_plane` method works great on planes, on spheres:

```py
import pyvista
mesh = pyvista.Plane()
tex = pyvista.read_texture("Earth.png")
mesh.texture_map_to_plane(inplace=True)
mesh.plot(texture=tex)
```

![image](https://user-images.githubusercontent.com/11981631/95289702-a8e18c80-0828-11eb-9fdf-b1b24daf789b.png)

What the ``texture_map_to_plane`` is doing is taking each coordinate of the image and interpolating it onto each coordinate of the plane mesh.  This is easy to do in 2 dimensions, but in 3 dimensions, there's too many possible solutions.  If you plot the mesh of the sphere, you can see that there's a non-uniform distribution of points:

![image](https://user-images.githubusercontent.com/11981631/95289837-01188e80-0829-11eb-8c49-b11faa96ecdb.png)

So, what you'd have to do if you wanted it properly mapped is to get the right relationship of the points on the sphere to a plane (effectively, [U V Mapping](https://en.wikipedia.org/wiki/UV_mapping)), and then use that projection to apply your texture.

If you do choose to project to a sphere, please post your solution here so others can benefit from it.

**Comment by KDarshan20** [comment]
Thanks, that helped me understand why the texture gets mapped so. 
How do I implement uv mapping?

**Comment by banesullivan** [comment]
> So I have to implement UV mapping by defining t_coords by determining a relation between the XYZ coordinates and texture coordinates?

That's correct! Keep your UV coordinates scaled between 0 and 1 and map each vertex to its coordinates in the UV image space.

FYI, there is a [`vtkTextureMapToSphere`](https://vtk.org/doc/nightly/html/classvtkTextureMapToSphere.html) that we could implement much like the `texture_map_to_plane` filter

**Comment by banesullivan** [comment]
I created the globe example manually with the code in [this PVGeo filter](https://github.com/OpenGeoVis/PVGeo/blob/8d257ffe0960e5838244544476cf5b300bd58c7c/PVGeo/model_build/earth.py#L53-L141)

Basically, I reproject the sphere's coordinates to a Lat/Lon space (thus a 2D plane) and essentially map the UV coordinates linearly there.

On a sphere, you HAVE to make sure there is an open edge along one longitude or else you will get artifacts of the texture folding back on itself.

I outlined all of this in [this ParaView discourse thread](https://discourse.paraview.org/t/single-azimuthal-segment-texture-distortion-for-earth-texturemaptosphere/783/9)

**Comment by KDarshan20** [comment]
I used this slight modified form of the relation given in [Wikipedia](https://en.wikipedia.org/wiki/UV_mapping#Finding_UV_on_a_sphere):
![665757524997177365](https://user-images.githubusercontent.com/60852800/95453483-92eadd80-0988-11eb-88c4-953bc8e77b7c.png)
And also applied the [solution](https://discourse.paraview.org/t/single-azimuthal-segment-texture-distortion-for-earth-texturemaptosphere/783/5) you had given to remove the distortion at the seam, and came up with this code:
```
import pyvista
import math
import numpy
sphere = pyvista.Sphere(radius=1, theta_resolution=120, phi_resolution=120, start_theta=270.001, end_theta=270)
sphere.t_coords = numpy.zeros((sphere.points.shape[0], 2))
for i in range(sphere.points.shape[0]):
    sphere.t_coords[i] = [0.5 + (math.atan2(-sphere.points[i, 0], sphere.points[i, 1]))/(2 * math.pi), 0.5 + math.asin(sphere.points[i, 2])/math.pi]
tex = pyvista.read_texture("Earth.png")
sphere.plot(texture=tex)
```
(I've used a sphere of radius 1, so I don't have to explicitly calculate the unit vector)
And got this satisfactory output:
![image](https://user-images.githubusercontent.com/60852800/95454012-7ac78e00-0989-11eb-9eb4-ad158d243c53.png)
Thanks for the help! I'll close this issue now.

**Comment by banesullivan** [comment]
Awesome work, @KDarshan20! Thanks for sharing this

**Comment by KDarshan20** [comment]
Thanks to you as well!

**Comment by bluetyson** [comment]
Nice, now need to find a Mars!

**Comment by akaszynski** [comment]
Found Mars.

![mars_pv](https://user-images.githubusercontent.com/11981631/95625815-5bd30580-0a36-11eb-80fb-f157d42591bd.png)

```python
import pyvista
import math
import numpy
import numpy as np

sphere = pyvista.Sphere(radius=1, theta_resolution=120, phi_resolution=120,
                        start_theta=270.001, end_theta=270)
sphere.t_coords = numpy.zeros((sphere.points.shape[0], 2))


sphere.t_coords[:, 0] = 0.5 + np.arctan2(-sphere.points[:, 0], sphere.points[:, 1])/(2 * math.pi)
sphere.t_coords[:, 1] = 0.5 + np.arcsin(sphere.points[:, 2]) / math.pi


tex = pyvista.read_texture("mars.jpg")
# sphere.plot(texture=tex, smooth_shading=False, background='black', show_axes=False)

# with stars
pl = pyvista.Plotter()
pl.add_background_image('stars.jpg')
pl.add_mesh(sphere, texture=tex, smooth_shading=False)
pl.show()

```


---
### Mars
http://www.solarviews.com/raw/mars/marscyl1l.jpg

### Stars
https://pngio.com/PNG/a44278-space-stars-png.html

**Comment by bluetyson** [comment]
Great, thanks Alex!

**Comment by banesullivan** [comment]
Nice! @akaszynski, let's add that to https://github.com/pyvista/pyvista/pull/940

**Comment by KDarshan20** [comment]
A source of textures for all planets, the sun, etc.: [https://www.solarsystemscope.com/textures/]()

**Comment by banesullivan** [comment]
Awesome! I think I have to make a solar system example then!

**Comment by BrandonEscamilla** [comment]
@akaszynski your code also works for the moon for example?

**Comment by akaszynski** [comment]
Hello,

Please post the full code you used.

**Comment by BrandonEscamilla** [comment]
Hi @akaszynski, 

I am sorry for my late response but here is the code and the output. I am creating a sphere with the real radius of the moon. (1738 km)

`p = pv.Plotter()
sphere = pv.Sphere(radius=1738)

sphere.t_coords = np.zeros((sphere.points.shape[0], 2))


sphere.t_coords[:, 0] = 0.5 + np.arctan2(-sphere.points[:, 0], sphere.points[:, 1])/(2 * math.pi)
sphere.t_coords[:, 1] = 0.5 + np.arcsin(sphere.points[:, 2]) / math.pi
print(sphere.t_coords)

tex = pv.read_texture("2k_moon.jpg")
# sphere.plot(texture=tex, smooth_shading=False, background='black', show_axes=False)

# with stars
#pl = pyvista.Plotter()
#pl.add_background_image('stars.jpg')

#
#pl.show()
p.add_mesh(sphere, texture=tex)
p.add_axes()
p.show_grid()

#NORMAL
p.show()`

![Captura de Pantalla 2021-03-07 a la(s) 15 00 39](https://user-images.githubusercontent.com/21966716/110254715-e2443280-7f55-11eb-806d-3db4a5523404.png)

**Comment by akaszynski** [comment]
BTW, if anyone is using this with `pyvista>=0.33`:

```py
import pyvista
import math
import numpy
import numpy as np

from pyvista import examples

sphere = pyvista.Sphere(radius=1, theta_resolution=120, phi_resolution=120,
                        start_theta=270.001, end_theta=270)
sphere.active_t_coords = numpy.zeros((sphere.points.shape[0], 2))


sphere.active_t_coords[:, 0] = 0.5 + np.arctan2(-sphere.points[:, 0], sphere.points[:, 1])/(2 * math.pi)
sphere.active_t_coords[:, 1] = 0.5 + np.arcsin(sphere.points[:, 2]) / math.pi

mars = pyvista.Texture(examples.download_mars_jpg())
stars = examples.download_stars_jpg()

# with stars
pl = pyvista.Plotter()
pl.add_background_image(stars)
pl.add_mesh(sphere, texture=mars, smooth_shading=False)
pl.show()
```

**Comment by RichardScottOZ** [comment]
Definitely will try that one!

**Comment by RichardScottOZ** [comment]
![image](https://user-images.githubusercontent.com/72196131/155687041-59161a67-b7f7-44b9-87a0-eef341656665.png)

**Comment by f123-maker** [comment]
Are there any methods to control the mapping position with coordinates? Many of the methods found are full package methods. I want a method to use coordinates for local mapping
