### ISSUE TITLE
How to extract volume field from vtk.

### ISSUE THREAD

**Issue by oarcelus** [pyvista/pyvista-support#258]
Dear All,

I am using pyvista to read a vtk grid. The software im using inputs a 3D image (.tiff) file and returns a vtk file where the points (in the same positions as the pixels of the 3D image) are linked to different float values.

Now what I want is just convert this vtk file back into a 3D numpy array, containing the float values. But I am failing to do so.

Just by printing the information:

`data = pv.read('rho_f1_001_00000100.vti')`
`print(data)`

I get the following output 

UniformGrid (0x2dbbeb052e8)
  N Cells:      970299
  N Points:     1000000
  X Bounds:     0.000e+00, 9.900e+01
  Y Bounds:     0.000e+00, 9.900e+01
  Z Bounds:     0.000e+00, 9.900e+01
  Dimensions:   100, 100, 100
  Spacing:      1.000e+00, 1.000e+00, 1.000e+00
  N Arrays:     1

Which I do not know how to further treat. 

Any help would be greatly appreciated.

Cheers,

**Comment by akaszynski** [comment]
I think you're looking for the points array.  Please see https://docs.pyvista.org/getting-started/simple.html#accessing-the-wrapped-data-object

**Comment by banesullivan** [comment]
```py
print(data.point_arrays)
```

**Comment by oarcelus** [comment]
Hi all,

Thanks! I got exactly what I wanted!
