### ISSUE TITLE
Enable/Disable interaction

### ISSUE THREAD

**Issue by GuillaumeFavelier** [pyvista/pyvista-support#260]
Hello PyVista community! I would like to know if there is a way to disable interactions with the plotter completely (mouse, keyboard, ...) temporarily. It could be restored afterwards. Ideally, I am looking for something like `enable/disable`.

If such a feature is not available yet and you know a way to accomplish this, I would be happy to open a PR to add it with your guidance.

This is useful for a specific use case (https://github.com/mne-tools/mne-python/issues/8363).

**Comment by banesullivan** [comment]
The renderers have both `enable()`/`disable()` methods to do tjust this which are wrapped by the plotter for the current active renderer:

```py
>>> import pyvista as pv
>>> p = pv.Plotter()
>>> p.add_mesh(pv.Cube())
>>> p.disable()
>>> p.show()
# non-interactive plot shown
```

**Comment by banesullivan** [comment]
I do this often for ortho slicing where I only want the 3D view to be interactive and have the other slices views remain still in a parallel projection, e.g. https://github.com/pyvista/pyvista/pull/263

**Comment by GuillaumeFavelier** [comment]
Thank you so much for your quick answer @banesullivan ! I missed this feature completety :sweat_smile: 

Sadly, it does not directly solve my particular issue so I think it's something specific to `mne-python` or `pyvistaqt`. Anyway, it's a step forward :+1:
