### ISSUE TITLE
Rendering window doesn't respond

### ISSUE THREAD

**Issue by KDarshan20** [pyvista/pyvista-support#262]
I am testing a small piece of code, which I will be using in another project.
The code:
```python
from math import sin, cos, pi

import numpy
import pyvista
import time

p = pyvista.Plotter()
sun = pyvista.Sphere(10)
earth = pyvista.Sphere(radius=2, center=(0, 0, 0))


def get_coords(hours):
    x = 15 * cos(hours * 2 * pi / 24)
    y = 15 * sin(hours * 2 * pi / 24)
#    print([x, y])
    return numpy.array([[x, y, 0]])


p.add_mesh(sun, color="yellow")
p.add_mesh(earth, color="blue")
pts = earth.points.copy()
p.show(auto_close=False, interactive_update=True)
for i in range(24000):
    ptsnew = pts + numpy.repeat(get_coords(i), pts.shape[0], 0)
    p.update_coordinates(ptsnew, earth, True)
#    print(i)
    time.sleep(0.1)
p.close()

```
The code seems to work for a while, but after some iterations, the rendering window stops responding. I inserted the `print(i)` and `print([x, y])` statements (commented out in the above code) and tested it and found that the values were printed even after the rendering window stops responding.
Where is the problem? Is my code wrong? Or is it some performance issue?

**Comment by banesullivan** [comment]
This is expected. The plotter's event loop is tied to yuor current thread. We create `pyvistaqt` and specifically the `BackgroundPlotter` for this sort of use case. 

See http://qtdocs.pyvista.org

Basically, install `pyvistaqt` and change out the `pyvista.Plotter` for `pyvistaqt.BackgroundPlotter`

**Comment by KDarshan20** [comment]
I did the changes and I have this code now:
```python
from math import sin, cos, pi

import numpy
import pyvista
import pyvistaqt
import time

p = pyvistaqt.BackgroundPlotter()
sun = pyvista.Sphere(radius=10)
earth = pyvista.Sphere(radius=2, center=(0, 0, 0))


def get_coords(hours):
    x = 15 * cos(hours * 2 * pi / 24)
    y = 15 * sin(hours * 2 * pi / 24)
    print([x, y])
    return numpy.array([[x, y, 0]])


p.add_mesh(mesh=sun, color="yellow")
p.add_mesh(mesh=earth, color="blue")
pts = earth.points.copy()
for i in range(24000):
    p.update_coordinates(points=pts + numpy.repeat(get_coords(i), pts.shape[0], 0), mesh=earth, render=True)
    print(i)
    time.sleep(0.1)
```
But the problem still exists. The window stops responding when I click somewhere on the window.

**Comment by KDarshan20** [comment]
@banesullivan can you take a look at this?

**Comment by GuillaumeFavelier** [comment]
Hello @KDarshan20 , I suggest that you take a look at the [documentation of `add_callback`](http://qtdocs.pyvista.org/api_reference.html#pyvistaqt.BackgroundPlotter.add_callback) for more details but basically it will call the function that you send with a certain interval. In your version, you ask the routine to execute 24000 iterations every second.

I may be wrong on your intention but this is what I obtain when I modify your script a little :smile: :

```py
from math import sin, cos, pi

import numpy
import pyvista
import pyvistaqt

time_stamp = 0
p = pyvistaqt.BackgroundPlotter()
sun = pyvista.Sphere(radius=10)
earth = pyvista.Sphere(radius=2, center=(0, 0, 0))

def get_coords(hours):
    x = 15 * cos(hours * 2 * pi / 24)
    y = 15 * sin(hours * 2 * pi / 24)
    return numpy.array([[x, y, 0]])

p.add_mesh(mesh=sun, color="yellow")
p.add_mesh(mesh=earth, color="blue")

def callback():
    global time_stamp
    pts = earth.points.copy()
    p.update_coordinates(points=pts + numpy.repeat(get_coords(time_stamp), pts.shape[0], 0), mesh=earth, render=True)
    time_stamp += 1

p.add_callback(callback, interval=100)
```

![output](https://user-images.githubusercontent.com/18143289/97014792-1856bc00-154b-11eb-89ab-caa17602d7fa.gif)

**Comment by KDarshan20** [comment]
That's the output you get for that code? I copy-pasted the exact same code and ran it, and the window closes immediately after it opens. Here's what I got in the terminal (but I am not sure if it is relevant):
`QWindowsWindow::setGeometry: Unable to set geometry 1024x768+363+124 (frame: 1040x807+355+93) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1024x749+363+124 (frame: 1040x788+355+93) margins: 8, 31, 8, 8 minimum size: 177x62 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=193,101 maxtrack=0,0)`

**Comment by KDarshan20** [comment]
@GuillaumeFavelier I tried running the code in another computer, but I didn't get this message this time:
> `QWindowsWindow::setGeometry: Unable to set geometry 1024x768+363+124 (frame: 1040x807+355+93) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1024x749+363+124 (frame: 1040x788+355+93) margins: 8, 31, 8, 8 minimum size: 177x62 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=193,101 maxtrack=0,0)`
But the window still closes immediately after I run the code, so I guess the message has got nothing to do with the output.
Can you recheck if the output _does_ correspond to the code you sent?

**Comment by GuillaumeFavelier** [comment]
Sorry for the late response @KDarshan20 :pray: 

I checked again and the code gives the same result. Many the difference is how you start the script?

I can confirm that everything works for me if I use `python -i script.py` or through `ipython`:

```
Python 3.8.5 | packaged by conda-forge | (default, Jul 31 2020, 02:39:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: run script.py
```

*Where `script.py` contains the snippet in https://github.com/pyvista/pyvista-support/issues/262#issuecomment-715373816*

**Comment by GuillaumeFavelier** [comment]
When I use only `python script.py`, the window closes. IIRC, it's because `BackgroudPlotter` does not creates it's own `QApplication` event loop by default.

The code needs to be modified slightly to allow such a usage:

```py
from math import sin, cos, pi
from PyQt5.QtWidgets import QApplication

import numpy
import pyvista
import pyvistaqt

app = QApplication([])  # create Qt application here

time_stamp = 0
p = pyvistaqt.BackgroundPlotter()
sun = pyvista.Sphere(radius=10)
earth = pyvista.Sphere(radius=2, center=(0, 0, 0))

def get_coords(hours):
    x = 15 * cos(hours * 2 * pi / 24)
    y = 15 * sin(hours * 2 * pi / 24)
    return numpy.array([[x, y, 0]])

p.add_mesh(mesh=sun, color="yellow")
p.add_mesh(mesh=earth, color="blue")

def callback():
    global time_stamp
    pts = earth.points.copy()
    p.update_coordinates(points=pts + numpy.repeat(get_coords(time_stamp), pts.shape[0], 0), mesh=earth, render=True)
    time_stamp += 1

p.add_callback(callback, interval=100)

app.exec()  # and start event loop here
```

**Comment by KDarshan20** [comment]
Thank you, that worked! Just one small thing. My intention was to make the blue sphere orbit the yellow sphere in a circle, so I had to make a small change: I removed the `pts = earth.points.copy()` and added it above the definition of `callback()`, so the final code is now
```python
from math import sin, cos, pi
from PyQt5.QtWidgets import QApplication  # import QApplication from PyQt5/PySide2 here

import numpy
import pyvista
import pyvistaqt

app = QApplication([])  # create Qt application here

time_stamp = 0
p = pyvistaqt.BackgroundPlotter()
sun = pyvista.Sphere(radius=10)
earth = pyvista.Sphere(radius=2, center=(0, 0, 0))

def get_coords(hours):
    x = 15 * cos(hours * 2 * pi / 24)
    y = 15 * sin(hours * 2 * pi / 24)
    return numpy.array([[x, y, 0]])

p.add_mesh(mesh=sun, color="yellow")
p.add_mesh(mesh=earth, color="blue")

pts = earth.points.copy()

def callback():
    global time_stamp
    p.update_coordinates(points=pts + numpy.repeat(get_coords(time_stamp), pts.shape[0], 0), mesh=earth, render=True)
    time_stamp += 1

p.add_callback(callback, interval=100)

app.exec()  # and start event loop here
```
