### ISSUE TITLE
Saving a VTK mesh with texture

### ISSUE THREAD

**Issue by shakasaki** [pyvista/pyvista-support#265]
## Description

I am trying to save a VTK object, using pyvista, which in this case is a mesh with some added texture. The mesh comes from a Digital Elevation Model (DEM) and the texture is a satellite image. The texture and DEM are not necessarily of the same size (satellite image is usually denser spacing in my case).

Of course I looked at the docs : https://docs.pyvista.org/examples/02-plot/texture.html

and I also found a post here https://github.com/pyvista/pyvista-support/issues/242 where @banesullivan suggests a solution. However, I was not able to implement this solution. I am able to save a mesh using export_obj() but not sure how to save the texture.

Or perhaps, is there is another way to do this?

I use pyvista version 0.26.1
Ubuntu 18.04
python 3.6

## Example Data

```py
import pyvista as pv
import numpy as np
import pyvistaqt as pvqt


# I create some dummy data here for the example

# domain size
nx = 100
ny = 100

# point cloud creation
east,north = np.meshgrid(np.linspace(0,1,nx),np.linspace(0,1,ny))
elevation = np.ones((nx,ny))
point_cloud = np.array([east.ravel(), north.ravel(),elevation.ravel()]).T

# image 
image = np.random.randint(0,256,(nx,ny,3))


# get the surface mesh
cloud = pv.PolyData(point_cloud).extract_geometry().triangulate()
surface = cloud.delaunay_2d()
surface.texture_map_to_plane(use_bounds=True, inplace=True)

# add texture to surface dictionary
surface.textures['aerial-image'] = pv.numpy_to_texture(image)

# this saves the surface correctly but not the texture
surface.save('foo.vtk') 


# This exports the surface as well, but not the texture
p = pvqt.BackgroundPlotter()
p.add_mesh(surface, texture='aerial-image')
p.export_obj("foo")

```

I can open both foo.vtk and foo.obj with paraview but the textures are not there. Here are the screenshots from
1. pyvista, texture works
2. paraview vtk file, doesnt have texture
3. paraview obj file, doesnt have texture

![pv-screenshot](https://user-images.githubusercontent.com/7264182/96235474-23ce4400-0f9b-11eb-8cdf-29ce262e274a.png)

![paraview-vtk](https://user-images.githubusercontent.com/7264182/96235488-2761cb00-0f9b-11eb-826c-d805dea9d4c0.png)

![paraview-obj](https://user-images.githubusercontent.com/7264182/96235500-2b8de880-0f9b-11eb-86ce-2b1f67ea4b3b.png)

**Comment by banesullivan** [comment]
textures are treated as separate entities in VTK. You will need to save the mesh with its texture coordiantes and save the texture itself as an image file.

So after you do `surface.texture_map_to_plane(use_bounds=True, inplace=True)`, save the mesh to a VTK format:

```py
surface.save("texture-mapped-surface.vtk")
```

Then save your image

```py
from PIL import Image
im = Image.fromarray(image)
im.save("your_image.jpeg")
```

Then load the mesh in ParaVeiw like you have before but to load the texture, you have to go through the properties panel and load the texture:

<img width="405" alt="Screen Shot 2020-10-16 at 9 40 13 AM" src="https://user-images.githubusercontent.com/22067021/96279221-9dfaca80-0f93-11eb-961a-942f028d6fe6.png">

**Comment by shakasaki** [comment]
@banesullivan this works perfectly, thanks! But still, I was wondering whether it is possible to save a mesh in VTK format that has different attributes on its notes. For example, these could be RGB values that can serve as a texture.. It seems that it should be possible, based on VTK documentation (https://vtk.org/doc/release/6.2/html/classvtkDataSetAttributes.html)

Is this possible using pyvista? Thank you, by the way, pyvista is awesome

**Comment by banesullivan** [comment]
Ah yep, you can associate any data arrays with a mesh that correspond to the points or cells. e.g. `.point_arrays` and `.cell_arrays`. See: https://docs.pyvista.org/getting-started/what-is-a-mesh.html#what-are-attributes

You can also store arbitrary data arrays under `.field_arrays`

**Comment by shakasaki** [comment]
Thank you Bane, this works perfectly
