### ISSUE TITLE
Advice how to proceed with interactive surface plot of large data set (320,000,000 points)

### ISSUE THREAD

**Issue by dominicjtriana** [pyvista/pyvista-support#274]
## Description
I need some general advice on how to visualize a large data set as a surface plot.  I came across pyVista as a potential solution by reading on pyViz.org.  

I've played around with some of the examples but I'm getting odd results with my data (basically a flat plot).  In trying to troubleshoot the issue, I noticed interactive ability with pyVista plots seems to be added via matplotlib...  I've tried to plot this data with matplotlib and in order to maintain interactive ability the plot must be very coarse.  Before troubleshooting my flat plot, I want to make sure pyvista is the best library to use for my application. 

FYI my data set is on the order of 300 million data points and I'm trying to generate an interactive surface plot (Zoom, rotate, pan) while maintaining the resolution of my data.  The pyvista method I was using was StruturedGrid().

Thank you for any advice or tips about how to proceed.  I'm looking into paraview at the moment.

**Comment by banesullivan** [comment]
Can you provide a link to the data file with the points? It's tough for us to debug this without working with the data...

**Comment by dominicjtriana** [comment]
> Can you provide a link to the data file with the points? It's tough for us to debug this without working with the data...

Thanks for helping.  This will take some doing on my part, security protocols at my company are rough but I will figure something out.  

The data is stored in a csv file, the size is around 1.5 GB.  I will try to share a 100mb snippet.  No header, n x 3200 array, where 0 < n < 100,000.  The data is height data.  The spacing between each data point is 5 um with the units of the data being in mm.  The range of data 1.1mm to 1.7mm.  Features on a flat surface are 0.5mm x 0.5mm pyramids.

**Comment by dominicjtriana** [comment]
> Can you provide a link to the data file with the points? It's tough for us to debug this without working with the data...

Well I got lucky. Link contains 109mb snippet.
https://drive.google.com/file/d/1192XgCN7fJ69P5XtancVAbYRbK95nBya/view?usp=drive_web

The range is actually around 0.8 to 1.7.  You will see there are some -99.9999 data points.  These are missing data, these should be ignored.  Below is the code I used.  Looking at the data I assumed the missing data was in the first few rows so I didn't use them to create the structured grid. Ignored the first 200 rows or so.  I double check to see if there was any -99.999 points in the region I tried to mesh and I don't think there is...

import pyvista as pv
import numpy as np

file_name = r'C:/path'

# I understand this isn't the best import method but that's the next step.  
# Any advice here would also be much appreciated.
z = np.genfromtxt(file_name,delimiter=',')  

data_shape = z.shape
x = np.linspace(1,data_shape[0],data_shape[0])
y = np.linspace(1,data_shape[1],data_shape[1])
x, y = np.meshgrid(x,y,sparse=False,indexing='ij')

a = 200
b = 3000

grid = pv.StructuredGrid(x[a:b,:], y[a:b,:], z[a:b,:])
grid.plot()
grid.points

**Comment by akaszynski** [comment]
Looks like I need permission to access the link.  My email starts with akas...

**Comment by dominicjtriana** [comment]
> 
> 
> Looks like I need permission to access the link. My email starts with akas...

Ok I think i've given you permission.  Let me know if that didn't work.  Honestly haven't shared many files with google drive.

**Comment by akaszynski** [comment]
Downloading.  In the future, I'd encode this as a numpy array and save it that way.

```py
import numpy as np
z = np.genfromtxt(file_name,delimiter=',')  
np.save('8060.npy', z.astype(np.float32))
# read this in in the future with np.load('8060.npy')
```

I've saved it as float32 due to size considerations.  I'm zipping it here for anyone else who wants to look into this problem.
[8060.zip](https://github.com/pyvista/pyvista-support/files/5459956/8060.zip)

**Comment by akaszynski** [comment]
I didn't have any issue plotting, but I guess we're only plotting 16 million points.

```py
import pyvista as pv
import numpy as np

z = np.load('8060.npy')
data_shape = z.shape
x = np.linspace(1,data_shape[0],data_shape[0])
y = np.linspace(1,data_shape[1],data_shape[1])
x, y = np.meshgrid(x,y,sparse=False,indexing='ij')

grid = pv.StructuredGrid(x, y, z)
grid.plot()
grid.plot(eye_dome_lighting=True, color='w')
```

![desktop 1_251](https://user-images.githubusercontent.com/11981631/97608633-3489ab80-19d8-11eb-9419-f709b6b62b66.png)

Since the data appears structured, you can always downselect the data you're displaying with:
```
i_res = 6  # display every 6th point
j_res = 5  # display every 5th point

grid = pv.StructuredGrid(x[::i_res, ::j_res], y[::i_res, ::j_res],
                         z[::i_res, ::j_res])
print('Grid contains %.2f million points' % (grid.points.size/1E6))
```

You can change the resolution of the data at will to be able to handle the large dataset.

**Comment by dominicjtriana** [comment]
> Downloading. In the future, I'd encode this as a numpy array and save it that way.
> 
> ```python
> import numpy as np
> z = np.genfromtxt(file_name,delimiter=',')  
> np.save('8060.npy', z.astype(np.float32))
> # read this in in the future with np.load('8060.npy')
> ```
> 
> I've saved it as float32 due to size considerations. I'm zipping it here for anyone else who wants to look into this problem.
> [8060.zip](https://github.com/pyvista/pyvista-support/files/5459956/8060.zip)

Thanks for posting an easier format for others.  As far as my application I have to work with csv because that is the file format the data comes off of the machine.

**Comment by dominicjtriana** [comment]
> I didn't have any issue plotting, but I guess we're only plotting 16 million points.

I was able to achieve a similar output as you however this isn't correct.  First you should try to plot only rows 200:3000  to ensure you don't include any -99.999 data points.  Below is an output using matplotlib. As you can see there is much more geometry to the plot.  (I cannot use matplotlib for my app because it's too slow to load and interact with)

![image](https://user-images.githubusercontent.com/73613276/97610793-55a3c980-19e3-11eb-8ce9-74f4c9bd97c0.png)

**Comment by akaszynski** [comment]
The very first value of the very first row of your csv is `-99.9996 `, and there's lots of data that's less than -90:

```py
np.any(z < -90, axis=1).nonzero()
Out[40]: 
(array([   0, 3411, 3412, 3413, 3414, 3415, 3416, 3417, 3418, 3419, 3420,
        3421, 3422, 3423, 3424]),)
```

You can get rid of this data by turning it into NANs.  As for the scale, it seems that this is something matplotlib does automatically, but I disagree with this since all data isn't always scaled in the correct dimension.  Here's how to scale:

```py
import pyvista as pv
import numpy as np

z = np.load('8060.npy')
z[z < 1] = np.nan
# z[z > 3] = np.nan
data_shape = z.shape

x = np.linspace(1,data_shape[0],data_shape[0])
y = np.linspace(1,data_shape[1],data_shape[1])
x, y = np.meshgrid(x,y,sparse=False,indexing='ij')

i_res = 6  # display every 6th point
j_res = 5  # display every 5th point

grid = pv.StructuredGrid(x[::i_res, ::j_res], y[::i_res, ::j_res],
                         z[::i_res, ::j_res])
print('Grid contains %.2f million points' % (grid.points.size/1E6))


pl = pv.Plotter()
pl.enable_eye_dome_lighting()
pl.add_mesh(grid, color='w', smooth_shading=True, lighting=False)
pl.set_scale(1, 1, 1000)
pl.show()
```
![desktop 1_252](https://user-images.githubusercontent.com/11981631/97614874-1e7fe900-19e0-11eb-8dcd-e1826c53fff6.png)

Cool dataset!  You might need to wiggle the plotting window a little bit as soon as it displays (at least I needed to do that on Linux due to the high scaling).

We might consider adding auto-scaling the data for an isometric representation in 3 dimensions.

**Comment by akaszynski** [comment]
With colors and different lighting:

```py
pl = pv.Plotter()
# pl.enable_eye_dome_lighting()
pl.add_mesh(grid, color='w', smooth_shading=True, lighting=True,
            scalars=grid.points[:, 2])
pl.set_scale(1, 1, 1000)
pl.show()
```

![image](https://user-images.githubusercontent.com/11981631/97615136-87fff780-19e0-11eb-9bb2-332c9e087127.png)

**Comment by akaszynski** [comment]
Out of curiosity, would we be able to adapt this dataset for a pyvista example?  I really like these plots.  Also, what's the background of this data?  I'm guessing it's some sort of surface scan.

**Comment by dominicjtriana** [comment]
> Out of curiosity, would we be able to adapt this dataset for a pyvista example? I really like these plots. Also, what's the background of this data? I'm guessing it's some sort of surface scan.

Yes this is a surface scan but that's about as much as I should say.  I would ask that you please don't use this data specifically but I could take some data of a different surface if you would like...?    These features are in the 100's of microns and I could find something similar. Maybe like a circuit board or something?  Or would you rather have the repeating structure?

**Comment by dominicjtriana** [comment]
> pl = pv.Plotter()
> pl.enable_eye_dome_lighting()
> pl.add_mesh(grid, color='w', smooth_shading=True, lighting=False)
> pl.set_scale(1, 1, 1000)
> pl.show()

Thank you so much for you help akaszynski.  Seriously you saved me a ton of time.  Now that I have a working example this will be easier to learn about the library.

So what was wrong with our initial use of grid.show()?  Even after removing the missing data this method still didn't work.

**Comment by akaszynski** [comment]
> Maybe like a circuit board or something?

That would be even cooler.  We won't use the data your posted.



> So what was wrong with our initial use of grid.show()? Even after removing the missing data this method still didn't work.

`grid.plot()` works for me on my end, but because the data is over a few meters, a few millimetres of variation doesn't show up and the plot looks like nearly flat plane for me.

**Comment by dominicjtriana** [comment]
> > Maybe like a circuit board or something?
> 
> That would be even cooler. We won't use the data your posted.

I can't promise when it will happen but I will add it to my list!
> 
> > So what was wrong with our initial use of grid.show()? Even after removing the missing data this method still didn't work.
> 
> `grid.plot()` works for me on my end, but because the data is over a few meters, a few millimetres of variation doesn't show up and the plot looks like nearly flat plane for me.

Ah I see... the set_scale method took care of this.  I manually scaled the data and yes now grid.plot() works perfectly fine.

Ok last question what's the major difference between the two methods? (grid.plot() and pv.plotter())  It seems like grid.plot() might be a bit faster...

**Comment by akaszynski** [comment]
> Ok last question what's the major difference between the two methods? (grid.plot() and pv.plotter()) It seems like grid.plot() might be a bit faster...

`grid.plot` is just a convenience method that uses the `pv.Plotter` class "under the hood".  You're free to use either, but for more complex plots, you end up having to use `pv.Plotter` in order to plot several simultaneous meshes.

**Comment by dominicjtriana** [comment]
I guess I should close this issue.  Thanks again to akasynski and banesullivan.  You guys are good people.  I will shoot you guys a scan of something interesting for an example next month.
