### ISSUE TITLE
Plot show_axes not displaying

### ISSUE THREAD

**Issue by jpmorr** [pyvista/pyvista-support#280]
## Description
although show_axes is supposed to be enabled by default, no axes is ever shown on my plots. When adding the show_axes=True flag to any plot, no XYZ axes is shown on the plot. I've tried on many of the examples and get the same outcome. 

Is this the correct option for showing the XYZ global axis? It's incredibly important for identifying orientation in figures.

Could this be a computer specific problem? I'm running pyvista 0.26.1 and vtk 9.0.1.

## Example Data
Using the create uniform grid example and adding the show_axes=True flag, no XYZ axes is shown on the plot. 
````
import pyvista as pv
import numpy as np

###############################################################################
# Take a 3D NumPy array of data values that holds some spatial data where each
# axis corresponds to the XYZ cartesian axes. This example will create a
# :class:`pyvista.UniformGrid` object that will hold the spatial reference for
# a 3D grid which a 3D NumPy array of values can be plotted against.

###############################################################################
# Create the 3D NumPy array of spatially referenced data.
# This is spatially referenced such that the grid is 20 by 5 by 10
# (nx by ny by nz)
values = np.linspace(0, 10, 1000).reshape((20, 5, 10))
values.shape

# Create the spatial reference
grid = pv.UniformGrid()

# Set the grid dimensions: shape + 1 because we want to inject our values on
#   the CELL data
grid.dimensions = np.array(values.shape) + 1

# Edit the spatial reference
grid.origin = (100, 33, 55.6)  # The bottom left corner of the data set
grid.spacing = (1, 5, 2)  # These are the cell sizes along each axis

# Add the data values to the cell data
grid.cell_arrays["values"] = values.flatten(order="F")  # Flatten the array!

# Now plot the grid!
grid.plot(show_edges=True, show_axes=True)
````
Here's the output on my computer - No axes shown.
![image](https://user-images.githubusercontent.com/10863809/98109427-71044e00-1e95-11eb-951d-6756f5fd959c.png)

**Comment by akaszynski** [comment]
That's a strange bug, and I can't recreate it on my end in Linux with the same package versions.  Can you send off a `pyvista.Report()`?

**Comment by jpmorr** [comment]
@akaszynski  Yes, unusual. And I can't remember when it stopped working. See report below.

````
Wed Nov 04 15:39:22 2020 GMT Standard Time
OS	Windows	
CPU(s)	16	
Machine	AMD64
Architecture	64bit	
RAM	31.8 GB	
Environment	Jupyter
GPU Vendor	NVIDIA Corporation	
GPU Renderer	Quadro RTX 5000/PCIe/SSE2	
GPU Version	4.5.0 NVIDIA 452.39
Python 3.8.6 | packaged by conda-forge | (default, Oct 7 2020, 18:22:52) [MSC v.1916 64 bit (AMD64)]
pyvista	0.26.1	
vtk	9.0.1	
numpy	1.19.2
imageio	2.9.0	
appdirs	1.4.4	
scooby	0.5.6
meshio	4.3.3	
matplotlib	3.3.2	
pyvistaqt	0.2.0
PyQt5	5.12.3	
IPython	7.19.0	
colorcet	1.0.0
cmocean	2.0	
scipy	1.5.3	
tqdm	4.51.0
Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
````

**Comment by akaszynski** [comment]
Ah, I see.  You're on `jupyterlab` at the moment.  Axes won't display there right now.  We're working on an update that will allow you to see (and play) with the mesh within the jupyterlab environment just like as in a standard render window.

Disable the notebook plotting with `notebook=False` to plot outside the notebook for the moment until we get this fixed.

**Comment by jpmorr** [comment]
@akaszynski Ok, well technically I'm using a Python Interactive window on VS Code, which I guess is actually launching a `jupyterlab` interface. Anyway, the `notebook=False` brings back the axes.

**Comment by banesullivan** [comment]
Basically this isn't supported for any offscreen plotting at the moment. https://github.com/pyvista/pyvista/pull/824 will fix that which I have been meaning to update... will do soon here

**Comment by banesullivan** [comment]
This is originally posted as a bug in https://github.com/pyvista/pyvista/issues/285
