### ISSUE TITLE
Animate point cloud by iterating through files

### ISSUE THREAD

**Issue by Boorhin** [pyvista/pyvista-support#281]
## Description
I have a set of vtk legacy files that contain points and scalars. Each file corresponds to a timestep output from a model.
I am trying to make an animation from it but the last iteration doesn't disappear from the plot. So it crashes at some point. I tried to use the example of the brain slice and other methods from the doc, I cannot seem to find the right way.

## Example Data
A simplified version of the code I use. With a few files for testing
[part_000.zip](https://github.com/pyvista/pyvista-support/files/5489714/part_000.zip)
```python
import pyvista as pv
from pyvistaqt import BackgroundPlotter
import numpy as np
import glob

def newpts(f):
    upd= pv.read_legacy(f).glyph(geom=S)
    plotter.add_mesh(upd, scalars="Lices",cmap="autumn_r", annotations=annotations, clim=[1,2])
    plotter.write_frame()

l = sorted(glob.glob(*.vtk"))
plotter = BackgroundPlotter(show = True)
S = pv.Sphere(radius=350,theta_resolution =8, phi_resolution =8)
annotations = { 1: "type1",    2: "type2"}
plotter.open_gif('test.gif')
for f in l:
    newpts(f)

**Comment by banesullivan** [comment]
Something odd is happening here with the GIF... not sure what... but here is a working way to do it with MP4:

```py
import pyvista as pv
import numpy as np
import glob

l = sorted(glob.glob("*.vtk"))
S = pv.Sphere(radius=350, theta_resolution =8, phi_resolution =8)
annotations = { 1: "type1",    2: "type2"}

plotter = pv.Plotter(off_screen=True, notebook=False)
# Add an initial mesh that will update inplace
mesh = pv.read_legacy(l[0]).glyph(geom=S)
plotter.add_mesh(mesh, scalars="Lices", cmap="autumn_r", 
                 annotations=annotations, clim=[1,2])

plotter.camera_position = [(350546.5590681669, 6174776.859998149, 2830.6765611501532),
 (345638.890625, 6172737.25, 0.6100006103515625),
 (-0.5183546542851111, 0.06399391523345686, 0.8527679820408691)]

plotter.show(auto_close=False)

def newpts(f):
    upd = pv.read_legacy(f).glyph(geom=S)
    mesh.overwrite(upd)
    plotter.render()
    plotter.write_frame()

plotter.open_movie('test.mp4')
for f in l:
    newpts(f)
    
plotter.close()
```

**Comment by Boorhin** [comment]
Thanks a lot, very helpful!
So we cannot do it with the backgroundplotter (gives an error regarding image)
For some reason the colour of the scalar doesn't update 
Here the movie, at the end each sphere should be 2 (red)
[test.zip](https://github.com/pyvista/pyvista-support/files/5505382/test.zip)

**Comment by Boorhin** [comment]
Thanks a lot, very helpful!
So we cannot do it with the backgroundplotter (gives an error regarding image)
For some reason the colour of the scalar didn't update 
so I changed the function. It is strange that the plotter needs to be individually updated for scalar?
```python
def newpts(f):
    upd= pv.read_legacy(f).glyph(geom=S)
    mesh.overwrite(upd)
    plotter.update_scalars(upd.point_arrays["Lices"])
    plotter.render()
    plotter.write_frame()
