### ISSUE TITLE
Possibility to update plot with slider_widget in real time?

### ISSUE THREAD

**Issue by vpicouet** [pyvista/pyvista-support#283]
Hello,
when using a slider_widget,
is it possible to update the plot in real time when moving the slider (before releasing the click).
It seems that the callback function is only called when releasing the mouse (cf PyVista examples https://docs.pyvista.org/examples/03-widgets/slider-bar-widget.html?highlight=slider ), is it possible to change it like 
matplotlib did?
![unnamed](https://user-images.githubusercontent.com/37241971/98525820-4e997880-2279-11eb-87b5-c0afad71595c.gif)
Thanks for you help!

**Comment by banesullivan** [comment]
See the docs for the slider helper: https://docs.pyvista.org/plotting/widgets.html#pyvista.WidgetHelper.add_text_slider_widget

Change `event_type` to `'always'`

**Comment by vpicouet** [comment]
Thanks a lot,
sorry for not seeing that!

**Comment by TysonRayJones** [comment]
For future travellers; `event_type` became [`interaction_event`](https://github.com/pyvista/pyvista/blob/028b06d5be2cc36ff9e6ab8c302102344afabac2/pyvista/plotting/widgets.py#L1313)
