### ISSUE TITLE
Overlaying glyph or customize axes widget

### ISSUE THREAD

**Issue by T4mmi** [pyvista/pyvista-support#299]
Hi,
I'm looking to tweak the axis widget so it shows as a *North Arrow* 🧭 that always points to the "north".
Could you point me the direction to do that ?

**Comment by banesullivan** [comment]
There is a little known feature added in https://github.com/pyvista/pyvista/pull/702 to do this.

Simply load a north arrow or compass of your choice as a mesh and properly orient it, then pass it to `add_orientation_widget()`.

Here is an example using this north arrow I found: https://www.myminifactory.com/object/3d-print-north-arrow-2686

```py
import pyvista as pv
from pyvista import examples

mesh = examples.download_st_helens().warp_by_scalar()
compass = pv.read('north-arrow-1.stl')

p = pv.Plotter()
p.add_mesh(mesh)
p.add_orientation_widget(compass, color='maroon')
p.show()
```

![2020-11-20 13 52 01](https://user-images.githubusercontent.com/22067021/99848790-a36da680-2b37-11eb-8cd0-d54bf869e111.gif)

**Comment by T4mmi** [comment]
Wow that's exactly what I was looking for...
Thanks a lot, I missed it looking at QtInteractor doc :(

**Comment by banesullivan** [comment]
Do post a link to a better arrow/compass if you have one.

One thing this lacks is support for texture-mapped actors which we could add

**Comment by T4mmi** [comment]
![image](https://user-images.githubusercontent.com/6515799/99874610-b2ad2c80-2be9-11eb-8b5d-91b7d6cb6358.png)
I tried with the one from [Qgis2threejs](https://github.com/minorua/Qgis2threejs/blob/27cf42fa1955ebd32dd1adf050148b2ab476e530/js/Qgis2threejs.js#L823), looks great, thanks again.

```
import pyvista as pv
from pyvista import examples

mesh = examples.download_st_helens().warp_by_scalar()
compass = pv.PolyData(np.array([[-5,-10,0],[0,10,0],[0,-7,3],[5,-10,0]]),np.array([3,0,1,2,3,2,1,3]))

p = pv.Plotter()
p.add_mesh(mesh)
p.add_orientation_widget(compass, color="red") # a real nice addition would be to add scalars argument 
p.show()
```
