### ISSUE TITLE
Creating a support forum

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista-support#3]
Should we create a discourse forum to archive general use questions for PyVista?

I'm imagining something similar to VTK's: https://discourse.vtk.org

This would create a way to archive user questions and provide a place for new users to seek out community based help.

The slack channel has been filling this role, but it's not capable of being a support forum where questions can be searched

**Comment by banesullivan** [comment]
We need to add an issue template an screenshots on how to create a new issue

**Comment by akaszynski** [comment]
Agreed.  It would clean things up a bit on the main repo as well.  GitHub has great formatting and we could get people motivated to create a GitHub username and start contributing.
