### ISSUE TITLE
Tube from polydata with varying radius

### ISSUE THREAD

**Issue by shakasaki** [pyvista/pyvista-support#303]
**Feature request **

This is more of a feature request, if it does not already exist somewhere (I couldn't find it). 
Essentially I want to create a tube with varying radius. Creating a tube from polydata is quite straightforward 
[as is clearly explained here](https://docs.pyvista.org/examples/00-load/create-spline.html)
but this won't work with a varying radius. It would be quite handy to be able to give a radius list, that is the same size as the PolyData array, which would change the thickness accordingly.

Any hack-y solution to this would be also greatly appreciated. 

Thanks !

**Comment by akaszynski** [comment]
We should eventually add this as an example (unless we already have and I'm missing it).

**Comment by banesullivan** [comment]
I use the `add-to-gallery` tag to track what we should add to the examples down the road so we can still close issues

**Comment by shakasaki** [comment]
Awesome, I didn't spot that in the documentation. Would be useful to have it as an example.

So it works smoothly, and when I now save the Tube as a VTK object, paraview automatically uses the radius (stuff in the above example) to create a colormap. Is there a way to override this, and set a single RGB value for that? I don't see that as an option in the documentation. Anyhow, the primary question was answered, thanks again!

**Comment by banesullivan** [comment]
If you add an array to the point or cell data of the line/tube that has RGB components then ParaView can visualize that turning off the "Map Scalars" option

**Comment by banesullivan** [comment]
Or if you want a solid color, paraview handles that easily but these ParaView use questions get a bit out of scope for this forum. I'd head over to https://discourse.paraview.org

**Comment by shakasaki** [comment]
Thanks Bane !

**Comment by AlexanderJuestel** [comment]
Hey, this is exactly what we could need to display the results of well logs along the borehole path in the subsurface. We talked about that a while ago already I think. And great to see that others also need that :)

I could provide an example for that as well at some point :)

**Comment by shakasaki** [comment]
Hi Alexander, an example would be great! But displaying a full well log would be quite challenging right? Can pyvista handle that? 

What I mean is, a optical image of a well would have 360 RGB values for each step along the well (usually the image is taken at a 1 degree azimuthal resolution) and a spacing along the well of a few mm. 
So, at each point in the pyvista tube we would need to assign 360 RGB values, and at quite a high density along the tube. I agree that this would be great to have! :)

**Comment by AlexanderJuestel** [comment]
Hey, I was thinking more about well logs like gamma Ray or so. Depending on the data density you would also have to resample them but it definitely aid the visualization of the data

**Comment by banesullivan** [comment]
@shakasaki, PyVista can handle the image log data you mention... with some determination 😉 

If you have an example of publicly available data, I'd love to put together an example of how to visualize that!

**Comment by shakasaki** [comment]
Bane to the rescue, once again :)

I attach an excerpt of the logging data as an .npz file. The whole file is a bit too large (about half a GB) but this should do the trick for the example purpose! 

If you unpack the npz file you'll find three arrays inside:

```
arrays['depth'].shape
(25263,)

arrays['rgb_values'].shape
(25263, 360, 3)

arrays['borehole'].shape
(500, 3)
```

The depth is the borehole length along which the optical image is taken. The rgb_values are the image values (360 pixels -one per angle- and 3 unsigned integers per pixel) and the borehole array has the XYZ coordinates of the borehole trajectory (0.1m spacing, over 50m in total).

I use the following code (which of course you pointed out above) to get the trajectory to a PyVista tube:

```

    def tube_from_points(points, rad=0.1, radius_variations=False):
        polyline = pv.PolyData()
        polyline.points = points
        the_cell = np.arange(0, len(points), dtype=np.int_)
        the_cell = np.insert(the_cell, 0, len(points))
        polyline.lines = the_cell
        if(radius_variations):
            polyline['radius'] = rad
            tube = polyline.tube(scalars='radius')
        else:
            tube = polyline.tube(radius=rad)
        tube.plot(smooth_shading=True)
        return tube

```

with of course importing pyvista and numpy for this to work.

Your input and time is always greatly appreciated !

p.s. I had to zip the npz array in order to be able to upload it here.

[optv_data.zip](https://github.com/pyvista/pyvista-support/files/5599577/optv_data.zip)

**Comment by AlexanderJuestel** [comment]
> @shakasaki, PyVista can handle the image log data you mention... with some determination 😉 
> 
> If you have an example of publicly available data, I'd love to put together an example of how to visualize that!

@banesullivan

This has come to my attention again and I will see that I can find a dataset that I can provide for you, so that we can solve this. This would be a really nice feature to have in the future :)

Cheers Alex

**Comment by shakasaki** [comment]
@AlexanderJuestel would be great to have this running. Does the dataset I include above work? It is optical televiewer data in a numpy array format. I can also provide the last file, and representative borehole trajectories, but we could also use any trajectory (like the funky tube that @banesullivan made above). Would be happy to help here too!
