### ISSUE TITLE
Multi-Window plotting features

### ISSUE THREAD

**Issue by jacobgrasmick** [pyvista/pyvista-support#31]
I am working with the Multi-Window plotting and am wondering if it is possible to do a couple of things:

1) `set_scale`, `show_grid`, etc... applies to all windows (rather than having to define within each subplot).

2) 'Link' the camera between all windows so that zoom/pane applies to all windows simultaneously (when notebook=False)

Thanks!
JG

**Comment by banesullivan** [comment]
1. The first question is an interesting feature request and something I've definitely thought about - I also understand how cumbersome it can be to apply all those methods to each subplot so I'll see what I can do to implement this in the next release. In the meantime, you could define a helper function for all these common tasks across the subplots. For example:

```py
import pyvista as pv

def my_helper(p):
    p.set_scale(10, 2, 3)
    p.show_grid()

p = pv.Plotter(shape=(2,2)

p.subplot(0,0)
p.add_mesh(pv.Sphere())
my_helper()

p.subplot(0,1)
p.add_mesh(pv.Cone())
my_helper()

p.subplot(1,0)
p.add_mesh(pv.Cube())
my_helper()

p.subplot(1,1)
p.add_mesh(pv.Ellipsoid())
my_helper()

p.show()
```


-----

2. This is currently possible using the `.link_views()` method right before your `.show()` call (afters all the subplots are created). Check out these examples:
    - https://docs.pyvista.org/examples/02-plot/linked.html?highlight=link_views
    - https://docs.pyvista.org/examples/01-filter/decimate.html?highlight=link_views

**Comment by jacobgrasmick** [comment]
Awesome, thanks @banesullivan ! Apologies, I overlooked the ```.link_views()``` in the documentation...
