### ISSUE TITLE
Creating a collection of geometric objects without directly plotting (for exporting)

### ISSUE THREAD

**Issue by shakasaki** [pyvista/pyvista-support#310]
## Description

Hello, i'm trying to do something rather trivial but did not yet find the optimal way to do so. Basically, I want to plot a large (~10k) collection of lines. The lines have simply an endpoint and starting point.
I have numpy arrays with the coordinates of these points and my approach is to loop over the array and create lines. I initially create a mesh and add these lines to the mesh as I go.

Here is an example code:

```
import numpy as np
import pyvista as pv
from pyvistaqt import BackgroundPlotter

p = BackgroundPlotter()
n = 1000
point_a = np.random.random((n,3))
point_b = np.random.random((n,3))
for line in range(n):
    p.add_mesh(pv.Line(point_a[line,:],point_b[line,:]))
```

This works (slowly) up to about n=1000 (attached picture). But for larger n's it crashes, at least on my laptop. I'm sure pyvista can handle the actual final graphic, but its only the implementation that causes it to crash (looping and plotting each line individually).

What's the best way to do this? I do not want a separate entry for each line, which I assume is what is killing the implementation. The lines can be all lumped together in one mesh to begin with. I simply want to export the final figure for later use!

Thanks for the feedback

![100_lines](https://user-images.githubusercontent.com/7264182/100761516-4bfeee80-33f3-11eb-98c8-63a4a65855d8.png)

**Comment by akaszynski** [comment]
The best solution is to create one mesh containing all the individual lines rather than adding each line to the plotter class.

```py
import numpy as np
import pyvista as pv

n = 1000
point_a = np.random.random((n,3))
point_b = np.random.random((n,3))

points = np.vstack((point_a, point_b))

# Define lines based on the points where: each line is the number of
# points in the line followed by the indices of the line for example,
# the first two lines in the lines array are [2, 0, 1000, 2, 1, 1001]
#
# This will change based on the ordering of points, I'm just extending
# your example, so I'll use your initial order.  There's a more
# efficient way of doing this.
#
lines = np.vstack((np.ones(n)*2,
                   np.arange(n),
                   np.arange(n, n*2))).astype(np.int32).T.ravel()

# create a mesh composed of the lines above
pd = pv.PolyData()
pd.lines = lines
pd.points = points

rand_scal = np.random.random(n)
pv.plot(pd, scalars=rand_scal)
```

![image](https://user-images.githubusercontent.com/11981631/100786043-cb2dfb80-33ce-11eb-89e4-52e6756c6cf1.png)

**Comment by AlexanderJuestel** [comment]
Hey, 

thanks for the example. I have done some tasks the same way as @shakasaki before by looping through a list of NumPy arrays and plotting lines from it. How could this code be extended to fit lines with a variable length/number of vertices for each line?

I tried replacing the code for `lines` with the number of lengths of my lines but it brakes when trying to inspect `pd`. I had no issue creating the points array.

Here, `vertices_list` is a list of lists containing a varying number of vertices per line.

```
lengths = [len(i) for i in vertices_list]

lines = np.vstack((lengths,
                   np.arange(len(lengths)),
                   np.arange(len(lengths), len(lengths)*2))).astype(np.int32).T.ravel()
```

**Comment by shakasaki** [comment]
@akaszynski thanks, the rendering speed of you solution is impressive!

**Comment by akaszynski** [comment]
@AlexanderJuestel,

You can describe a variable number of points per line with:
```py
lines = np.hstack(([4, 0, 1, 2, 3], [5, 9, 8, 7, 6, 5]))  # etc.
```

I'd avoid looping if possible as loops within python are slow, but if you have to loop, loop through a bunch of lists and then assemble it at the end using `hstack`.

**Comment by AlexanderJuestel** [comment]
Hey @akaszynski, 

I do not understand what you are doing with `lines`. So you say for the first element that '4' is the number of points and '0-3' are the indices? 

And the same for the '5' then and 5 integers after that?

**Comment by akaszynski** [comment]
> I do not understand what you are doing with `lines`. So you say for the first element that '4' is the number of points and '0-3' are the indices?
> 
> And the same for the '5' then and 5 integers after that?

Exactly.  Indexing within VTK is done based on "walking through" a flat list of indices with a header in front of each entity that describes the number of points composing the entity.  There's some additional documentation describing this at [Creating an Unstructured Grid](https://docs.pyvista.org/examples/00-load/create-unstructured-surface.html#creating-an-unstructured-grid).

**Comment by AlexanderJuestel** [comment]
That is very interesting. Thanks for the reference. Then I will try it that way ;)

**Comment by endarthur** [comment]
By discussing the issue with @AlexanderJuestel , we came with this as a general solution:

```
# Creating array of points
points = np.vstack(vertices_list)
# Create list with number of vertices per points and indices per lines
lines = []
start = 0
for element in vertices_list:
    lines.extend([len(element), *range(start, start + len(element))])
    start += len(element)
# Creating PyVista PolyData containing the lines and vertices
poly = pv.PolyData()
poly.lines = lines
poly.points = points
```
I still think that there's a more elegant way somewhere, but at least this works. Thanks for the explanations as well!
