### ISSUE TITLE
creating a collection of geometric objects and plotting several disks

### ISSUE THREAD

**Issue by shakasaki** [pyvista/pyvista-support#315]
## Description

Hello again! This time i'm trying to create a pyvista collection of geometric objects. I have two questions:

What's the best way to group geometric objects, like spheres or disks, together? Right now I'm simply looping over the objects and adding them to a mesh like so:

```
import pyvista as pv
import numpy as np
p = pv.Plotter()
centers = np.random.randn(10,3)
for cen in centers:
    p.add_mesh(pv.Sphere(radius=0.1,center=(cen)))
p.show()
```
This works but is there a way to group these objects into a structure that is not the plotter? To save as a VTK file later, but not visualize on the go?

Which brings me to the second question:

When I try to create a group of disks instead of spheres, it does not work. Only the last disk shows in the graphic. So unlike the example above (which works) this one does not:

```
import pyvista as pv
import numpy as np
p = pv.Plotter()
centers = np.random.randn(10,3)
for cen in centers:
    p.add_mesh(pv.Disc(center=(cen), inner=0., outer=0.1, normal=(cen), r_res=1, c_res=6))
p.show()
```
Any clue what's going wrong?

Thanks for the feedback!

**Comment by shakasaki** [comment]
I have a follow up on this and a hacky solution. It seems that pv.Disc does not honor the center and normal inputs.

While a sphere shifted along the z-axis turns out fine:

`pv.Sphere(center=([0,0,10]))
Out[91]: 
PolyData (0x7f01402e0980)
  N Cells:	1680
  N Points:	842
  X Bounds:	-4.993e-01, 4.993e-01
  Y Bounds:	-4.965e-01, 4.965e-01
  Z Bounds:	9.500e+00, 1.050e+01
  N Arrays:	1`


When a disk is created, it does not really inherit the correct coordinates:

`pv.Disc(center=([0,0,10]), inner=0., outer=1, normal=([0,0,1]), r_res=1, c_res=6)
Out[89]: 
PolyData (0x7f01402b8a60)
  N Cells:	6
  N Points:	12
  X Bounds:	-1.000e+00, 1.000e+00
  Y Bounds:	-8.660e-01, 8.660e-01
  Z Bounds:	0.000e+00, 0.000e+00
  N Arrays:	0`


Looking at the source code, it seems that the translation is missing for the disk object while it is there for the Sphere and other geometries (For pyvista version 0.26.1 lines 502-537 (Disk) and 237-290 (Sphere) in pyvista -> utilities ->geometric_objects.py)

I managed to get it to work by changing 
```
    src = vtk.vtkDiskSource()
    src.SetInnerRadius(inner)
    src.SetOuterRadius(outer)
    src.SetRadialResolution(r_res)
    src.SetCircumferentialResolution(c_res)
    src.Update()
    return pyvista.wrap(src.GetOutput())
```

to
```

    src = vtk.vtkDiskSource()
    src.SetInnerRadius(inner)
    src.SetOuterRadius(outer)
    src.SetRadialResolution(r_res)
    src.SetCircumferentialResolution(c_res)
    src.Update()
    surf = pyvista.PolyData(src.GetOutput())
    surf.rotate_y(-90)
    translate(surf, center, normal)
    return surf
```
 
but it would be nice to have your input on that as well.

Cheers
alexis

**Comment by akaszynski** [comment]
Thanks for pointing this out @shakasaki.  Would you mind submitting a PR for this fix as this should be corrected in our source?  I also don't think the `rotate_y` is necessary in this case, but we need a test to verify this.

**Comment by shakasaki** [comment]
hi @akaszynski, I was about to submit a pull release when I realized that this is already fixed in a newer version of pyvista. Here's the output for the current version

```
import pyvista as pv
from pyvistaqt import BackgroundPlotter
p = BackgroundPlotter()
p.add_mesh(pv.Disc(center=(0,0,0), inner=0., outer=1, normal=(1,0,0), r_res=1, c_res=6), color='red')
p.add_mesh(pv.Disc(center=(0,0,0), inner=0., outer=1, normal=(0,1,0), r_res=1, c_res=6), color='green')
p.add_mesh(pv.Disc(center=(0,0,0), inner=0., outer=1, normal=(0,0,1), r_res=1, c_res=6), color='blue')

```

![disks](https://user-images.githubusercontent.com/7264182/102457697-72539980-4043-11eb-9fcc-87f58018b894.png)



```

pv.__version__
Out[1]: '0.27.4'
```

**Comment by shakasaki** [comment]
Actually, I just noticed that the new version of pyvista rotates correctly, but does not translate correctly. That is, the disks are not placed according to their center. Here's one example:

```
import pyvista as pv
from pyvistaqt import BackgroundPlotter
p = BackgroundPlotter()
disk1 = pv.Disc(center=(0,0,10), inner=0., outer=1, normal=(0,0,1), r_res=1, c_res=6)
p.add_mesh(disk1, color='red')
disk2 = pv.Disc(center=(0,0,0), inner=0., outer=1, normal=(0,0,1), r_res=1, c_res=6)
p.add_mesh(disk2, color='green')

disk1
Out[40]: 
PolyData (0x7ff6531d7a00)
  N Cells:	6
  N Points:	12
  X Bounds:	-1.000e+00, 1.000e+00
  Y Bounds:	-8.660e-01, 8.660e-01
  Z Bounds:	0.000e+00, 0.000e+00
  N Arrays:	0

disk2
Out[41]: 
PolyData (0x7ff6531d7b20)
  N Cells:	6
  N Points:	12
  X Bounds:	-1.000e+00, 1.000e+00
  Y Bounds:	-8.660e-01, 8.660e-01
  Z Bounds:	0.000e+00, 0.000e+00
```

These two disks plot identically one on top of the other, even though they should be 10 units apart along the vertical. 

I could not figure out why this happens, as the source code seems to apply the transform twice:

`    transform = vtk.vtkTransform()
    transform.Translate(-center)
    transform.RotateWXYZ(angle, axis)
    transform.Translate(center)
`

**Comment by shakasaki** [comment]
Yep, sorry for the back and forths.

So finally the existing code only works if the disk is centered at (0,0,0)

Then the rotation works. If you suggest a different center, the rotation doesn't work. I applied the same fix as suggested above, that is:

`def Disc(center=(0.,0.,0.), inner=0.25, outer=0.5, normal=(0,0,1), r_res=1,
         c_res=6):
    """Create a polygonal disk with a hole in the center.

    The disk has zero height. The user can specify the inner and outer radius
    of the disk, and the radial and circumferential resolution of the polygonal
    representation.

    Parameters
    ----------
    center : np.ndarray or list
        Center in [x, y, z]. middle of the axis of the disc.

    inner : float
        The inner radius

    outer : float
        The outer radius

    normal : np.ndarray or list
        direction vector in [x, y, z]. orientation vector of the cone.

    r_res: int
        number of points in radius direction.

    r_res: int
        number of points in circumferential direction.

    """
    src = vtk.vtkDiskSource()
    src.SetInnerRadius(inner)
    src.SetOuterRadius(outer)
    src.SetRadialResolution(r_res)
    src.SetCircumferentialResolution(c_res)
    src.Update()
    normal = np.array(normal)
    center = np.array(center)
    surf = pyvista.PolyData(src.GetOutput())
    surf.rotate_y(-90)
    translate(surf, center, normal)
    return surf`


The rotation around y seems to be necessary because the translate function assumes objects oriented along x, and the disk is oriented along z.

Here's a test:

```
import pyvista as pv
from pyvistaqt import BackgroundPlotter
p = BackgroundPlotter()
p.add_mesh(pv.Disc(center=(0,0,0), inner=0., outer=1, normal=(1,0,0), r_res=1, c_res=6), color='red')
p.add_mesh(pv.Disc(center=(0,0,0), inner=0., outer=1, normal=(0,1,0), r_res=1, c_res=6), color='green')
p.add_mesh(pv.Disc(center=(0,0,0), inner=0., outer=1, normal=(0,0,1), r_res=1, c_res=6), color='blue')

```
![disk_example_1](https://user-images.githubusercontent.com/7264182/102465319-cf544d00-404d-11eb-87fd-9bf2889d335b.png)






```

import pyvista as pv
from pyvistaqt import BackgroundPlotter
p = BackgroundPlotter()
p.add_mesh(pv.Disc(center=(0,0,1), inner=0., outer=1, normal=(1,0,0), r_res=1, c_res=6), color='red')
p.add_mesh(pv.Disc(center=(0,1,0), inner=0., outer=1, normal=(0,1,0), r_res=1, c_res=6), color='green')
p.add_mesh(pv.Disc(center=(1,0,0), inner=0., outer=1, normal=(0,0,1), r_res=1, c_res=6), color='blue')

```

![disk_example_2](https://user-images.githubusercontent.com/7264182/102465337-d4190100-404d-11eb-8b50-d36027958c0c.png)


I'll submit the pull release today ;)
