### ISSUE TITLE
Creating 2D outline/convex hull of 3D object 

### ISSUE THREAD

**Issue by PeterBetlem** [pyvista/pyvista-support#316]
## Description

Problem at hand is the following: 
We have a bunch of 3D digital outcrop models of which the outline needs to be projected onto the XY plane.

No problem with getting the projection - thanks for the tutorial on that one :) - but having some issues with generating an outline for the models - preferably as a shapely polygon. (see below)

![image](https://user-images.githubusercontent.com/28719452/101775607-0677ab00-3af0-11eb-95b5-8a7741244664.png)

Any suggestions?

## Example Data

Example data for the model in question below:

[FortetSouthSvalbox.zip](https://github.com/pyvista/pyvista-support/files/5672916/FortetSouthSvalbox.zip)

<--
It greatly helps us address your question if you have example data for us
to work with - if your question does not require a dataset for an example,
please ignore this section
-->

**Comment by PeterBetlem** [comment]
For those running into a similar issue, below a solution that manages the above roughly:
```
from rasterio import transform
from rasterio.features import shapes
from shapely.geometry import Polygon, MultiPolygon
import pyvista as pv

model = pv.read(Path(self.cfg["data"]["data_path"],
             self.cfg["data"]["model_file"]))
zi, yi, xi = np.histogram2d(model.points[:,1], model.points[:,0], bins=(50,50), weights=model.points[:,2], normed=False)
zi[zi>0] = 1
poly = gpd.GeoDataFrame(crs="EPSG:32633")

bounds = (model.points[:,0].min(),
          model.points[:,1].max(),
          model.points[:,0].max(), # Looks weird, but is needed to have the shapes right sight up ;)
          model.points[:,1].min())
          
tform = transform.from_bounds(*bounds,50,50)

for shape, value in shapes(zi.reshape((50,50)).astype(int), transform = tform):
     edges = shape['coordinates'][0].copy()
     d = {'val': [value], 'geometry': [Polygon(edges)]}
     poly_row = gpd.GeoDataFrame(d, crs="EPSG:32633")
     poly = poly.append(poly_row, ignore_index=True)

poly = poly[poly.val>0]

poly.plot()

MultiPoly = MultiPolygon([p for p in poly.geometry])
d = {'val': 1, 'geometry': MultiPoly}

multipoly = gpd.GeoDataFrame(d, crs="EPSG:32633")
multipoly = multipoly.dissolve(by='val')
self.gdf_bounds["shape"] = multipoly.iloc[0].geometry
```

**Comment by larsoner** [comment]
Maybe you could also try [`vtkPolyDataSilhouette`](https://vtk.org/doc/nightly/html/classvtkPolyDataSilhouette.html), e.g.:

https://github.com/mne-tools/mne-python/blob/e2357ad7848a3c3968678557ef5ded4602bed0c8/mne/viz/_brain/_brain.py#L1897-L1904

It can be a bit hit or miss, though.
