### ISSUE TITLE
Trouble with opacity and UniformGrid

### ISSUE THREAD

**Issue by AndreEbel** [pyvista/pyvista-support#318]
## Description

I try to plot 3d numpy arrays with Pyvista 0.27.4. and i have trouble with opacity settings. The cell values are only rendered on the boundary surfaces of the mesh. If all the outter cells of the mesh are nans with opacity 0, nothing is rendered. 

## Example Data

Two very short examples: 

```
import numpy as np 
import pyvista as pv

cube = np.ones((10,10,10), dtype=np.float32)
cube[0,:,:]= np.nan
cube[5,:,:]= np.nan
cube[:,0,:]= np.nan
cube[:,2,:]= np.nan
cube[:,6,:]= np.nan
cube[:,:,0]= np.nan
cube[:,:,4]= np.nan

grid = pv.UniformGrid()
grid.dimensions = np.array(cube.shape) + 1
grid.origin = (0, 0, 0)  # The bottom left corner of the data set
grid.spacing = (1, 1, 1)  # These are the cell sizes along each axis
grid.cell_arrays['values'] = cube.flatten(order="F")  # Flatten the array!

p = pv.Plotter()
p.add_mesh(grid,scalars='values', show_edges=True, nan_opacity=0)
p.show()
```

The result : 

![plot](https://user-images.githubusercontent.com/62537359/102355169-c90d9480-3fab-11eb-8642-b44b6cf81d4a.png)

```
cube = np.ones((10,10,10), dtype=np.float32)
cube[0,:,:]= np.nan
cube[-1,:,:]= np.nan

cube[:,0,:]= np.nan
cube[:,-1,:]= np.nan

cube[:,:,0]= np.nan
cube[:,:,-1]= np.nan

grid = pv.UniformGrid()
grid.dimensions = np.array(cube.shape) + 1
grid.origin = (0, 0, 0)  # The bottom left corner of the data set
grid.spacing = (1, 1, 1)  # These are the cell sizes along each axis
grid.cell_arrays['values'] = cube.flatten(order="F")  # Flatten the array!

p = pv.Plotter()
p.add_mesh(grid,scalars='values', show_edges=True, nan_opacity=0)
p.show()
```

result: 

![emptycube](https://user-images.githubusercontent.com/62537359/102356199-32da6e00-3fad-11eb-8b77-43d489bedf56.png)

Any idea about what is wrong?

Thanks !

**Comment by banesullivan** [comment]
When using the `add_mesh` method it only renders the outer surface of the mesh. For uniform grids, you can use `add_volume` to perform volume rendering.

See https://docs.pyvista.org/examples/02-plot/volume.html#sphx-glr-examples-02-plot-volume-py

**Comment by AndreEbel** [comment]
Ok, thanks for your time, the answer was in front of my nose....

I tried with add_volume but it converts cell data to point data and the rendering with the 'smart' mapper is ok. 

I read in the add_volume code the following sentence : 

> place all data on the nodes as issues arise when volume rendering on the cells

why is that ? (just for my own understanding)

**Comment by banesullivan** [comment]
> why is that ? (just for my own understanding)

Honestly, I'm not sure/I can't remember why that is the case. I worked through a lot of issues when implementing much of the volume rendering code in PyVista and simply found there to be issues with the mapper without a good explanation at the time.

Apologies for the delayed response... I am going through and attempting to resolve stale issues
