### ISSUE TITLE
When will the explicit structured grid be available?

### ISSUE THREAD

**Issue by rodrigomologni** [pyvista/pyvista-support#319]
Hi, Team!

I've been working with visualization of reservoir models. PyVista is making my job a lot easier. Thank you so much! ❤️

I'd love to use `vtkExplicitStructuredGrid` class within the PyVista because these models are corner-point grids. Do you intend to include this class in the package? Say yes, please! :pray::grin:

Best regards,

**Comment by akaszynski** [comment]
> I'd love to use `vtkExplicitStructuredGrid` class within the PyVista because these models are corner-point grids. Do you intend to include this class in the package? Say yes, please!

We can add that to our (growing) to-do list, but I can't give you a specific time frame for when it will be completed.  The `pyvista` project is 100% supported by the community with no commercial support at the moment and the core developers all have day jobs, so I can't make any guarantees on when it will be added.

If you'd like, please feel free to submit a PR to add this feature.  If you need help getting started, see pyvista's contributing [guidelines](https://docs.pyvista.org/extras/developer_notes.html).  We'd really appreciate any contributions!

**Comment by rodrigomologni** [comment]
Hi @akaszynski! Thanks for answering me. I understand perfectly. I will try to include it as an task in my work. 😉

**Comment by rodrigomologni** [comment]
Hi @akaszynski and @banesullivan!

I written the classes `ExplicitStructuredGrid` and `ExplicitStructuredGridFilters`: https://github.com/rodrigomologni/pyvista/commit/08606fb55f1ec81768257e1115ca218826065217

```python
import numpy as np
import pyvista as pv

# Loads pre-processed data from a reservoir grid
reservoir = np.load('reservoir.npz')
dims = reservoir['arr_0']
points = reservoir['arr_1']
cells = reservoir['arr_2']
blank_cells = reservoir['arr_3']
blank_cells = np.argwhere(blank_cells == 0)

grid = pv.ExplicitStructuredGrid(dims, points, cells)
grid.hide_cells(blank_cells)
grid.plot(color='w', show_edges=True, lighting=False, show_bounds=True)
```

![image](https://user-images.githubusercontent.com/1608652/102728078-73691d00-4308-11eb-8bb5-94e66bf09108.png)

**Comment by banesullivan** [comment]
@rodrigomologni, could you link `reservoir.npz`? I'd like to make an example of this

**Comment by rodrigomologni** [comment]
Hi @banesullivan! 

The same dataset in VTU format: [UNISIM-II-D.zip](https://github.com/pyvista/pyvista-support/files/6328286/UNISIM-II-D.zip). This dataset is the [UNISIM-II-D](https://www.unisim.cepetro.unicamp.br/benchmarks/en/unisim-ii/unisim-ii-d) reservoir model.

```python
import pyvista as pv

grid = pv.ExplicitStructuredGrid('UNISIM-II-D-BO.vtu')
# grid.show_cells()
grid.plot(color='w', show_edges=True, lighting=False, show_bounds=True)
```
![image](https://user-images.githubusercontent.com/1608652/115093585-406b1a80-9ef1-11eb-9989-2c85ed8fac49.png)

**Comment by banesullivan** [comment]
Thanks!! I hope it's okay to reshape that dataset?

**Comment by rodrigomologni** [comment]
Just reference the [UNISIM](https://www.unisim.cepetro.unicamp.br/) research group and the [SOLPE](https://www.solpe.com.br/) company, please. You can use (and modify) this file if you prefer: [references.md](https://github.com/pyvista/pyvista-support/files/6328396/references.md).
