### ISSUE TITLE
SEG-Y viewer

### ISSUE THREAD

**Issue by gsakkis** [pyvista/pyvista-support#320]
Hi, I discovered PyVista and PVGeo recently and I was wondering if/how I can use them to create a simple viewer for interactive seismic volume rendering in a Jupyter notebook, something like [this](https://blog.kitware.com/new-segy-reader/) or [this](https://webviz-subsurface-example.azurewebsites.net/seg-y-viewer). My experience in (especially 3D) visualization (and geophysics for that matter) is minimal so any pointers to examples I can use as a starting point, or even better, any existing project that has done this already, would be great.

**Comment by gsakkis** [comment]
Hi Bane, thanks for referencing the related issues. Did you have the chance to look into it? Any help would be much appreciated.

**Comment by GGDRriedel** [comment]
This is pretty straightforwar with the SEGYIO package from equinor .


There is also this REALLY great talk from 2014 here: 
https://www.youtube.com/watch?v=PFOd01fqcyQ

The visualization uses mayavi as a tool which was a bit of a hassle to set up but works SUPERBLY
