### ISSUE TITLE
add_mesh_clip_plane for pv.MultiBlock objects

### ISSUE THREAD

**Issue by AlexanderJuestel** [pyvista/pyvista-support#324]
## Description
When creating a geological model, we are getting several meshes representing the different geological surfaces. I would now like to use `add_mesh_clip_plane` to "scroll" through my model but I want to clip all meshes at once. 

![image](https://user-images.githubusercontent.com/45469915/102996663-c965dc80-4523-11eb-9119-08b9788cb9ec.png)

## Example Data
I added some sample data. 

I have tried the following so far:

```ruby
import pyvista as pv

mesh1 = pv.read(file_path + 'mesh1.vtk')
mesh2 = pv.read(file_path + 'mesh2.vtk')

meshes = pv.MultiBlock([mesh1, mesh2])

p = pv.Plotter(notebook=False)

p.add_mesh_clip_plane(meshes)

p.set_background('white')
p.show_grid(color='black')
p.show()

```

However, I get the following error:

```ruby
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-9ad0564c994e> in <module>
      1 p = pv.Plotter(notebook=False)
      2 
----> 3 p.add_mesh_clip_plane(meshes)
      4 
      5 p.set_background('white')

~\Anaconda3\envs\test_gempy\lib\site-packages\pyvista\plotting\widgets.py in add_mesh_clip_plane(self, mesh, normal, invert, widget_color, value, assign_to_axis, tubing, origin_translation, outline_translation, implicit, **kwargs)
    382         rng = mesh.get_data_range(kwargs.get('scalars', None))
    383         kwargs.setdefault('clim', kwargs.pop('rng', rng))
--> 384         mesh.set_active_scalars(kwargs.get('scalars', mesh.active_scalars_name))
    385 
    386         self.add_mesh(mesh.outline(), name=name+"outline", opacity=0.0)

AttributeError: 'MultiBlock' object has no attribute 'set_active_scalars'
```

So I guess that `add_mesh_clip_plane` is not suitable for multiple meshes right now :) 

[mesh1.zip](https://github.com/pyvista/pyvista-support/files/5734220/mesh1.zip)

**Comment by banesullivan** [comment]
> So I guess that add_mesh_clip_plane is not suitable for multiple meshes right now :)

That is correct. The best solution for this would be to merge all the blocks in the `MultiBlock` dataset to a single mesh before clipping interactively. e.g. [`combine()`](https://docs.pyvista.org/core/filters.html?highlight=combine#pyvista.CompositeFilters.combine) or [`merge()`](https://docs.pyvista.org/core/filters.html?highlight=combine#pyvista.DataSetFilters.merge)

```py
meshes = pv.MultiBlock([mesh1, mesh2]).combine()
```

or

```py
meshes = mesh1 + mesh2
```

HTH

Apologies for the slow response, I am trying to go through and resolve stale issues. Please re-open/re-comment if you still have a question for this topic
