### ISSUE TITLE
Calculate layer thickness to calculate temperature at depth

### ISSUE THREAD

**Issue by AlexanderJuestel** [pyvista/pyvista-support#325]
## Description

Hello, 
I would like to calculate the thickness of a GemPy layer down from the topography. I have the vertices and faces for the layer and can easily create a PolyData object. For the topography, I have the x, y and z values from which I can create both, a StructuredGrid and a PolyData object with no issues. 

I was able to calculate the thicknesses for layers that are returned by GemPy using this example here: https://docs.pyvista.org/examples/01-filter/distance-between-surfaces.html#sphx-glr-examples-01-filter-distance-between-surfaces-py

However, it does not work with the topography data. For the StructuredGrid, I am getting the error `AttributeError: 'StructuredGrid' object has no attribute 'ray_trace'` and for the PolyData it returns an array with only NaN values...

It is necessary to get the thickness of so that we can calculate temperature at depth for geothermal applications. 

Brown: Topography (as structured grid), blue and red: model layers
![image](https://user-images.githubusercontent.com/45469915/102995823-25c7fc80-4522-11eb-9f6a-a6232a1db34d.png)

## Example Data

I have attached the meshes and the topo array retrieved from GemPy

(geo_model._grid.topography.values = topo.npy)

```ruby
import pyvista as pv

mesh1 = pv.read('mesh1.vtk')

grid = pv.StructuredGrid(geo_model._grid.topography.values[:,0], geo_model._grid.topography.values[:,1], geo_model._grid.topography.values[:,2])

surf = pv.PolyData(geo_model._grid.topography.values)


# Calculating thickness
base_surface = mesh1

top_surface = surf

base_surface_normals = base_surface.compute_normals(point_normals=True,
                                                    cell_normals=False,
                                                    auto_orient_normals=True)

# Travel along normals to the other surface and compute the thickness on each vector
base_surface_normals["Thickness [m]"] = np.empty(base_surface.n_points)
for i in range(base_surface_normals.n_points):
    p = base_surface_normals.points[i]
    vec = base_surface_normals["Normals"][i] * base_surface_normals.length
    p0 = p - vec
    p1 = p + vec
    ip, ic = top_surface.ray_trace(p0, p1, first_point=True)
    dist = np.sqrt(np.sum((ip - p) ** 2))
    base_surface_normals["Thickness [m]"][i] = dist

# Replace zeros with nans
mask = base_surface_normals["Thickness [m]"] == 0
base_surface_normals["Thickness [m]"][mask] = np.nan

```

![image](https://user-images.githubusercontent.com/45469915/102996336-3fb60f00-4523-11eb-8242-421f7c5f0ac9.png)

[mesh1.zip](https://github.com/pyvista/pyvista-support/files/5735113/mesh1.zip)

**Comment by AlexanderJuestel** [comment]
Happy New Year guys, 

any chance you have some tips for me on that here? 

Cheers Alex

**Comment by AlexanderJuestel** [comment]
@endarthur and I figured it out using simple rasterio methods and numpy arrays :) 

You just extract the x and y coordinates from the vertices of the subsurface meshes, sample the topography at these x and y points using the rasterio sample functions and then substracting the z values of the vertices from the topography and voila, you got the vertical height difference. Plotting was done in PyVista of course. I also had to apply a threshold to filter out vertices that were located above the topography (artifact from the mesh building process). 

A first result is shown below. The temperatures at the edges of the layers where it is outcropping is 10 degrees (average surface temperature) but the temperature is the highest in the center where the layer is the thickest. You can then just apply an average geothermal gradient or the thermal conductivity of your lithological unit to calculate the temperature at depth :) 

So closing this for now :)

![image](https://user-images.githubusercontent.com/45469915/103454937-dd11ff80-4ce8-11eb-9997-982f9cec1d0f.png)

**Comment by akaszynski** [comment]
Nicely done!  Thanks for posting your solution here.
