### ISSUE TITLE
Add multiple thresholds or sliders in one plot at once

### ISSUE THREAD

**Issue by laserman781** [pyvista/pyvista-support#33]
Is it possible to add multiple sliders/multiples thresholds at once?

In #32, I was shown how to clip several meshes by combining them. I have points and line segments, from there I have a threshold for the closest points to the lines. I also have a clip slider for the elevation.

The goal is to try and have a threshold for the elevation of the point and the line individually and for the shortest distance in one plot. Is this possible?

**Comment by banesullivan** [comment]
I'm a bit confused on what exactly you want to do... could you provide data files for this?

Do you want to have a slider/widget to both clip the merged mesh and a slider/widget to threshold that same mesh by a scalar array? or do you want to threshold the clipped mesh?

**Comment by laserman781** [comment]
See below:

---------- Forwarded message ---------
From: Quade Howald <quade.howald@gmail.com>
Date: Mon, 29 Jul 2019 at 20:46
Subject: Fwd: [pyvista/pyvista-support] Add multiple thresholds or sliders
in one plot at once (#33)
To: <chrsulli@mines.edu>

Good evening,

I don't really want to share any datafiles, but if it might help solve the
problem I'd prefer to not have them available to everyone online, let me
know. But to answer your question:

I'm a bit confused on what exactly you want to do... could you provide data
files for this?

Do you want to have a slider/widget to both clip the merged mesh and a
slider/widget to threshold that same mesh by a scalar array? or do you want
to threshold the clipped mesh?


I determined that it would be better for me to have a separate slider for
the line elevation and the point elevation, rather than merging the meshes.
If this can't be done the I really just want to have the threshold for the
shortest distance and for the elevation. I just have no clue how to include
multiple sliders/thersholds in one plot.

This is what it would look like:
 I couldn't get the different colors to work, but here I have the shortest
distance set to a certain maximum value and it is all cut at a certain
elevation.
[image: image.png]


Does this clarify the question a little bit?

Thank you so much for your help,

---------- Forwarded message ---------

**Comment by laserman781** [comment]
I would prefer not to share any datafiles, but if it might help solve the problem I'd prefer to not have them available to everyone online, let me know. But to answer your question:

I determined that it would be better for me to have a separate slider for the line elevation and the point elevation, rather than merging the meshes. If this can't be done then I really just want to have the threshold for the shortest distance and for the elevation. I just have no clue how to include multiple sliders/thresholds in one plot.
