### ISSUE TITLE
ray_trace is inaccurate

### ISSUE THREAD

**Issue by dbodily1** [pyvista/pyvista-support#331]
I find that when I call ray_trace on a mesh, then pull the point information using vtk numpy support, then plot widgets at the points of the cell that ray_trace returns, that the resulting triangle is NOT triangle the ray actually intersects.  Instead it's usually the adjacent or slightly near the triangle being intersected.   In general it doesn't seem like ray_trace is very accurate.

My Code Below - Use any stl to replicate.  Does anyone else have this issue?

![image](https://user-images.githubusercontent.com/9097953/103418135-f84b0680-4b52-11eb-9121-638f1071d4f2.png)

############################################
import numpy as np
import pyvista as pv
import os
from vtk.util import numpy_support as ns

p = pv.Plotter()
start = [-.24, .43, .8]
stop = [-.27,.33,-.5]

f_loc = os.path.dirname(os.path.abspath(__file__))
mesh_path = f_loc+"/default_meshes/part.stl"
mystl = pv.read(mesh_path)
mystl.points*=10
p.add_mesh(mystl,color=np.array([.8,.8,1]))
points, ind = mystl.ray_trace(start, stop,first_point=True)
ray = pv.Line(start, stop)
pts = ns.vtk_to_numpy(mystl.GetCell(ind).GetPoints().GetData())
print(pts)
intersection = pv.PolyData(points)

for pt in pts:
   p.add_sphere_widget(callback=None, center=pt, color="green", radius=.01, pass_widget=True,selected_color = 'green',test_callback=False)
p.add_sphere_widget(callback=None, center=points, color="red", radius=.01, pass_widget=True,selected_color = 'green',test_callback=False)

p.add_mesh(mystl,
           show_edges=True, opacity=0.5, color="w",
           lighting=False, label="Test Mesh")
p.add_mesh(ray, color="blue", line_width=5, label="Ray Segment")
p.add_mesh(intersection, color="maroon",
           point_size=25, label="Intersection Points")
p.add_legend()
p.show()

**Comment by dbodily1** [comment]
https://pypi.org/project/pyoctree/ 

pyoctree is an efficient solution for this problem for anyone looking to solve this issue

**Comment by akaszynski** [comment]
Thanks for noting this!  Yes, this is a known issue.

Part of the desirability of VTK is it has many features, like octrees, ray-tracing, boolean operations, etc.  However, each of those libraries is limited by the limited maintenance the VTK library gets as a whole, meaning that it won't be as well maintained as the core plotting and data libraries.  I'd recommend using other Python modules for kd-trees and ray-tracing unless it's a simple operation.
