### ISSUE TITLE
Issue with plotting a fan blade mesh by using Pyvista

### ISSUE THREAD

**Issue by Chris-Jiang09** [pyvista/pyvista-support#333]
Hi, Pyvista Developer
I have got a issue with plotting a fan blade mesh by using Pyvista.
It's a complex point cloud data of a fan blade. 
Please check the attached file which contain the input data and figures used for illustration. 
I have tried to adjust the alpha in delaunay function, but still can't get the mesh I want.
Colud you help me check my code and give some advice? Really thanks! 
[data and figure.zip](https://github.com/pyvista/pyvista-support/files/5768966/data.and.figure.zip)

```py
import pyvista as pv
import numpy as np
import pandas as pd


file_path = './'
Coor_file = 'blade.csv'

X = pd.read_csv(file_path+Coor_file, sep=';', usecols=[0], header=None)
with pd.option_context('display.precision', 12):
    X = np.array(X)


with pd.option_context('display.precision', 12):
    Y = pd.read_csv(file_path+Coor_file, sep=';', usecols=[1], header=None)
    Y = np.array(Y)


with pd.option_context('display.precision', 12):
    Z = pd.read_csv(file_path+Coor_file, sep=';', usecols=[2], header=None)
    Z = np.array(Z)


points = np.c_[X.reshape(-1), Y.reshape(-1), Z.reshape(-1)]
cloud = pv.PolyData(points)


volume = cloud.delaunay_3d(alpha=3, tol=0.5, offset=2.5, progress_bar=True)
shell = volume.extract_surface(pass_pointid=False, pass_cellid=False, inplace=False)
shell.plot(show_grid=False)
```

| Truth | Generated by PyVista |
| --- | --- |
| ![The wantted mesh](https://user-images.githubusercontent.com/22067021/113795795-ed33e380-970a-11eb-9b7f-4243769eaf92.png) | ![mesh plot by pyvista](https://user-images.githubusercontent.com/22067021/113795797-f02ed400-970a-11eb-9724-00e2344a6781.png)

**Comment by banesullivan** [comment]
Mesh reconstruction from points clouds is a tough task and it is not PyVista's focus. There are likely other Computer Vision and meshing libraries out there better suited for the task.

IMO, your result isn't all that bad though.

Unfortunately, I don't think we'll be able to help you much further on this.

Apologies for the slow response, I am trying to go through and resolve stale issues. Please re-open/re-comment if you still have a question for this topic
