### ISSUE TITLE
Extracting Lines/Contours from PolyData for Export as GeoDataFrame/Shapely Objects

### ISSUE THREAD

**Issue by AlexanderJuestel** [pyvista/pyvista-support#335]
## Description
I would like to save the contours shown on the image below created with `contour(...)` in a way that I get the vertices of each line in a separate array or list or can at least filter the points for each LineString by index. I can access the points and this pointer ('returns a pointer to a line as numpy object', what does that mean actually?) but I have not found out how to extract the vertices for each single line. The goal would be to create a list of lists containing the vertices of each LineString and then creating Shapely LineStrings from that and converting them into a GeoDataFrame to save these as Shape Files. The contour lines are not unique and the same depth value may occur several times.

![image](https://user-images.githubusercontent.com/45469915/103759116-7e63c300-5013-11eb-9e31-7c048f9da7b0.png)

## Example Data

Contours are created the following way: 

```ruby
contours = surf.contour(isosurfaces=np.arange(-2450, 400,50))
contours

```

Thanks for your tips and I will try to find it out myself as well :)

**Comment by AlexanderJuestel** [comment]
Small Update:

So the `lines` attribute defines which indices belong together in this "weird" vtk style (see large image at the bottom). The resulting line in this example that I am currently looking at (not the contour example) looks fine afterwards. 

However, for my contour lines in the example mentioned above, I cannot find this pattern, see below. The lines should have a sufficient amount of vertices..**.orrrr actually, each line only consists of two vertices, that is why the 2 is repeated so often....** 
![image](https://user-images.githubusercontent.com/45469915/103871534-76685980-50cd-11eb-98b8-6f4c73708e16.png)



Other project where `lines` attribute works as expected
![image](https://user-images.githubusercontent.com/45469915/103871259-1f628480-50cd-11eb-8ed4-0413e6145bad.png)

**Comment by AlexanderJuestel** [comment]
Hey hey, 

I think I came up with a solution :) 

So, `contours` is the dataset containing the lines and points. I am then iterating over the total number of cells/lines and extract the values from the respective arrays (lines and points). It took me a while but I think that is a good first approach. Sorry if the variable names got too long sometimes :D 

Below, I added the original data in color from which the mesh that was shown above was created and then in blue the extracted LineStrings plotted as GeoDataFrame. There are slight differences due to the triangulation of the first set of contour lines but that could be expected. 

Waiting for @akaszynski or @banesullivan to close this :) 

```ruby
from shapely.geometry import LineString

linestrings = []
number_of_previous_points=0

for i in range(contours.number_of_cells):

    index_to_find_length_of_line = i + number_of_previous_points

    number_of_points_of_line = contours.lines[index_to_find_length_of_line]

    values = [contours.lines[index_to_find_length_of_line+i+1] for i in range(number_of_points_of_line)]

    points = [contours.points[value] for value in values]

    number_of_previous_points = number_of_previous_points + number_of_points_of_line

    linestrings.append(LineString(np.array(points)))

```

Original Data from which a mesh was created
![image](https://user-images.githubusercontent.com/45469915/104065827-b2e8a200-5200-11eb-9aba-30011f8bba9f.png)

Contour lines extracted from mesh as LineStrings and plotted as GeoDataFrame
![image](https://user-images.githubusercontent.com/45469915/104065879-c5fb7200-5200-11eb-9b29-dd3aad826df5.png)

**Comment by lmarschall** [comment]
Hey Alexander, 
thank you so much for demystifying the relationship between contours.lines and contours.points, i was looking for a solution but didnt recognize how they are connected.

**Comment by AlexanderJuestel** [comment]
I am glad I could help. I am also closing this now :)

**Comment by lmarschall** [comment]
Hey Alexander,

is it possible to use your algorithm, to extract specific lines that meet certain criteria?

![image](https://user-images.githubusercontent.com/1447571/105224518-8d8f5880-5b5d-11eb-887f-f179fd0ad215.png)

I'm currently trying to extract the height lines of the example mesh, but i dont have any success.

**Comment by AlexanderJuestel** [comment]
What criteria do you have?

**Comment by lmarschall** [comment]
I wanted to extract closed contours and get inbound normal vectors and scalar values, i dont know if thats possible.

**Comment by AlexanderJuestel** [comment]
Hey @lmarschall,
sorry for my late response. 
I am not sure if the LineStrings are closed but you could maybe check out https://shapely.readthedocs.io/en/latest/manual.html#shapely.ops.linemerge for merging LineStrings. 
I am not aware of any Shapely function that creates normal vectors. In that case you may want to have a look at NumPy to perform that for each line segment maybe. 

Feel also free to contact me privately for further chats. I saw that you are at the same university as me ;)
