### ISSUE TITLE
How to export 2D Vector Graphic from 3D streamline plot?

### ISSUE THREAD

**Issue by SimonHn7** [pyvista/pyvista-support#336]
Hey guys, 

I am using Python to post process some CFD results. Specifically, I am trying to create streamline plots from the velocity data at the nodes of the cells. To learn how to use Pyvista I ran the following example code from the website: 

```py
import numpy as np
import pyvista as pv
from pyvista import examples

nx = 20
ny = 15
nz = 5

origin = (-(nx - 1)*0.1/2, -(ny - 1)*0.1/2, -(nz - 1)*0.1/2)
mesh = pv.UniformGrid((nx, ny, nz), (.1, .1, .1), origin)
x = mesh.points[:, 0]
y = mesh.points[:, 1]
z = mesh.points[:, 2]
vectors = np.empty((mesh.n_points, 3))
vectors[:, 0] = np.sin(np.pi * x) * np.cos(np.pi * y) * np.cos(np.pi * z)
vectors[:, 1] = -np.cos(np.pi * x) * np.sin(np.pi * y) * np.cos(np.pi * z)
vectors[:, 2] = (np.sqrt(3.0 / 3.0) * np.cos(np.pi * x) * np.cos(np.pi * y) *
                 np.sin(np.pi * z))

mesh['vectors'] = vectors

stream, src = mesh.streamlines('vectors', return_source=True,
                               terminal_speed=0.0, n_points=200,
                               source_radius=0.1)

cpos = [(1.2, 1.2, 1.2), (-0.0, -0.0, -0.0), (0.0, 0.0, 1.0)]
stream.tube(radius=0.0015).plot(cpos=cpos)
stream.save("/Users/simonhenn/Desktop/streamlines.vtk")
```

<img width="505" alt="Screenshot 2021-01-06 at 16 15 33" src="https://user-images.githubusercontent.com/77064248/103784581-694e5a80-503a-11eb-979c-5d0b70872acd.png">

It works as expected and the streamlines are plotted. Is there a way to now export the current view of the 3D plot to a 2D vector graphic as .eps/.pdf...?

Thanks for your help!

**Comment by banesullivan** [comment]
Please see the `save_graphic` method: https://docs.pyvista.org/plotting/plotting.html#pyvista.BasePlotter.save_graphic

HTH

Apologies for the slow response, I am trying to go through and resolve stale issues. Please re-open/re-comment if you still have a question for this topic
