### ISSUE TITLE
Additional CRS attribute for geographic data

### ISSUE THREAD

**Issue by AlexanderJuestel** [pyvista/pyvista-support#337]
## Description

Currently, PyVista does not deal with any sorts of Coordinate reference systems (CRS) if I am correct? So I would be interested in having an attribute such as ``polydata.crs`` that returns the CRS for instance as PROJ string like it is done for GeoPandas. For now, the CRS could just be passed to the PolyData objects without any functionality. It comes in handy when looking at #335. If I want to create a GeoDataFrame from the extracted LineStrings, there is no way of passing the CRS to GeoPandas except for doing it manually. If one could just access the attribute, GeoDataFrames could be created like this:

`gdf = gpd.GeoDataFrame(geometry=linestrings, crs= polydata.crs`)

Other possibilities could then include reprojecting the data directly in PyVista.

Looking forward to your opinions :)

Cheers Alex

**Comment by banesullivan** [comment]
> Currently, PyVista does not deal with any sorts of Coordinate reference systems (CRS) if I am correct?

This is correct.

I would suggest tracking the CRS in the field data of the mesh. Perhaps you could have a set of tools/routines that work with PyVista meshes and expect those meshes to have a specific set of key/value pairs in the field data.

Field data = `.field_arrays`: Field data is not well documented in PyVista, but the gist is that it is a series of named arrays just like point/cell data except there is not enforcement of the shape/length of those arrays (though, don't be going trying to store 10+ by 100+ or higher dimensional arrays in there.

Then you could at least have a way of tracking the CRS across PyVista filtering routines.

e.g.

```py
>>> from pyvista import examples
>>> mesh = examples.download_st_helens()
>>> mesh.field_arrays['crs'] = ['+init=epsg:4326',]
>>> warped = mesh.warp_by_scalar()
>>> warped.field_arrays['crs']
pyvista_ndarray(['+init=epsg:4326'], dtype='<U15')
```

Then you could have your tools that convert between PyVista/GeoPandas expect the necessary meta data be present in the `field_arrays`

HTH

Apologies for the slow response, I am trying to go through and resolve stale issues. Please re-open/re-comment if you still have a question for this topic
