### ISSUE TITLE
Create a poly line from point data

### ISSUE THREAD

**Issue by laserman781** [pyvista/pyvista-support#34]
I am trying to plot a polyline rather than simply plotting the points. I was able to plot a spline but this is not what I want. How can I accomplish this?

This is what I have written so far:
```py
xyz = pd.read_csv('line_points.csv')
coords = xyz[['x', 'y', 'z']].values
poly = pv.PolyData(coords)
spline = pv.Spline(coords)
poly.plot(show_grid=False, point_size=3, color='red')
spline.plot(show_grid=False, point_size=3, color='white')
```

**Comment by laserman781** [comment]
@banesullivan The spline comes out correctly with `pv.Spline`, although I want to avoid the interpolation of spline. Any suggestions?

**Comment by banesullivan** [comment]
Ah yes, the `Spline` is parametric and interpolates the points which might not be desired.

Try this solution with `lines_from_points()`:

```py
import pyvista as pv
import numpy as np
pv.set_plot_theme('doc')

def make_points():
    """Helper to make XYZ points"""
    theta = np.linspace(-4 * np.pi, 4 * np.pi, 100)
    z = np.linspace(-2, 2, 100)
    r = z**2 + 1
    x = r * np.sin(theta)
    y = r * np.cos(theta)
    return np.column_stack((x, y, z))


def lines_from_points(points):
    """Given an array of points, make a line set"""
    poly = pv.PolyData()
    poly.points = points
    cells = np.full((len(points)-1, 3), 2, dtype=np.int)
    cells[:, 1] = np.arange(0, len(points)-1, dtype=np.int)
    cells[:, 2] = np.arange(1, len(points), dtype=np.int)
    poly.lines = cells
    return poly

points = make_points()

line = lines_from_points(points)

p = pv.Plotter()
p.add_mesh(points, color='red')
p.add_mesh(line, color='blue',)
p.show(use_panel=False)
```

![download](https://user-images.githubusercontent.com/22067021/62155878-29bd0400-b2c7-11e9-94a8-6609669dbf50.png)

**Comment by banesullivan** [comment]
Also, note that a very similar function exists in PyVista: https://docs.pyvista.org/utilities/utilities.html#pyvista.lines_from_points

However, it requires the points array to be explicit about which lines make each segment - if the points are already ordered, then you can probably stick with the method I shared in the post above.

**Comment by laserman781** [comment]
@banesullivan This is excellent information thank you!

**Comment by banesullivan** [comment]
I'm assuming this solution worked? If so, would you please close the issue?
