### ISSUE TITLE
Create a 2D matplotlib plot from Slices

### ISSUE THREAD

**Issue by jacobgrasmick** [pyvista/pyvista-support#341]
Say I create a slice via the Slicing tools:
https://docs.pyvista.org/examples/01-filter/slicing.html?highlight=slicing

I would like to be able to achieve any of the following:
1. extract a numpy array of the slice(s)
2. plot a slice in a 2D plot such as matplotlib

I can see this being a challenge if the slice is generated via `slice_along_line`...

**Comment by banesullivan** [comment]
There are a few examples of doing this with a planar slice: see #70 and #89 

As for doing this with a curvilinear slice produced from `slice_along_line` that is a bit more complex but doable. I will come back to this (hopefully this evening) to post an example.

**Comment by Dementiy** [comment]
Hello.

This question is still relevant. How to get the right order of points from slice that was created by `slice_along_line`?

Matplotlib 2D (using `points` attribute from slice):
![image](https://user-images.githubusercontent.com/4396325/174078394-e40de0f5-2b2f-4260-b703-55277bad109a.png)

Pyvista 3D (everything looks good):
![image](https://user-images.githubusercontent.com/4396325/174078612-10dade67-cfa1-4555-adb0-30624e762a41.png)

**Comment by banesullivan** [comment]
I believe the problem is that you are projecting the 3D line onto a 2D plane in your Matplotlib plot, that's why you see the line going back on itself...( from an quick glance)

**Comment by Dementiy** [comment]
Hi, @banesullivan , thanks for the reply. I got the answer in this discussion https://github.com/pyvista/pyvista/discussions/2798 there is a more suitable example.
