### ISSUE TITLE
Translate volume to real world coordinates

### ISSUE THREAD

**Issue by AlexanderJuestel** [pyvista/pyvista-support#344]
## Description

Hello again, 

I have the solutions of a GemPy model stored as 3D NumPy array and can display it as volume. However, I would like to have the volume placed at its real world coordinates. So I would like to adjust the X, Y and Z bounds of the volume. This will be needed for later to [extract for instance sections along a line](https://docs.pyvista.org/examples/01-filter/slicing.html#slice-along-line). This line (i.e. Shapely LineString) usually holds the real world coordinates.

So far I could not find a function to translate the data or change the bounds. Setting the bounds attribute is not possible. 

![image](https://user-images.githubusercontent.com/45469915/104848403-13549f00-58e5-11eb-9580-5d157573fae2.png)

![image](https://user-images.githubusercontent.com/45469915/104848554-cb824780-58e5-11eb-90a4-e991756cfcad.png)

**Comment by akaszynski** [comment]
I've not tried this on a wrapped object, but it appears according to [Creating a Uniform Grid](https://docs.pyvista.org/examples/00-load/create-uniform-grid.html#sphx-glr-download-examples-00-load-create-uniform-grid-py), you can change the origin and the size of the cells.  If you change the size of the cells, you can get the uniform grid to match your real world coordinates.

**Comment by AlexanderJuestel** [comment]
Thanks for pointing that out. I will give it a try! Also good, that you can change the size of the cells!

**Comment by AlexanderJuestel** [comment]
Hey @akaszynski, 
I just tested it and that is exactly what I was looking for :) Closing that now

**Comment by RichardScottOZ** [comment]
@AlexanderJuestel  is that an example?

**Comment by AlexanderJuestel** [comment]
@RichardScottOZ, do you mean in GemGIS? Yes, there should be a simple example for that

**Comment by RichardScottOZ** [comment]
Yes, as I can imagine me having that problem in the near future.
