### ISSUE TITLE
Voxelising Point Cloud

### ISSUE THREAD

**Issue by aayushbhardwaj1** [pyvista/pyvista-support#346]
Voxelising Point Cloud From CSV file
-->

Hi guys, 
I have a CSV file here with x,y,z and a scalar value column[called "a"]. From PVGeo, I am able to create a point cloud perfectly, however, I was hoping to create voxels from the point cloud. I noticed that due to my dataset being perhaps unstructured(spherical shaped) it may be difficult.

Any help would be appreciated!

CODE

##DISPLAYING THE POINT CLOUD
vtkpoints = PVGeo.points_to_poly_data(adjusted_dataset)
print(vtkpoints)
vtkpoints.plot(notebook = False)

##Voxelising Point Cloud
print("Point Cloud Creation...")
voxelizer = PVGeo.filters.VoxelizePoints()
voxelizer.set_deltas(50, 50, 50)
voxelizer.set_estimate_grid(False)
grid = voxelizer.apply(vtkpoints)
grid.plot(notebook= False)

## Example Data

![Screenshot (39)](https://user-images.githubusercontent.com/77475206/104977686-11045900-5a3b-11eb-8894-946d43e62a8f.png)

-->

**Comment by akaszynski** [comment]
I think the main issue is that pyvista's voxelization requires a surface and a point cloud is insufficient.  You may want to try to use the [delaunay_3d](https://docs.pyvista.org/core/filters.html?highlight=delaunay#pyvista.DataSetFilters.delaunay_3d) filter to first create a 3d surface and then attempt voxelization.

**Comment by aayushbhardwaj1** [comment]
The delaunay_3d filer seems to not work on my dataset. Essentially what I wish to do is, to make this point cloud here into voxels.
![Screenshot (35)](https://user-images.githubusercontent.com/77475206/104980133-d998ab00-5a40-11eb-9528-16dde9ecc695.png)

**Comment by akaszynski** [comment]
I'll need you to post the dataset here (along with any scripts to read it in) to be able to help you out.

**Comment by aayushbhardwaj1** [comment]
> I'll need you to post the dataset here (along with any scripts to read it in) to be able to help you out.

The dataset is extremely large, so I am not sure how to send it. I have however attached part of the dataset. But here is the attached code so far. 

[DATSET.zip](https://github.com/pyvista/pyvista-support/files/5846954/DATSET.zip)

##IMPORTING PACKAGES
import pandas as pd 
import matplotlib.pyplot as plt
import vtk
import pyvista
import numpy as np
import pandas as pd
import glob
import os  
import PVGeo
from PVGeo.filters import VoxelizePoints
import vedo
from vedo import *
from pyntcloud import PyntCloud
import open3d as o3d
from mpl_toolkits import mplot3d
from vtkplotter import *
import pyvista as pv
import plotly
import k3d
from pythreejs import *
%matplotlib inline
import matplotlib
import matplotlib as mpl
import itk
from itkwidgets import view

##CODE- Importing dataset
fields = ["x","y","z","a"]
adjusted_dataset = pd.read_csv("alldata.csv",usecols = fields)
X = adjusted_dataset["x"]
Y = adjusted_dataset["y"]
Z = adjusted_dataset["z"]
A = adjusted_dataset["a"]

##CODE PLOTTING -DISPLAYING THE POINT CLOUD
vtkpoints = PVGeo.points_to_poly_data(adjusted_dataset)
print(vtkpoints)
#vtkpoints.plot(notebook = False)

##ATTEMPTING VOXELISATION- DOES NOT WORK
print("Point Cloud Creation...")
voxelizer = PVGeo.filters.VoxelizePoints()
voxelizer.set_deltas(50, 50, 50)
voxelizer.set_estimate_grid(False)
grid = voxelizer.apply(vtkpoints)
grid.plot(notebook= False)

Also, I am trying to add a slider bar widget to control the scalar value such that as it changes, only areas with the selected value are shown, could you also assist with this. The slider is able to change, however the visualisation is not updated?
##ATTACHED CODE FOR SLIDER

import pyvista
pyvista.rcParams['use_ipyvtk'] = True
polydata =  pv.PolyData(vtkpoints)
polydata
plotter = pyvista.Plotter(notebook=False)
plotter.add_mesh(polydata)
plotter.add_mesh_threshold(polydata, continuous= True)
plotter.threshold_meshes
plotter.show(use_ipyvtk=True)

**Comment by akaszynski** [comment]
I'd output the data as a numpy array.  That will compress much smaller than a csv file.  If the data is huge, you'll need to upload it to a file sharing service.

**Comment by aayushbhardwaj1** [comment]
> I'd output the data as a numpy array. That will compress much smaller than a csv file. If the data is huge, you'll need to upload it to a file sharing service.

I have sent the dataset to akascap@gmail.com. I hope that is okay. I am unsure on how to output as a numpy array.

**Comment by akaszynski** [comment]
Thanks for sending me the data.  First, the good news, you can sorta do it:
```py
# this is after your "CODE PLOTTING" section
pts = vtkpoints.extract_points(range(100000))
pts.glyph(geom=pv.Cube(), factor=5).plot()
```
![image](https://user-images.githubusercontent.com/11981631/105428380-870bea00-5c0c-11eb-985b-96e879f20a10.png)

Bad news is this breaks down when plotting all 7 million points.  I was happy with the performance of 100000, and you can probably do a million, but anymore is too much.

I suppose what you're really looking for is a way of reducing the data to voxels, rather than outright converting it to cubes.  I'm looking into that solution.

**Comment by akaszynski** [comment]
Did it:

```py
## voxelize a point cloud

# make a grid the same size (with an additional margin) as vtkpoints
bounds = vtkpoints.bounds
margin = 100
diameter = bounds[1] - bounds[0] + margin*2
n = 300
grid = pv.UniformGrid((n, n, n))
grid.origin = [bounds[0] - margin]*3
spacing = diameter/(n - 1)
grid.spacing = [spacing]*3

# interpolate the cloud's values onto the uniform grid
vox = grid.interpolate(vtkpoints, radius=spacing*2, progress_bar=True)

# extract the cell containing valid values
mask = vox['a'] > 0
vox_valid = vox.extract_points(mask, adjacent_cells=False)
# vox_valid.plot()

# save
# vox_valid.save('vox.vtk')  # save to be loaded later with pv.read('vox.vtk')
```

![image](https://user-images.githubusercontent.com/11981631/105430443-c2a8b300-5c10-11eb-9035-bad63d7fbea6.png)

**Comment by aayushbhardwaj1** [comment]
Thank you so much!! Worked perfectly and how I wanted it to. Do you know how I could possibly add a scalar widget to help toggle between the "a" value such that areas with the same value are shown?

**Comment by akaszynski** [comment]
I'm not 100% sure what you mean.  If you modify the mask then you can selectively change the voxels shown.  Make the mask a np.logical_and

**Comment by aayushbhardwaj1** [comment]
Essentially, if you look at the image below, I want to create the slider above such that if the user toggles between the value selected, only the voxels which match the number chosen will be displayed. 

...basically a  slider bar as shown below to only show the regions with the selected value. For example, if I was to pick a scalar value of 7.8 on the scale, is it possible to show those regions with that scalar value. Essentially, I want to toggle between selected areas using a slider widget

##THIS IS CODE FOR THE POINT CLOUD AND NOT VOXELS
Here is some of the code below:
plotter = pyvista.Plotter(notebook=False)
plotter.add_mesh(polydata)
plotter.add_mesh_threshold(polydata, continuous= True)
plotter.threshold_meshes
plotter.show(use_ipyvtk=True,screenshot='PointCloud.png')

![image](https://user-images.githubusercontent.com/77475206/105437644-64291680-5c9c-11eb-8fd7-02aa748f7e48.png)

**Comment by akaszynski** [comment]
I'm not sure if you can implement it like that.  @banesullivan implemented the threshold filter and might be able to help you there.

**Comment by aayushbhardwaj1** [comment]
@banesullivan would you have any tips on how to do this?

**Comment by banesullivan** [comment]
*Quickly glancing at this...*

From what it sounds like, thresholding would be exactly what you want to do. Perhaps the `add_mesh_threshold` helper is sufficient?

There is an example here: https://docs.pyvista.org/examples/03-widgets/slider-bar-widget.html#slider-bar-widget

**Comment by banesullivan** [comment]
I think you want to plot an isocontour of the mesh. The `add_mesh_isovalue` method might work for you.

See https://docs.pyvista.org/plotting/plotting.html#pyvista.BasePlotter.add_mesh_isovalue
