### ISSUE TITLE
attach RGB color to each node, slice

### ISSUE THREAD

**Issue by nschloe** [pyvista/pyvista-support#351]
I'd like to plot the sRGB cube with coloring in pyvista. This
```python
import meshzoo
import pyvista as pv

points, cells = meshzoo.cube_hexa((0.0, 0.0, 0.0), (1.0, 1.0, 1.0), n)
cells = np.column_stack([np.full(cells.shape[0], 8), cells])

celltypes = np.full(len(cells), vtk.VTK_HEXAHEDRON, dtype=np.uint8)

grid = pv.UnstructuredGrid(cells.ravel(), celltypes, cs_coords)
_ = grid.plot(show_edges=True)
```
gives me the cube, but I don't know how to attach RGBs to each point. Any hint?

As a side-note, I find it really weird having to prepend a whole column to `cells` just for the counts. This is an in memory-copy of an array that can be quite large. Isn't there another way?

**Comment by nschloe** [comment]
Got it:
```
p = pv.Plotter()
mesh = p.add_mesh(grid,
    scalars=my_rgb_values,,
    rgb=True,
)
p.show()
```
does it.

**Comment by nschloe** [comment]
Next question: How to slice through the colored object? `add_mesh` apparently returns an object that cannot be worked with?

**Comment by banesullivan** [comment]
Sorry for the slow response, @nschloe! I'm glad you were able to figure out the RGB coloring on your own.

As for slicing, PyVista separates mesh analysis/filter and plotting. The output of `add_mesh` or any plotting routine is totally separate from filtering routines. If you want to slice the mesh, this is done directly from the mesh via a filter.

See https://docs.pyvista.org/core/filters.html and https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.slice

For example, you'd do:

```py
import meshzoo
import pyvista as pv

points, cells = meshzoo.cube_hexa((0.0, 0.0, 0.0), (1.0, 1.0, 1.0), n)
cells = np.column_stack([np.full(cells.shape[0], 8), cells])

celltypes = np.full(len(cells), vtk.VTK_HEXAHEDRON, dtype=np.uint8)

... # define my_rgb_values

grid = pv.UnstructuredGrid(cells.ravel(), celltypes, cs_coords)
grid['rgb'] = my_rgb_values

p = pv.Plotter()
p.add_mesh(grid, scalars=my_rgb_values, rgb=True)
p.show()

slc = grid.slice()

p = pv.Plotter()
p.add_mesh(grid, scalars=my_rgb_values, rgb=True)
p.show()
```

**Comment by nschloe** [comment]
That works, thank you!
