### ISSUE TITLE
screenshots: transparent background, screenshot from show()

### ISSUE THREAD

**Issue by nschloe** [pyvista/pyvista-support#352]
I would like to save a screenshot from a plotter object
```python
pv.Plotter()
```
Unfortunately, it seems that `show()` doesn't have all the options of `plot()`, https://docs.pyvista.org/plotting/plotting.html#pyvista.plot, in particular no `off_screen` rendering.

Another thing I wasn't able to do is to save a screen shot with transparent background.

Any hints?

**Comment by akaszynski** [comment]
This should work for you:
```
import pyvista

pl = pyvista.Plotter(off_screen=True)
pl.add_mesh(pyvista.Sphere())
pl.show(screenshot='screenshot.png')
```

Implementation details are all in [Plotting](https://docs.pyvista.org/plotting/plotting.html), though it's a long read.

**Comment by nschloe** [comment]
That fixes the off-screen rendering; do you happen to know anything about screenshots with transparent background?

**Comment by akaszynski** [comment]
You could add a transparent background to your plot by manually generating it outside pyvista and then adding it with [add_background_image](https://docs.pyvista.org/plotting/plotting.html#pyvista.BasePlotter.add_background_image).

**Comment by MarkusZimmerDLR** [comment]
I am having a somewhat similar problem, as I am trying to save vector graphics.
The option
`pl.save_graphic('screenshot.svg') `
seems to be the only way, as the screenshot function does not support vector graphics.

Unfortunately, this still opens a window which is not closed automatically. Even with:
`pl.close()`

Furthermore, the saved plot has a lot of aliasing (the main reason why I am trying to save it as a vector graphic). Increasing the anti aliasing with
`pl = pyvista.Plotter(multi_samples=8)`
does not do anything for the saved plot.

The worst thing: If I close the window manually and rerun the code, the ipython shell crashes completely:

`pl = pyvista.Plotter(off_screen=True) 
pl.add_mesh(pyvista.Sphere()) 
pl.save_graphic('screenshot.svg')    
<manual closing of window>
pl = pyvista.Plotter(off_screen=True) 
pl.add_mesh(pyvista.Sphere()) 
pl.save_graphic('screenshot.svg')                                                               
Gdk-Message: 16:38:29.070: python: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.`

**Comment by nschloe** [comment]
@MarkusZimmerDLR Sounds like a different issue.

**Comment by nschloe** [comment]
> You could add a transparent background to your plot by manually generating it outside pyvista and then adding it with add_background_image.

Thanks @akaszynski for the suggestion! To make things easier, perhaps this could be added as a `background_transparent=True` option to `show`/`save_graphic`. What do you think?

**Comment by banesullivan** [comment]
FYI `screenshot` has this covered with the `transparent_background` option. See: https://docs.pyvista.org/plotting/plotting.html#pyvista.BasePlotter.screenshot

adding a `screenshot='filename'` option to `show()` is simply a convenience method.

for example:

```py
p = pv.Plotter(off_screen=True)
p.add_mesh(pv.Sphere())
p.screenshot('foo.png', transparent_background=True)
p.show()
```

AND this is handled in the `rcParams`: https://github.com/pyvista/pyvista/blob/7747c6d9bad8179030a5f57e1ffff40a8ff23481/pyvista/plotting/theme.py#L57

```py
pv.rcParams['transparent_background'] = True

p = pv.Plotter(off_screen=True)
p.add_mesh(pv.Sphere())
p.show(screenshot='foo2.png')
```

![foo](https://user-images.githubusercontent.com/22067021/113807448-62aaae80-9721-11eb-8e17-5fb2a5cac4d9.png)
