### ISSUE TITLE
Best way to apply arbitrary colors to edges?

### ISSUE THREAD

**Issue by karldd** [pyvista/pyvista-support#359]
## Description

I'm looking for the best way to display arbitrary colors for edges of a mesh. I can see from the [Create PolyData example](https://docs.pyvista.org/examples/00-load/create-poly.html) that assigning colors to faces is quite straightforward. Is there a similar thing that can be done for edges?

## Example Data
Below is a mock up of what I am interested in doing. Here edges that are assigned a color are displayed, others (such as the hidden edge in the top square) are not.
![image](https://user-images.githubusercontent.com/619336/107734160-992ff400-6cb1-11eb-9f86-648f33481f7c.png)

A simple example of coloring edges as shown above, with code based on the [Create PolyData example](https://docs.pyvista.org/examples/00-load/create-poly.html) would be very helpful.
```py
import numpy as np
import pyvista as pv

# mesh points
vertices = np.array([[0, 0, 0],
                     [1, 0, 0],
                     [1, 1, 0],
                     [0, 1, 0],
                     [0.5, 0.5, -1]])

# mesh faces
faces = np.hstack([[4, 0, 1, 2, 3],  # square
                   [3, 0, 1, 4],     # triangle
                   [3, 1, 2, 4]])    # triangle

surf = pv.PolyData(vertices, faces)

# plot each face with a different color
surf.plot(scalars=np.arange(3), cpos=[-1, 1, 0.5])
```

Thanks in advance!

**Comment by akaszynski** [comment]
I'd extract the edges and plot those:
```py
>>> edges = surf.extract_all_edges()
>>> edges.lines  # line connectivity stored here
>>> edges.plot(scalars=np.random.random(edges.n_faces), line_width=10, cmap='jet')
```

![image](https://user-images.githubusercontent.com/11981631/107735139-43147e00-6cbc-11eb-8671-7a9ea2799d81.png)

You can plot the two meshes (original and extracted edges) together using the `Plotter` class.

**Comment by karldd** [comment]
Excellent! Thank you.

And is there a way to create the wireframe mesh directly by passing in edge data? Rather than extracting the edges from the face mesh.

**Comment by akaszynski** [comment]
Yes, and working on this makes me realize we could improve our interface a bit to support building lines.
```
import numpy as np
import pyvista as pv

# mesh points
vertices = np.array([[0, 0, 0],
                     [1, 0, 0],
                     [1, 1, 0],
                     [0, 1, 0],
                     [0.5, 0.5, -1]])

# mesh faces
# faces = np.hstack([[4, 0, 1, 2, 3],  # square
#                    [3, 0, 1, 4],     # triangle
#                    [3, 1, 2, 4]])    # triangle

# line connectivity
lines = np.hstack([[2, 0, 1],
                   [2, 1, 2],
                   [2, 2, 3],
                   [2, 0, 3],
                   ])

line_poly = pv.PolyData(vertices)
line_poly.lines = lines
line_poly.plot(line_width=10)
```

**Comment by karldd** [comment]
Thank you!

As a note to others/future self...

The first value of each face is the face type, 4 for square, 3 for triangle. The following 3 values are the vertex indices.
```python
# mesh faces
faces = np.hstack([[4, 0, 1, 2, 3],  # square
                   [3, 0, 1, 4],     # triangle
                   [3, 1, 2, 4]])    # triangle
```

The first value of each line is the line type, 2 for line. The following 2 values are the vertex indices.
```python
lines = np.hstack([[2, 0, 1],
                   [2, 1, 2],
                   [2, 2, 3],
                   [2, 0, 3],
                   ])
```

**Comment by akaszynski** [comment]
> The first value of each face is the face type, 4 for square, 3 for triangle.

Or more specifically, the number of points in the face.  5 would be for a pentagon, 6 would be for a hexagon, etc...

> The first value of each line is the line type, 2 for line. The following 2 values are the vertex indices.

Here, it's the number of points within the line segment.  You could have 1000s of points within a line segment.
