### ISSUE TITLE
Color by distance

### ISSUE THREAD

**Issue by laserman781** [pyvista/pyvista-support#36]
I have data called shortest distance with is the shortest distance from a list of point to line segments or polylines. I would like to have closer distances (minimum) to be a warm color and the furthest a cold color. I've somewhat been able to accomplish this by setting shortest distance as a scalar and applying a threshold although the color scheme is backward.  Is there any way I can accomplish this statically in a plotter?

Here's what I have written so far:
```py
points_array = points[['x', 'y', 'z']].values
poly = pv.PolyData(points_array)
poly['shortest distance'] = points['shortest distance'].values
poly = pv.Threshold(bpoly)
```
I would like to accomplish the same thing (color by distance) but using plotter:
```py
p = pv.Plotter()
p.add_mesh(bpoly.clip(normal='z',
        origin = [0,0,clip_pts]),
    color='b', render_points_as_spheres=True)
p.plot()
```

**Comment by banesullivan** [comment]
When using the `Plotter`, all you should need to do is specify the colormap in the `add_mesh` call instead of the `color` argument. Sounds like you want to use the `'coolwarm_r'` colormap but any [Matplotlib colormap](https://matplotlib.org/3.1.1/gallery/color/colormap_reference.html) is supported

Try this:
```py
p = pv.Plotter()
p.add_mesh(bpoly.clip(normal='z',origin=[0,0,clip_pts]), cmap='coolwarm_r', render_points_as_spheres=True)
p.show()
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by laserman781** [comment]
@banesullivan by adding cmap = 'coolwarm_r' to the add_mesh the points are all white and don't change by distance...

**Comment by banesullivan** [comment]
Hm, do you have scalars on the mesh? Maybe make sure:

```
points_array = points[['x', 'y', 'z']].values
poly = pv.PolyData(points_array)
poly['shortest distance'] = points['shortest distance'].values

p = pv.Plotter()
p.add_mesh(poly.clip(normal='z',
        origin=[0,0,clip_pts]), 
    cmap='coolwarm_r',
    scalars='shortest distance',
    render_points_as_spheres=True)
p.show()
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by laserman781** [comment]
It worked after I defined the scalar as shortest distance. Now my problem is, I want to filter for  blocks within a specified distance and after trying to include the color map is get this error:

Exception: Number of scalars (153813)must match either the number of points (4910) or the number of cells (4910). 

Code:
```
q=50
points_array = points[points['shortest distance']<=q][['x', 'y', 'z']].values
bpoly = pv.PolyData(points_array)
bpoly['shortest distance'] = points['shortest distance'].values
```

**Comment by laserman781** [comment]
Never mind I solved the issue, thanks!

**Comment by banesullivan** [comment]
Make sure to index the data frame with the same conditional when grabbing the shortest distance array as you do when you grab the points. Better yet, I’d make an indexing array:

```
q=50
indices = points['shortest distance']<=q
points_array = points[indices][['x', 'y', 'z']].values
bpoly = pv.PolyData(points_array)
bpoly['shortest distance'] = points[indices]['shortest distance'].values
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
