### ISSUE TITLE
Calculating the length of an extracted edge

### ISSUE THREAD

**Issue by reevesj191** [pyvista/pyvista-support#360]
## Description

I have a set of irregularly shaped surfaces and I would like to calculate the length of their boundary edge. I have been using .extract_feature_edges(boundary_edges = True) to extract the edge of the mesh. However, calculating the length of the edge from the returned point set still is not clear to me. I thought I would loop through the indices of the points calculating the distances between one point and the subsequent one but the points do not seem to be ordered in any particular way. 

I would greatly appreciate any advice on how to calculate the length of the line of the extracted edge. 

Thanks.

**Comment by banesullivan** [comment]
Here is an examples:

```py
>>> from pyvista import examples
>>> line = examples.load_random_hills().extract_feature_edges(boundary_edges=True)
>>> sized = line.compute_cell_sizes()
>>> sum(sized['Length'])
95.61899712552004
```

and there is also:

```py
>>> arc = line.compute_arc_length()
>>> sum(arc['arc_length'])
95.61899699270725
```

HTH

Apologies for the slow response, I am trying to go through and resolve stale issues. Please re-open/re-comment if you still have a question for this topic
