### ISSUE TITLE
Export colored obj with mtl

### ISSUE THREAD

**Issue by Sea421** [pyvista/pyvista-support#361]
Hi team,

I would like to export colored obj file with mtl. But it can't export colors. Here is my code.

```python
import pyvista as pv
import numpy as np

sphere = pv.Sphere()
colors = np.random.random((sphere.points.shape[0], 3))
sphere['colors'] = colors

p = pv.Plotter()
p.add_mesh(sphere, scalars='colors', rgb=True)
p.export_obj("sphere")
p.show()
```

Please, help me to export colors in mtl file.

Result:
![export_obj_with_mtl](https://user-images.githubusercontent.com/55222313/107932351-6c812280-6fb8-11eb-9a2b-e86268efc916.png)

mtl file:
```mtl
# wavefront mtl file written by the visualization toolkit

newmtl mtl1
Ka 0 0 0
Kd 1 1 1
Ks 0 0 0
Ns 100
Tr 1
illum 3

```

**p.s:** My ultimate goal is to export obj with mtl then export it to u3d and embed it in pdf file.

Thanks

**Comment by akaszynski** [comment]
I don't think that the current exporter can output point or cell scalars to an *obj file.  If you want to do a more direct conversion to u3d, there's some posts for it here indicating it's possible:
http://vtk.1045678.n5.nabble.com/colored-surface-model-as-a-3D-PDF-td5077778.html

Seems that there's not a direct interface from VTK at the moment to support this, but if you need to use an intermediate file, I recommend using a different file type other than *.obj.

**Comment by Sea421** [comment]
Thanks for your answer :)

**Comment by eloyvallinaes** [comment]
It's been a couple years and I find myself trying to do the same thing and seemingly stuck at the same place.

Was this feature ever added? 🤞
