### ISSUE TITLE
Plot VTK meshes in a same window to check overlapping

### ISSUE THREAD

**Issue by isurusuranga** [pyvista/pyvista-support#365]
## Description
Hi,

I’m new to PyVista and I am trying to plot 3D volumetric meshes in a same window.
I have generated a set of volumetric liver meshes in .vtk format and now I want to plot all of them in a same window with different colours to check how much overlap that they have ? Is it possible in PyVista? If so can you elaborate with an example please ?

I have herewith attached two samples .vtk files for your further reference.

## Example Data
[sample_meshes.zip](https://github.com/pyvista/pyvista-support/files/6011618/sample_meshes.zip)

**Comment by akaszynski** [comment]
Without looking at your data, you can do this with (pseudo code)
```py
import random
import pyvista as pv
meshes = [pv.read(filename) for filename in filenames]

pl = pv.Plotter()
for mesh in meshes:
    random_color = [random.random(), random.random(), random.random()]
    pl.add_mesh(mesh, color=random_color)

pl.show()
```

For further help, please see https://docs.pyvista.org/examples/index.html
