### ISSUE TITLE
Remove/move bar at bottom of plot

### ISSUE THREAD

**Issue by laserman781** [pyvista/pyvista-support#37]
Is there a way to remove or move the bars that go on the bottom of the plot for cmaps?
![image](https://user-images.githubusercontent.com/12982931/62231341-d8c61200-b391-11e9-8c2b-feb51d547328.png)
^As you can see above, the bars are in the way.

I want to be able to remove the top one and move the bottom one.

Thanks!

**Comment by banesullivan** [comment]
When you add the mesh that is associated with the colorbar that you do not want to see, pass `show_scalar_bar=False` as an argument.

To make the other one interactive, do something like the following which is from [this example](https://docs.pyvista.org/examples/02-plot/scalar-bars.html#customize-scalar-bars):

```py
# create dictionary of parameters to control scalar bar
sargs = dict(interactive=True)  # Simply make the bar interactive

p = pv.Plotter(notebook=False)  # If in IPython, be sure to show the scene
p.add_mesh(mesh, scalar_bar_args=sargs)
p.show()
```
