### ISSUE TITLE
Slice area

### ISSUE THREAD

**Issue by oalahurikar** [pyvista/pyvista-support#384]
Hello,

I am trying to get area of sliced mesh 

I tried following solution, but I am keep getting area 0. Any help on this issue is much appreciated. 
https://github.com/pyvista/pyvista-support/issues/102

![image](https://user-images.githubusercontent.com/13579623/111558259-d1b96680-8764-11eb-8c26-e1771562fdc4.png)

## Description

Here is my code and attached stl file I used.
[Companion_Cube.zip](https://github.com/pyvista/pyvista-support/files/6160704/Companion_Cube.zip)

```py
import pyvista as pv
import numpy as np
path ='C:\SHARE\CAD Files\Companion_Cube.stl'
mesh = pv.read(path)
slices = mesh.slice_along_axis(n=10, axis="z")
cmap = plt.cm.get_cmap("viridis", 4)
slices.plot(cmap=cmap)
sliced_plane = slices[1].compute_cell_sizes()
np.sum(sliced_plane["Area"])
```

## Example Data
And here is the output.

![image](https://user-images.githubusercontent.com/13579623/111558679-a125fc80-8765-11eb-8a5b-429adbdbe2d1.png)

**Comment by akaszynski** [comment]
The issue here is that we're taking slices of a mesh, not a solid unstructured grid.  This means that each of the slices will be returned as lines, and the lines mesh doesn't have an area as you discovered.

Fortunately, these are enclosed, manifold loops, unfortunately `pyvista` is having problems converting those into meshes.  However, we can just use the `triangle` library to tessellate them:


```py
import triangle as tr
import pyvista as pv
import numpy as np

mesh = pv.read('Companion_Cube.stl')
slices = mesh.slice_along_axis(n=10, axis="z")

def triangulate_slice(slc):

    seg = slc.lines.reshape(-1, 3)[:, 1:]
    A = dict(vertices=np.array(slc.points[:, :2], dtype=np.float64), segments=seg)
    B = tr.triangulate(A, 'qp')

    n_faces = B['triangles'].shape[0]
    triangles = np.hstack((np.ones((n_faces, 1), np.int32)*3, B['triangles']))

    # back to 3D
    pts = np.empty((B['vertices'].shape[0], 3))
    pts[:, :2] = B['vertices']
    pts[:, -1] = slc.points[0, 2]
    pd = pv.PolyData(pts, triangles, n_faces)
    return pd

tslices = pv.MultiBlock([triangulate_slice(slc) for slc in slices])

pl = pv.Plotter()
pl.add_mesh(mesh, color='r', opacity=0.1)
pl.add_mesh(slices, line_width=2, color='k')
pl.add_mesh(tslices, color='grey')
pl.background_color = 'w'
pl.add_text('Weighted Companion Cube Slices', color='k')
pl.show()
```
![cube](https://user-images.githubusercontent.com/11981631/111665454-60b39680-87d8-11eb-90d5-7ec5eef6dd73.png)

Finally, your areas can be computed:

```py
>>> areas = np.array([tslice.area for tslice in tslices])
>>> print(areas.sum())
4990.472670895162
```

**Comment by oalahurikar** [comment]
Thank you Alex, above solution works for me.
