### ISSUE TITLE
Voxelization of a 3D mesh- only the surface but not the bulk

### ISSUE THREAD

**Issue by tmatsuzawa** [pyvista/pyvista-support#386]
## Description
The current `pyvista.voxelize(mesh)` voxelizes the regions bounded by the mesh. I'd like a feature that voxelizes only the surface but not the bulk. i.e. it assigns 255 if the mesh intersects with a voxel, 0 otherwise. 

This issue is very similar to Issue #78. 
If there is a workaround, I'd be eager to know as well.
## Example
Below I provide a sample code to demonstrate the issue. First, I define a scalar function, find its isosruface, create a mesh, then voxelize it using `pyvista.voxelize()`.

```
import numpy as np
import pyvista
from skimage import measure

# Define positional grids (x, y, z)
x, y, z = np.linspace(-10, 10, 50, endpoint=True), np.linspace(-10, 10, 50, endpoint=True), np.linspace(-10, 10, 50, endpoint=True)
xxx, yyy, zzz = np.meshgrid(x, y, z)
dx, dy, dz = x[1] - x[0], y[1] - y[0], z[1] - z[0] 

# Define sample data
m=2. # m=2: sphere, higher m: more cubic
rrr = np.abs((xxx**m + yyy**m + zzz**m) ** (1/m))
data = 5000 * np.exp(-0.5 * rrr)

# Find a isosurface with value 
value = 1680
verts, faces_skimg, normals, values = measure.marching_cubes_lewiner(data, value, spacing=(dx, dy, dz))
verts[:, 0] += np.min(yyy)
verts[:, 1] += np.min(xxx)
verts[:, 2] += np.min(zzz)

# Define a useful function for later.
def convertFaces_skimg2vtk(faces_skimg):
    """This function fixes the data format of scikit-image to the one of vtk/pyvista."""
    nf, _ = faces_skimg.shape
    faces = []
    for i in range(nf):
        faces += [3]
        faces += list(faces_skimg[i, :])
    return np.asarray(faces)

faces_pyvista = convertFaces_skimg2vtk(faces_skimg)

# Create a mesh, then voxelize
mesh = pyvista.PolyData(verts, faces_pyvista)
voxels = pyvista.voxelize(mesh, density=mesh.length/200)
slices = voxels.slice_orthogonal(x=0, y=0, z=0)

# Show the created mesh and voxels
p = pyvista.Plotter()
# p.add_mesh(mesh, color=True, show_edges=False, opacity=1) # show a mesh with VTK
#p.add_mesh(voxels, color=True, show_edges=True, opacity=1) # show voxels with VTK
p.add_mesh(slices, color='skyblue')

p.add_bounding_box()
p.show()
```

This produces a mesh (2D object embedded in 3D) but the voxelizing it simply fills up the region bounded by this surface. I'm showing you the slices here.

**Mesh- created from an isosurface of a scalar function**
![image](https://user-images.githubusercontent.com/29457620/111688985-76858380-87f9-11eb-8d22-f99428ba2273.png)
**`pyvista.voxelize()` fills up the region bounded by the mesh** 
![image](https://user-images.githubusercontent.com/29457620/111689830-82257a00-87fa-11eb-85d3-d95ccfc2848e.png)

**Comment by banesullivan** [comment]
or rather if you don't want to do the extraction then you can assign 255 to those voxels in the model by:

```py
...
voxels['cell_ids'] = np.arange(voxels.n_cells)
cell_ids = voxels.extract_surface()['cell_ids']
voxels['interects'] = np.zeros(voxels.n_cells)
voxels['interects'][cell_ids] = 255  # or whatever value
```

**Comment by tmatsuzawa** [comment]
Thank you @banesullivan! I am a VTK newbie, so I appreciate your help.
The first method using the` extract_surface() ` did the trick. I was not aware of that. The second method failed to make the bulk disappear. It appeared that `voxels['interects'] = np.zeros(voxels.n_cells)` did nothing.
