### ISSUE TITLE
render_points_as_spheres other options?

### ISSUE THREAD

**Issue by zhen-dong-zhang** [pyvista/pyvista-support#387]
Hi,
I'm wondering whether there are other options for the render?
for example, can I render points as triangles, diamonds?
Thanks a lot for your attention.
Zhendong

**Comment by akaszynski** [comment]
Yes, please see [glpyhs](https://docs.pyvista.org/examples/01-filter/glyphs.html).  I've even made minecraft plots (see https://github.com/pyvista/pyvista-support/issues/374) using glyphs.

**Comment by zhen-dong-zhang** [comment]
Hi Alex,
Thanks for the quick response. 
I think I'm using a single point for such kind of plotting.
Please find my example plotting here: I want to replace the sphere with a triangle.
![triangle](https://user-images.githubusercontent.com/74623393/112169167-53c3e800-8bc8-11eb-9f99-f9b72b1462de.png)
Thanks a lot!
Zhendong

**Comment by akaszynski** [comment]
Pyramids are probably better:

```
import pyvista as pv
import numpy as np

points = np.random.random((10, 3))
point_cloud = pv.PolyData(points)

pointa = [1.0, 1.0, 1.0]
pointb = [-1.0, 1.0, 1.0]
pointc = [-1.0, -1.0, 1.0]
pointd = [1.0, -1.0, 1.0]
pointe = [0.0, 0.0, 2.0]
pyramid = pv.Pyramid([pointa, pointb, pointc, pointd, pointe])
pyramid = pyramid.extract_surface()

glyphs = point_cloud.glyph(factor=0.05, geom=pyramid)
glyphs.plot(color='grey', background='w')
```

![sc](https://user-images.githubusercontent.com/11981631/112232263-e29f2780-8bfd-11eb-90ad-0f82e53978cf.png)

If you really want to use triangles:
```
triangle = pv.PolyData([[0, 0, 0],
                        [1, 0, 0],
                        [0.5, 0.5, 0]],
                       [3, 0, 1, 2])
# use triangle in geom=
```

**Comment by zhen-dong-zhang** [comment]
Hi Alex,
Thanks for your reply. It really helps!
But I found it is hard to adjust the angle of the pyramid especially when I set the cpos.
What I need is a triangle marker. I'm wondering whether there are other ways to add a marker to a figure?
Otherwise, I may try different pyramids.
Best Regards,
Zhendong

**Comment by akaszynski** [comment]
AFAIK, there's no way to have an orientation independent "sprite" or 2D figure in VTK.  I'd recommend changing the orientation of the `PolyData` by changing the coordinates themselves, or simply rotating it with `rotate_x`, `rotate_y`, or `rotate_z`.

**Comment by zhen-dong-zhang** [comment]
Hi Alex,
Thanks a lot for your suggestions.
I will play with rotations.
Best Regards,
Zhendong
