### ISSUE TITLE
Rotating Glyphs

### ISSUE THREAD

**Issue by laserman781** [pyvista/pyvista-support#39]
I am trying to plot points as blocks, and the goal is to have them all perfectly in line. I've been able to have the blocks stack perfectly although they would need to be rotated in order to be perfect. How would I go about this?
![image](https://user-images.githubusercontent.com/12982931/62544492-db12eb00-b82d-11e9-8912-96d6d629e494.png)
Code so far:
```
block_pts = blocks[['x', 'y', 'z']].values
Poly = pv.PolyData(block_pts)
geom = pv.Cube()
cubes = Poly.glyph(geom=geom,scale=False,factor=75,absolute=True)
p = pv.Plotter()
p.add_mesh(cubes)
p.plot()
```

**Comment by banesullivan** [comment]
Rotating the `geom` object before passing it as the glyph geometry should do this. Try using one of `rotate_x()`, `rotate_y()`, `rotate_z()` or some custom rotating function you have on the `geom` object:

```py
...
geom = pv.Cube()
geom.rotate_z(33.3) # this is performed inplace
cubes = Poly.glyph(geom=geom, scale=False, factor=75, absolute=True)
...
```
