### ISSUE TITLE
Calculate volume of overlap between two meshes

### ISSUE THREAD

**Issue by renatobellotti** [pyvista/pyvista-support#391]
## Description

Hello,

I'm trying to analyse some medical image data with pyvista. I have a set of contours of organs. They are given as a set of points connected by straight lines. I managed to build a mesh for every organ using 3D Delaunay triangulation. Now I'm interested in the overlap between different structures. Is there a possibility to calculate a mesh of the overlap region and calculate its volume?

Thanks for this amazing package, it looks really cool!

**Comment by renatobellotti** [comment]
Nevermind, I've found ``boolean_difference()``. Sorry for not looking for the right keywords at first.

**Comment by akaszynski** [comment]
> Nevermind, I've found boolean_difference(). Sorry for not looking for the right keywords at first.

Thanks for posting your solution here!
