### ISSUE TITLE
Issue with modified mesh coordinates

### ISSUE THREAD

**Issue by jbbarre** [pyvista/pyvista-support#394]
Hello,

I have already described my problem on [StackOverflow](https://stackoverflow.com/questions/66966578/reproject-mesh-points-of-vtu-file-using-pyvista-and-pyproj). But here, I'm gonna try to be more specific. 

## Description

I need to transform the mesh coordinates of a pvtu file (a glacier) from an original coordinates reference system (CRS) (EPSG 27562) to a destination CRS (EPSG 4326). For that purpose, I use the pyproj module. It can transform a NumPy array from a CRS to another. On my dataset, everything went ok.  Then, I updated the pyvista object with the transformed coordinates. It looks like everything went ok again, but the plot just shows me a line of points instead of the 3d model. I checked multiples times the arrays type of the different objects. The object _mesh.points_ seems to work as before the reprojection, but seems only.

I can't figure out where the problem comes from? Any suggestion is welcome. 

Here is my code:

```py
import pyvista as pv
import numpy as np
import os
from pyproj import Transformer
from pyproj import CRS
from pyproj import Proj,itransform


#load data
filename = os.path.join("C:\\argentiere\\", "arg_Tm2__t0002.pvtu")
mesh = pv.read(filename)
#mesh.plot(scalars="height", categories=True)
print(mesh.points)

#Lambert II centre France
crs1= CRS.from_epsg(27562)
#WGS84
crs2 = CRS.from_epsg(4326)
# create the transformer
reproj = Transformer.from_crs(crs1, crs2)
# Reprojection
reproj_dataY,reproj_dataX,altitude =  reproj.transform(mesh.points[:,0],mesh.points[:,1],mesh.points[:,2])
print ('Longitude WGS84:', reproj_dataX)
print ('Latitude WGS84:', reproj_dataY)
print ('Altitude WGS84:', altitude)

# create the numpy array
reprojData = np.column_stack((reproj_dataX,reproj_dataY,altitude))
print('Original Mesh points -> ', mesh.points)
print('Original Mesh type: ', type(mesh.points))
print('Reprojected points-> ', reprojData)
print('Reprojected type: ', type(reprojData))

#update the pyvista object
mesh.points = reprojData
print(mesh.points)
type(mesh.points)
print(mesh)

mesh.plot(scalars="height", categories=True)
```

## Example Data
here is the data: https://github.com/jbbarre/glacierargentiere.git

**Comment by banesullivan** [comment]
I suspect this is because only the XY values and Z were left untouched. Before the transform, the XYZ arrays were all in the same units. After the transform, XY are in one unit and Z is in some other unit. Hence the dramatic difference in extents for XY and Z.

```py
# at the end
>>> np.array(mesh.bounds).reshape((3,-1)).ptp(axis=1)
array([1.22515302e-01, 7.78657599e-02, 2.47978788e+03])
```
Note the large extent difference for Z compared to X and Y.

Try scaling the Z array.

```py
mesh.points[:,-1] /= 100000
mesh.plot(notebook=0)
```

<img width="624" alt="Screen Shot 2021-04-06 at 10 36 55 PM" src="https://user-images.githubusercontent.com/22067021/113811005-9f2dd880-9728-11eb-9fde-4aa3533e87b7.png">

**Comment by jbbarre** [comment]
You are right: with WGS84, X and Y are in degrees and Z still in meter. In the previous CRS, everything was in meter. Thank you for pointing this out.
