### ISSUE TITLE
Black  jagged edges on surfaces

### ISSUE THREAD

**Issue by fmz0211** [pyvista/pyvista-support#396]
## Description
When I use pyvistajin to visualize intracranial blood vessels and turn on smooth_shading, there are jagged edges in part of the blood vessels, as shown in the following figure. How to eliminate the jagged edges?

**Comment by banesullivan** [comment]
Can you please provide screenshots and a way to reproduce this issue?

**Comment by fmz0211** [comment]
smooth shading:
![1](https://user-images.githubusercontent.com/48152544/113888376-e1245080-97f4-11eb-83cb-6ad0d8550ab5.png)
   default flat shading:
![2](https://user-images.githubusercontent.com/48152544/113888484-f9946b00-97f4-11eb-85b0-d832aeb0b1ca.png)

**Comment by banesullivan** [comment]
Huh, very strange.... (also, cool dataset!!)

If you can share that mesh (`mesh.save('mesh.vtk')`), and share here, that'd be very helpful. Otherwise, we'll need to try to reproduce this with some other mesh. Unfortunately, I suspect this is a result of the geometry of this specific mesh so it will likely be difficult to debug without that particular mesh.

**Comment by fmz0211** [comment]
[surface.zip](https://github.com/pyvista/pyvista-support/files/6275529/surface.zip)
The polydata was shared in the zip file.
To Visualize the mesh, the code was as follows:
 `p.add_mesh(surf, scalars="wss", cmap="jet", name='surf', diffuse=0.5, specular=0.5, ambient=0.5, smooth_shading=True) `

**Comment by banesullivan** [comment]
This is indeed very, very add. The shading implies there is something wacky going on with the mesh in the spots, but the edges look generally okay there.

```py
p = pv.Plotter(notebook=False, shape=(1,3), window_size=[1024*3, 768])

p.add_mesh(surf, scalars="wss", cmap="jet", 
           diffuse=0.5, specular=0.5, ambient=0.5, smooth_shading=True)
p.subplot(0,1)
p.add_mesh(surf, scalars="wss", cmap="jet", show_edges=True)

p.subplot(0,2)
p.add_mesh(surf, scalars="wss", cmap="jet", 
           diffuse=0.5, specular=0.5, ambient=0.5, smooth_shading=True,
           show_edges=True
          )

p.link_views()
p.camera_position = [(33.32891224208835, 86.53576807799237, 49.08600322635364),
 (9.36415211987961, 51.68663420434663, 66.25997551310361),
 (-0.7880054389655586, 0.6030357268560812, 0.12407796055647834)]
p.show()
```

![Screen Shot 2021-04-09 at 9 15 18 AM](https://user-images.githubusercontent.com/22067021/114202121-225f5200-9914-11eb-8dcd-956ffc704d79.png)


A view from inside too:

![Screen Shot 2021-04-09 at 9 16 28 AM](https://user-images.githubusercontent.com/22067021/114202307-4a4eb580-9914-11eb-95a1-41c366e2cfa8.png)


I can kind off see these lines/shadows following the edges of some cells which made me wonder if the feature edges are a little sharper in these regions and thus having some odd shading effects.

```py
edges = surf.extract_feature_edges(feature_angle=30)

p = pv.Plotter(notebook=False, shape=(1,3), window_size=[1024*3, 768])

p.add_mesh(surf, scalars="wss", cmap="jet", 
           diffuse=0.5, specular=0.5, ambient=0.5, smooth_shading=True)
p.subplot(0,1)
p.add_mesh(surf, scalars="wss", cmap="jet", show_edges=True)

p.subplot(0,2)
p.add_mesh(surf, scalars="wss", cmap="jet", 
           diffuse=0.5, specular=0.5, ambient=0.5, smooth_shading=True,
           show_edges=True
          )
p.add_mesh(edges, color='red', line_width=5)

p.link_views()
p.camera_position = [(33.32891224208835, 86.53576807799237, 49.08600322635364),
 (9.36415211987961, 51.68663420434663, 66.25997551310361),
 (-0.7880054389655586, 0.6030357268560812, 0.12407796055647834)]
p.show()
```

and indeed that is what we are seeing:

![Screen Shot 2021-04-09 at 9 19 30 AM](https://user-images.githubusercontent.com/22067021/114202762-bdf0c280-9914-11eb-823f-83b911e74651.png)

I can't, off the top of my head come up with a clean way to smooth these edges. I tried the [`smooth()`](https://docs.pyvista.org/core/filters.html#pyvista.PolyDataFilters.smooth) filter without much luck.

```py
smooth = surf.smooth(n_iter=1000, feature_angle=30, feature_smoothing=True,
```

I figured I'd at least try to help outline what's going one though I don't have a good solution for you off hand

**Comment by fmz0211** [comment]
Thanks a lot! 
I've met this problem for a long time, but always can't find a right way to solve it. U provided a good idea that may solve this problem in future.

**Comment by banesullivan** [comment]
You may want to open an issue on the VTK discourse about this and see if there are methods to resolve these shading artifacts around sharp feature angles

https://discourse.vtk.org

**Comment by fmz0211** [comment]
good idea :)

**Comment by akaszynski** [comment]
Fixed it using `pymeshfix`:

```py
import pyvista

mesh = pyvista.read('surface.vtk')
# mesh.plot(smooth_shading=True, color='w')



# help(mesh.compute_normals)

# mesh_fixed = mesh.compute_normals(auto_orient_normals=True,
#                                   consistent_normals=True,
#                                   non_manifold_traversal=False)

import pymeshfix
pfix = pymeshfix.MeshFix(mesh)
pfix.repair()
mesh_fixed = pfix.mesh

mesh_fixed.plot(smooth_shading=True, color='w')


pl = pyvista.Plotter()
pl.add_mesh(mesh_fixed, scalars="wss", cmap="jet", name='surf', diffuse=0.5,
            specular=0.5, ambient=0.5, smooth_shading=True)
```

Issue has to with the ordering of the triangles.

**Comment by banesullivan** [comment]
Nice work, @akaszynski!

**Comment by fmz0211** [comment]
Thanks very much!
Before we discussed this issue may be caused by the direction of the normals, but with modifying the direction of normals, the issue existed still.  U done a very nice work, Alex.
