### ISSUE TITLE
Problem with triangulation of a point cloud

### ISSUE THREAD

**Issue by subodh-malgonde** [pyvista/pyvista-support#397]
## Description

I have a numpy array, which contains the `(X, Y, Z)` coordinates of the points. It is of shape `(N, 3)` where N is the number of points in the cloud. I convert this numpy array to `pyvista.PolyCloud` object.

Also these points are on the surface of a sphere. However they do not cover the entire sphere. Here is how it looks like:

![point_cloud](https://user-images.githubusercontent.com/5463437/113876014-f4bfbf00-97d4-11eb-900f-f2ef0db0c3bf.png)

I want to triangulate this point cloud so that a smooth surface is generated. I tried using the `delaunay_2d` method with various values of `alpha` such as `0.9, 1.0, 1.5, 2,` etc. However each time I get a similar result, which looks like this:

![delaunay_2d](https://user-images.githubusercontent.com/5463437/113877016-eb832200-97d5-11eb-90c0-1774edd1f58f.png)

Increasing the value of alpha beyond 1.0 does not make sense since the points are uniformly spaced with a distance of approx. `0.89`.

Using `delaunay_3d` gives a better result, but it also includes triangles which are not on the surface of the sphere.

![delaunay_3d](https://user-images.githubusercontent.com/5463437/113877690-91369100-97d6-11eb-968e-3cd63a28259c.png)

Using non-zero values of alpha (between 0.85 and 0.95) results in something closer to my desired result, but some triangles are missed.

![delaunay_3d_alpha](https://user-images.githubusercontent.com/5463437/113878813-92b48900-97d7-11eb-9899-6162b810d16d.png)

What am I missing here?

**Comment by akaszynski** [comment]
My experience with `delaunay_3d` has been fraught with difficulties.  What you can do is just remove the large "faces" with:

```py
import pyvista as pv

sphere = pv.Sphere()
areas = sphere.compute_cell_sizes().cell_arrays['Area']

some_max_area = <user-value>
final_mesh = sphere.extract_cells(areas < some_max_area)
```

**Comment by banesullivan** [comment]
Since this is a poly surface, you should stick with delaunay_2D. The Delaunay filter reprojects the data to a plane first. I suspect the best-fitted plane is not great. I would recommend manually projecting the data to a plane, running the Delaunay filter, and then copying the cell connectivity back to the original mesh.

**Comment by subodh-malgonde** [comment]
Thanks for the suggestions @akaszynski  and @banesullivan. Using `delaunay_3d` and removing large faces worked for me. Here is the code:

```
# point_cloud_numpy_array has shape (N, 3) where N is the number of points
point_cloud = pv.PolyData(point_cloud_numpy_array)

surface = point_cloud.delaunay_3d(progress_bar=True).extract_surface().triangulate().clean()
areas = surface.compute_cell_sizes().cell_arrays['Area']
final_surface = surface.extract_cells(areas < 1).extract_surface().triangulate().clean()
```

I am running `extract_surface().triangulate()` so that the `UnstructuredGrid` is converted to a `PolyData` object, allowing computation of area. Otherwise area computed is zero.

**Comment by akaszynski** [comment]
Thanks!  Sometimes the easiest solution is the best.
