### ISSUE TITLE
Camera view

### ISSUE THREAD

**Issue by gunjan71011** [pyvista/pyvista-support#40]
Hello, I am trying to figure out if we can focus on one mesh when plotting multiple meshes. I would like the camera to focus on that mesh more, for example if one mesh is really small, then I would like to zoom in to that to see the details on it.

**Comment by banesullivan** [comment]
Hi @gunjan71011, this an excellent question! Like most tasks in PyVista, there a few ways this can be done. One of the easiest would be to tell the plotter that the camera has been set after adding the small mesh to the scene. For example, create a plotter and add the mesh you'd like to focus on first:

```py
p = pv.Plotter()
p.add_mesh(focus_mesh) # this is the one to focus on
p.camera_set = True # tell the plotter that the camera has been set and to not automatically adjust
p.add_mesh(some_mesh)
p.add_mesh(another_mesh)
p.show()
```

another easy option would be to use a convenience method like `set_focus` with the center of the mesh as the focus point:

```py
p = pv.Potter()
p.add_mesh(focus_mesh)
p.add_mesh(some_mesh)
p.add_mesh(another_mesh)
p.set_focus(sphere.center)
p.camera_set = True
p.show()
```

Or you could manually set the camera position if you have that already - FYI after the `show()` call, the last used camera position if returned. You could zoom/pan to a view you like and copy/paste that position into your code to set the position manually:

```py
p = pv.Potter()
p.add_mesh(focus_mesh)
p.add_mesh(some_mesh)
p.add_mesh(another_mesh)
# tuple: camera location, focus point, viewup vector
p.camera_position = [(x, y, z), (fx,fy,fz,), (nx,ny,nz)]
p.show()
```

**Comment by gunjan71011** [comment]
Thanks Bane, that is exactly what I wanted!

**Comment by banesullivan** [comment]
Pro tip if you weren't aware: you can hold the `shift` key while clicking the scene to pan/translate the camera

**Comment by mli0603** [comment]
Hi Bane @banesullivan , I ran into a similar but not exact problem. I need to control the camera position, focal point, view up and view angle individually. It looks like the view angle (the zoom level) is not supported yet. But the first three do not work if I use the interface from the BasePlotter. Here is a minimal example.

```python
import pyvista as pv
from pyvista import examples

mesh = examples.load_airplane()

# set camera position
cpos = [(-15862.8819973254, 5342.483170010628, 4153.88265742117),
 (896.9955291748047, 676.0221252441406, 132.19440269470215),
 (0.20163101424110583, -0.114200357111363, 0.9727811740220615)]

# this works
plotter = pv.Plotter(off_screen=True)
plotter.add_mesh(mesh, color='tan')
plotter.camera_position = cpos
plotter.show(screenshot='airplane_1.png')

# this should render exactly the same image but the output is blank
plotter = pv.Plotter(off_screen=True)
plotter.add_mesh(mesh, color='tan')
plotter.set_position([-15862.8819973254, 5342.483170010628, 4153.88265742117])
plotter.set_focus([896.9955291748047, 676.0221252441406, 132.19440269470215])
plotter.set_viewup([0.20163101424110583, -0.114200357111363, 0.9727811740220615])
plotter.show(screenshot='airplane_2.png')
```
In both cases, the camera parameters are identical. The second image should be the same as the first one. However, the second image renders only background. Do you know why this is the case? Thank you!

**Comment by banesullivan** [comment]
Ah, this is actually intentional behavior. The clipping planes for the camera only get reset on a full camera position set by PyVista (e.g. `reset_camera` or on the `camera_position` property. Setting intermediate values will not trigger the clipping planes to reset. This is needed by some folks (and myself at one point). To mitigate, call `plotter.renderer.ResetCameraClippingRange()` after calling each of the set methods.

If you predefine the camera position and want the clipping planes to reset, then use the `.camera_position` property setter to do all three at once.

**Comment by mli0603** [comment]
Thanks @banesullivan ! That solved the problem. Good to know the cliping planes need to be reset.

**Comment by banesullivan** [comment]
It would be good to add a `reset_camera_clipping_planes` wrapper on the `Renderer` and `BasePlotter` if you are up for a pull request

**Comment by mli0603** [comment]
I will take a look into that

**Comment by mli0603** [comment]
@banesullivan I just created a pull request. this is my first time so let me know if I did anything wrong :)
