### ISSUE TITLE
remove_actor() in pvQtInteractor

### ISSUE THREAD

**Issue by bistek** [pyvista/pyvista-support#408]
I have been using SetVisibility for some time. Unfortunately I have just found a bug or at leas an unexpected behaviour. If a scalar property or a texture is shown it appears that SetVisibility does not work, i.e. it is not able to show or hide the actor.

Do you have ideas about this?

Thanks!

**Comment by akaszynski** [comment]
Could you please post a minimum working example?

**Comment by banesullivan** [comment]
Yeah, we'll need to see your code. I cannot reproduce.

```py
import pyvista as pv
from pyvista import examples

mesh = examples.load_globe()

p = pv.Plotter(notebook=0)
actor = p.add_mesh(mesh)

def toggle_vis(flag):
    actor.SetVisibility(flag)

p.add_checkbox_button_widget(toggle_vis, value=True)

p.show()
```

![2021-04-15 15 58 30](https://user-images.githubusercontent.com/22067021/114943642-88ac0f00-9e03-11eb-8591-65bc5881640b.gif)


or with scalars

```py
mesh = examples.load_hexbeam()

p = pv.Plotter(notebook=0)
actor = p.add_mesh(mesh)

def toggle_vis(flag):
    actor.SetVisibility(flag)

p.add_checkbox_button_widget(toggle_vis, value=True)

p.show()
```
![2021-04-15 15 58 48](https://user-images.githubusercontent.com/22067021/114943647-8ba6ff80-9e03-11eb-8c50-8f76a81a547b.gif)

**Comment by bistek** [comment]
Hello, I'm using `pyvistaqt` in a QT application, with several objects, actors, etc., so it's a bit difficult to isolate the problem in a few lines of code. I'll update all the libraries and see if the problem is still there. Then I will dig more in depth...

Question: the `SetVisibility()`, `VisibilityOn()` and `VisibilityOff()` methods are re-implemented somehow in PyVista, or they are the standard VTK methods inherited transparently? In the second case maybe I should post this issue to VTK developers directly...

Thanks!

**Comment by bistek** [comment]
Hello, I have traced the problem upwards in the code, and it looks like that the real problem is different.

In my application, when I change the property shown by an actor that is already shown, or apply a texture, I (1) remove the old actor, and (2) create a new actor with the same name of the old actor. In this way I am able to always use the same "name" (the name of the actor) to call it for instance to set visibility on and off.

Note that I am not aware of a different/better way to change the appearance of an actor, since filters like colour maps, textures etc. are created before creating the actor in the VTK pipeline.

This is the way it SHOULD work. However I have noticed that the actor are no longer removed from the scene with `self.plotter.remove_actor(name_of_the_actor)`, hence actors with the same name start accumulating and the system does not work anymore. For instance `SetVisibility()` no more points to the right actor.

Here `self `is my Qt window and `plotter `is an instance of `pvQtInteractor `(I am using pyvistaqt).

My present impression is that the `remove_actor()` method is not working, This is surprising because it used to work some time ago. Unfortunately I cannot say easily since which release of pyvistaqt we have this problem. At the moment I am using the last one installed with conda:

pyvista                   0.29.1             pyhd8ed1ab_0    conda-forge
pyvistaqt                 0.3.0              pyhd8ed1ab_0    conda-forge
vtk                       9.0.1           no_osmesa_py37h278bbdf_106    conda-forge

qt                        5.12.9               h5909a2a_4    conda-forge
qtawesome                 1.0.2              pyhd8ed1ab_0    conda-forge
qtconsole                 5.0.3              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge

Maybe you will be able to reproduce this problem, or alternatively point me to a way to remove the actor directly with a VTK method.

Thanks very much!

**Comment by bistek** [comment]
One more detail. If I get the output from `remove_actor()`, it should be `True` if the actor is successfully removed and `False` if it is not removed. However I got `True` and the actor is still there in the middle of my window, so definitely not removed.

I hope this could be useful!

**Comment by bistek** [comment]
I changed the title after recognizing what the real issue is. Thanks!

**Comment by bistek** [comment]
Solved! When calling `plotter.remove_actor()` I was using the name of the actor, like in `plotter.remove_actor('actor')`, instead of the actor as an object, like in `plotter.remove_actor(actor)`.

The real problem was tracing the error in a large code with Qt involved etc., so I have a suggestion: a property of the plotter that returns a list or dictionary of actors would be very useful. I guess that this is included in the Renderer() class, but apparently not passed to QtInteractor().

Thanks very much!
