### ISSUE TITLE
camera adjustment problems

### ISSUE THREAD

**Issue by nschloe** [pyvista/pyvista-support#412]
I'm having a little trouble adjusting the default camera position for my sliced views. The slice is always
```python
slc = grid.slice([1.0, 0.0, 0.0], [x, 0.0, 0.0])
```
The default view generated by pyvista is

![out](https://user-images.githubusercontent.com/181628/115438511-c64ad680-a20d-11eb-8866-0d68c84a1f11.png)

I'd love to have it _orthogonal_ on the slice of course, and ideally locked that way. Any idea how this can be achieved?

**Comment by tkoyama010** [comment]
You can set the camera position explicity using [`pyvista.Camera`](https://dev.pyvista.org/core/camera.html
) class.

```python
p = pv.Plotter()
p.camera.position = (1.1, 1.5, 0.0)
p.camera.focal_point = (0.2, 0.3, 0.3)
p.camera.clipping_rang =  (0.3, 0.8)
```
![camera_1_0](https://user-images.githubusercontent.com/7513610/115476330-9be43200-a27c-11eb-9b8b-4d7363f52dee.png)

**Comment by nschloe** [comment]
Thanks for the explanation! Is it possible to rotate the camera, too?

**Comment by tkoyama010** [comment]
Yes. You can `Roll`, `Elevation` and `Azimuth` the camera.
```python
p = pv.Plotter()
p.camera.Roll(45.0)
p.camera.Elevation(60.0)
p.camera.Azimuth(30.0)
```
This it the direct acess to method of `vtkCamera` object so you can reference it's [API document](https://vtk.org/doc/nightly/html/classvtkCamera.html#a138feeb7a5e7b45bd078ab9cf3cb3391). 

![camera](https://raw.githubusercontent.com/Kitware/vtk-examples/gh-pages/src/Testing/Baseline/Python/Visualization/TestCameraModel1.png)

**Comment by nschloe** [comment]
Perfect, thank you!

**Comment by akaszynski** [comment]
> Yes. You can `Roll`, `Elevation` and `Azimuth` the camera.
> 
> ```python
> p = pv.Plotter()
> p.camera.Roll(45.0)
> p.camera.Elevation(60.0)
> p.camera.Azimuth(30.0)
> ```
> 
> This is the direct acess to method of `vtkCamera` object so you can reference it's [API document](https://vtk.org/doc/nightly/html/classvtkCamera.html#a138feeb7a5e7b45bd078ab9cf3cb3391).
> 
> ![camera](https://raw.githubusercontent.com/Kitware/vtk-examples/gh-pages/src/Testing/Baseline/Python/Visualization/TestCameraModel1.png)

We might want to wrap these to make them more pythonic, like:
```py
>>> p.camera.roll = 30
>>> p.camera.roll
30
```

**Comment by tkoyama010** [comment]
+1 for wrapping. I will make PR.
