### ISSUE TITLE
2D streamlines

### ISSUE THREAD

**Issue by guido-granda** [pyvista/pyvista-support#414]
## Description
Hello,
I'm trying to use the streamlines in two dimensions. To do this I'm using a 3d vector field with one component of the vector field equal to zero and a grid with the x dimension given only by one cell. I'm getting an error message saying that the mesh has zero points, however when I print meshx.n_points I get the expected number of points. How is the right way to do this?

```
import pyvista as pv
import numpy as np
import h5py
import sys
import matplotlib.pyplot as plt
from data_helper import *

file_n="/home/guido/sims_snapshot/reg_test_50h5.h5"
f = h5py.File(file_n,'r')
x=np.array(f['/grid/x']) # cm
y=np.array(f['/grid/y']) # cm
z=np.array(f['/grid/z']) # cm
dens=np.array(f['/grid/dens']) # g/cm³
dx=np.array(f['/grid/dx'][0]) # cm
bx=np.array(f['/grid/magx'])/1e-6 # uG
by=np.array(f['/grid/magy'])/1e-6 # uG
bz=np.array(f['/grid/magz'])/1e-6 # uG

x_min=np.amin(x)
x_max=np.amax(x)
y_min=np.amin(y)
y_max=np.amax(y)
z_min=np.amin(z)
z_max=np.amax(z)


x_lin=np.arange(x_min,x_max+dx,dx)
y_lin=np.arange(y_min,y_max+dx,dx)
z_lin=np.arange(z_min,z_max+dx,dx)

tidy_dens=tidy_3d_field(x,y,z,dens,dx,dx,dx)
tidy_bx  =tidy_3d_field(x,y,z,bx,dx,dx,dx)
tidy_by  =tidy_3d_field(x,y,z,by,dx,dx,dx)
tidy_bz  =tidy_3d_field(x,y,z,bz,dx,dx,dx)

#x slice
spacing=(dx,dx,dx)
origin =(x_min,y_min,z_min)
meshx = pv.UniformGrid((1,y_lin.shape[0],z_lin.shape[0]),spacing,origin)

vectors = np.empty((meshx.n_points, 3))
vectors[:,0]=np.zeros(x_lin.shape[0]**2)
vectors[:,1]=tidy_by[32,:,:].reshape(((y_lin.shape[0]**2)))
vectors[:,2]=tidy_bz[32,:,:].reshape(((z_lin.shape[0]**2)))


meshx['vectors']=vectors

stream = meshx.streamlines('vectors',n_points=100 )
p = pv.Plotter(notebook=False)
p.add_mesh(meshx.outline(), show_edges=True, color='white')
p.add_mesh(stream.tube(radius=3.0e16), lighting=False)
```

## Error

5 p.add_mesh(stream.tube(radius=3.0e16), lighting=False)
      6 #p.add_mesh(slices, **dargs)
      7 #mesh.plot(scalars='dens',opacity="geom",cmap=boring_cmap)

~/anaconda3/envs/hubble/lib/python3.8/site-packages/pyvista/plotting/plotting.py in add_mesh(self, mesh, color, style, scalars, clim, show_edges, edge_color, point_size, line_width, opacity, flip_scalars, lighting, n_colors, interpolate_before_map, cmap, label, reset_camera, scalar_bar_args, show_scalar_bar, stitle, multi_colors, name, texture, render_points_as_spheres, render_lines_as_tubes, smooth_shading, ambient, diffuse, specular, specular_power, nan_color, nan_opacity, culling, rgb, categories, use_transparency, below_color, above_color, annotations, pickable, preference, log_scale, render, **kwargs)
   1487 
   1488         if mesh.n_points < 1:
-> 1489             raise ValueError('Empty meshes cannot be plotted. Input mesh has zero points.')
   1490 
   1491         # Try to plot something if no preference given

ValueError: Empty meshes cannot be plotted. Input mesh has zero points.

**Comment by MatthewFlamm** [comment]
Your `meshx` object has points, but your `stream` object does not.  The reason is that the default behavior for `streamlines` is to use a 3D sphere to pick starting pointse.  Check the documentation for [`streamlines`](https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.streamlines).  You will almost never have a point on a sphere lie on the plane you have chosen.

It would be great if you could pass in an arbitrary object if needed, but a workaround is to use `meshx.streamlines(source_radius=0, n_points=1, source_center=(x, y, z))`.  Then you can construct your own set of streamlines with a set of `(x, y, z)` values.  You can group them into a `Multiblock` dataset if you like.  You can also use a line using the `pointa` and `pointb` parameters.

There is also a `surface_streamlines` parameter that will do what you want without the preprocessing of the normal direction.

The documentation of this filter is confusing, so it takes some trial and error to figure out what actually happens.

**Comment by guido-granda** [comment]
Thank you for your help. Yeah, the documentation is confusing. I have some questions:
1) When I use meshx.streamlines(source_radius=0, n_points=1, source_center=(x, y, z)) It still uses the sphere for the sphere but only with the central point?
2) To construct a set of streamlines using the method you mention, do you mean doing sth like this:
`    stream[i] =mesx..streamlines(source_radius=0, n_points=1, source_center=(x[i], y[i], z[i]))`
   this inside a loop because I think that source_center just accepts the three coordinates.
3) I tried making a single stream line on this way:
`stream,src = mesh.streamlines('vectors',start_position=[0.0,3.0e18,1.2e19],n_points=1,return_source=True)`
  is this also correct to obtain a single streamline ?
4) I'm really confused about how to use the parameters pointa and pointb. Are the also used to set the coordinate of the streamline on the following way:
`stream,src = mesh.streamlines('vectors',pointa=[0.0,3.0e18,1.2e19],n_points=1,return_source=True)`
Thank you,

**Comment by MatthewFlamm** [comment]
For 1 and 2, yes. 

 For 3, I'm not sure what `start_position` does.  It isn't documented well.  I think it is supposed to allow what you are suggesting, but I'm not sure it works by looking at the code.  Have you tried it?

For 4, you would use something like `stream,src = mesh.streamlines('vectors',pointa=[x,y,z], pointb=[xb, yb, zb], n_points=100, return_source=True)`.  This gives you 100 points between `pointa` and `pointb`.

I also opened a PR to allow an arbitrary source mesh to be used as a starting source, hopefully not too add to the confusion on all the options here.

**Comment by MatthewFlamm** [comment]
For number 2 after making a list of streamlines from single points in the `stream` object, you can make the list into a `MultiBlock` object.  I find this convenient for plotting later.

```python
mb_stream = pyvista.MultiBlock(stream)
```

**Comment by MatthewFlamm** [comment]
I tested `start_position` and it seems to have no effect, no matter how you provide it.  I raised an issue https://github.com/pyvista/pyvista/issues/1291.
