### ISSUE TITLE
Colormap issue between version 0.29.1 and 0.25.3

### ISSUE THREAD

**Issue by vpicouet** [pyvista/pyvista-support#417]
Hello,
using the exact same code I get two different color maps between version 0.29.1 and 0.25.3.
version 0.25.3:
![Capture d’écran, le 2021-05-04 à 08 52 44](https://user-images.githubusercontent.com/37241971/116969316-5c730800-acb6-11eb-8a38-d66da5480822.jpg)
version 0.29.1:
![Capture d’écran, le 2021-05-04 à 08 51 08](https://user-images.githubusercontent.com/37241971/116969322-5f6df880-acb6-11eb-93f3-8ec4844a5a2c.jpg)

In the last versions I do not manage to get a meaningful colormap. I stayed in version  0.25.3 for the last few months but maybe you know how to solve the issue.
I plot the mesh like this:
```
range_ = [np.nanpercentile(data, 30), np.nanpercentile(data, 99)]
p.add_mesh(mesh, clim=range_, scalars=data.flatten(), opacity=0.7, nan_opacity=0, use_transparency=False, name="Data", flip_scalars=True, stitle="Value") 
```
Thanks

**Comment by akaszynski** [comment]
What happens if you force rng rather than `clim`?  Also, can you check if this bug still occurs with the master branch?  If the problem exists in both cases, can you post a minimum working example so we can reproduce this locally?

**Comment by vpicouet** [comment]
Thanks for the quick answer, it works perfectly well in both case when I force rng instead of clim!
Thanks
