### ISSUE TITLE
custom themes?

### ISSUE THREAD

**Issue by natter1** [pyvista/pyvista-support#419]
Pyvista provides a few Themes to change the appearence of plots. Is there a way to add a custom Theme? If it is not possible, consider this a festure request ;)

**Comment by JBum21** [comment]
See [here](https://docs.pyvista.org/examples/02-plot/cmap.html) on the docs.

**Comment by natter1** [comment]
Thanks @JBum21 but thats not exactly what I'm looking for. Its about [Themes](https://docs.pyvista.org/examples/02-plot/themes.html?highlight=theme), not just a custom color map. Basically the default themes are implemented as dict, so I guess I could write my own function to write to rcParams, but if there are default themes, why shouldn't there be a functionality to add/use custom themes?

**Comment by natter1** [comment]
Thats how it could look like [here](https://github.com/natter1/playground/blob/master/plotter_theme.py)

**Comment by akaszynski** [comment]
Implementing something like this within https://github.com/pyvista/pyvista/pull/1310

I'll document creating a custom theme, but the idea would be something like:

```
import pyvista
from pyvista import Theme
my_theme = Theme
my_theme.font = 'courier'

pyvista.theme = my_theme
```

Would something like that work?  You could also subclass your theme and use that.
