### ISSUE TITLE
Set recovery angle in voxelizer?

### ISSUE THREAD

**Issue by laserman781** [pyvista/pyvista-support#42]
Is there a way to set the voxelizer recovery angle? There is a method for setting the cell sizes, although I have not been able to find a way to do this with the recovery angle.

I have a uniform point grid and I receive the proper deltas and recovery angle when I plot it as a whole. Although, when I try to sort for blocks within a certain range and plot it the angle seems to be different and the cubes overlap when they should not be.

`voxelizer_sorted  = PVGeo.filters.VoxelizePoints(unique=False, estimate=False) voxelizer_sorted.set_deltas(75,75,75)`

what I would like to do:

`voxelizer_sorted.set_angle(get_recovered_angle(degrees=False))`

**Comment by banesullivan** [comment]
I just added this feature on the master branch of PVGeo in https://github.com/OpenGeoVis/PVGeo/commit/33dfda2057a8f2be31bca596e0d807f123f7f7e3

With those changes, you can now use `set_angle`:

```py
voxelizer_sorted = PVGeo.filters.VoxelizePoints(unique=True, estimate=False) 
voxelizer_sorted.set_deltas(75,75,75)
voxelizer_sorted.set_angle(np.pi / 3.0) # in radians
```

**Comment by laserman781** [comment]
This is the error I am receiving when I execute the code above:

AttributeError: 'VoxelizePoints' object has no attribute 'set_angle'

**Comment by banesullivan** [comment]
Have you upgraded PVGeo to the version on the master branch?

```bash
pip uninstall PVGeo
pip install git+git://github.com/OpenGeoVis/PVGeo@master
```

**Comment by laserman781** [comment]
![image](https://user-images.githubusercontent.com/12982931/62886813-e5d7ef00-bd09-11e9-88d2-55b9cc20e70d.png)

This is my version^

The code above isn't running at all...

**Comment by banesullivan** [comment]
But did you install PVGeo from the master branch on GitHub? `2.0.3` is the deployed version on PyPI but the master branch will also show that as its version even though they are different states of the software.

Make sure you uninstall PVGeo, reinstall from the master branch, shutdown your Python kernels, relaunch, and re-import PVGeo

**Comment by laserman781** [comment]
Got it, thank you so much!
