### ISSUE TITLE
Colorbar scale problem with 3D structured data

### ISSUE THREAD

**Issue by petercorke** [pyvista/pyvista-support#425]
Using PyVista 0.30.1 with Numpy 1.19.5 on macOS Catalina.

## Description

I have a  function Z=f(X,Y) and I want the colorbar to indicate height.  This code is based on the examples.

```
import pyvista as pv
import numpy as np
from matplotlib import cm

x = np.arange(-10, 10, 0.25)
y = np.arange(-10, 10, 0.25)
x, y = np.meshgrid(x, y)
r = np.sqrt(x ** 2 + y ** 2)
z = np.sin(r)

grid = pv.StructuredGrid(x, y, z)
print('z range is', z.min(), z.max())

plotter = pv.Plotter()
plotter.add_mesh(grid, show_scalar_bar=False, cmap=cm.get_cmap("viridis"), ambient=0.3, diffuse=0.8, specular=0.1, smooth_shading=True)

plotter.add_scalar_bar(title='Distance (m)',
    vertical=True,
    title_font_size=16,
    label_font_size=16,
    height=0.6,
    width=0.1,
    position_x=0.8,
    position_y=0.2)

plotter.show()
```
which produces this:

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/11801682/118096770-24d23180-b415-11eb-859c-43353015dd1c.png">

Two things are wrong:

1. The numbers on the color bar are way too high, and
2. The color gradient is in the x-direction not z- as I was expecting/wanting.

I saw a sketchy mention of a way to attach scalar data which led me to this (changed lines indicated)

```
import pyvista as pv
import numpy as np
from matplotlib import cm

x = np.arange(-10, 10, 0.25)
y = np.arange(-10, 10, 0.25)
x, y = np.meshgrid(x, y)
r = np.sqrt(x ** 2 + y ** 2)
z = np.sin(r)

grid = pv.StructuredGrid(x, y, z)
print('z range is', z.min(), z.max())
grid['Z'] = z   # CHANGED

plotter = pv.Plotter()
plotter.add_mesh(grid, show_scalar_bar=False, cmap=cm.get_cmap("viridis"), ambient=0.3, diffuse=0.8, specular=0.1, smooth_shading=True)

plotter.add_scalar_bar(title='Distance (m)',
    scalar='Z',  # CHANGED
    vertical=True,
    title_font_size=16,
    label_font_size=16,
    height=0.6,
    width=0.1,
    position_x=0.8,
    position_y=0.2)

plotter.show()
```
which generates the error
```
    raise ValueError(f'Number of scalars ({scalars.size}) '
ValueError: Number of scalars (6400) must match either the number of points (6400) or the number of cells (6241).
```

which is confusing since the number of scalars **does**  match the number of points - both are 6400.  But maybe I am not understanding this mechanism.

It would also be nice if the colorbar title could be positioned a bit further away from the top data label, or be rotated by 90 deg alongside the bar.

Kudos for the rapid evolution and quality of this package.  It's become my goto for 3d plotting now, faster and better than matplotlib.

**Comment by MatthewFlamm** [comment]
First example: I believe that since you do not have an active scalar to plot the first example colors by the cell number.  You have 6241 cells which matches the range in the color bar.  Using `grid.points` you can see the ordering of the points in the resulting grid to confirm that it is indeed ordered in the way it is plotted.

Second example:  You are on the right track.  The error message is not very helpful in this case.  It should say that the first dimension of the input must match the number of points or the number of cells.  This example works:

```python
import pyvista as pv
import numpy as np
from matplotlib import cm

x = np.arange(-10, 10, 0.25)
y = np.arange(-10, 10, 0.25)
x, y = np.meshgrid(x, y)
r = np.sqrt(x ** 2 + y ** 2)
z = np.sin(r)

grid = pv.StructuredGrid(x, y, z)
print('z range is', z.min(), z.max())
grid['Z'] = z.ravel()   # Note that this line was modified

plotter = pv.Plotter()
plotter.add_mesh(grid, show_scalar_bar=False, cmap=cm.get_cmap("viridis"), ambient=0.3, diffuse=0.8, specular=0.1, smooth_shading=True)

# Note that I removed an argument here
plotter.add_scalar_bar(title='Distance (m)',
    vertical=True,
    title_font_size=16,
    label_font_size=16,
    height=0.6,
    width=0.1,
    position_x=0.8,
    position_y=0.2)

plotter.show()
```

![image](https://user-images.githubusercontent.com/39341281/118301622-4b45aa80-b4b1-11eb-883b-b4fb09277e36.png)
