### ISSUE TITLE
Export meshes or .csv's as vtk

### ISSUE THREAD

**Issue by laserman781** [pyvista/pyvista-support#43]
Is there a method to export meshes or their csv files as a vtk file and not a vtkjs file? 

Thanks!

**Comment by banesullivan** [comment]
[`.save()`](https://docs.pyvista.org/core/common.html#pyvista.Common.save) on any PyVista mesh does this - just pass a filename with a `.vtk` extension.

Exporting as `.vtkjs` is only for the rendering scene.
