### ISSUE TITLE
it is pyvista compatible with pyside2?

### ISSUE THREAD

**Issue by ezalorpro** [pyvista/pyvista-support#44]
not much more to said, i want to embed a 3D surface plot in a PySide2 GUI, it is compatible? how?

regards

**Comment by banesullivan** [comment]
Yes, it is possible to embed a PyVista in a pyside2 app! This requires a bit of hacking but we could likely get a branch going in the main repo for this. I think simply replacing PyQt5 imports with PySide2 will do the trick 

Are you familiar with PyVista’s `BackgroundPlotter` class and the internal`QtInteractor`class it inherits?

https://github.com/pyvista/pyvista/blob/66e9495273adb0ca4fc5441e913d239837543140/pyvista/plotting/qt_plotting.py#L270

You’d likely need to inherit the `QtInteractor` class and embed that after replacing the PyQt5 imports for PySide2

Is this GUI app you’re making open source? If so maybe we could collaborate and get a general template for embedding pyvista in PySide2 apps...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ezalorpro** [comment]
Hello, thanks for the quick answer, indeed it is possible, i figure it out like 20 minuts ago, i am currently expertimenting, but in breef  it is just like you said, just replace PyQt5 import for PySide2 and replace pyqtsignal and pyqtslot for Signal and Slot.

![pyside2pyvista](https://user-images.githubusercontent.com/37134637/62838444-2a03ba80-bc4a-11e9-886d-a3d8acc9e43e.png)

My only problem it is with the scalars and cmap, you can see in the imagen that dont correspond with the height, but that's another topic. i have intendet to release the code eventually,  but  i cant do it right now, since it is a work for university stuff.

btw, after making those changes, the basic example of PyVista + PyQt5 works with pyside2 changing Qt for QtWidgets.

```python
from PySide2 import QtWidgets
import numpy as np
import pyvista as pv

class MainWindow(QtWidgets.QMainWindow):

    def __init__(self, parent=None, show=True):
        super(MainWindow, self).__init__(parent)

        # create the frame
        self.frame = QtWidgets.QFrame()
        vlayout = QtWidgets.QVBoxLayout()

        # add the pyvista interactor object
        self.vtk_widget = pv.QtInteractor(self.frame)
        vlayout.addWidget(self.vtk_widget)

        self.frame.setLayout(vlayout)
        self.setCentralWidget(self.frame)

        # simple menu to demo functions
        mainMenu = self.menuBar()
        fileMenu = mainMenu.addMenu('File')
        exitButton = QtWidgets.QAction('Exit', self)
        exitButton.setShortcut('Ctrl+Q')
        exitButton.triggered.connect(self.close)
        fileMenu.addAction(exitButton)

        # allow adding a sphere
        meshMenu = mainMenu.addMenu('Mesh')
        self.add_sphere_action = QtWidgets.QAction('Add Sphere', self)
        self.add_sphere_action.triggered.connect(self.add_sphere)
        meshMenu.addAction(self.add_sphere_action)

        if show:
            self.show()

    def add_sphere(self):
        """ add a sphere to the pyqt frame """
        sphere = pv.Sphere()
        self.vtk_widget.add_mesh(sphere)
        self.vtk_widget.reset_camera()

```
![pyside2pyvistasphere](https://user-images.githubusercontent.com/37134637/62838523-6be13080-bc4b-11e9-9ce0-ffe19e7b8f31.png)

**Comment by banesullivan** [comment]
Excellent work! I'm glad you were able to figure out how to get this working so quickly!

It'd be nice if we could set up PyVista to work with both. PyQt5 and PySide2 - I'll think about how we could make this work

> My only problem it is with the scalars and cmap, you can see in the imagen that don't correspond with the height, but that's another topic.

Feel free to open another issue if you need help with this

**Comment by ezalorpro** [comment]
> It'd be nice if we could set up PyVista to work with both. PyQt5 and PySide2 - I'll think about how we could make this work

about that, perhaps you can find inspiration in the Qt.py file of pyqtgraph, it deals with the same problem, kinda.

https://github.com/pyqtgraph/pyqtgraph/blob/develop/pyqtgraph/Qt.py

**Comment by banesullivan** [comment]
Nice find, thanks for sharing!

**Comment by banesullivan** [comment]
@ezalorpro - I actually cannot get the script you shared above to work... Am I missing something:

```py
from PySide2 import QtWidgets
import numpy as np
import pyvista as pv
import sys

class MainWindow(QtWidgets.QMainWindow):

    def __init__(self, parent=None, show=True):
        super(MainWindow, self).__init__(parent)

        # create the frame
        self.frame = QtWidgets.QFrame()
        vlayout = QtWidgets.QVBoxLayout()

        # add the pyvista interactor object
        self.vtk_widget = pv.QtInteractor(self.frame)
        vlayout.addWidget(self.vtk_widget)

        self.frame.setLayout(vlayout)
        self.setCentralWidget(self.frame)

        # simple menu to demo functions
        mainMenu = self.menuBar()
        fileMenu = mainMenu.addMenu('File')
        exitButton = QtWidgets.QAction('Exit', self)
        exitButton.setShortcut('Ctrl+Q')
        exitButton.triggered.connect(self.close)
        fileMenu.addAction(exitButton)

        # allow adding a sphere
        meshMenu = mainMenu.addMenu('Mesh')
        self.add_sphere_action = QtWidgets.QAction('Add Sphere', self)
        self.add_sphere_action.triggered.connect(self.add_sphere)
        meshMenu.addAction(self.add_sphere_action)

        if show:
            self.show()

    def add_sphere(self):
        """ add a sphere to the pyqt frame """
        sphere = pv.Sphere()
        self.vtk_widget.add_mesh(sphere)
        self.vtk_widget.reset_camera()


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    sys.exit(app.exec_())
```

Then I get the error:

```
Traceback (most recent call last):
  File "test.py", line 48, in <module>
    window = MainWindow()
  File "test.py", line 16, in __init__
    self.vtk_widget = pv.QtInteractor(self.frame)
  File "/Users/bane/Documents/OpenGeoVis/Software/pyvista/pyvista/plotting/qt_plotting.py", line 290, in __init__
    QVTKRenderWindowInteractor.__init__(self, parent)
  File "/Users/bane/anaconda3/envs/fras/lib/python3.7/site-packages/vtk/qt/QVTKRenderWindowInteractor.py", line 235, in __init__
    QGLWidget.__init__(self, parent)
TypeError: arguments did not match any overloaded call:
  QGLWidget(parent: QWidget = None, shareWidget: QGLWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'PySide2.QtWidgets.QFrame'
  QGLWidget(QGLContext, parent: QWidget = None, shareWidget: QGLWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'PySide2.QtWidgets.QFrame'
  QGLWidget(QGLFormat, parent: QWidget = None, shareWidget: QGLWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'PySide2.QtWidgets.QFrame'
Exception ignored in: <function BasePlotter.__del__ at 0x7fcd604de620>
Traceback (most recent call last):
  File "/Users/bane/Documents/OpenGeoVis/Software/pyvista/pyvista/plotting/plotting.py", line 3375, in __del__
    self.close()
RuntimeError: super-class __init__() of type QtInteractor was never called
```

**Comment by banesullivan** [comment]
I have version `5.13.0` of PyQt5 and version `5.13.0` of PySide2

**Comment by ezalorpro** [comment]
i am using:

python  ->  3.7.3 - 32 bits
pyvista   ->   0.21.4
PySide2  ->   5.13.0
VTK  ->   8.2.0

No PyQt5 since it is a virtual enviroment, the only thing worth mentioning is that the line 235 of my QVTKRenderWindowInteractor.py is not that one the show the error, so maybe it is the VTK version?

I try the replace PySide2 thing cuz i read this in the QVTKRenderWindowInteractor.py :

> Changes by Tobias Hänel, Sep. 2018
 Support for PySide2

**Comment by banesullivan** [comment]
Ah yep - I had VTK 8.1.2 in that virtual env. VTK 8.2.0 resolves the issue

**Comment by markeastwood82** [comment]
Hi. Is there a trick to make the above posted code work? I have

python 3.7.6 (64 bit)
vtk 8.2.0
pyvista 0.24.1
pyside2 5.13.2

All installed by Anaconda3 2020.02. I've not modified anything besides creating an environment to install the required components (including pyside2). I can run PyVista fine without Qt.

Running the code from @ezalorpro I get the following error

```
Traceback (most recent call last):
  File "C:\Users\User\Documents\Mark\Code\pyvista-muck\inaqt.py", line 56, in <module>
    window = MainWindow()
  File "C:\Users\User\Documents\Mark\Code\pyvista-muck\inaqt.py", line 24, in __init__
    self.vtk_widget = pv.QtInteractor(self.frame)
  File "C:\Users\User\anaconda3\envs\MPos\lib\site-packages\pyvista\plotting\qt_plotting.py", line 449, in __init__
    self.render_timer = QTimer(parent=parent)
TypeError: QTimer(parent: QObject = None): argument 'parent' has unexpected type 'PySide2.QtWidgets.QFrame'
```
Would anyone be able to help?
