### ISSUE TITLE
Interpreting RuntimeError: Maximum number of color bars reached.

### ISSUE THREAD

**Issue by wybeturing** [pyvista/pyvista-support#450]
Hi, 
I have been trying to use a custom callback to interact with a rendered mesh. I was using an approach that is arguably not the best to get a hack when I realized that the .remove_scalar_bar() seems to only be "hiding" the scalar bar instead of completely deleting it. Due to the complexity of what I am working on, I quickly set up an example to demonstrate what I was experiencing. 

```# sphinx_gallery_thumbnail_number = 2
import pyvista as pv
from pyvista import examples# Load St Helens DEM and warp the topography
mesh = examples.download_st_helens().warp_by_scalar()
# First a default plot with jet colormap
p = pv.Plotter()
# Add the data, use active scalar for coloring, and show the scalar bar
for i in range(15):
    p.add_mesh(mesh, name='st_helen')
    p.remove_scalar_bar(title='Elevation', render=False) 
    # Display the scene
p.show()
```
#1366 seems to be discussing thesame issue.  Is this a bug with the remove_scalar_bar()? Or is there some maximum number of color bars that can be added?

**Comment by akaszynski** [comment]
> Is this a bug with the remove_scalar_bar()

This.  I think we fixed for the next release, but to be sure, can you install pyvista from master?
```
pip install -U git+https://github.com/pyvista/pyvista.git@main
```

**Comment by wybeturing** [comment]
Great, this worked.
