### ISSUE TITLE
How to open a .ply file with textures

### ISSUE THREAD

**Issue by T-AbdelAlim** [pyvista/pyvista-support#457]
I am interested in using a .ply file with textures. However, if I pv.read(mesh.ply), I get the file with a default cmap instead of the textures. When I open the same mesh.ply file in MeshLab, it opens the file by default with the appropriate textures. 

Is there a way to do this using pyvista? 

Thanks in advance.

![image](https://user-images.githubusercontent.com/37778854/124956422-4536fa80-e018-11eb-9593-4fa00d7e0d66.png)
![image](https://user-images.githubusercontent.com/37778854/124956617-73b4d580-e018-11eb-991a-70ac6acb08e4.png)

**Comment by akaszynski** [comment]
Without seeing the file I can't be sure, but I think that you can enable RGBA plotting with by enabling `rgba=True` when plotting.

**Comment by T-AbdelAlim** [comment]
Thank you very much. I had quite an elaborate workaround, but this is much better.

**Comment by T-AbdelAlim** [comment]
> Without seeing the file I can't be sure, but I think that you can enable RGBA plotting with by enabling `rgba=True` when plotting.

Do you by any chance know how to save a transformed (rotated) ply file with textures? 

mesh = pv.read(mesh.ply)
mesh.rotate_x(90)
mesh.save(mesh_rotated.ply) --> no longer contains textures

**Comment by T-AbdelAlim** [comment]
> Without seeing the file I can't be sure, but I think that you can enable RGBA plotting with by enabling `rgba=True` when plotting.

Do you by any chance know how to save a transformed (rotated) ply file with textures?

mesh = pv.read(mesh.ply)
mesh.rotate_x(90)
mesh.save(mesh_rotated.ply) --> no longer contains textures
