### ISSUE TITLE
Neighbor vertices on the surface

### ISSUE THREAD

**Issue by Joseles666** [pyvista/pyvista-support#459]
**## Description:**

Dear Pyvista team,

It is my first time using this fantastic library, so I apologize in advance if my question has already been answered.

I have been practicing with the triangular mesh on the dolphin example, and I have a question. How could I get the points of the mesh that are on the boundary? 

Thank you so much in advance for your time.

Regards,
Jose.

**## Example Data**

Please consider the dolphin from Pyvista

**Comment by akaszynski** [comment]
Hello,

Here's how I'd do it:

```py
from pyvista import examples

dolfin = examples.download_dolfin()
boundary = dolfin.extract_feature_edges(boundary_edges=True,
                                        non_manifold_edges=False,
                                        feature_edges=False,
                                        manifold_edges=False)

# points on the boundary
boundary.points

# indices of the boundary
boundary.point_arrays['vtkOriginalPointIds']
```

**Comment by Joseles666** [comment]
Dear Akaszynski,

Thank you very much for your quick and precise response. It has been very helpful. 

Where can I find information about how each class and method of the Pyvista works? I want to go deeper into its use because it seems to be an incredible library.

Again, thank you for your time.
Jose

**Comment by akaszynski** [comment]
> Where can I find information about how each class and method of the Pyvista works? I want to go deeper into its use because it seems to be an incredible library.

Release documentation is here: doc.pyvista.org

We're updating the way our docs look and you'll find better docs here: dev.pyvista.org

**Comment by Joseles666** [comment]
Thank you!
