### ISSUE TITLE
How to Set Values to PolyData?

### ISSUE THREAD

**Issue by adamgranthendry** [pyvista/pyvista-support#463]
How do you assign (scalar) values to (3D) points of a `PolyData` surface?

**Comment by akaszynski** [comment]
Assign each point a scalar equal to its Z position
```
import pyvista
mesh = pyvista.Sphere()
mesh.point_arrays['zposition'] = mesh.points[:, 2]
```

Alternatively, Pyvista is smart enough to know that if the array you provide is sized to the points, it will just set the points array:
```
mesh['zposition'] = mesh.points[:, 2]
```

**Comment by adamgranthendry** [comment]
@akaszynski Thanks!

Can I assign scalars to cells/faces by cell id? For example, if I wanted to mark certain cells with values and plot those across the surface?

**Comment by akaszynski** [comment]
> Perhaps as a trivial example, could you show me how to assign values 1 to 6 for each face of a cube (hexahedron) and plot the cube with those scalars as active?

```py
>>> import numpy as np
>>> import pyvista
>>> cube = pyvista.Cube()
>>> cube
PolyData (0x7f9fbca59760)
  N Cells:	6
  N Points:	24
  X Bounds:	-5.000e-01, 5.000e-01
  Y Bounds:	-5.000e-01, 5.000e-01
  Z Bounds:	-5.000e-01, 5.000e-01
  N Arrays:	2
```

Simply assign scalars 0-5 to the cube faces and plot it.  Added scalars are immediately made "active" by default.  You could also specify the scalars plotted with `cube.plot(scalars=np.arange(6))` or `cube.plot(scalars='myscalars')`.

```py
>>> cube.cell_arrays['myscalars'] = np.arange(6)
>>> cube.plot()
```
![tmp](https://user-images.githubusercontent.com/11981631/125648401-1094acec-082f-43b4-8717-eb6c72d6c840.png)

**Comment by adamgranthendry** [comment]
@akaszynski Thank you so much! I love how easy this is!

Sorry, but another question: How do I label a specific cell with a value? For example, how could I make face "2" (whatever that is) have a value of 10?

**Comment by adamgranthendry** [comment]
@akaszynski Thank you for your help! This fixed my issue and I will close this now.
