### ISSUE TITLE
How to Perform Algorithm in Parallel on Same Mesh

### ISSUE THREAD

**Issue by adamgranthendry** [pyvista/pyvista-support#464]
If I have a mesh with a large number of faces, what is the best way to run the same algorithm on each face of the mesh using parallel processing?

For example, my mesh is completely triangulated and I want to extrude wedges for each triangular face and plot them in one plot. What would be the fastest way to achieve this?

**Comment by akaszynski** [comment]
> For example, my mesh is completely triangulated and I want to extrude wedges for each triangular face and plot them in one plot. What would be the fastest way to achieve this?

The way I'd do it is to construct an unstructured grid using wedge cells based on the normals of the triangular faces.  Then plot that single unstructured grid.  Plotting individual elements is slow and sometimes leads to segfaults if VTK get's overloaded with too many actors.

**Comment by adamgranthendry** [comment]
@akaszynski Thank you again! Another good suggestion.

One more question: If I have a bunch of data in a plane and want to clip to just that data inside a triangle, how do I do that in `pyvista`?

**Comment by akaszynski** [comment]
> If I have a bunch of data on a plane and I want just the data inside a triangle on the plane, how do I clip that data in pyvista?

I don't know of how to do that within pyvista, but I'd use the Moeller–Trumbore algorithm to determine if a point lies within a triangle and then reduce the data.  We have an example in our development documentation at https://dev.pyvista.org/examples/99-advanced/ray-trace-moeller.html#sphx-glr-examples-99-advanced-ray-trace-moeller-py

**Comment by adamgranthendry** [comment]
@akaszynski Since I have the triangle and the points on the plane, perhaps I could do pull the data into `numpy` and do a boolean AND operation to get the end result? Or perhaps in `opencv`?

**Comment by adamgranthendry** [comment]
@akaszynski I use a `multiprocessing.Pool` to run ray tracing over every (triangular) face of the same mesh. There is a huge amount of dead time where the CPU is idle before I get any result. Is there a way to make this run faster? I have over 10 million faces in my mesh, so this currently won't run in any reasonable amount of time (even with two 24-core processors). (I'm on Windows 10, if that makes a difference):

![image](https://user-images.githubusercontent.com/77850046/125665860-784d43eb-d8b4-4306-84e7-8bf4ba7473f9.png)

Here is my code:

```python
from multiprocessing import Pool
import numpy as np
import pyvista as pv
from tqdm import tqdm

def project(ndx, data, vertices, normals):
    normal = np.average(normals, axis=0)

    x0 = np.average(vertices[:, 0])
    y0 = np.average(vertices[:, 1])
    z0 = np.average(vertices[:, 2])

    origin = np.array([x0, y0, z0])

    start = origin - 10 * normal
    stop = origin + 10 * normal

    points, _ = data.ray_trace(start, stop, first_point=True)

    if np.any(points):
        return (ndx, 1)

    return (ndx, 0)

def get_projected_faces(planes, data):
    planes.cell_arrays["scalars"] = np.zeros((planes.n_cells,))

    planes_ = planes.faces.reshape(-1, 4)
    vertices = planes.points
    normals = planes.cell_normals

    with Pool(60) as executor:
        results = executor.starmap(
            project,
            tqdm(
                [
                    (ndx, data, vertices[planes_[ndx, 1:]], normals[planes_[ndx, 1:]])
                    for ndx in range(faces.shape[0])
                ],
                total=faces.shape[0],
            ),
            chunksize=faces.shape[0] // 60
        )

    results = np.array([ndx for ndx, val in results if val == 1])

    return results
            

if __name__ == '__main__';

    # Load data
    data = pv.read('data.vtk')
    planes = pv.read('planes.vtk')

    # Compute projections
    faces = get_projected_faces(planes, data)

    # Plot result
    planes.cell_arrays["scalars"][cells] = np.ones_like(cells)
    planes.set_active_scalars("scalars")

    p = pv.Plotter()
    p.add_mesh(faces)
    p.show()
```

**Comment by akaszynski** [comment]
>     points, _ = data.ray_trace(start, stop, first_point=True)

This will be the bottleneck.  First, VTK's ray tracking algorithm isn't all that efficient.  Secondly, it's not thread compatible, meaning you'll have to use less efficient multi-processing.

I recommend if you want to go the ray tracing route, try [Vectorised Ray Tracing](https://docs.pyvista.org/user-guide/optional_features.html#vectorised-ray-tracing)

**Comment by adamgranthendry** [comment]
@akaszynski Brilliant! Is there a fast way to get the cell centers and normals, or should I use multiprocessing to get these? (i.e. change `get_projected_faces` and `project` to `get_origins_and_normals` and `origin_and_normal`, resp.)

**Comment by akaszynski** [comment]
> Is there a fast way to get all cell centers and their normals on a completely triangulated mesh

[cell_centers](https://dev.pyvista.org/api/core/_autosummary/_autosummary/pyvista.CompositeFilters.cell_centers.html?highlight=cell_centers#pyvista-compositefilters-cell-centers)
[compute_normals](https://dev.pyvista.org/api/core/_autosummary/_autosummary/pyvista.PolyDataFilters.compute_normals.html?highlight=cell_normals#pyvista-polydatafilters-compute-normals)

**Comment by adamgranthendry** [comment]
@akaszynski You completely read my mind. I just saw these. Thank you!

**Comment by adamgranthendry** [comment]
@akaszynski I get this error, even though I have installed these packages:

![image](https://user-images.githubusercontent.com/77850046/125682785-22eaef2a-e45b-4669-9401-f471952a72ec.png)

**Comment by adamgranthendry** [comment]
@akaszynski The vectorized ray tracing works great, but it grabs everything along the vector passed it whereas VTK's method grabs just those points between a `start` and `stop` point. Is there a vectorized way of emulating that? e.g., does `trimesh` have a vectorized equivalent for `poly_data.obbTree.IntersectWithLine`?

**Comment by adamgranthendry** [comment]
@akaszynski *Another facepalm!* I have the `origins` array and `trimesh` gives the intersection points (`points`), so I can just use `np.linalg.norm` to compute the distances between the two and filter the returned indeces based on my required distance. The complete example looks like this (for posterity and/or if you want to add some example to the docs):

```python
import pyvista as pv
import numpy as np

if __name__ == "__main__":

    # Load data
    data = pv.read('data.vtk')
    planes = pv.read('planes.vtk')

    # Get origins and normals
    origins = planes.cell_centers().points
    normals = planes.compute_normals(cell_normals=True, point_normals=False)["Normals"]

    # Vectorized Ray trace
    points, inds, _ = data.multi_ray_trace(origins, normals)

    # Filter based on distance threshold
    threshold = 10  # Some threshold distance
    distances = np.linalg.norm(origins[inds] - points, ord=2, axis=1)
    inds = inds[distances <= threshold]

    # Mask points on planes
    planes.cell_arrays["scalars"][inds] = np.ones((len(inds),))
    planes.set_active_scalars("scalars")

    # Plot results
    p = pv.Plotter(shape=(1, 2))
    p.add_mesh(data)
    p.subplot(0, 1)
    p.add_mesh(planes)
    p.show()
```

**Comment by akaszynski** [comment]
About to respond.  Yes, that's your best bet.  Also, if you can't provide data, could you create a minimum working example that we could add to the docs?  I think others will want to try this out as well.

**Comment by adamgranthendry** [comment]
@akaszynski Oh sure, that shouldn't be too hard. I was just messing with the [Project to Plane](https://docs.pyvista.org/examples/01-filter/project-plane.html#sphx-glr-examples-01-filter-project-plane-py) example really.

To finish my example, I need to get the "Elevation" values at specific `load_random_hills` cells. How do I get that data?

**Comment by adamgranthendry** [comment]
The code below projects the `random_hills` example data to the triangular plane with vertices at `[10,0,0], [0,10,0], [0,0,10]`:

(You could call this something like "Project to Finite Plane" or "Project to PolyData")

```python
import pyvista as pv
from pyvista import examples
import numpy as np
from pykdtree.kdtree import KDTree
from tqdm import tqdm

if __name__ == "__main__":
    # Load data
    data = examples.load_random_hills()
    data.translate((10, 10, 10))

    # Create triangular plane (vertices [10,0,0], [0,10,0], [0,0,10])
    size = 10
    vertices = np.array([[size, 0, 0], [0, size, 0], [0, 0, size]])
    face = np.array([3, 0, 1, 2])

    planes = pv.PolyData(vertices, face)

    # Subdivide plane so we have multiple points to project to
    planes = planes.subdivide(8)

    # Get origins and normals
    origins = planes.cell_centers().points
    normals = planes.compute_normals(cell_normals=True, point_normals=False)["Normals"]

    # Vectorized Ray trace
    points, pt_inds, cell_inds = data.multi_ray_trace(
        origins, normals
    )  # Must have rtree, trimesh, and pyembree installed

    # Filter based on distance threshold, if desired (mimicks VTK ray_trace behavior)
    # threshold = 10  # Some threshold distance
    # distances = np.linalg.norm(origins[inds] - points, ord=2, axis=1)
    # inds = inds[distances <= threshold]

    tree = KDTree(data.points.astype(np.double))
    _, data_inds = tree.query(points)

    elevations = np.hstack(
        [
            data.extract_points(ind, include_cells=False)["Elevation"]
            for ind in tqdm(data_inds)
        ]
    )

    # Mask points on planes
    planes.cell_arrays["Elevation"] = np.zeros((planes.n_cells,))
    planes.cell_arrays["Elevation"][pt_inds] = elevations
    planes.set_active_scalars("Elevation")  # Probably not necessary, but just in case

    # Create axes
    axis_length = 20
    tip_length = 0.25 / axis_length * 3
    tip_radius = 0.1 / axis_length * 3
    shaft_radius = 0.05 / axis_length * 3
    x_axis = pv.Arrow(
        direction=(axis_length, 0, 0),
        tip_length=tip_length,
        tip_radius=tip_radius,
        shaft_radius=shaft_radius,
        scale="auto",
    )
    y_axis = pv.Arrow(
        direction=(0, axis_length, 0),
        tip_length=tip_length,
        tip_radius=tip_radius,
        shaft_radius=shaft_radius,
        scale="auto",
    )
    z_axis = pv.Arrow(
        direction=(0, 0, axis_length),
        tip_length=tip_length,
        tip_radius=tip_radius,
        shaft_radius=shaft_radius,
        scale="auto",
    )
    x_label = pv.PolyData([axis_length, 0, 0])
    y_label = pv.PolyData([0, axis_length, 0])
    z_label = pv.PolyData([0, 0, axis_length])
    x_label.point_arrays["label"] = [
        "x",
    ]
    y_label.point_arrays["label"] = [
        "y",
    ]
    z_label.point_arrays["label"] = [
        "z",
    ]

    # Plot results
    p = pv.Plotter()
    p.add_mesh(x_axis, color="r")
    p.add_point_labels(x_label, "label", show_points=False, font_size=24)
    p.add_mesh(y_axis, color="r")
    p.add_point_labels(y_label, "label", show_points=False, font_size=24)
    p.add_mesh(z_axis, color="r")
    p.add_point_labels(z_label, "label", show_points=False, font_size=24)
    p.add_mesh(data)
    p.add_mesh(planes)
    p.show()
```

**Output:**

![image](https://user-images.githubusercontent.com/77850046/125869024-8c7ef7cf-5e9b-41bd-8c98-4ecbea12e582.png)

**Comment by adamgranthendry** [comment]
@akaszynski Thank you for all your help! I will close this issue and link it to [Project Surface Mesh to Cell/Finite Plane #461](https://github.com/pyvista/pyvista-support/issues/461) as it really answers that question. I would love it if this could be added as an example to the docs! Would you please let me know if you're able to do this?

**Comment by akaszynski** [comment]
Thanks for the example!

> I would love it if this could be added as an example to the docs! Would you please let me know if you're able to do this?

Added in https://github.com/pyvista/pyvista/pull/1521
