### ISSUE TITLE
Fix Non-Manifold Mesh

### ISSUE THREAD

**Issue by adamgranthendry** [pyvista/pyvista-support#465]
I have a surface that isn't manifold after smoothing and even after cleaning. As a result, I cannot subdivide it. How can I fix a non-manifold surface?

**Comment by akaszynski** [comment]
I'd try using [pymeshfix](https://github.com/pyvista/pymeshfix)

**Comment by adamgranthendry** [comment]
@akaszynski Thanks! Worked like a charm. 

Unrelated question: Is there a progressbar for `PolyData.subdivide`? I'd like to see the progress if at all possible.

**Comment by akaszynski** [comment]
No, but we can add it.  Could you please open an issue for this on pyvista issues?

**Comment by adamgranthendry** [comment]
Sure! No problem!

**Comment by adamgranthendry** [comment]
@akaszynski Thank you again! This fixed my problem and I will close this issue.
