### ISSUE TITLE
Select cell by a string label

### ISSUE THREAD

**Issue by laserman781** [pyvista/pyvista-support#49]
Say I have several line segments and each one has a name (string), how can I query them and display.

Thanks!

**Comment by banesullivan** [comment]
Using my example from https://github.com/pyvista/pyvista-support/issues/47#issuecomment-520591265

```py
import pandas as pd
import numpy as np
import pyvista as pv

##########
# Make a sample dataframe
df = pd.DataFrame()
df['x'] = np.array([0.0, 2.0])
df['y'] = np.array([0.0, 0.0])
df['z'] = np.array([0.0, 0.0])
df['x2'] = np.array([1.0, 2.0])
df['y2'] = np.array([0.0, 2.0])
df['z2'] = np.array([0.0, 0.0])
df['IDs'] = np.array(['Line ID 1', 'Line ID 2'])
##########

weaved = np.empty((len(df) * 2, 3))
weaved[0::2] = df[['x', 'y', 'z']].values
weaved[1::2] = df[['x2', 'y2', 'z2']].values

def lines_from_points(points):
    """Generates line from weaved points."""
    n_points = len(points)
    n_lines = n_points // 2
    lines = np.c_[(2 * np.ones(n_lines, np.int),
                   np.arange(0, n_points-1, step=2),
                   np.arange(1, n_points+1, step=2))]
    poly = pv.PolyData()
    poly.points = points
    poly.lines = lines
    return poly

lines = lines_from_points(weaved)
lines.cell_arrays['IDs'] = df['IDs'].values
lines.plot(line_width=5)
```

You can then querry just like you would with any NumPy array. The details of string comparison in arrays becomes more of a general Python/NumPy question than a PyVista question.

```py
indices = np.argwhere(lines['IDs'] == b'Line ID 2').ravel()
print(indices)
```
[1]

Once you have those indices, you could use to extract those cells by:

```py
extracted = lines.extract_cells(indices)
extracted.plot(scalars='IDs')
```

**Comment by laserman781** [comment]
Not working...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-36-1c9c705bd4e9> in <module>
----> 1 extracted = weaved.extract_cells(indices)
      2 extracted.plot(scalars='Name')

AttributeError: 'PolyData' object has no attribute 'extract_cells'

**Comment by banesullivan** [comment]
The `extract_cells` filter was made available to all datasets on the last release - please make sure you are up to date in that kernel

**Comment by laserman781** [comment]
That was the issue, got it working...

Thank you!

**Comment by laserman781** [comment]
Is there any way we can apply this with wild cards and query for multiple elements?
