### ISSUE TITLE
Plot Truss-like FEA solution with cylinders

### ISSUE THREAD

**Issue by supergra** [pyvista/pyvista-support#494]
Specific question: How do I plot connections between points in 3D as cylinders, colored by some scalar?

<img width="293" alt="Screen Shot 2021-08-27 at 09 22 27" src="https://user-images.githubusercontent.com/2165840/131158555-4bf1e0bb-22c2-49d7-94a3-b45ef89273c9.png">

Context: I am trying to move over from MayaVi, after one two many frustrations with the documentation and painfully slow processing times. I'm delighted at how snappy PyVista is on the examples, but I'm stymied about how to get started with my current project. 

Here is some sample code from MayaVi that I'm trying to port. **It doesn't need to look exactly like this**, I just want to understand how to go about creating something that roughly conveys this same information. Even a pointer to the right place in the API would be helpful. I found many useful functions for surface meshes, but no examples in the gallery that look quite like this.

```
import random
from mayavi import mlab

nodes = [
    [0.0, 0.0, 0.0],
    [0.0, 1.0, 0.0],
    [4.0, 3.0, 0.0],
    [4.0, 0.0, 0.0],
    [0.0, 1.0, 2.0],
    [4.0, 1.0, 2.0],
    [4.0, 3.0, 2.0]
    ]

edges = [
    [0, 4],
    [1, 4],
    [3, 4],
    [5, 4],
    [6, 4],
    [3, 5],
    [2, 5],
    [5, 6],
    [2, 6],
    ]

mfig = mlab.figure()

for iA, iB in edges:
    xs, ys, zs = zip(nodes[iA], nodes[iB])

    # (Color would come from a nice scalar)
    col = (random.random(),random.random(),random.random())

    mlab.plot3d(xs, ys, zs,  color=col, figure=mfig, tube_radius=0.1)

mlab.show()
```

**Comment by akaszynski** [comment]
Keeping this open as a reminder to add
