### ISSUE TITLE
Select element on plotter and save it as it's own vtk file

### ISSUE THREAD

**Issue by laserman781** [pyvista/pyvista-support#51]
I was wondering if it was possible to select elements on a plot interactively (ex.: a collection of holes) and save them as their own vtk file or perhaps print their table data?

Thank you!

**Comment by banesullivan** [comment]
Cell selection is currently possible - check out the `.enable_cell_picking` method on the plotter: https://docs.pyvista.org/plotting/plotting.html#pyvista.BasePlotter.enable_cell_picking

You could pass a custom `callback` function to save out the mesh or grab the saved mesh after closing the plotter from the `.picked_cells` attribute

Otherwise, I'm not sure what you mean by selecting elements/holes...

**Comment by laserman781** [comment]
What kind of function would I need to create to do this? I simply want to be able to select a mesh from the plot and export it as it's own vtk file using the save function.

**Comment by laserman781** [comment]
Or more specifically selecting a vtk cell

**Comment by laserman781** [comment]
The goal is to try and get something similar to extract selection from ParaView.

**Comment by banesullivan** [comment]
After making a selection with the plotter's `.enable_cell_picking` (which recently had some enhancements that aren't released yet), you can grab the mesh from the `.picked_cells` attribute on that plotter - then you could save that mesh if desired.

Here's an example

```py
import pyvista as pv
from pyvista import examples

mesh = examples.download_dragon()

p = pv.Plotter(notebook=False)
p.add_mesh(mesh)
p.enable_cell_picking(mesh)
p.show()
```
![2019-08-19 12 02 23](https://user-images.githubusercontent.com/22067021/63288182-525a6d00-c279-11e9-9342-9a1d40acdd63.gif)


```py
selection = p.picked_cells
selection.plot(color='white')
```

![download](https://user-images.githubusercontent.com/22067021/63288187-54243080-c279-11e9-88fc-cbc3c367c190.png)

```py
# Save it
selection.save('my_selection.vtk')
```

**Comment by laserman781** [comment]
This works great! I am getting the option "Press P to pick a single cell  under the mouse"

Is this coming in the next release?

**Comment by banesullivan** [comment]
Yes, a few new features with cell selection are coming in the next release! Along with many other point selection tools and widgets.

**Comment by laserman781** [comment]
Awesome! Final question... I mentioned above being able to select from a table. In ParaView there is the option to have a spreadsheet view side by side with the plot and be able to select the cells by their rows (see screenshot in email). from there I can apply the extract cellls filter. Is something like this possible in PyVista as well?

**Comment by banesullivan** [comment]
In short, not really as PyVista isn't designed to be GUI application like ParaView.

But if you know the cell ids (the rows in the spreadsheet view) then you can use PyVista's [`.extract_cells`](https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.extract_cells) filter to extract celsl by their IDs which is exactly what ParaView's extract selection filter is doing.

Coming in the next release of PyVista is support for `vtkTable` objects in a new `Table` class which can go back and forth with Pandas `DataFrame` objects. Perhaps there are good tools for interactively making selections from Pandas data frames that would be well suited for this? I image we could make a tool that would display the cell data (or point data) as a pandas dataframe and perhaps leverage some sort of interactive dataframe tool like to make selections and extract cells in a similar fashion.

Unfortunately it is out of scope for us to deisgn any sort of interactive selection tool based on a table representation.

**Comment by banesullivan** [comment]
Or if you are feeling really adventurous, you could make a plugin to PyVista using PyQt to show these tables and allow selections to callback to the extract filters. Making the GUI would be the hard part... all the extraction and PyVista stuff is already implemented

**Comment by laserman781** [comment]
Okay, I will give this a try. Thank you!

**Comment by banesullivan** [comment]
> > @banesullivan  You could make a plugin to PyVista using PyQt to show these tables and allow selections to callback to the extract filters. Making the GUI would be the hard part... all the extraction and PyVista stuff is already implemented". 

> @laserman781 Do you have any ideas on how I could do this? Also, how do I get the mesh data (point data and or cell data) in a table for this?

On the lastest version of PyVista, the `Table` class was introduced - a wrapped implementation of `vtkTable` which can also go back and forth to a Pandas DataFrame. I'd start by making tables of the mesh's point/cell data by passing those dictionaries to the `Table` constructor:

```py
import pyvista as pv
from pyvista import examples

# Any mesh
mesh = examples.download_st_helens().warp_by_scalar()

# Make a table
point_table = pv.Table(mesh.point_arrays)
```

Also, now you have a `Table` which can be converted to a Pandas `DataFrame`:

```
df = point_table.to_pandas()
```

I'd recommend starting there and then taking a look at the [Qt Table Widget](https://doc.qt.io/qt-5/qtablewidget.html) and [this SO post](https://stackoverflow.com/questions/31475965/fastest-way-to-populate-qtableview-from-pandas-data-frame) about making Qt Tables from data frames. Then you'd want to display that widget in an app (maybe link it to PyVista's `BackgroundPlotter) and enable row selection in the qt widget which would call back to function that extracts the cell/point indices (row indices from the table) using either [`extract_cells`](https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.extract_cells) or [`extract_points`](https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.extract_points)

**Comment by banesullivan** [comment]
FYI... there are some custom Qt widgets implemented in VTK for tables but I'm not sure if they are available on the Python distribution: https://vtk.org/doc/nightly/html/classvtkQtTableView.html

It might require a custom build of VTK
