### ISSUE TITLE
Seismic Horizon with Pyvista

### ISSUE THREAD

**Issue by YosmelyBermudez** [pyvista/pyvista-support#522]
Hi!Will someone have an example of a horizon worked with pyvista? I already have my horizon exported from Opendtect, I just want to represent it in python as an Explicit Structured Grid

**Comment by RichardScottOZ** [comment]
What does the data look like?

**Comment by RichardScottOZ** [comment]
There is this sort of thing https://github.com/pyvista/pyvista-support/issues/135

**Comment by YosmelyBermudez** [comment]
What do you mean? I do not understand

**Comment by RichardScottOZ** [comment]
https://github.com/pyvista/pyvista-support/issues/272

**Comment by RichardScottOZ** [comment]
You haven't said whether you want 2D, 3D plots... or what - you need more detail with examples.

**Comment by YosmelyBermudez** [comment]
I would like it to be a 3D graphic but it will depend on the difficulty. It would be good to see the two options because the problem is that with 2D my horizon comes out in parts and I want it complete.

**Comment by RichardScottOZ** [comment]
Yes - remember when you ask in general to consider your audience - a lot of people here wouldn't know a seismic survey from a soupa can.

So, some idea of the things you can try:- https://github.com/RichardScottOZ/Transform-2021/blob/main/Seismic-2D-Fence.ipynb
