### ISSUE TITLE
Add cell Labels on plot

### ISSUE THREAD

**Issue by laserman781** [pyvista/pyvista-support#54]
I know there is an option to add cell labels to points, although is it possible to add cell labels to each cell? How would I accomplish this?

**Comment by banesullivan** [comment]
You'd need to extract the outer surface of your mesh, the run a `cell_centers` filter to get the points at the center of the cells

```py
# Extract the outer surface
surface = mesh.extract_surface()

# Grabb the cell centers
cells = surface.cell_centers()

p = pv.Plotter(notebook=False)
p.add_mesh(mesh, show_edges=True)
p.add_point_labels(cells, cells.active_scalar_name)
p.show()
```

**Comment by laserman781** [comment]
This worked perfectly, thank you!
