### ISSUE TITLE
Avoid "active scalar" in vtk unstructured grid file

### ISSUE THREAD

**Issue by war-mbw** [pyvista/pyvista-support#55]
## Description

When creating a vtk unstructured grid file using pyvista(0.21.4) first celldata array is handled like an active scalar.
With vtki(0.16.7) all celldata arrays are equally treated. How to get back vtki's behaviour?

Kind regards,
Mario

## Example Data

test_pyvista.py
```
import pyvista
import numpy as np
offset = np.array([0])
cells = np.array([[4,0,1,2,3]])
cell_type = np.array([9])
nodes = np.array([[0,0,0],
                  [0,1,0],
                  [1,1,0],
                  [1,0,0]])
grid = pyvista.UnstructuredGrid(offset, cells, cell_type, nodes)
grid.cell_arrays['A'] = np.array([1])
grid.cell_arrays['B'] = np.array([2])
grid.cell_arrays['C'] = np.array([3])
grid.save('test_pyvista.vtk', binary=False)
```
test_pyvista.vtk
```
# vtk DataFile Version 4.2
vtk output
ASCII
DATASET UNSTRUCTURED_GRID
POINTS 4 int
0 0 0 0 1 0 1 1 0 
1 0 0 
CELLS 1 5
4 0 1 2 3 

CELL_TYPES 1
9

CELL_DATA 1
SCALARS A int
LOOKUP_TABLE default
1 
FIELD FieldData 2
B 1 1 int
2 
C 1 1 int
3 
```
test_vtki.py
```
import vtki
import numpy as np
offset = np.array([0])
cells = np.array([[4,0,1,2,3]])
cell_type = np.array([9])
nodes = np.array([[0,0,0],
                  [0,1,0],
                  [1,1,0],
                  [1,0,0]])
grid = vtki.UnstructuredGrid(offset, cells, cell_type, nodes)
grid.cell_arrays['A'] = np.array([1])
grid.cell_arrays['B'] = np.array([2])
grid.cell_arrays['C'] = np.array([3])
grid.save('test_vtki.vtk', binary=False)
```
test_vtki.vtk
```
# vtk DataFile Version 4.2
vtk output
ASCII
DATASET UNSTRUCTURED_GRID
POINTS 4 int
0 0 0 0 1 0 1 1 0 
1 0 0 
CELLS 1 5
4 0 1 2 3 

CELL_TYPES 1
9

CELL_DATA 1
FIELD FieldData 3
A 1 1 int
1 
B 1 1 int
2 
C 1 1 int
3 
```

**Comment by banesullivan** [comment]
We consider this a feature rather than an issue at this time. We automatically set an active scalar so that filters and plotting routines have a default array to use.

Do you have a specific reason why you don’t want this behavior?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by war-mbw** [comment]
Our vtk models including a great many cell arrays are processed by Paraview. Depending on the use case an array can be important or irrelevant.
So I think it reasonable to start Paraview in "Solid Color mode" and let the user decide which array to focus on.
If an active scalar is really needed, though, one could use the set_active_scalar method easily.

**Comment by banesullivan** [comment]
That's a fair point. I'll have to think about our current implementation to see if there is a way we could only set the active scalars if and only if needed.

In the meantime, I just added a way to clear the active scalars by passing `None` to the `set_active_scalar` method which you could do before saving:

```py
...
grid.set_active_scalar(None)
grid.save('~/Desktop/test_pyvista.vtk', binary=False)
```

This was added in https://github.com/pyvista/pyvista/commit/142a6d0a5079661ce63dd2bf5df4e6200e206afe and is currently only on the master branch. If you want to do this now, you could call `grid.GetCellData().SetActiveScalars(None)` before saving.

**Comment by banesullivan** [comment]
Also, is there something lacking in PyVista that has you going to ParaView over PyVista for 3D rendering?

**Comment by war-mbw** [comment]
Thanks for the workaround! It's working fine with me.
Regarding your last question ...
Not beeing aware of pyvista I was struggling with vtk in my python scripts a lot, recently.
Pyvista obviously makes things easier and I'm sure I'll come back to you later :-)
