### ISSUE TITLE
Can't get Press P to pick a single cell under mouse to work

### ISSUE THREAD

**Issue by laserman781** [pyvista/pyvista-support#56]
Upon toggling R in the plotter I am able to get the box selection tool to work, but the single cell under the mouse is not. 

![image](https://user-images.githubusercontent.com/12982931/63616270-30ccee80-c5b5-11e9-8ff3-b6c67891ceba.png)

**Comment by banesullivan** [comment]
The single-cell picking only works when `through=False` (visible cell selection). I just update the message displayed to only show up when using the visible cell selection tool. 

```py
import pyvista as pv
from pyvista import examples

mesh = examples.download_cow_head().tri_filter()

p = pv.Plotter(notebook=False)
p.add_mesh(mesh, color=True)
p.enable_cell_picking(through=False)
p.show()
```

![2019-08-23 14 21 20](https://user-images.githubusercontent.com/22067021/63621541-6a9bf600-c5b1-11e9-8d1f-5dcca271b347.gif)

**Comment by laserman781** [comment]
When I add through = False, it doesn't allow me to select anything
anymore... Also, it raises the error "AttributeError: 'Plotter' object has
no attribute 'picked_cells'"

**Comment by demacdo** [comment]
Hey, I'm having this same issue. 

When `through = True`, the "R" selection tool works, but picking individual cells with "P" does not work. 
When `through = False`, neither "R" or "P" works. 

Example:
```
import pyvista as pv
from pyvista import examples

mesh = examples.download_cow_head().triangulate()

p = pv.Plotter(notebook=False)
p.add_mesh(mesh, color=True)
p.enable_cell_picking(through=False)
p.show()
```

Report here:
```
--------------------------------------------------------------------------------
  Date: Tue Jul 06 13:36:09 2021 EDT

                OS : Darwin
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 32.0 GiB
       Environment : IPython
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : NVIDIA GeForce GTX 680MX OpenGL Engine
       GPU Version : 4.1 NVIDIA-12.0.24 355.11.10.50.10.103

  Python 3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:31:56)
  [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]

           pyvista : 0.31.3
               vtk : 8.1.0
             numpy : 1.13.0
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.7
            meshio : unknown
        matplotlib : 3.1.0
           IPython : 7.16.1
          colorcet : 1.0.0
             scipy : 1.2.1
--------------------------------------------------------------------------------
```
