### ISSUE TITLE
Change the range of the axes' plots

### ISSUE THREAD

**Issue by Andersongeofisco** [pyvista/pyvista-support#60]
Hello everyone! I hope that everyone is fine. I have a doubt :) I'd like to know if it is possible to change the range of the axes in a volume plot for example. The axes of my plots always start from 0 to length of my 3d numpy array, I'd like to plot for example something like, -5 to 5 (-5,-4,-3,-2,-1,0,1,2,3,4,5) instead (0,1,2,3,4,5,6,7,8,9,10) at the axes.

Thanks!

**Comment by banesullivan** [comment]
Hi, @Andersongeofisco! Do you have any code to go with your question so that I can help you implement this with your workflow?

It sounds like you are using PyVista strictly for plotting and passing a 3D numpy array to the Plotter's `add_mesh` or `add_volume` methods to render that dataset. Behind the scenes when you do this, an `UniformGrid` object is created of your 3D data. I'd recommend creating a PyVista dataset before plotting and properly set the spatial reference of that dataset. For example:


```py
import numpy as np
import pyvista as pv

# Create a 3D numpy array like what is used
arr = np.arange(1000).reshape((10,10,10))

# Now wrap that as a PyVista UniformGrid
grid = pv.UniformGrid()
# Set the spatial reference
grid.dimensions = np.array(arr.shape) + 1 #dim + 1 because cells
grid.origin = (-5, -5, -5)
grid.spacing = (1, 1, 1)
# Add data arrays
grid['data'] = arr.ravel(order='F')

# Now clip by a box:
grid.plot(show_grid=True, show_edges=True)
```

![download](https://user-images.githubusercontent.com/22067021/65340461-8502c880-db8b-11e9-84c7-d0df94e4be17.png)

**Comment by Andersongeofisco** [comment]
Hi @banesullivan ! Here is a example of my code.

import pyvista as pv
import numpy as np
ns=401
nv=21
nps=52
dado1=open("dvp3.ad",'rb')
d=np.fromfile(dado1,dtype=np.float32,count=ns*nv*nps).reshape([ns,nv,nps],order='F')

a=pv.wrap(d)
outline = a.outline()
slices = a.slice_orthogonal(x=401,y=5,z=52)
p = pv.Plotter()
p.add_mesh(outline)
p.add_mesh(slices,cmap='jet',opacity=1.,stitle="Semblance")
p.add_volume(a,cmap='jet',stitle="Semblance")
p.add_text("Semblance",position='upper_edge')
p.show_bounds(xlabel='Time',ylabel='Velocity',zlabel='Slope',location='outer')
p.show()

**Comment by banesullivan** [comment]
So the `a` object is a `pv.UniformGrid` in your example. You create in manually without `wrap` like:

```py
a = pv.UniformGrid()
# Set the spatial reference
a.dimensions = np.array(arr.shape) + 1 #dim + 1 because cells
a.origin = (-5, -5, -5)
a.spacing = (1, 1, 1)
# Add data arrays
a['Semblance'] = d.ravel(order='F')
```

**Comment by Andersongeofisco** [comment]
Thanks @banesullivan for your help! You helped a lot this young phd student :)

**Comment by Andersongeofisco** [comment]
I will try it and if everything works well I will return to say thanks.

**Comment by Andersongeofisco** [comment]
Hi @banesullivan ! I tried your tip, but I get another problem now. If I try to use the **a** object that was created to add_volume or slice I have this error message:

**ERROR:root:Cell Scalars not supported
Falha de segmentação (imagem do núcleo gravada)**

Here is my code:

import pyvista as pv
from pyvista import examples
import numpy as np
import matplotlib.pyplot as plt


ns=401
nv=21
nps=52
dado1=open("dvp3.ad",'rb')
d=np.fromfile(dado1,dtype=np.float32,count=ns*nv*nps).reshape([ns,nv,nps],order='F')

a = pv.UniformGrid()
# Set the spatial reference
a.dimensions = np.array(d.shape) + 1 #dim + 1 because cells
a.origin = (-5, -5, -5)
a.spacing = (1, 1, 1)
#Add data arrays
a['Semblance'] = d.ravel(order='F')

outline = a.outline()
slices = a.slice_orthogonal(x=401,y=5,z=52,contour='True')
p = pv.Plotter()
p.add_mesh(outline)
p.add_mesh(slices,cmap='jet',opacity=1.,stitle="Semblance")
p.add_volume(a,cmap='jet',stitle="Semblance")
p.add_text("Semblance",position='upper_edge')
p.show_bounds(xlabel='Time',ylabel='Velocity',zlabel='Slope',location='outer')
p.show()

**Comment by Andersongeofisco** [comment]
import pyvista as pv
from pyvista import examples
import numpy as np
import matplotlib.pyplot as plt

ns=401
nv=21
nps=52
dado1=open("dvp3.ad",'rb')
d=np.fromfile(dado1,dtype=np.float32,count=nsnvnps).reshape([ns,nv,nps],order='F')

a = pv.UniformGrid()

a.dimensions = np.array(d.shape) + 1 #dim + 1 because cells
a.origin = (-5, -5, -5)
a.spacing = (1, 1, 1)
#Add data arrays
a['Semblance'] = d.ravel(order='F')

outline = a.outline()
slices = a.slice_orthogonal(x=401,y=5,z=52,contour='True')
p = pv.Plotter()
p.add_mesh(outline)
p.add_mesh(slices,cmap='jet',opacity=1.,stitle="Semblance")
p.add_volume(a,cmap='jet',stitle="Semblance")
p.add_text("Semblance",position='upper_edge')
p.show_bounds(xlabel='Time',ylabel='Velocity',zlabel='Slope',location='outer')
p.show()

**Comment by Andersongeofisco** [comment]
Hi @banesullivan ! I tried your tip, but I get another problem now. If I try to use the a object that was created to add_volume or slice I have this error message:

ERROR:root:Cell Scalars not supported
Falha de segmentação (imagem do núcleo gravada)

Here is my code:

import pyvista as pv
from pyvista import examples
import numpy as np
import matplotlib.pyplot as plt

ns=401
nv=21
nps=52
dado1=open("dvp3.ad",'rb')
d=np.fromfile(dado1,dtype=np.float32,count=nsnvnps).reshape([ns,nv,nps],order='F')

a = pv.UniformGrid()

a.dimensions = np.array(d.shape) + 1 #dim + 1 because cells
a.origin = (-5, -5, -5)
a.spacing = (1, 1, 1)
#Add data arrays
a['Semblance'] = d.ravel(order='F')

outline = a.outline()
slices = a.slice_orthogonal(x=401,y=5,z=52,contour='True')
p = pv.Plotter()
p.add_mesh(outline)
p.add_mesh(slices,cmap='jet',opacity=1.,stitle="Semblance")
p.add_volume(a,cmap='jet',stitle="Semblance")
p.add_text("Semblance",position='upper_edge')
p.show_bounds(xlabel='Time',ylabel='Velocity',zlabel='Slope',location='outer')
p.show()

**Comment by banesullivan** [comment]
Ah, my bad. Take away that `+ 1` when setting the dimensions. I order for it to stretch from -5 to 5, you may need to adjust the spacing to something other than 1

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Andersongeofisco** [comment]
Thanks again @banesullivan

**Comment by Andersongeofisco** [comment]
**a**

**Comment by Andersongeofisco** [comment]
**a**
