### ISSUE TITLE
extracting 1 cell from a grid and plotting

### ISSUE THREAD

**Issue by awa5114** [pyvista/pyvista-support#63]
To my pleasant surprise, reading an unstructured grid from a .vtk file using pyvista and plotting it is a 3-line piece of cake.

```py
import pyvista as pv
mesh = pv.read('test/test_0.vtk')
mesh.plot()
```

A huge improvement if you compare with `vtk's` cumbersome actors, renderers, filters and what not. 

However now, I would like to extract cell from this unstructured grid and then plot it with relative ease. What I have tried so far is as follows:

```py
import pyvista as pv
mesh = pv.read('test/test_0.vtk')
cell = mesh.GetCell(0)
new_mesh = pv.UnstructuredGrid(pv.wrap(cell))
new_mesh.plot()
```

However I get a warning followed by an error:

> WARNING:root:VTK data type (vtkTetra) is not currently supported by pyvista.
> Traceback (most recent call last):
>   File "D:/11203719_dgflow/test.py", line 5, in <module>
>     new_mesh = pv.UnstructuredGrid(pv.wrap(cell))
>   File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\11203719_dgflow\lib\site-packages\pyvista\core\pointset.py", line 567, in __init__
>     raise Exception('Cannot work with input type %s' % itype)
> Exception: Cannot work with input type <class 'vtkCommonDataModelPython.vtkTetra'>

How can I extract the very first cell from my unstructured grid and plot it on its own?

Thanks

**Comment by banesullivan** [comment]
Hi @awa5114!

To perform what you describe, try out the `.extract_cells` filter and pass the id/index of the cell you’d like to grab:
```
import pyvista as pv
mesh = pv.read("mymesh.vtu")
cell = mesh.extract_cells(0)
cell.plot()
```

**Comment by akaszynski** [comment]
Beat me to it!

**Comment by awa5114** [comment]
Thanks guys. Will keep working on it.

**Comment by banesullivan** [comment]
FYI: https://pyvista.slack.com/archives/CBA5095UH/p1569418138028000
