### ISSUE TITLE
Plotting with scalar bar

### ISSUE THREAD

**Issue by nataliarvboas** [pyvista/pyvista-support#64]
I am currently using PyVista to plot some .vtk files into Jupyter. I've been looking at the examples with MyBinder to learn how to use PyVista. On "pyvista-examples/examples/02-plot" the example "scalar-bars.ipynb" is exactly what I need, however when I run the notebook the scalar bars are now shown in the example plots. I tried to use the same commands to plot my .vtk files with the scalar bar in the jupyter notebook I am working, but the scalar bar is not shown either.

![scalar-bar-missing](https://user-images.githubusercontent.com/31484121/65687595-ffc25c80-e03f-11e9-9b81-61ee355f920c.png)

**Comment by banesullivan** [comment]
Hi @nataliarvboas and thanks for trying out PyVista! 

So what’s happening here is currently expected as when you have the embedded 3D renderings in the notebook, we are actually converting the PyVista scene to another framework that does not support scalar bars, axes grids, etc. - This framework is undergoing some major development that will bring scalar bar support soon though!! See https://github.com/pyviz/panel/pull/606

To start seeing the scalar bars, you have a few options which require you to not use this embedded notebook rendering framework:

1. Do you have the ability to install and run PyVista on a local machine? if so, you can leverage the actual PyVista plotter by passing `notebook=False` when instantiating the plotter (doing so on MyBinder will likely crash the kernel).

```py
p = pv.Plotter(notebook=False)
...
```

2. Another option is to pass `use_panel=False` on the `p.show()` call to tell PyVista not to convert the scene to the external notebook rendering framework and to simply show a static screenshot of the scene. 

```py
...
p.show(use_panel=False)
```

What you’ll get are results much like whats shown in the docs for this example: https://docs.pyvista.org/examples/02-plot/scalar-bars.html

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nataliarvboas** [comment]
Hi @banesullivan! Thanks for your reply. For now I will use the option ```use_panel=False``` to show the static screenchot of the scene, since I need my Jupyter Notebook to work with MyBinder. Then, I'll wait for the improvements of PyVista! :)

Thanks!
