### ISSUE TITLE
Interactive pyVista Jupyter - colorScale

### ISSUE THREAD

**Issue by elavoine** [pyvista/pyvista-support#65]
I'm currently trying to use pyvista for nice visualization of simulations results stored in '.vtp' files with various scalars. Thanks to pyvista, I can do it interactively in the Jupyter Notebook. But still, I can't find how to display the color bar, and if possible, plot log values. Can you help me on that ? Thanks a lot for your work !

![pyvista_color_bar_issue](https://user-images.githubusercontent.com/48127078/65817877-9fcce100-e20c-11e9-9e61-0b00c575bdbd.PNG)

**Comment by banesullivan** [comment]
#64 discusses why you are not able to use scalar bars in the interactive notebook renderings

as for plotting log values, using `numpy.log` on your scalars array before plotting should do the trick:

```py
import numpy as np
visu[‘log(FractureArea)’] = np.log(visu[‘FractureArea’])
```

then set the `scalars` argument to `’log(FractureArea)’` instead when plotting

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by banesullivan** [comment]
The PyVista plotter should allow a `log` Boolean argument in the `add_mesh` function to logarithmically map the scalars, but I don’t think that works when converting to the notebook rendering framework 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by elavoine** [comment]
Thanks for your reply. I will use the pop-up window while waiting for the scalar bar in interractive visualization. Thx for your work.
