### ISSUE TITLE
Plotting 2d array on a sphere

### ISSUE THREAD

**Issue by dennissergeev** [pyvista/pyvista-support#67]
## Description

Does `pyvista` allow for "stretching" a 2D array over a sphere?
(Related to #52, but simpler.)

I would like to create a 3D sphere with a 2D array as its surface. I tried creating a VTK sphere with specific resolution and then filling cells with flattened data, e.g.
```python
import pyvista as pv

mesh = pv.Sphere(theta_resolution=45, phi_resolution=75, start_phi=1, end_phi=179)
mesh.cell_arrays["data"] = my_array.flatten(order="F")
```
However, I don't understand what the correct the number of cells / points depending on resolution should be, so my data dimensions don't match and in the end I end up with a mess. Is this because VTK sphere has tiangles as cells? What is the correct order of a data array then?

What I would like to get, can be shown using `matplotlib` and `cartopy`:
```python
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
import xarray as xr

lsm = xr.open_dataarray("lsm_4x5.nc")  # netCDF file is attached as a tar.gz archive

# Figure 1
lsm.plot()
```
![pyvista-support-issue-figure1](https://user-images.githubusercontent.com/12111288/65920992-c3448700-e3d8-11e9-9541-0df494c12454.png)

```python
# Figure 2
fig, ax = plt.subplots(
    subplot_kw=dict(projection=ccrs.Orthographic(central_longitude=180, central_latitude=45))
)
ax.imshow(lsm, transform=ccrs.PlateCarree())
```
![pyvista-support-issue-figure2](https://user-images.githubusercontent.com/12111288/65920993-c3448700-e3d8-11e9-91d2-426ad03d945e.png)

Thanks!

## Example Data

[lsm_4x5.tar.gz](https://github.com/pyvista/pyvista-support/files/3673645/lsm_4x5.tar.gz)

**Comment by banesullivan** [comment]
What you'll need to do is create a mesh and transform it to a sphere - the dataset you give isn't a complete sphere (latitudes range from -88 to 88  and longitudes range from 0 to 355), so you cannot inject his specific dataset onto a PolyData sphere object without significantly customizing it. Considering the dataset you give has latitudes and longitudes, I'd avoid creating a Sphere surface and just make a grid of the given spatial reference like so:

```py
import xarray as xr
import numpy as np
import pyvista as pv

lsm = xr.open_dataarray("lsm_4x5.nc")  # netCDF file is attached as a tar.gz archive

xx, yy, zz = np.meshgrid(np.radians(lsm['longitude']), 
                         np.radians(lsm['latitude']), 
                         [0])

# Transform to spherical coordinates
radius = 6371.0e6
x = radius * np.cos(yy) * np.cos(xx)
y = radius * np.cos(yy) * np.sin(xx)
z = radius * np.sin(yy)

grid = pv.StructuredGrid(x, y, z)
grid['lsm'] = np.array(lsm).ravel(order='F')

grid.plot()
```

![download](https://user-images.githubusercontent.com/22067021/65935075-000e7f00-e3d5-11e9-9322-852b39b1631b.png)

**Comment by banesullivan** [comment]
I suppose you might actually want this data to be on the cells and not the vertices of the mesh... in that case, maybe try this which will create a closed sphere:

(however this requires some knowledge about the spatial reference which could likely be implemented programatically besides explicitly setting the `arange` values)

```py
import xarray as xr
import numpy as np
import pyvista as pv

lsm = xr.open_dataarray("lsm_4x5.nc")  # netCDF file is attached as a tar.gz archive

xx, yy, zz = np.meshgrid(np.radians(np.arange(0, 365, 5, )), 
                         np.radians(np.arange(-90, 94, 4)), 
                         [0])

# Transform to spherical coordinates
radius = 6371.0e6
x = radius * np.cos(yy) * np.cos(xx)
y = radius * np.cos(yy) * np.sin(xx)
z = radius * np.sin(yy)

grid = pv.StructuredGrid(x, y, z)
grid.cell_arrays['lsm'] = np.array(lsm).ravel(order='F')

grid.plot()
```

![download](https://user-images.githubusercontent.com/22067021/65935361-1406b080-e3d6-11e9-8b06-84433c7efbb3.png)

**Comment by dennissergeev** [comment]
This is brilliant, thank you!

**Comment by dennissergeev** [comment]
Continuing this topic, I was wondering if it is also possible to create a spherical "shell", i.e. a mesh that has multiple z levels instead of just `[0]`?

**Comment by banesullivan** [comment]
Hm... maybe it is possible to do it with some meshgrid tricks. I’ll see if I can make something work. I remember trying this back when I was looking at #52, but didn’t figure it out then

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by banesullivan** [comment]
Check this out and let me know what you think:

```py
import numpy as np
import pyvista as pv

radial = np.linspace(0, 6371.0e6, 10)
xx, yy, zz = np.meshgrid(np.radians(np.arange(0, 365, 5, )), 
                         np.radians(np.arange(-90, 94, 4)), 
                         radial)

# Transform to spherical coordinates
x = zz * np.cos(yy) * np.cos(xx)
y = zz * np.cos(yy) * np.sin(xx)
z = zz * np.sin(yy)

grid = pv.StructuredGrid(x, y, z)
grid['radials'] = zz.ravel(order='F')

# Show wireframe to see inside of mesh
grid.wireframe().plot(notebook=0)
```

![2019-10-02 10 21 54](https://user-images.githubusercontent.com/22067021/66062340-7a86ee00-e4fe-11e9-923d-12f0dafa9bd9.gif)

**Comment by dennissergeev** [comment]
Thanks a lot, @banesullivan! This is great.

This is exactly what I mean, so the next step that I tried is to plot something in this 3D wireframe, for example an isosurface. It seems to work for me, but only if I transpose the data array, i.e.:
```python
grid.cell_arrays["iso_arr"] = scalar3d.data[:20].transpose((1, 2, 0)).ravel(order="F")
```
where `scalar3d` has dimensions (height, latitude, longitude). The order of axes looks odd, but it seems to give what I expect. Does this make sense to you?

**Comment by banesullivan** [comment]
That order has to do with the F ordering (z, y, x) so when you ravel it it comes out right

**Comment by banesullivan** [comment]
or maybe not, I'm not sure. This is a bit messy

**Comment by dennissergeev** [comment]
OK, thanks!
