### ISSUE TITLE
Picking a point and calling point ID/value... from picked_points

### ISSUE THREAD

**Issue by MYOSUN** [pyvista/pyvista-support#72]

**Comment by MYOSUN** [comment]
Dears,
I have tried to get point ID or value by picking, but didnt succeeded.
I'm new at pyvista, couldn't found an example for this. A simple example will be really helpful.
Thanks in advance.

**Comment by banesullivan** [comment]
You’re absolutely right that we don’t have any examples in the docs for point/cell picking and leveraging a few of the helper methods for those features - hopefully we can use this issue as a place to aggregate some of the demos/examples that are floating around in different threads.

There are two modes of picking in PyVista:

1. Cell picking (`enable_cell_picking()`) - this allows you to either select a region of cells on a mesh’s surface or through a mesh. When using surface picking, you can select a single cell and that cell will be passed to the callback with the ID in the cell data.
2. Point picking (`.enable_point_picking()`)- this allows you to select a single point on a mesh’s surface. If you leverage the `use_mesh=True`, then it will pass the selected point and it’s ID to the given callback method.

Here are some issues where we have snippets that leverage these picking features as we were developing them:

- https://github.com/pyvista/pyvista/pull/278
- https://github.com/pyvista/pyvista/pull/281
- https://github.com/pyvista/pyvista/pull/362
- https://github.com/pyvista/pyvista/issues/282

Do you have code that you are working with that I can help you get running?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MYOSUN** [comment]
Dear Sullivan,

Thank you for these information and for the well documented guide of pyvista. I need to implement more to understand the structure of this library. 

"pyvista/pyvista#282" is close to what i m trying to do. My purpose is to select several points arbitrary and get information of each node. So i can process these values to generate new results.

I tried to edit the script below to get information from selected node, but not succeeded.
i will be really appreciated for your help on these issues:
- How should i run succesfully the script below to get the value, id of the node.
- In this example dispacements are defined only on Y axis. What should i do to define displecement on X,Y,Z axes. (example calculated the value of Y as a function of Z. Could you please extend this example adding X displcement.)
- I want to highlight the selected nodes. I thought that when i get coordinates of selected node, i can create a new point. Or do you suggest an easy way to make selected points highlighted.
- As i understand only single point is allowed to select at once, right? Suggestion to make it arbitrary.

Now i m working on the example codes. Here is the a bit modified one for my purpose.
Thanks in advance.
--
import pyvista as pv
from pyvista import examples
import numpy as np

# Load example beam grid
grid = pv.UnstructuredGrid(examples.hexbeamfile)

# Create fictitious displacements as a function of Z location
d = np.zeros_like(grid.points)
d[:, 1] = grid.points[:, 2]**3/250

# Displace original grid
grid.points += d


# Camera position. 
cpos = [(12, 6, 3.6),(0.0, 0.375, 2.0),(-0.425, 0.9, -0.068)]

# plot this displaced beam

p = pv.Plotter(notebook=0)
p.add_mesh(grid, show_edges=True, scalars=d[:, 1], stitle='Y Displacement', rng=[-d.max(), d.max()])
p.add_axes()
p.camera_position = cpos

dargs = dict(name='labels', font_size=12)
callback = lambda selected: p.add_point_scalar_labels(selected,'scalars' **dargs)
p.enable_point_picking(callback=callback, show_message=True, font_size=18, color='pink', point_size=10, use_mesh=True, show_point=True)
p.show()

**Comment by banesullivan** [comment]
A few points:
- You need to track the scalar array on the mesh: `grid[array_name] = d[:, 1]`
- Per the docs of `enable_point_picking()`, you need to take two arguments in your callback finction when using `use_mesh=True`
    > If ``use_mesh`` is True, the callback function will be passed a pointer
to the picked mesh and the point ID of the selcted mesh.
- you should use `.add_point_labels` in your callback instead and manually construct the message that you want to display

```py
import pyvista as pv
from pyvista import examples
import numpy as np

grid = pv.UnstructuredGrid(examples.hexbeamfile)

d = np.zeros_like(grid.points)
d[:, 1] = grid.points[:, 2]**3/250

array_name = 'Y Displacement'
grid[array_name] = d[:, 1]

grid.points += d
cpos = [(12, 6, 3.6),(0.0, 0.375, 2.0),(-0.425, 0.9, -0.068)]

p = pv.Plotter(notebook=0)
p.add_mesh(grid, show_edges=True, scalars=array_name, 
           clim=[-d.max(), d.max()])
p.add_axes()
p.camera_position = cpos

dargs = dict(name='labels', font_size=24)

def callback(mesh, pid):
    point = grid.points[pid]
    label = ['ID: {}\n{}: {}'.format(pid, 
                                     array_name, 
                                     grid[array_name][pid])]
    p.add_point_labels(point, label, **dargs)

p.enable_point_picking(callback=callback, show_message=True, 
                       color='pink', point_size=10, 
                       use_mesh=True, show_point=True)
p.show()
```

![2019-10-29 12 46 30](https://user-images.githubusercontent.com/22067021/67799002-31b54d00-fa4a-11e9-960a-753a7506b749.gif)
