### ISSUE TITLE
Suggestion or question: How to use a mask or extract a Polydata mesh with scalar_arrays?

### ISSUE THREAD

**Issue by math-artist** [pyvista/pyvista-support#76]
I have Polydata objects with 5 or more scalar_arrays.  One of the arrays is the points indices.

After some work on the Polydata, it has been trimmed, moved, etc. and the indices are useful, but what if I want to create a mask based on a scalar_array to filter the mesh and create a new Polydata object containing all the scalar arrays from the remaining points/cells?

Is there a simple way to do that with PyVista?

Edit: I tried mesh.extract_points(my indices) on my original mesh, but something strange happens. When I use an array of 74 indices, I get an Unstructuredgrid of 131 points and 201 cells. I've looked at the bounds and it seems to be properly located.

**Comment by banesullivan** [comment]
Wouldn't the [`.threshold()`](https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.threshold) filter based on the masking array's conditions work? This filter will operate on a singles scalar array at a time and produce a new mesh meeting the condition on that scalar array. (at the moment the `.threshold()` filter always returns an `UnstructuredGrid` but you can cast that back to a `PolyData` mesh with the `.extract_surface` filter).

Here is an example where I create a masking array that can be displayed on the original mesh:

```py
import pyvista as pv
from pyvista import examples

# load example globe and add an elevation scalar
mesh = examples.load_globe().elevation()
# add an points id scalar
mesh["PointIDs"] = np.arange(mesh.n_points)

# Value is the contion to evaluate
#  note the `extract_surface` filter chained on
evaluated = mesh.threshold(value=[-4e+09, 4e+09], 
                           scalars="Elevation", 
                           invert=False).extract_surface()
# Now used that evaluated mesh to mask the original mesh
mesh["mask"] = np.zeros(mesh.n_points)
mesh["mask"][evaluated["PointIDs"]] = 1

# Display that mask on the oroiginal mesh
mesh.plot(scalars="mask", 
          cmap="coolwarm",
          texture=True,
          lighting=False,
          interpolate_before_map=False)
```
![download](https://user-images.githubusercontent.com/22067021/68515452-33e38c80-023e-11ea-8f10-1ffc998f9fa9.png)

**Comment by math-artist** [comment]
Not in this situation. I first get a list of indices from a selection. Then I use numpy.in1d to remove some of my indices to avoid having indices out of range, because they need to be applied on another mesh with additional scalars, but less points than the original mesh. 

The scalars I am using now are indices and they can't be filtered by range...

I get this from the extract_points. It takes additional points during extraction.
```
new_mesh = original_mesh.extract_points(indices)
indices
Out[48]: 
array([271637, 271636, 271638, 271639, 271641, 271660, 271661, 271662,
       271642, 271663, 271664, 271665, 271666, 271667, 271668, 271648,
       271650, 271669, 271670, 271671, 271672, 271674, 271676, 379005,
       379006, 379014, 379016, 379015, 379017, 379043, 379047, 379048,
       379049, 379050, 474737])
new_mesh["id"]
Out[49]: 
array([271636, 271635, 271630, 271637, 271638, 271633, 271639, 271634,
       271640, 271641, 271642, 271626, 271648, 271647, 271649, 271650,
       271657, 271656, 271660, 271661, 271662, 271663, 271664, 271665,
       271666, 271667, 271668, 271669, 271670, 271671, 271672, 271673,
       271674, 271676, 378997, 378999, 379005, 379004, 379006, 379008,
       379014, 379015, 379016, 379017, 379019, 379022, 379042, 379043,
       379044, 379045, 379047, 379048, 379049, 379050, 379056, 379057,
       474737, 474738, 474739, 474740, 474742, 474745])
```

**Comment by banesullivan** [comment]
I'm not sure I follow what you are trying to do. Could you reproduce and share your workflow using one of the meshes available in PyVista's `examples` module? or better yet, upload a subset of your own mesh?

**Comment by math-artist** [comment]
OK, I read your post a few times to better understand what's happening on this line
`mesh["mask"][evaluated["PointIDs"]] = 1
`
After you set a mask, is it possible to "trim" that mesh for `mesh["mask"] = 1` and get a new mesh?

Maybe I am going in the wrong direction with this. I have **many** meshes in the renderer and currently I am allowed to select only one mesh at a time. Thoses meshes get clipped into smaller sub-meshes and each one is then processed differently. Later in the workflow, it is possible to select a small area and create a spline based on the scalars. 

To simplify the selection, I kept the original mesh as the target, to avoid constantly switching between meshes. Then I am trying to filter selected ids not in the sub-mesh to create the sub-mesh selection because this mesh will be processed with a StructuredGrid by the FindCell function to create a new array. Basically, convert a mesh into a structured array/numpy array to perform array operations on it.

This may seem overcomplicated, but later I will have non-linear curved structuredgrids following and slicing data, so I can't simply use ranges of coordinates to do this.

**Comment by math-artist** [comment]
OK, I found the reason why the number of points returned is different. This flag:
`selectionNode.GetProperties().Set(vtk.vtkSelectionNode.CONTAINING_CELLS(), 1)`
will return all the cells containing the point. But the cell cannot be made without adding other points. This intentionally adds one layer of cells and additional points connected to the new cells. 

Is this the desired behavior for the extracted_points method?

**Comment by math-artist** [comment]
I found the solution to my problem.
```
new_indices = np.where(np.isin(sub_mesh_indices, selected_indices)) 
sub_mesh["array_name"][new_indices]
```
to convert my original indices to the new indices and properly select the scalars.
