### ISSUE TITLE
Voxelisation of a 3D mesh

### ISSUE THREAD

**Issue by bsburnham** [pyvista/pyvista-support#78]
## Description
I'm wondering if there is the opportunity to add the capability to voxelise a 3D polygonal dataset and then attribute scalar properties to that 3D polygon? This type of data would have unconventional 3D geometry associated with it that would be difficult to replicate without the use of specialist 3D modelling tools (e.g. Maya, Blender, Rhino etc). An example would be a 3D geobody generated from an outcrop dataset that is used as a subsurface analogue. Having the ability to voxelise the 3D objects and add scalar properties (e.g. porosity, permeability, density etc.) would help in preparation for use in a (reservoir) modelling package if they wish,  but more importantly to utilise the tools and capabilities in `pyvista`. 

## Example Data
An example dataset to use that would have similar unconventional geometry is a salt dome. The SEG/EAGE 3D Salt Model is a good example. (https://github.com/pyvista/show-room/blob/master/seg-eage-3d-salt-model.ipynb). I've attached a `.ply` version of the salt dome as this would be a similar file format that one would have when building a 3D deterministic model.

**Comment by akaszynski** [comment]
I know of a way to voxelize a dataset that's manifold.  If there's a surface, you can create a background structured grid and then remove any cells that don't lie within that surface.  Then you can extract those cells and create an unstructured grid containing just those cells.

Does that work for your dataset?

**Comment by akaszynski** [comment]
Also, have you tried looking at ``pyvista.voxelize``?

**Comment by tmatsuzawa** [comment]
You can throw a 3D mesh to pyvista.voxelize but it voxelizes not only the surface/mesh but also the region bounded by the surface. (In the image below, I used a spherical mesh.) How can I voxelize only the surface but not the bulk?

![image](https://user-images.githubusercontent.com/29457620/111685439-eb56be80-87f5-11eb-9f77-01074fb0f76a.png)

**Comment by RichardScottOZ** [comment]
What's the biggest you can do?

I am considering large block model type things currently and was wondering how to break things up.
