### ISSUE TITLE
Animation for time history analysis

### ISSUE THREAD

**Issue by motiurce** [pyvista/pyvista-support#79]
I want to make animation file (gif/mp4) for time history analysis of structures (unstructured mesh) using PyVista. If possible please help me, how can can I make code for this file?

**Comment by banesullivan** [comment]
Have you checked out the following examples?

- https://docs.pyvista.org/examples/02-plot/gif.html
- https://docs.pyvista.org/examples/02-plot/movie.html

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by motiurce** [comment]
Thank you so much. If possible please help me the following>>I how can I start/pouse this animation in pyqt5 frame using button?

**Comment by banesullivan** [comment]
> I how can I start/pouse this animation in pyqt5 frame using button?

That is a non-trivial task and something I don't have sample code for at the moment. Basically you'll need to use PyVista's `BackgroundPlotter` or embedd PyVista's `QtInteractor` class into your own Qt app then add a button to the app that triggers a callback for controlling the time anaimation.

I imagine you'd need to have two class variables `timestep` for keeping track of the time value and a boolean `is_playing`. The button would switch the value of `is_playing` and when the button is pressed, it will trigger a background thread that updates your mesh through time much like the examples above.

**Comment by banesullivan** [comment]
@GuillaumeFavelier's work on the new checkbox button might be relevant here. See https://github.com/pyvista/pyvista/pull/528 for details.
