### ISSUE TITLE
Distance/thickness between two surfaces

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista-support#80]
## Description

I was recently asked if it were possible to compute the average thickness between two surfaces. For example, you might have two surfaces that represent the boundaries of lithological layers in a subsurface geological model and you want to know the average thickness of a unit between those boundaries.

I have used the `ParametricRandomHills` helper to create some surface data to try this out.

**Edit: see KDTree example in later comments**

## Example

The following does the trick by ray tracing but does anyone have any ideas on other ways to compute the average thickness?

```py
import pyvista as pv
from pyvista import examples
import numpy as np

def hill(seed):
    mesh = pv.ParametricRandomHills(randomseed=seed, 
                                    hillamplitude=0.5)
    mesh.rotate_y(80) # give the surfaces some tilt
    return mesh

# Shift one surface
h0 = hill(1).elevation()
h1 = hill(10)
h1.points[:,-1] += 5
h1 = h1.elevation()

p = pv.Plotter(notebook=1)
p.add_mesh(h0)
p.add_mesh(h1)
p.show_grid()
p.show()
```

![download](https://user-images.githubusercontent.com/22067021/69761814-b2d53200-1125-11ea-9edd-f26f6a78321e.png)

```py
# compute normals of lower surface
h0n = h0.compute_normals(point_normals=True, cell_normals=False, 
                         auto_orient_normals=True, )

# Travel along noramals to the other surface
# and compute the thickness on each vector
h0n["distances"] = np.empty(h0.n_points)
for i in range(h0n.n_points):
    p = h0n.points[i]
    vec = h0n["Normals"][i] * h0n.length
    p0 = p - vec
    p1 = p + vec
    ip, ic = h1.ray_trace(p0, p1, first_point=True)
    dist = np.sqrt(np.sum((ip - p)**2))
    h0n["distances"][i] = dist
    
# Replace zeros with nans
mask = h0n["distances"] == 0
h0n["distances"][mask] = np.nan
np.nanmean(h0n["distances"])
```
5.14863403912341

That value of about 5 makes sense as I shifted the hills by 5 and they have a small variance.

```py
p = pv.Plotter(notebook=True)
p.add_mesh(h0n, scalars="distances")
p.add_mesh(h1, color=True, opacity=0.75)
p.show()
```

![download](https://user-images.githubusercontent.com/22067021/69761855-d4ceb480-1125-11ea-931c-a73d1e5a956a.png)

**Comment by akaszynski** [comment]
You could also use `pykdtree` or `scipy.spatial.KDTree` to compare the distance between each point of the upper surface and the nearest neighbor of the lower surface.  This won't be the exact surface to surface distance, but it will be noticeably faster than a ray trace, especially for large surfaces.

**Comment by banesullivan** [comment]
Ah, a KDTree would be way simpler - I'll do that too real quick

**Comment by banesullivan** [comment]
And here is the same thing with a KDTree (I'd recommend using SKLearn's tree over scipy)

```py
import pyvista as pv
import numpy as np
from scipy.spatial import KDTree

def hill(seed):
    mesh = pv.ParametricRandomHills(randomseed=seed, 
                                    hillamplitude=0.5)
    mesh.rotate_y(80) # give the surfaces some tilt
    return mesh

# Shift one surface
h0 = hill(1).elevation()
h1 = hill(10)
h1.points[:,-1] += 5
h1 = h1.elevation()

tree = KDTree(h1.points)
d, idx = tree.query(h0.points )
h0["distances"] = d
np.mean(d)
```

4.842395356478514

```py
p = pv.Plotter(notebook=True)
p.add_mesh(h0, scalars="distances")
p.add_mesh(h1, color=True, opacity=0.75)
p.show()
```

![download](https://user-images.githubusercontent.com/22067021/69762527-b8337c00-1127-11ea-9790-370b4fb93e86.png)

**Comment by gokceay** [comment]
Hi, I am using pyvista for data visualization and data preprocessing for a dataset. I fixed my meshes, smoothed, and aligned them. After that I used ray tracing distance or KDTree approach to calculate the difference between surfaces. What I need to take 2D matrix of heatmap from the calculation. I think I need to use Kernel Density Approach to make a grid of smoothed values of differences between 2 aligned surfaces. I am not sure which one to use for to calculate the distance between surfaces(KDTree or ray tracing distance), and how to get 2D matrix from that measurement. Would you show me the way to get 2D matrix  of distance between two surfaces? thanks in advance

**Comment by banesullivan** [comment]
@gokceay, Would you please open a new discussion here: https://github.com/pyvista/pyvista/discussions
