### ISSUE TITLE
Animation quality

### ISSUE THREAD

**Issue by dennissergeev** [pyvista/pyvista-support#81]
Is there a away to increase the quality of animation saved to as a GIF or movie?

## Description
I create animation using `Plotter.orbit_on_path()` method. When I save it, the quality is much lower than what appears when I just `show()` the scene. As an example, I added `orbit_on_path()` to the first "spherical" example. You can see that the scene is very "rasterised".

![orbit_sphere](https://user-images.githubusercontent.com/12111288/69827433-59493200-120f-11ea-8762-c09c2bf360d2.gif)

Here I used the default call to create an orbit
```python
path = p.generate_orbital_path(n_points=36, shift=1e4)
```
However, changing arguments of this function doesn't help.

**Comment by banesullivan** [comment]
The "rasterization" is due to the pixel resolution of the frames. The resolution of the frames is determined by the `window_size` of the plotter. 

Also with GIFs, the colors aren't very good, writing them takes a while, and the file sizes are overly big. I'd try increasing the window size and using an MP4 instead like:

```py
import pyvista as pv

mesh = pv.Sphere().decimate(0.3).compute_cell_quality()

p = pv.Plotter(window_size=([2048, 1536]))
p.add_mesh(mesh, cmap="jet")
path = p.generate_orbital_path(n_points=25, viewup=(1,1,1))
p.show(auto_close=False)
p.open_movie("~/Desktop/foo.mp4")
# p.open_gif("~/Desktop/foo.gif")
p.orbit_on_path(path, write_frames=True)
p.close()
```

MP4s aren't supported by github so here is the GIF with the increased resolution

![foo](https://user-images.githubusercontent.com/22067021/69830625-efb32e80-11e2-11ea-928b-6df0284d44e1.gif)

**Comment by banesullivan** [comment]
Also, using `smooth_shading=True` on your `.add_mesh()` call with smooth out the surface mesh and might help a bit

**Comment by dennissergeev** [comment]
Thanks for the prompt response @banesullivan !

I'm not sure what I am doing wrong, but increasing `window_size` doesn't really help, and the final output MP4 file has the same (small) size. I also get the same warning every time:
```
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (1853, 1025) to (1856, 1040) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
```

Also, while we're on this topic, changing `step=` kwarg in `p.orbit_on_path()` doesn't seem to change the duration or speed of the movie. Could you please explain why?

**Comment by banesullivan** [comment]
> I'm not sure what I am doing wrong, but increasing window_size doesn't really help, and the final output MP4 file has the same (small) size. I also get the same warning every time

Huh. That's weird.  It looks like it is writing to the correct resolution as the warning is just letting you know it has to fix your size choice for MP4 compatibility. Can you make sure to delete the original movie file and make sure your checking the right file? If so, could you then share a system report to help me figure out why its not writing to the correct resolution:

```py
import pyvista as pv
print(pv.Report()
```

> Also, while we're on this topic, changing step= kwarg in p.orbit_on_path() doesn't seem to change the duration or speed of the movie. Could you please explain why?

The step argument there has nothing to do with the speed of the video/GIF but is there for when using with a `BackgroundPlotter` and you want to have the orbit done in real time rather than as a movie.

The movie framerate (FPS) is controlled by the second argument in the `open_movie()` method and defaults to 24

**Comment by dennissergeev** [comment]
> The step argument there has nothing to do with the speed of the video/GIF but is there for when using with a BackgroundPlotter and you want to have the orbit done in real time rather than as a movie.

Thanks for the explanation!

**Comment by dennissergeev** [comment]
>  the warning is just letting you know it has to fix your size choice for MP4 compatibility
But "resizing from (1853, 1025)" part in the warning stays the same however large the `window_size` is - and it's not 2048 by 1536 when I use your example.

I tried a bunch of different sizes (see GIFs below) and I think the problem is that it can't be above ~1853x1025 (the file size confirms it). Can this be capped by my screen size? If so, is it possible to write animations without opening a display window?

<details><summary>GIFs</summary>
200x100

![foo_200x100](https://user-images.githubusercontent.com/12111288/69907330-49764d00-13cb-11ea-9d0d-1318d87a5419.gif)

1024x768 (default)

![foo_1024x768](https://user-images.githubusercontent.com/12111288/69907343-84788080-13cb-11ea-87a1-1a1c88fa26f0.gif)

2048x1536

![foo_2048x1536](https://user-images.githubusercontent.com/12111288/69907353-ae31a780-13cb-11ea-8c51-29a8628acd76.gif)

4096x3072

![foo_4096x3072](https://user-images.githubusercontent.com/12111288/69907359-c1dd0e00-13cb-11ea-9665-4f725f397710.gif)

Note that even with large window size the image quality is not great... 
</details>

Here's the output of `pv.Report()`
```
--------------------------------------------------------------------------------
  Date: Sat Nov 30 23:31:50 2019 GMT

             Linux : OS
                 4 : CPU(s)
            x86_64 : Machine
             64bit : Architecture
            7.7 GB : RAM
           IPython : Environment

  Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)
  [GCC 7.3.0]

            0.22.4 : pyvista
             8.2.0 : vtk
            1.17.3 : numpy
             2.6.1 : imageio
             1.4.3 : appdirs
             0.4.3 : scooby
             2.2.4 : matplotlib
            5.12.3 : PyQt5
             7.9.0 : IPython
             7.5.1 : ipywidgets
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment]
Do the MP4s look better? I think the less than desired quality here is just due to them being in the GIF format. 

I’ll see what else I can do to increase the resolution 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dennissergeev** [comment]
I think they look only slightly better (see the [archive](https://github.com/pyvista/pyvista-support/files/3910861/pv_movie_diff_res.tar.gz) attached). The quality doesn't really improve after hitting the cap of ~141KB per file, as I mentioned in the previous comment.

**Comment by banesullivan** [comment]
Yeah, the resolution isn't great in those images either. I'll see what I can do to figure out how to increase the DPI of screenshots

**Comment by akaszynski** [comment]
Found that the trick was plotting `off_screen`:

```python
import pyvista as pv

mesh = pv.Sphere().decimate(0.3).compute_cell_quality()

p = pv.Plotter(window_size=([2048, 1536]), off_screen=True)
p.add_mesh(mesh, cmap="hot", smooth_shading=True)
path = p.generate_orbital_path(n_points=250, viewup=(1,1,1))
p.show(auto_close=False)
p.open_movie("foo.mp4")
p.orbit_on_path(path, write_frames=True)
p.close()
```
@dennissergeev, can you let me know if this worked for you?  Also, can you please post your code here?  I'm lazy ;)

**Comment by dennissergeev** [comment]
Thanks @akaszynski, `off_screen` option seems to solve the problem. The IMAGEIO resizing error does not pop up and the file size increases with higher resolution.

<details><summary>My script, if you're interested</summary>

```python

"""
Example script for https://github.com/pyvista/pyvista-support/issues/81
"""
import pyvista as pv
import numpy as np


def grid_from_sph_coords(theta, phi, r):
    """Create a structured grid from arrays of spherical coordinates.
    Parameters
    ----------
    theta: array-like
        Azimuthal angle in degrees [0, 360)
    phi: array-like
        Polar (zenith) angle in degrees [0, 180]
    r: array-like
        Distance (radius) from the point of origin
    Return
    ------
    pyvista.StructuredGrid
    """
    x, y, z = np.meshgrid(np.radians(theta), np.radians(phi), r)
    # Transform grid to cartesian coordinates
    x_cart = z * np.sin(y) * np.cos(x)
    y_cart = z * np.sin(y) * np.sin(x)
    z_cart = z * np.cos(y)
    # Make a grid object
    return pv.StructuredGrid(x_cart, y_cart, z_cart)


def _cell_bounds(points, bound_position=0.5):
    """
    Calculate coordinate cell boundaries.

    Parameters
    ----------
    points: numpy.array
        One-dimensional array of uniformy spaced values of shape (M,)
    bound_position: bool, optional
        The desired position of the bounds relative to the position
        of the points.

    Returns
    -------
    bounds: numpy.array
        Array of shape (M+1,)

    Examples
    --------
    >>> a = np.arange(-1, 2.5, 0.5)
    >>> a
    array([-1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])
    >>> cell_bounds(a)
    array([-1.25, -0.75, -0.25,  0.25,  0.75,  1.25,  1.75,  2.25])
    """
    assert points.ndim == 1, "Only 1D points are allowed"
    diffs = np.diff(points)
    delta = diffs[0] * bound_position
    bounds = np.concatenate([[points[0] - delta], points + delta])
    return bounds


# First, create some dummy data

# Approximate radius of the Earth
RADIUS = 6371.0

# Longitudes and latitudes
x = np.arange(0, 360, 5)
y = np.arange(-90, 91, 10)
y_polar = 90.0 - y  # grid_from_sph_coords() expects polar angle

xx, yy = np.meshgrid(x, y)

# x- and y-components of the wind vector
u_vec = np.cos(np.radians(xx))  # zonal
v_vec = np.sin(np.radians(yy))  # meridional

# Scalar data
scalar = u_vec ** 2 + v_vec ** 2

# Create arrays of grid cell boundaries, which have shape of (x.shape[0] + 1)
xx_bounds = _cell_bounds(x)
yy_bounds = _cell_bounds(y_polar)
# Vertical levels
# in this case a single level slightly above the surface of a sphere
levels = [RADIUS * 1.01]

###############################################################################
# Create a structured grid
grid_scalar = grid_from_sph_coords(xx_bounds, yy_bounds, levels)

# And fill its cell arrays with the scalar data
grid_scalar.cell_arrays["ex"] = np.array(scalar).swapaxes(-2, -1).ravel("C")

# Make a plot
w, h = 2048, 1536
p = pv.Plotter(window_size=([w, h]), off_screen=True)
p.add_mesh(pv.Sphere(radius=RADIUS))
p.add_mesh(
    grid_scalar, clim=[0.1, 2.0], opacity=0.75, cmap="plasma",
)
path = p.generate_orbital_path(n_points=250, viewup=[1, 1, 1])
p.show(auto_close=False)
p.open_movie(f"foo_{w:04d}x{h:04d}.mp4")
p.orbit_on_path(path, write_frames=True)
p.close()
```
</details>

**Comment by akaszynski** [comment]
Glad it worked out.  Thanks for the script!

**Comment by adouverny** [comment]
Hi everyone, first off I'd like to say PyVista is probably my favorite python package, it's truly phenomenal!

I seem to have the same issue when saving an mp4/mkv file, even if I use the `off_screen` option. It seems no matter what window size I choose, it gets capped at 1920x1080  - rather, it is first rescaled to 1924x1061 before `write_frame()` is called, and then rescaled by ImageIO to 1936x1072 - and the resulting video is quite pixelated. The video file size is also capped at around 1 MB.  The same goes for any screenshots, with the file size capped at 300 KB.

Since I am using a laptop with a dedicated GPU, at first I thought it was due to python utilizing integrated graphics. However, I have set it up such that it now always uses the dedicated GPU, but the problem persists. 

Additionally, I get the following warnings:

```
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (1924, 1061) to (1936, 1072) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
[swscaler @ 0000022afedf0f80] Warning: data is not aligned! This can lead to a speed loss
```

My code is not much different, than the above, so I am not too sure what is causing this. I have a workaround, which is to just open the plotter and record the screen, but the movements are not as smooth as using the orbit paths. Any help would be greatly appreciated! 

Note: I am using Python 3.6, with pyvista 0.31

```
# Make grid
grid = pv.UniformGrid()
grid.dimensions = np.array(data.shape) + 1
grid.origin = origin
grid.spacing = spacing

grid.cell_arrays['data'] = data.flatten(order='F')

print('Setting up plotter...')
plotter = pv.Plotter(window_size=([1920, 1080]), off_screen=True,
                     line_smoothing=True, polygon_smoothing=True, multi_samples=8)
plotter.set_background(color=[0, 0, 0])

plotter.add_mesh(grid.slice(normal='x', origin=grid.center - 50 * np.array([1, 0, 0])), opacity=0.75,
                 show_scalar_bar=False, smooth_shading=True)
plotter.add_mesh(grid.slice(normal='y', origin=grid.center), opacity=0.75, show_scalar_bar=False, smooth_shading=True)
plotter.add_mesh(grid.slice(normal='z', origin=grid.center - 50 * np.array([0, 0, 1])), opacity=0.75,
                 show_scalar_bar=False, smooth_shading=True)

viewup = [0, 0, 1]
orbit = plotter.generate_orbital_path(factor=2.0, n_points=250, shift=0.0, viewup=viewup)

print('Saving to mkv file...')
plotter.show(auto_close=False)
plotter.open_movie('movie.mkv', framerate=60)
plotter.orbit_on_path(orbit, write_frames=True, viewup=viewup)
plotter.close()
```

**Comment by akaszynski** [comment]
Does saving to a different file type change anything?  If this continues to be an issue we might have to implement some sort of quality parameter in `open_movie`

**Comment by adouverny** [comment]
> 
> 
> Does saving to a different file type change anything? If this continues to be an issue we might have to implement some sort of quality parameter in `open_movie`

I have tried saving the file as .mov, .avi, .mpg, .mp4, .mpeg and .mkv, yet the problem persists in all of these cases. Interestingly enough, changing `open_movie` to `open_gif` seems to work, color issues notwithstanding.
