### ISSUE TITLE
Trouble making PolyData from CSV file

### ISSUE THREAD

**Issue by Sunil7545** [pyvista/pyvista-support#84]
## Description
Dear PyVista team,
I am using delaunay_2d function to create a triangulated mesh from a given point set (numpy 3d array).  However, the method is not returning the corresponding mesh.
I do not have much experience with PyVista.
I would be really grateful if you can take a look and help me regrading this issue.
I am attaching the data and a code snippet (in example data section
[objtest.zip](https://github.com/pyvista/pyvista-support/files/3960376/objtest.zip)
 ), which I used for this task. 

## Example Data

```py
import pandas as pd
import pyvista as pv

raw_data = pd.read_csv('objtest.csv', header=None)
loc = raw_data[raw_data.columns[1:4]]
points_3d = loc.to_numpy()
cloud = pv.PolyData(points_3d)
surf = cloud.delaunay_2d()
surf.plot(show_edges=True)
```

**Comment by banesullivan** [comment]
So. A few things

1. You need to specify a delimiter when reading your file
2. This file has comments starting with `#`
3. This file isn't just a CSV of a point cloud, it has vertices and faces defined: the `v` and `f` qualifiers which is a proper mesh
4. You can either use the fces defined in the file or use a delaunay triangulation

The issues you are having are simply due to how you are reading this file. below is some code to properly input the file and use its vertices and faces

----

```py
import pandas as pd
import pyvista as pv
import numpy as np

f = "/Users/bane/Desktop/objtest.csv"

raw_data = pd.read_csv(f, header=None, comment="#",
                       delim_whitespace=True, names=["type", "a", "b", "c"])

vidxs = np.argwhere(raw_data["type"].str.contains("v")).ravel()
fidxs = np.argwhere(raw_data["type"].str.contains("f")).ravel()

# The XYZ coordinates
vertices = raw_data.iloc[vidxs][["a", "b", "c"]].values

cloud = pv.PolyData(vertices)
cloud.plot(eye_dome_lighting=True)
```
![download](https://user-images.githubusercontent.com/22067021/70810622-5ad33800-1d81-11ea-950f-407a09fad84c.png)


```py
# Let's delaunay this because why not
interp = cloud.delaunay_2d()

# But let's also use the faces defined in the input file
# Build faces for PyVsta
# Note the minus 1 because someone used off by 1 indexing
faces = (raw_data.iloc[fidxs][["a", "b", "c"]].values).astype(int) - 1
faces = np.column_stack((np.full(len(faces), 3), faces))

# Create PolyData mesh
surf = pv.PolyData(vertices, faces)
surf.plot()
```
![download](https://user-images.githubusercontent.com/22067021/70810663-6d4d7180-1d81-11ea-96d4-4244338c00b0.png)

```py
# Compare!
dargs = dict(show_edges=True, edge_color="grey", line_width=1)

p = pv.Plotter(shape="2|1")

p.add_mesh(cloud)
p.add_text("Point Cloud")

p.subplot(1, 0)
p.add_mesh(interp, **dargs)
p.add_text("Delaunay Triangulation")

p.subplot(2, 0)
p.add_mesh(surf, **dargs)
p.add_text("Original Mesh")

p.link_views()
p.camera_position = [(58.063124972354686, 252.6373929549568, 185.66316942673754),
 (84.25545821345024, 185.6159221031039, 169.38926971347774),
 (0.03409505366222231, -0.22322013612480637, 0.9741715958414068)]
p.show()
```

![download](https://user-images.githubusercontent.com/22067021/70810684-73dbe900-1d81-11ea-9495-307bf155fba4.png)

**Comment by Sunil7545** [comment]
Dear Bane,
Thank you very much for the quick response and solution.

Regards
Sunil

**Comment by Sunil7545** [comment]
Just one more question, PyVista also has marching cube algorithm, which can be applied on a point set ?

**Comment by akaszynski** [comment]
The marching cubes algorithm implemented in pyvista uses VTK's underlying `vtkMarchingCubes` algorithm, which isn't setup for handling unstructured point sets:

> vtkMarchingCubes is a filter that takes as input a volume (e.g., 3D structured point set) and generates on output one or more isosurfaces. One or more contour values must be specified to generate the isosurfaces. Alternatively, you can specify a min/max scalar range and the number of contours to generate a series of evenly spaced contour values.

**Comment by Sunil7545** [comment]
Thanks for the reply. So for the above point set, can I create voxelized 3D structure using a tool from PvGeo (PvGeo.fileters.volxelizePoints) and apply vtkMarchingCubes ?

Or can you recommend some other methods to compute a triangulated mesh from 3D points using python  ?

**Comment by banesullivan** [comment]
What’s your goal? You already have a triangulated mesh...

Why do you want to use the marching cubes algorithm? Is there a scalar field you want to contour? This will help use make an example workflow for you

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sunil7545** [comment]
Hi Bane,
Thank you very much quick reply.
I want to reconstruct triangulated mesh from 3d data points.
The data, I have shared is basically a reference mesh, If I can reconstruct the a mesh surface with the similar quality, using the vertices of the given data, that would be really nice.

As you can see, delaunay_2d is not very suitable for this task. I would be really grateful, if you can suggest me some other method to reconstruct the triangulated mesh from the given points only.

Regards
Sunil

**Comment by Sunil7545** [comment]
Hi Bane,
Thank you for the help.
figured it out,

Regards
Sunil
