### ISSUE TITLE
Setup camera matrix

### ISSUE THREAD

**Issue by vahidk** [pyvista/pyvista-support#85]
Is there a way to directly provide the full modelViewProjection matrix in PyVista?

**Comment by banesullivan** [comment]
Yes! PyVista is just a layer on top of VTK, so any VTK properties are accessible. The model view projection matrix can be accesed from any plotter's `camera` propery. We do not have any clean helper routines to fetch the matrix, but the following should do the trick:

```py
import pyvista as pv
import numpy as np

# Some plotting routine
p = pv.Plotter()
p.add_mesh(pv.Sphere())
p.show()

# Now grab the matrix
vmtx = p.camera.GetModelViewTransformMatrix()
mtx = np.zeros((4,4))
for i in range(4):
    for j in range(4):
        mtx[i,j] = vmtx.GetElement(i, j)
mtx
```

**Comment by banesullivan** [comment]
FYI, it might be worth running `dir(p.camera)` to see all the options available to make sure `GetModelViewTransformMatrix` is the right method for you

**Comment by vahidk** [comment]
@banesullivan Thanks for the answer but that doesn't do what I'm asking. I want to set the model-view-projection matrix directly to have full control on what gets rendered. It seems there is SetExplicitProjectionTransformMatrix but it requires vtkMatrix as input. I can't seem to find a method to do the conversion from numpy array to vtkMatrix.

**Comment by akaszynski** [comment]
You can convert a  numpy array to a vtkMatrix with:
```python
def trans_to_matrix(trans):
    """ Convert a numpy.ndarray to a vtk.vtkMatrix4x4 """
    matrix = vtk.vtkMatrix4x4()
    for i in range(trans.shape[0]):
        for j in range(trans.shape[1]):
            matrix.SetElement(i, j, trans[i, j])
    return matrix
```

@banesullivan, this might be something we wish to add to `pyvista` under helpers.py as we already have `trans_from_matrix`.

**Comment by banesullivan** [comment]
Should we make a `convert_matrix` function that dynamically decides how to convert between    matrices and numpy arrays much like `pv.convert_array`

**Comment by vahidk** [comment]
I'm still having trouble making this to work. After setting the camera with SetExplicitProjectionTransformMatrix and SetModelTransformMatrix calling plotter.show() seems to reset the camera even when reset_camera flag is set to false. Using the image property seems to work, but it opens a window. I'm trying to do offscreen rendering, but the .image property seems to not respect off_screen=False flag.

**Comment by banesullivan** [comment]
Can you share your code?

**Comment by vahidk** [comment]
import pyvista as pv
import numpy as np
import matplotlib.pyplot as plt
import vtk

def trans_to_matrix(trans):
    """Convert a numpy.ndarray to a vtk.vtkMatrix4x4 """
    matrix = vtk.vtkMatrix4x4()
    for i in range(trans.shape[0]):
        for j in range(trans.shape[1]):
            matrix.SetElement(i, j, trans[i, j])
    return matrix

mesh = pv.Sphere()

plotter = pv.Plotter(off_screen=True)
plotter.add_mesh(mesh, reset_camera=False)

modelTransform = np.array([
  [1, 0, 0, 0],
  [0, 1, 0, 0],
  [0, 0, 1, 0],
  [0, 0, 0, 1]
], dtype=np.float32)

f = 1
projTransform = np.array([
  [f, 0, 0, 0],
  [0, f, 0, 0],
  [0, 0, 1, 0],
  [0, 0, 0, 1]
], dtype=np.float32)

plotter.camera.SetModelTransformMatrix(trans_to_matrix(modelTransform))
plotter.camera.SetExplicitProjectionTransformMatrix(trans_to_matrix(projTransform))
plotter.camera.SetUseExplicitProjectionTransformMatrix(1)

cam, img = plotter.show(return_img=True)
#img = plotter.image
plt.imshow(img)
plt.show()

**Comment by banesullivan** [comment]
> calling plotter.show() seems to reset the camera even when reset_camera flag is set to false

To keep the camera from resetting on the `show` call, add 
`plotter.camera_set = True` somewhere before the show call. If it isn't set, the `show` call will use the default camera position from the `pyvista.rcParams`

> Using the image property seems to work, but it opens a window.  I'm trying to do offscreen rendering, but the .image property seems to not respect off_screen=True flag.

huh, it shouldn't... you may see an icon pop up on your doc but a window shouldn't appear. If one does, could you open a new issue in the main PyVista repo with a report (`pv.Report()`) and screen capture?
