### ISSUE TITLE
Projecting Grid point cloud object onto plane point cloud object

### ISSUE THREAD

**Issue by ishangupta3** [pyvista/pyvista-support#87]
I would like to project a grid point cloud object onto a plane point cloud object and then export it as a single point cloud object. I am able to do this while plotting both a plane and grid, but unable to export it as a pointcloud file. Is this possible using PyVista library. Attached is a photo I am able to do using Plotter, but would love to do the same thing and export it as a single scene.

![beam_cell](https://user-images.githubusercontent.com/8518915/71039400-ed087280-20d8-11ea-904a-80ec3bdca1d1.jpg)

```py
import pyvista as pv
from pyvista import examples

surface = pv.Plane()
surface.points *= 25 # This makes the point cloud bigger
mesh_grid =  examples.load_uniform()

p = pv.Plotter()
p.add_mesh(surface, show_edges=True, color='white')
p.add_mesh(mesh_grid, show_edges=True, color='black')
p.add_mesh(pv.PolyData(mesh_grid.points))
p.show(screenshot='beam_cell.png')

print(p.points)
```

**Comment by banesullivan** [comment]
Do you want to actually project all of the points from a 3D grid to the plane, or do you just want the grid to be on top of the plane like in this example. Do note that you are viewing this from a funny angle and that it actually looks like so:

![2019-12-17 17 29 46](https://user-images.githubusercontent.com/22067021/71039728-d8d16f00-20f2-11ea-97e3-940b40846054.gif)

**Comment by ishangupta3** [comment]
Just like that, I would like to export this as a point cloud object - where I am able to place a grid on top of the plane.

**Comment by banesullivan** [comment]
Is there a specific file format you want to export this as? Also, do you literally want a "point cloud", as in just the points and no surface connectivities?

**Comment by ishangupta3** [comment]
Yes, I am only interested in the points of this scene - and would like to export it as .ply. Essentially, I am merging 2 different mesh objects into a single scene and then exporting it as a point cloud.

**Comment by banesullivan** [comment]
PLY files must have triangulated surfaces, raw point clouds are supported by that format to my knowledge

**Comment by ishangupta3** [comment]
Is it possible to export it as just a 'point cloud' regardless of the file format? Is extracting all the points from this scene possible?

**Comment by banesullivan** [comment]
Oh yes, totally possible! You can combine two meshes using the `+` operator, then save out the points as a CSV file using NumPy like:

```py
merged = pv.PolyData(surface.points) + pv.PolyData(mesh_grid.points)

import numpy as np
np.savetxt('point_cloud.csv', merged.points, delimiter=',')
```

**Comment by ishangupta3** [comment]
Thank you so much. My last question, is it possible to translate or rotate the cube on the plane itself?
