### ISSUE TITLE
Plotting gaussian curvature using pyvista

### ISSUE THREAD

**Issue by bis-13** [pyvista/pyvista-support#95]
I just started playing around with PyVista and looking at the different things that you can do with it. I am, however, running into some trouble calculating the gaussian curvature of a surface and I was hoping I can get some help here.
In the "Creating a Structured Surface From XYZ Points" example, after I get the surface, I do 
```python
mesh.plot_curvature(curv_type='gaussian')
```
and the resulting colormap scale doesn't look to be correct, it goes from -1e-05 up to 0.393.
Am I doing something wrong? The mean curvature seems to be correct from what I can tell, so perhaps I'm missing some other input parameter(?). 

To give more details about my motivation. I have a surface that contains vertices and face information and I would like to give vertex colors corresponding to their gaussian curvature. I have used MeshLab for this and I get satisfying results, but I'd like to remove MeshLab as a dependency from my program and do everything with python. 

The following is the surface colored using the mean curvature in both PyVista (left) and MeshLab (right). 

<img width="588" alt="s1_combined" src="https://user-images.githubusercontent.com/15009787/71939089-c638db80-316e-11ea-944a-231ceab63095.png">

The results match quite well and I like it a lot. However, when I try to do the same using the gaussian curvature, I get the following: 
<img width="587" alt="s2_combined" src="https://user-images.githubusercontent.com/15009787/71939097-ce911680-316e-11ea-86b1-4893c2ec62aa.png">

Something is not right and I cannot figure out what. BTW, in MeshLab to color the surface I first load the surface to the program, I go to "Color Creation and Processing Filters" and select "Colorize curvature (APSS)" and select Gauss curvature type with the default options. MeshLab also has a RIMLS curvature method, which does give me a single color coloring of the surface similar to PyVista. So if I had to guess, I'd say that the implementation in PyVista is different and perhaps doesn't support the APSS curvature calculation method. 

I did try trimesh as well, but that didn't work. Perhaps, it is not possible to get a similar gaussian curvature coloring in python as from MeshLab.

**Comment by banesullivan** [comment]
Can you zip up and attach this specific mesh here? If so, I can play with this and figure out what is going wrong with PyVista.

There might be an "imperfection" in the mesh that is causing the curvature value to blow up somewhere - you might be able to play with the `clim` to change the color mapping to a reasonable range of values if this is the case.

**Comment by bis-13** [comment]
[surface.zip](https://github.com/pyvista/pyvista-support/files/4033289/surface.zip)

Sure! Here you go. 
I tried playing with clim before and it indeed does give a better profile. As a matter of fact, if I apply a clim of ```[-0.0176, 0.030]``` I get the following profile: 

![pyvista_clim](https://user-images.githubusercontent.com/15009787/71944715-f178f600-3181-11ea-8ff3-3b61ea1af3cc.png)

Which does match decently well the profile calculated using MashLab. The problem now would be how to get the adequate clim values programmatically since I got the image above by manually tweaking the upper clim value.

**Comment by banesullivan** [comment]
Ah yep, it seems some part of the mesh is wack, so you'll just need to inspect the curvature values to find a decent range. I can't think of a clean, programatic way to do this off the top of my head, but I can image there is a way to compute several histograms of the data and then choose a range that has a desirable distribution.

maybe something along the lines of:

```py
import pyvista as pv
import numpy as np

mesh = pv.read("top_plane_curv.ply")
curv = mesh.curvature(curv_type="gaussian")
mesh["gaussian_curvature"] = curv

cmin = np.percentile(curv, 0)
cmax = np.percentile(curv, 95)
print(cmin, cmax)
mesh.plot(scalars="gaussian_curvature", 
          cmap="jet", clim=[cmin,  cmax], cpos="xy")
```

![download](https://user-images.githubusercontent.com/22067021/71946214-68b08900-3186-11ea-9665-cebc1ec8170b.png)

That's likely not the best approach to find the color range values, but I hope that at least helps!

**Comment by bis-13** [comment]
> it seems some part of the mesh is wack

That does not surprise me a single bit. If the source of the mesh was more reliable I wouldn't have to do this in the first place. But that's a different issue altogether.

Your code block is great and works really well. In addition to comparing data distributions, it may also be possible to loop through the final percentiles and check for a reasonably close delta between cmax and its closest neighbours. Perhaps, something like this: 
```python
curv = curv[np.where(curv < cmax)]
closest_neighbours = curv.copy()
closest_neighbours.sort()
closest_neighbours[-10:]

def minimize_delta(cmax, closest_neighbours):
    ...
```

I don't know how effective this approach is yet but all this is trivial at this point, now that I know where the problem was. Thank you for your help. I appreciate it.

**Comment by banesullivan** [comment]
Glad I could help you figure out where the issues were. I'm going to close this since the remaining tasks aren't really on topic.

Feel free to reopen if there is more you need help with in this!
