### ISSUE TITLE
Neighbor Vertices and faces in a triangulated surface

### ISSUE THREAD

**Issue by Sunil7545** [pyvista/pyvista-support#96]
## Description
Dear Pyvista team,
I have a triangulated mesh created by pyvista.delaunay2d() and I would like the following information from this mesh:
1.  Vertex indices of the 1-ring neighbor (connected vertices) of each vertex 
2. Face indices of 1-ring neighbor  (connected faces) of each vertex 
3. Indices of the faces connected to a face
4. indices of the vertex in each face

Is it possible to get all these information using PyVista without a for loop.

I would be really grateful, if you can let me know

Regards
Sunil  

## Example Data
Please consider the plane or bunny example from Pyvista

**Comment by banesullivan** [comment]
Hi @Sunil7545, let's use the following example triangulated mesh. Please note that the following code will only work for triangulated `PolyData` meshes (it can be modified for other cell types).

```py
from pyvista import examples
import numpy as np

mesh = examples.download_dolfin().extract_geometry()
assert mesh.is_all_triangles()
mesh.plot(show_edges=True, cpos="xy")
```

![download](https://user-images.githubusercontent.com/22067021/71943101-b1fbdb00-317c-11ea-873c-50590c359a32.png)

All of your questions will need to leverage the [`faces` property of the `PolyData`](https://docs.pyvista.org/core/points.html#pyvista.PolyData.faces) mesh type which gives face type and vertex indices for each face in the mesh. We can just grab the indices by doing the following; since we have a purely triangulated mesh, let's ignore the face type values, hence `[:, 1:4]`:

```py
faces = mesh.faces.reshape((-1,4))[:, 1:4]
```

```py
# a nifty camera location as I will investigate a small region of the mesh to demonstrate that everything works
cpos = [(0.6810602748607929, 0.3941940073292267, 0.33562144130853633), 
        (0.6810602748607929, 0.3941940073292267, 0.0), 
        (0.0, 1.0, 0.0)]
```

Now I'm going to answer these a bit out of order as the answer to some help in solving the others

> 4. indices of the vertex in each face

The `faces` array given above is this
```py
>>> faces
array([[  76,  914, 1153],
       [  84,  763, 1426],
       [ 233,  998, 1155],
       ...,
       [2782, 2859, 2861],
       [2751, 2862, 2866],
       [2817, 2864, 2867]])
```

> 2. Face indices of 1-ring neighbor (connected faces) of each vertex

Here is a helper method to find all the faces connected to a given vertex:
```py
def find_faces_with_node(index):
    """Pass the index of the node in question.
    Returns the face indices of the faces with that node."""
    return [i for i, face in enumerate(faces) if 0 in face]

pid = 2500 # The vertex of interest
cids = find_faces_with_node(pid)

p = pv.Plotter()
p.add_mesh(mesh, show_edges=True)
p.add_mesh(mesh.extract_cells(cids), color="red", show_edges=True)
p.add_mesh(mesh.points[pid], color="blue", point_size=10)
p.show(cpos=cpos)
```
![download](https://user-images.githubusercontent.com/22067021/71944549-57b14900-3181-11ea-9bb0-08d2ca11b488.png)



> 1. Vertex indices of the 1-ring neighbor (connected vertices) of each vertex

Here is a helper method that leverages the previous helper method to find all vertices that are connected to a given vertex:
```py
def find_connected_vertices(index):
    """Pass the index of the node in question.
    Returns the vertex indices of the vertices connected with that node."""
    cids = find_faces_with_node(index)
    connected = np.unique(faces[cids].ravel())
    return np.delete(connected, np.argwhere(connected == index))

pid = 2500
connected = find_connected_vertices(pid)

p = pv.Plotter()
p.add_mesh(mesh, show_edges=True)
p.add_mesh(mesh.points[pid], color="red")
p.add_mesh(mesh.points[connected], color="blue", point_size=10)
p.show(cpos=cpos)
```

![download](https://user-images.githubusercontent.com/22067021/71944597-85968d80-3181-11ea-8bd8-884abeee8607.png)


> 3.Indices of the faces connected to a face

and here is a helper method that uses the above helpers to find all faces that are connected/adjacent to a given face.

Do note that there are two ways to interpret this question: which faces share a any of a given faces vertices *or* which faces share an edge with the given face. The former is implemented as:

```py
def find_neighbor_faces(index):
    """Pass the face index. 
    Returns the indices of all neighboring faces"""
    face = faces[index]
    sharing = set()
    for vid in face:
        [sharing.add(f) for f in find_faces_with_node(vid)]
    sharing.remove(index)
    return list(sharing)



cid = 3723
neighbors = find_neighbor_faces(cid)

p = pv.Plotter()
p.add_mesh(mesh, show_edges=True)
p.add_mesh(mesh.extract_cells(cid), color="blue")
p.add_mesh(mesh.extract_cells(neighbors), color="red", show_edges=True)
p.show(cpos=cpos)
```

![download](https://user-images.githubusercontent.com/22067021/71944917-81b73b00-3182-11ea-8dfe-2b31068dc71f.png)


and the latter as:

```py
def find_neighbor_faces_by_edge(index):
    """Pass the face index. 
    Returns the indices of all neighboring faces with shared edges."""
    face = faces[index]
    a = set(f for f in find_faces_with_node(face[0]))
    a.remove(index)
    b = set(f for f in find_faces_with_node(face[1]))
    b.remove(index)
    c = set(f for f in find_faces_with_node(face[2]))
    c.remove(index)
    return [list(a.intersection(b))[0], 
            list(b.intersection(c))[0], 
            list(a.intersection(c))[0]]



cid = 3723
neighbors = find_neighbor_faces_by_edge(cid)

p = pv.Plotter()
p.add_mesh(mesh, show_edges=True)
p.add_mesh(mesh.extract_cells(cid), color="blue")
p.add_mesh(mesh.extract_cells(neighbors), color="red", show_edges=True)
p.show(cpos=cpos)
```

![download](https://user-images.githubusercontent.com/22067021/71945548-5afa0400-3184-11ea-9f79-93b905335518.png)

**Comment by Sunil7545** [comment]
Thank you

**Comment by nam-usth** [comment]
Hi there, thanks to @banesullivan solution. I would love to make my contribution to extending the neighbors' finding problem. 

**Question 1:** Given a vertex (by ID), find the connected vertices within the range of $n$ (usually known as $n$-ring neighbors).

**Question 2:** Given a face/cell (by ID), find the neighbor in terms of $n$-ring faces/cells.

p/s: The idea is based on the documentation of [pyvista.DataSet.point_neighbors_levels](https://docs.pyvista.org/version/stable/api/core/_autosummary/pyvista.dataset.point_neighbors_levels)

```python
import itertools
import numpy as np
import pyvista as pv
from pyvista import examples

def find_faces_with_node(index):
    return [i for i, face in enumerate(faces) if index in face]


def find_connected_vertices_with_level(index, level=1, edge_vertices_only=True):
    assert level >= 1, "Level must be greater than or equal to 1"
    
    if edge_vertices_only:
        return list(mesh.point_neighbors_levels(index, level))[level-1]
    else:
        return list(itertools.chain(*mesh.point_neighbors_levels(index, level)))


def find_neighbor_faces_with_level(index, level=1, edge_faces_only=True):
    assert level >= 1, "Level must be greater than or equal to 1"
    
    face = faces[index]
    sharing = set()

    if (level == 1):
        for vid in face:
            [sharing.add(f) for f in find_faces_with_node(vid)]
        sharing.remove(index)
        return list(sharing)
    else:
        all_vertices = []
        
        for vid in face:
            all_vertices.append(find_connected_vertices_with_level(vid, level-1, False))
        all_vertices = list(itertools.chain(*all_vertices))

        for vid in all_vertices:
            [sharing.add(f) for f in find_faces_with_node(vid)]
        
        if edge_faces_only:
            [sharing.remove(f) for f in find_neighbor_faces_with_level(index, level-1, False)]

        sharing.remove(index)
        return list(sharing)
```

Usage:
```python
if __name__ == "__main__":
    # Read mesh
    mesh = examples.download_dolfin().extract_geometry()

    faces = mesh.faces.reshape((-1,4))[:, 1:4]

    cpos = [(0.6810602748607929, 0.3941940073292267, 0.33562144130853633), 
            (0.6810602748607929, 0.3941940073292267, 0.0), 
            (0.0, 1.0, 0.0)]

    pid = 2500 # The vertex of interest
    connected = find_connected_vertices_with_level(pid, level=3, edge_vertices_only=True) # We can change the flag edge_vertices_only to False if we need to get all the vertices within this range

    cid = 3723 # The face/cell of interest
    neighbors = find_neighbor_faces_with_level(cid, level=3, edge_faces_only=True) # We can change the flag edge_faces_only to False if we need to get all the faces within this range

    # Visualization
    p = pv.Plotter(shape=(1, 2))

    p.subplot(0, 0)
    p.add_mesh(mesh, show_edges=True)
    p.add_mesh(mesh.points[pid], color="red")
    p.add_mesh(mesh.points[connected], color="blue", point_size=10)

    p.subplot(0, 1)
    p.add_mesh(mesh, show_edges=True)
    p.add_mesh(mesh.extract_cells(cid), color="blue")
    p.add_mesh(mesh.extract_cells(neighbors), color="red", show_edges=True)

    p.link_views()
    p.show(cpos=cpos)
```

Here is the visualization:

![neighbors_finding_within_range](https://github.com/pyvista/pyvista-support/assets/97352086/941ba39f-889a-4326-b786-6aae14e48fe4)

Cheers!
